In [2]:
import pandas as pd
import numpy as np
import collections
import time
from sklearn.model_selection import train_test_split

In [3]:
# (train_set_org['timestamp'].max()-train_set_org['timestamp'].min())/(60*60*24) # sekudny*minuty*dni

In [4]:
# train_set_org['timestamp'].min()

In [6]:
start = time.time()
train_set_org = pd.read_csv('D:\\Dokumenty\\Systemy_rekomendacyjne\\data\\trivagoRecSysChallengeData2019_v2\\train.csv',
                       sep=',',
                           nrows=1000)

In [7]:
train_set = train_set_org
train_set = train_set.set_index(['session_id','timestamp'])
train_set = train_set.sort_values(['timestamp'])
train_set[:30]

                               user_id  step             action_type  \
session_id    timestamp
7ddbbad580025 1541030660  0SO132S6MH3O     1  search for destination
              1541030692  0SO132S6MH3O     6        filter selection
              1541030692  0SO132S6MH3O     5        filter selection
              1541030692  0SO132S6MH3O     4        filter selection
              1541030692  0SO132S6MH3O     3        filter selection
              1541030692  0SO132S6MH3O     2        filter selection
              1541030693  0SO132S6MH3O    10        filter selection
              1541030693  0SO132S6MH3O     8        filter selection
              1541030693  0SO132S6MH3O     9        filter selection
              1541030693  0SO132S6MH3O    12        filter selection
              1541030693  0SO132S6MH3O    11        filter selection
              1541030693  0SO132S6MH3O     7        filter selection
              1541030703  0SO132S6MH3O    19        filter selection
              1541030703  0SO132S6MH3O    18        filter selection
              1541030703  0SO132S6MH3O    17        filter selection
              1541030703  0SO132S6MH3O    14        filter selection
              1541030703  0SO132S6MH3O    15        filter selection
              1541030703  0SO132S6MH3O    16        filter selection
              1541030703  0SO132S6MH3O    13        filter selection
              1541030707  0SO132S6MH3O    20        filter selection
              1541030713  0SO132S6MH3O    21        filter selection
              1541030732  0SO132S6MH3O    23          search for poi
              1541030732  0SO132S6MH3O    22        filter selection
fa3a53156ae5c 1541030832  02HGRBA06ODU     1   interaction item info
              1541030843  02HGRBA06ODU     2  interaction item image
              1541030843  02HGRBA06ODU     3  interaction item image
              1541030852  02HGRBA06ODU     4   interaction item info
              1541030867  02HGRBA06ODU     5   interaction item info
7ddbbad580025 1541030875  0SO132S6MH3O    24           clickout item
fa3a53156ae5c 1541030877  02HGRBA06ODU     6  interaction item image

                                  reference platform             city  \
session_id    timestamp
7ddbbad580025 1541030660    Toronto, Canada       US  Toronto, Canada
              1541030692             5 Star       US  Toronto, Canada
              1541030692             Resort       US  Toronto, Canada
              1541030692              Motel       US  Toronto, Canada
              1541030692              Hotel       US  Toronto, Canada
              1541030692        Hostal (ES)       US  Toronto, Canada
              1541030693             Resort       US  Toronto, Canada
              1541030693              Hotel       US  Toronto, Canada
              1541030693              Motel       US  Toronto, Canada
              1541030693             5 Star       US  Toronto, Canada
              1541030693             4 Star       US  Toronto, Canada
              1541030693        Hostal (ES)       US  Toronto, Canada
              1541030703             5 Star       US  Toronto, Canada
              1541030703             4 Star       US  Toronto, Canada
              1541030703             3 Star       US  Toronto, Canada
              1541030703              Hotel       US  Toronto, Canada
              1541030703              Motel       US  Toronto, Canada
              1541030703             Resort       US  Toronto, Canada
              1541030703        Hostal (ES)       US  Toronto, Canada
              1541030707        Hostal (ES)       US  Toronto, Canada
              1541030713              Motel       US  Toronto, Canada
              1541030732      Union Station       US  Toronto, Canada
              1541030732  Focus on Distance       US  Toronto, Canada
fa3a53156ae5c 1541030832            3377332       BR  Ubatuba, Brazil
              1541030843            3377332       BR  Ubatuba, Brazil
              1541030843            3377332       BR  Ubatuba, Brazil
              1541030852            3377332       BR  Ubatuba, Brazil
              1541030867            3066244       BR  Ubatuba, Brazil
7ddbbad580025 1541030875            9590036       US  Toronto, Canada
fa3a53156ae5c 1541030877            3066244       BR  Ubatuba, Brazil

                           device  \
session_id    timestamp
7ddbbad580025 1541030660  desktop
              1541030692  desktop
              1541030692  desktop
              1541030692  desktop
              1541030692  desktop
              1541030692  desktop
              1541030693  desktop
              1541030693  desktop
              1541030693  desktop
              1541030693  desktop
              1541030693  desktop
              1541030693  desktop
              1541030703  desktop
              1541030703  desktop
              1541030703  desktop
              1541030703  desktop
              1541030703  desktop
              1541030703  desktop
              1541030703  desktop
              1541030707  desktop
              1541030713  desktop
              1541030732  desktop
              1541030732  desktop
fa3a53156ae5c 1541030832   mobile
              1541030843   mobile
              1541030843   mobile
              1541030852   mobile
              1541030867   mobile
7ddbbad580025 1541030875  desktop
fa3a53156ae5c 1541030877   mobile

                                                            current_filters  \
session_id    timestamp
7ddbbad580025 1541030660                                                NaN
              1541030692              5 Star|Hotel|Motel|Resort|Hostal (ES)
              1541030692              5 Star|Hotel|Motel|Resort|Hostal (ES)
              1541030692              5 Star|Hotel|Motel|Resort|Hostal (ES)
              1541030692              5 Star|Hotel|Motel|Resort|Hostal (ES)
              1541030692              5 Star|Hotel|Motel|Resort|Hostal (ES)
              1541030693       5 Star|Hotel|Motel|Resort|Hostal (ES)|4 Star
              1541030693       5 Star|Hotel|Motel|Resort|Hostal (ES)|4 Star
              1541030693       5 Star|Hotel|Motel|Resort|Hostal (ES)|4 Star
              1541030693       5 Star|Hotel|Motel|Resort|Hostal (ES)|4 Star
              1541030693       5 Star|Hotel|Motel|Resort|Hostal (ES)|4 Star
              1541030693       5 Star|Hotel|Motel|Resort|Hostal (ES)|4 Star
              1541030703  5 Star|Hotel|Motel|Resort|Hostal (ES)|4 Star|3...
              1541030703  5 Star|Hotel|Motel|Resort|Hostal (ES)|4 Star|3...
              1541030703  5 Star|Hotel|Motel|Resort|Hostal (ES)|4 Star|3...
              1541030703  5 Star|Hotel|Motel|Resort|Hostal (ES)|4 Star|3...
              1541030703  5 Star|Hotel|Motel|Resort|Hostal (ES)|4 Star|3...
              1541030703  5 Star|Hotel|Motel|Resort|Hostal (ES)|4 Star|3...
              1541030703  5 Star|Hotel|Motel|Resort|Hostal (ES)|4 Star|3...
              1541030707            5 Star|Hotel|Motel|Resort|4 Star|3 Star
              1541030713                  5 Star|Hotel|Resort|4 Star|3 Star
              1541030732  5 Star|Hotel|Resort|4 Star|3 Star|Focus on Dis...
              1541030732  5 Star|Hotel|Resort|4 Star|3 Star|Focus on Dis...
fa3a53156ae5c 1541030832                                                NaN
              1541030843                                                NaN
              1541030843                                                NaN
              1541030852                                                NaN
              1541030867                                                NaN
7ddbbad580025 1541030875  5 Star|Hotel|Resort|4 Star|3 Star|Focus on Dis...
fa3a53156ae5c 1541030877                                                NaN

                                                                impressions  \
session_id    timestamp
7ddbbad580025 1541030660                                                NaN
              1541030692                                                NaN
              1541030692                                                NaN
              1541030692                                                NaN
              1541030692                                                NaN
              1541030692                                                NaN
              1541030693                                                NaN
              1541030693                                                NaN
              1541030693                                                NaN
              1541030693                                                NaN
              1541030693                                                NaN
              1541030693                                                NaN
              1541030703                                                NaN
              1541030703                                                NaN
              1541030703                                                NaN
              1541030703                                                NaN
              1541030703                                                NaN
              1541030703                                                NaN
              1541030703                                                NaN
              1541030707                                                NaN
              1541030713                                                NaN
              1541030732                                                NaN
              1541030732                                                NaN
fa3a53156ae5c 1541030832                                                NaN
              1541030843                                                NaN
              1541030843                                                NaN
              1541030852                                                NaN
              1541030867                                                NaN
7ddbbad580025 1541030875  6924590|43910|101019|44160|44872|44350|1835163...
fa3a53156ae5c 1541030877                                                NaN

                                                                     prices
session_id    timestamp
7ddbbad580025 1541030660                                                NaN
              1541030692                                                NaN
              1541030692                                                NaN
              1541030692                                                NaN
              1541030692                                                NaN
              1541030692                                                NaN
              1541030693                                                NaN
              1541030693                                                NaN
              1541030693                                                NaN
              1541030693                                                NaN
              1541030693                                                NaN
              1541030693                                                NaN
              1541030703                                                NaN
              1541030703                                                NaN
              1541030703                                                NaN
              1541030703                                                NaN
              1541030703                                                NaN
              1541030703                                                NaN
              1541030703                                                NaN
              1541030707                                                NaN
              1541030713                                                NaN
              1541030732                                                NaN
              1541030732                                                NaN
fa3a53156ae5c 1541030832                                                NaN
              1541030843                                                NaN
              1541030843                                                NaN
              1541030852                                                NaN
              1541030867                                                NaN
7ddbbad580025 1541030875  93|91|94|103|107|153|327|469|554|119|199|164|1...
fa3a53156ae5c 1541030877                                                NaN

In [35]:
x_train, x_test = train_test_split(train_set, test_size=0.2, shuffle=False)

In [36]:
x_train = x_train.reset_index()
x_train_session_ids = x_train['session_id'].values

In [37]:
x_test = x_test.reset_index()
x_test_session_ids = x_test['session_id'].values

In [38]:
print("Liczba unikalnych identyfikatorów sesji w zbiorze testowym:", len(x_train_session_ids))

Liczba unikalnych identyfikatorów sesji w zbiorze testowym: 12746393

In [39]:
print("Liczba unikalnych identyfikatorów sesji w zbiorze treningowym:", len(x_test_session_ids))

Liczba unikalnych identyfikatorów sesji w zbiorze treningowym: 3186599

In [40]:
# collections.Counter(x_train_session_ids)

In [41]:
intersected_ids = list(set(x_train_session_ids) & set(x_test_session_ids))
print("Liczba identyfikatorów przecinających się:", len(intersected_ids))

Liczba identyfikatorów przecinających się: 1232

In [42]:
# len(set(x_test[x_test['session_id'].isin(x_train_session_ids)]['session_id'].values))

In [43]:
# print("Zbiór treningowy przed usunięciem wierszy:", x_train.shape)
# print("Zbiór testowy przed dodaniem wierszy:", x_test.shape)

In [44]:
print("Zbiór treningowy przed dodaniem wierszy:", x_train.shape)
print("Zbiór testowy przed usunięciem wierszy:", x_test.shape)

Zbiór treningowy przed dodaniem wierszy: (12746393, 12)
Zbiór testowy przed usunięciem wierszy: (3186599, 12)

In [45]:
# print("Liczba wierszy do przeniesienia do zbioru testowego z treningowego:", len(x_train[x_train['session_id'].isin(x_test_session_ids)]) )

In [46]:
print("Liczba wierszy do przeniesienia do zbioru treningowego z testowego:", len(x_test[x_test['session_id'].isin(x_train_session_ids)]) )

Liczba wierszy do przeniesienia do zbioru treningowego z testowego: 37946

In [47]:
x_train = x_train.append(x_test[x_test['session_id'].isin(x_train_session_ids)])
x_test = x_test.loc[~x_test['session_id'].isin(intersected_ids)]

In [48]:
# x_test = x_test.append(x_train[x_train['session_id'].isin(x_test_session_ids)])
# x_train = x_train.loc[~x_train['session_id'].isin(intersected_ids)]

In [49]:
print("Zbiór treningowy po dodaniu wierszy:", x_train.shape)
print("Zbiór testowy po usunięciu wierszy:", x_test.shape)

Zbiór treningowy po dodaniu wierszy: (12784339, 12)
Zbiór testowy po usunięciu wierszy: (3148653, 12)

In [50]:
# print("Zbiór treningowy po usunięciu wierszy:", x_train.shape)
# print("Zbiór testowy po dodaniu wierszy:", x_test.shape)

In [51]:
# zmiana w zbiorze testowym reference na nan

In [52]:
x_test_ground_truth = x_test

In [53]:
x_test['counter'] = range(len(x_test))
last_clickout_item_rows = x_test[x_test['action_type']=='clickout item'].groupby('user_id').last()
x_test = x_test.set_index(['user_id','timestamp'])
last_clickout_item_rows.loc[:,'reference'] = np.nan
last_clickout_item_rows[:10]

,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices,counter
user_id,,,,,,,,,,,,
000I430EXZC0,ddabdf53a4d38,1541501642,1,clickout item,NaN,JP,"Tokyo, Japan",mobile,NaN,3247218|8805412|103452|95011|98265|103658|1036...,1744|458|494|243|354|203|244|235|136|157|75|11...,1296652
000O8CPC6T0W,846b712ae8e1f,1541480658,1,clickout item,NaN,DE,"Mainz, Germany",mobile,NaN,15196|923037|52196|51577|53603|51321|13876|528...,74|110|109|110|107|111|108|75|75|117|70|113|10...,819269
000REY2YYH1D,4a313f2eb8954,1541465923,1,clickout item,NaN,US,"Sedona, USA",desktop,NaN,65491|67551|70266|1045348|62474|65392|57541|68...,262|262|212|174|394|333|189|315|402|779|323|17...,420859
0010PD3FH7SV,26b9e7e18cc87,1541535269,2,clickout item,NaN,TR,"Afyon, Turkey",mobile,NaN,5963554|2267078|3443066|1207371|2826362|383066...,64|100|45|51|41|59|68|90|22|64|58|24|66|30|36|...,2618461
0012IHLNTQWC,a035e580f0e64,1541505846,39,clickout item,NaN,DE,"Barcelona, Spain",desktop,Hotel|Resort|Hostal (ES)|Sort by Price|Recepti...,2041695|1326566|3171798|1100198|1069656|106965...,28|30|31|34|36|36|36|36|36|37|37|39|40|40|41|4...,1431365
0015CRBC6OH9,8bcbd478ac2cf,1541519175,3,clickout item,NaN,CZ,"Paris, France",desktop,NaN,11926|82322|48827|48847|48405|48816|50434|1208...,159|93|293|90|107|156|191|79|305|213|66|133|11...,1936272
0018EAWF0OIK,10ce4a98a476f,1541513087,2,clickout item,NaN,PH,"Nasugbu, Philippines",mobile,NaN,998597|2567604|998593|8230426|4072668|3804510|...,89|133|70|58|86|24|51|25|94|182|149|30|232|89|...,1697238
001EBIZM062K,0e036884adc53,1541502068,1,clickout item,NaN,ES,"Amsterdam, Netherlands",mobile,NaN,214161|2467696|2164460|42278|9616040|3154396|9...,69|81|83|65|102|83|59|73|126|114|211|185|70|10...,1309227
001G88F8NP9P,2a2e9eb9c967c,1541511909,9,clickout item,NaN,DE,"Sibiu, Romania",desktop,Car Park|Reception (24/7),400791|1306503|972027|1314825|2855876|2678882|...,90|176|132|70|207|24|18|150|77|144|52|72|138|7...,1651097
001JFV0AYE6Z,73ad1e08b4430,1541481561,1,clickout item,NaN,MX,"North Miami, USA",desktop,NaN,67196|61991|149620|59822|59397|58414|6002482|7...,97|171|263|320|219|193|249|276|443|199|206|421...,835379

In [54]:
x_test = x_test.reset_index()
last_clickout_item_rows = last_clickout_item_rows.reset_index()

In [55]:
last_clickout_item_rows = last_clickout_item_rows.set_index(['user_id', 'timestamp'])
x_test = x_test.set_index(['user_id', 'timestamp'])

In [56]:
counter_list = last_clickout_item_rows['counter'].values
y_test = x_test.loc[x_test['counter'].isin(counter_list)]
x_test.loc[x_test['counter'].isin(counter_list)] = last_clickout_item_rows
y_test[:10]

,,session_id,step,action_type,reference,platform,city,device,current_filters,impressions,prices,counter
user_id,timestamp,,,,,,,,,,,
U9MAV55LZMOR,1541453209,0dd5544c71728,1,clickout item,366186,US,"Atlantic City, USA",mobile,NaN,366186|56563|3741160|63568|3478738|3137008|678...,69|68|46|39|69|47|48|52|74|70|44|34|57|69|37|7...,9
VXIWZ3NF0WHF,1541453212,be1b5623b2e12,3,clickout item,148127,DK,"Copenhagen, Denmark",tablet,NaN,4412788|53876|3147220|929429|148127|53835|1753...,122|144|195|100|92|117|72|107|268|166|171|657|...,15
2VZWKE7NWP8C,1541453213,7daf68934bfef,1,clickout item,57189,US,"Weston, USA",mobile,NaN,57189|404846|164156|111309|148435|77409|103228...,115|166|115|97|111|87|200|101|114|160|98|97|10...,16
YAD78TVUR09A,1541453216,1d988e8ec0a64,1,clickout item,15964,NO,"San Agustín, Spain",mobile,NaN,15964|7434|7279|94114|95048|100915|6466618|953...,128|196|166|224|101|306|101|143|623|362|252|27...,20
6EC3MQPWB5OA,1541453217,cfa803f10d6d9,1,clickout item,109994,IE,"Limerick City, Ireland",mobile,NaN,109994|363881|436766|109997|936331|19817|46029...,99|89|149|114|99|137|84|98|105|108|125|115|310...,23
PC3K486NASTS,1541453217,26ae80da84843,1,clickout item,2813583,AR,"San Clemente del Tuyú, Argentina",desktop,NaN,2813583|8927002|2812010|4274890|4274898|428472...,36|53|57|61|61|61|88,24
PE3W0TFH468N,1541453218,b082600e5f653,1,clickout item,2028485,BR,"Canoa Quebrada, Brazil",mobile,NaN,4120638|2028485|5837110|9819932|2781912|203646...,90|48|225|74|104|63|56|56|66|74|38|31|25|36|34...,39
J912TWKDU6QM,1541453221,79424b3732cbc,1,clickout item,3166358,CA,"Sainte Catherine, Canada",mobile,NaN,3166358|1285724|103379|347426|7107198|2342180|...,43|69|73|77|114|80|68|80|346|126|108|47|77|66|...,51
I91O2PDHF2F5,1541453222,84225439e3bbf,1,clickout item,2218036,MX,"Guadalajara, Mexico",desktop,NaN,4868870|6538232|1797067|4985074|42880|1257131|...,59|80|74|68|64|81|67|53|50|93|72|42|50|38|54|5...,52
X61L8I2E2U32,1541453224,a8206f4ba4497,1,clickout item,152836,UK,"Leeds, United Kingdom",tablet,NaN,138309|46612|1153462|126363|152836|148968|1874...,136|160|115|174|56|130|163|174|102|176|182|165...,64

In [57]:
x_test = x_test.drop('counter', axis=1)
x_test.sort_values(['user_id'])[:10]

                            session_id  step             action_type  \
user_id      timestamp
000I430EXZC0 1541501642  ddabdf53a4d38     1           clickout item
000O8CPC6T0W 1541480658  846b712ae8e1f     1           clickout item
             1541480740  846b712ae8e1f     2        filter selection
             1541480754  846b712ae8e1f     3        filter selection
000REY2YYH1D 1541465923  4a313f2eb8954     1           clickout item
0010PD3FH7SV 1541535143  26b9e7e18cc87     1           clickout item
             1541535269  26b9e7e18cc87     2           clickout item
0012IHLNTQWC 1541505605  a035e580f0e64    29  interaction item image
             1541505595  a035e580f0e64    23  interaction item image
             1541505595  a035e580f0e64    24  interaction item image

                                  reference platform              city  \
user_id      timestamp
000I430EXZC0 1541501642                 NaN       JP      Tokyo, Japan
000O8CPC6T0W 1541480658                 NaN       DE    Mainz, Germany
             1541480740  Breakfast Included       DE    Mainz, Germany
             1541480754  Breakfast Included       DE    Mainz, Germany
000REY2YYH1D 1541465923                 NaN       US       Sedona, USA
0010PD3FH7SV 1541535143             7988660       TR     Afyon, Turkey
             1541535269                 NaN       TR     Afyon, Turkey
0012IHLNTQWC 1541505605             1069658       DE  Barcelona, Spain
             1541505595             1069658       DE  Barcelona, Spain
             1541505595             1069658       DE  Barcelona, Spain

                          device     current_filters  \
user_id      timestamp
000I430EXZC0 1541501642   mobile                 NaN
000O8CPC6T0W 1541480658   mobile                 NaN
             1541480740   mobile  Breakfast Included
             1541480754   mobile  Breakfast Included
000REY2YYH1D 1541465923  desktop                 NaN
0010PD3FH7SV 1541535143   mobile                 NaN
             1541535269   mobile                 NaN
0012IHLNTQWC 1541505605  desktop                 NaN
             1541505595  desktop                 NaN
             1541505595  desktop                 NaN

                                                               impressions  \
user_id      timestamp
000I430EXZC0 1541501642  3247218|8805412|103452|95011|98265|103658|1036...
000O8CPC6T0W 1541480658  15196|923037|52196|51577|53603|51321|13876|528...
             1541480740                                                NaN
             1541480754                                                NaN
000REY2YYH1D 1541465923  65491|67551|70266|1045348|62474|65392|57541|68...
0010PD3FH7SV 1541535143  5963554|2267078|3443066|1207371|2826362|383066...
             1541535269  5963554|2267078|3443066|1207371|2826362|383066...
0012IHLNTQWC 1541505605                                                NaN
             1541505595                                                NaN
             1541505595                                                NaN

                                                                    prices
user_id      timestamp
000I430EXZC0 1541501642  1744|458|494|243|354|203|244|235|136|157|75|11...
000O8CPC6T0W 1541480658  74|110|109|110|107|111|108|75|75|117|70|113|10...
             1541480740                                                NaN
             1541480754                                                NaN
000REY2YYH1D 1541465923  262|262|212|174|394|333|189|315|402|779|323|17...
0010PD3FH7SV 1541535143  64|100|45|51|41|59|68|90|22|64|58|24|66|30|36|...
             1541535269  64|100|45|51|41|59|68|90|22|64|58|24|66|30|36|...
0012IHLNTQWC 1541505605                                                NaN
             1541505595                                                NaN
             1541505595                                                NaN

In [58]:
end = time.time()
end-start

72.39487981796265

In [60]:
(x_test['timestamp'].max()-x_test['timestamp'].min())/(60*60*24) # sekudny*minuty*dni

KeyError: 'timestamp'

In [28]:
# x_train = x_train.reset_index()
# x_train.to_csv('D:\\Dokumenty\\Systemy_rekomendacyjne\\additional_resources\\2019-master\\data\\train.csv', sep=',', index=False)

In [29]:
# x_test = x_test.reset_index()
# x_test.to_csv('D:\\Dokumenty\\Systemy_rekomendacyjne\\additional_resources\\2019-master\\data\\test.csv', sep=',', index=False)

In [30]:
# x_test_ground_truth = x_test_ground_truth.drop('counter', axis=1)
# x_test_ground_truth = x_test_ground_truth.reset_index()
# x_test_ground_truth.to_csv('D:\\Dokumenty\\Systemy_rekomendacyjne\\additional_resources\\2019-master\\data\\ground_truth.csv', sep=',', index=False)

In [ ]:
x_train[:100]

In [ ]:
x_test[x_test["reference"].isnull() & (x_test["action_type"] == "clickout item")]

In [ ]:
x_train[['session_id','user_id']].groupby("user_id").nunique()

In [ ]:
x_train[x_train['user_id'] == '0008BO33KUQ0' ]

In [ ]:
mask = x_train["action_type"] == "clickout item"
x_train2 = x_train[mask]
df_item_clicks = (
    x_train2
    .groupby("reference")
    .size()
    .reset_index(name="n_clicks")
    .transform(lambda x: x.astype(int))
)
x_train2.groupby(['session_id', 'user_id']).size()

In [ ]:
# DODATKOWE UWAGI

In [2]:
train_set_org = pd.read_csv('D:\\Dokumenty\\Systemy_rekomendacyjne\\data\\trivagoRecSysChallengeData2019_v2\\train.csv',
                           sep=',',
                           nrows=1000000,
                           skiprows=range(1,586586))
train_set_org[:5]

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices
0,FW0769LL3L2N,81dd4458c314d,1541149763,9,interaction item info,915703,AA,"Dubai, United Arab Emirates",desktop,NaN,NaN,NaN
1,FW0769LL3L2N,81dd4458c314d,1541149773,10,interaction item info,915703,AA,"Dubai, United Arab Emirates",desktop,NaN,NaN,NaN
2,FW0769LL3L2N,81dd4458c314d,1541149976,11,interaction item image,99078,AA,"Dubai, United Arab Emirates",desktop,NaN,NaN,NaN
3,FW0769LL3L2N,81dd4458c314d,1541149976,12,interaction item image,99078,AA,"Dubai, United Arab Emirates",desktop,NaN,NaN,NaN
4,FW0769LL3L2N,81dd4458c314d,1541149978,13,clickout item,99078,AA,"Dubai, United Arab Emirates",desktop,NaN,470526|1501989|99083|2562660|2588298|977137|67...,109|113|108|82|63|60|63|110|93|103|97|104|99|8...

In [56]:
item_metadata_org = pd.read_csv('D:\\Dokumenty\\Systemy_rekomendacyjne\\data\\trivagoRecSysChallengeData2019_v2\\item_metadata.csv',
                       sep=',')
item_metadata_org[:5]

   item_id                                         properties
0     5101  Satellite TV|Golf Course|Airport Shuttle|Cosme...
1     5416  Satellite TV|Cosmetic Mirror|Safe (Hotel)|Tele...
2     5834  Satellite TV|Cosmetic Mirror|Safe (Hotel)|Tele...
3     5910  Satellite TV|Sailing|Cosmetic Mirror|Telephone...
4     6066  Satellite TV|Sailing|Diving|Cosmetic Mirror|Sa...

In [57]:
item_metadata_org['item_id'].nunique()

927142

In [58]:
train_set_org['reference'].nunique()

400277

In [59]:
import math
def string_to_array(s):
    """Convert pipe separated string to array."""

    if isinstance(s, str):
        out = s.split("|")
    elif math.isnan(s):
        out = []
    else:
        raise ValueError("Value must be either string of nan")
    return out

def explode(df_in, col_expl):
    """Explode column col_expl of array type into multiple rows."""

    df = df_in.copy()
    df.loc[:, col_expl] = df[col_expl].apply(string_to_array)  # zamienia 1|2|3 na [1,2,3]

    # df = df.sort_values(by=['session_id']) #ZMIANA
    # df['number_of_impressions'] = df['impressions'].apply(len) #ZMIANA

    df_out = pd.DataFrame(
        {col: np.repeat(df[col].values,
                        df[col_expl].str.len())
         for col in df.columns.drop(col_expl)}
    )

    df_out.loc[:, col_expl] = np.concatenate(df[col_expl].values)
    df_out.loc[:, col_expl] = df_out[col_expl].apply(int)

    return df_out

In [60]:
# train_last_200k = train_set_org[train_set_org['action_type'] == 'clickout item'][1486586:]

In [61]:
# train_10k = train_set_org[train_set_org['action_type'] == 'clickout item'][:10000]

In [62]:
train_set_org[train_set_org['action_type'] == 'clickout item'].shape

(1586586, 12)

In [63]:
df_expl = explode(train_set_org, 'impressions')
df_expl[:5]

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,prices,impressions
0,00RL8Z82B2Z1,aff3928535f48,1541037543,14,clickout item,109038,AU,"Sydney, Australia",mobile,NaN,95|66|501|112|95|100|101|72|82|56|56|143|70|25...,3400638
1,00RL8Z82B2Z1,aff3928535f48,1541037543,14,clickout item,109038,AU,"Sydney, Australia",mobile,NaN,95|66|501|112|95|100|101|72|82|56|56|143|70|25...,1253714
2,00RL8Z82B2Z1,aff3928535f48,1541037543,14,clickout item,109038,AU,"Sydney, Australia",mobile,NaN,95|66|501|112|95|100|101|72|82|56|56|143|70|25...,3367857
3,00RL8Z82B2Z1,aff3928535f48,1541037543,14,clickout item,109038,AU,"Sydney, Australia",mobile,NaN,95|66|501|112|95|100|101|72|82|56|56|143|70|25...,5100540
4,00RL8Z82B2Z1,aff3928535f48,1541037543,14,clickout item,109038,AU,"Sydney, Australia",mobile,NaN,95|66|501|112|95|100|101|72|82|56|56|143|70|25...,1088584

In [69]:
# Brak danych w metadata
len(set(df_expl['impressions'].values).difference(set(item_metadata_org['item_id'].values)))

798

In [71]:
# Różna liczba impressions
df_expl[df_expl['reference'] == '673981']

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,prices,impressions
39568,9U03V73W63YF,73b22aa50be7c,1541164705,2,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,121|57|54|18|61|37|267|858|47,673981
39569,9U03V73W63YF,73b22aa50be7c,1541164705,2,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,121|57|54|18|61|37|267|858|47,4907322
39570,9U03V73W63YF,73b22aa50be7c,1541164705,2,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,121|57|54|18|61|37|267|858|47,4956312
39571,9U03V73W63YF,73b22aa50be7c,1541164705,2,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,121|57|54|18|61|37|267|858|47,8266872
39572,9U03V73W63YF,73b22aa50be7c,1541164705,2,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,121|57|54|18|61|37|267|858|47,1849539
39573,9U03V73W63YF,73b22aa50be7c,1541164705,2,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,121|57|54|18|61|37|267|858|47,6208042
39574,9U03V73W63YF,73b22aa50be7c,1541164705,2,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,121|57|54|18|61|37|267|858|47,1788201
39575,9U03V73W63YF,73b22aa50be7c,1541164705,2,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,121|57|54|18|61|37|267|858|47,9973144
39576,9U03V73W63YF,73b22aa50be7c,1541164705,2,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,121|57|54|18|61|37|267|858|47,8848040
365205,XAMET9VK9WGZ,7065917b50786,1541514521,2,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,52|83|103|176|61|36|47|63|183,4907322
365206,XAMET9VK9WGZ,7065917b50786,1541514521,2,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,52|83|103|176|61|36|47|63|183,1788201
365207,XAMET9VK9WGZ,7065917b50786,1541514521,2,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,52|83|103|176|61|36|47|63|183,673981
365208,XAMET9VK9WGZ,7065917b50786,1541514521,2,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,52|83|103|176|61|36|47|63|183,10369176
365209,XAMET9VK9WGZ,7065917b50786,1541514521,2,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,52|83|103|176|61|36|47|63|183,4956312
365210,XAMET9VK9WGZ,7065917b50786,1541514521,2,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,52|83|103|176|61|36|47|63|183,8266872
365211,XAMET9VK9WGZ,7065917b50786,1541514521,2,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,52|83|103|176|61|36|47|63|183,6208042
365212,XAMET9VK9WGZ,7065917b50786,1541514521,2,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,52|83|103|176|61|36|47|63|183,1849539
365213,XAMET9VK9WGZ,7065917b50786,1541514521,2,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,52|83|103|176|61|36|47|63|183,9973144
365214,XAMET9VK9WGZ,7065917b50786,1541514624,4,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,52|83|103|176|61|36|47|63|183,4907322
365215,XAMET9VK9WGZ,7065917b50786,1541514624,4,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,52|83|103|176|61|36|47|63|183,1788201
365216,XAMET9VK9WGZ,7065917b50786,1541514624,4,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,52|83|103|176|61|36|47|63|183,673981
365217,XAMET9VK9WGZ,7065917b50786,1541514624,4,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,52|83|103|176|61|36|47|63|183,10369176
365218,XAMET9VK9WGZ,7065917b50786,1541514624,4,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,52|83|103|176|61|36|47|63|183,4956312
365219,XAMET9VK9WGZ,7065917b50786,1541514624,4,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,52|83|103|176|61|36|47|63|183,8266872
365220,XAMET9VK9WGZ,7065917b50786,1541514624,4,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,52|83|103|176|61|36|47|63|183,6208042
365221,XAMET9VK9WGZ,7065917b50786,1541514624,4,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,52|83|103|176|61|36|47|63|183,1849539
365222,XAMET9VK9WGZ,7065917b50786,1541514624,4,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,52|83|103|176|61|36|47|63|183,9973144
365223,XAMET9VK9WGZ,7065917b50786,1541514675,5,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,52|83|103|176|61|36|47|63|183,4907322
365224,XAMET9VK9WGZ,7065917b50786,1541514675,5,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,52|83|103|176|61|36|47|63|183,1788201
365225,XAMET9VK9WGZ,7065917b50786,1541514675,5,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,52|83|103|176|61|36|47|63|183,673981
...,...,...,...,...,...,...,...,...,...,...,...,...
33666944,7AN1RMSIF735,0e143deab63c8,1541085542,16,clickout item,673981,US,"Desaru, Malaysia",desktop,NaN,76|303|67|40|112|813|76,6208042
33666945,7AN1RMSIF735,0e143deab63c8,1541085542,16,clickout item,673981,US,"Desaru, Malaysia",desktop,NaN,76|303|67|40|112|813|76,4907322
33666946,7AN1RMSIF735,0e143deab63c8,1541085542,16,clickout item,673981,US,"Desaru, Malaysia",desktop,NaN,76|303|67|40|112|813|76,9973144
33666947,7AN1RMSIF735,0e143deab63c8,1541085542,16,clickout item,673981,US,"Desaru, Malaysia",desktop,NaN,76|303|67|40|112|813|76,1849539
33730312,DITEK4BM4SNC,cf5ba7fb920ef,1541242416,2,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,184|210|96|47|81|949,673981
33730313,DITEK4BM4SNC,cf5ba7fb920ef,1541242416,2,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,184|210|96|47|81|949,4907322
33730314,DITEK4BM4SNC,cf5ba7fb920ef,1541242416,2,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,184|210|96|47|81|949,4956312
33730315,DITEK4BM4SNC,cf5ba7fb920ef,1541242416,2,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,184|210|96|47|81|949,6208042
33730316,DITEK4BM4SNC,cf5ba7fb920ef,1541242416,2,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,184|210|96|47|81|949,1849539
33730317,DITEK4BM4SNC,cf5ba7fb920ef,1541242416,2,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,184|210|96|47|81|949,9973144
34914948,03591OJQ0QXR,a0b829776413f,1541098698,54,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,70|66|75|47|18|209|144|279|47|101|107,4907322
34914949,03591OJQ0QXR,a0b829776413f,1541098698,54,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,70|66|75|47|18|209|144|279|47|101|107,4956312
34914950,03591OJQ0QXR,a0b829776413f,1541098698,54,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,70|66|75|47|18|209|144|279|47|101|107,1849539
34914951,03591OJQ0QXR,a0b829776413f,1541098698,54,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,70|66|75|47|18|209|144|279|47|101|107,6208042
34914952,03591OJQ0QXR,a0b829776413f,1541098698,54,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,70|66|75|47|18|209|144|279|47|101|107,8266872
34914953,03591OJQ0QXR,a0b829776413f,1541098698,54,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,70|66|75|47|18|209|144|279|47|101|107,10369176
34914954,03591OJQ0QXR,a0b829776413f,1541098698,54,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,70|66|75|47|18|209|144|279|47|101|107,673981
34914955,03591OJQ0QXR,a0b829776413f,1541098698,54,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,70|66|75|47|18|209|144|279|47|101|107,1788201
34914956,03591OJQ0QXR,a0b829776413f,1541098698,54,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,70|66|75|47|18|209|144|279|47|101|107,8848040
34914957,03591OJQ0QXR,a0b829776413f,1541098698,54,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,70|66|75|47|18|209|144|279|47|101|107,9020228
34914958,03591OJQ0QXR,a0b829776413f,1541098698,54,clickout item,673981,MY,"Desaru, Malaysia",mobile,NaN,70|66|75|47|18|209|144|279|47|101|107,9016654
35160300,C27L90W3FFDI,17f262ed36e6d,1541256081,6,clickout item,673981,MY,"Kota Tinggi, Malaysia",mobile,NaN,174,673981
35266174,LVBQ8UFG6ARR,c1f924fc5448a,1541486663,4,clickout item,673981,SG,"Desaru, Malaysia",mobile,NaN,134|220|302|85|18|47|60|88,673981
35266175,LVBQ8UFG6ARR,c1f924fc5448a,1541486663,4,clickout item,673981,SG,"Desaru, Malaysia",mobile,NaN,134|220|302|85|18|47|60|88,4907322
35266176,LVBQ8UFG6ARR,c1f924fc5448a,1541486663,4,clickout item,673981,SG,"Desaru, Malaysia",mobile,NaN,134|220|302|85|18|47|60|88,1788201
35266177,LVBQ8UFG6ARR,c1f924fc5448a,1541486663,4,clickout item,673981,SG,"Desaru, Malaysia",mobile,NaN,134|220|302|85|18|47|60|88,4956312
35266178,LVBQ8UFG6ARR,c1f924fc5448a,1541486663,4,clickout item,673981,SG,"Desaru, Malaysia",mobile,NaN,134|220|302|85|18|47|60|88,8266872
35266179,LVBQ8UFG6ARR,c1f924fc5448a,1541486663,4,clickout item,673981,SG,"Desaru, Malaysia",mobile,NaN,134|220|302|85|18|47|60|88,6208042
35266180,LVBQ8UFG6ARR,c1f924fc5448a,1541486663,4,clickout item,673981,SG,"Desaru, Malaysia",mobile,NaN,134|220|302|85|18|47|60|88,1849539
35266181,LVBQ8UFG6ARR,c1f924fc5448a,1541486663,4,clickout item,673981,SG,"Desaru, Malaysia",mobile,NaN,134|220|302|85|18|47|60|88,9140274

In [34]:
df_expl = df_expl.astype({'reference':int})
df_expl.dtypes

user_id            object
session_id         object
timestamp           int64
step                int64
action_type        object
reference           int32
platform           object
city               object
device             object
current_filters    object
prices             object
impressions         int64
dtype: object

In [35]:
import collections
views_of_id = df_expl['impressions'].value_counts()
print('unikalne id: ', df_expl['impressions'].nunique())
print("Liczba wyświetleń danego id:")
print(views_of_id)
# collections.Counter(t.values)

unikalne id:  343362
Liczba wyświetleń danego id:
8621        478
8577        468
8796        463
8805412     461
8618        421
8568        408
103600      406
102080      402
2793224     401
1810141     396
3218556     395
8588        388
2593971     381
891093      379
8589        378
1811137     374
3143733     369
8518        361
8586        358
103452      354
103484      351
103656      348
8744        343
1519063     340
12695       334
32727       331
1321090     331
8599        329
8561        328
488501      317
           ...
3972370       1
8215850       1
4042036       1
971865        1
7982520       1
3890666       1
8113656       1
10751488      1
8633566       1
10882624      1
6692418       1
6733398       1
6745692       1
9288756       1
10597260      1
2117256       1
6434500       1
2244294       1
7342978       1
7863164       1
3480352       1
6479578       1
3902194       1
3898092       1
3840720       1
2940698       1
7270236       1
6852496       1
6946750       1
2196234       1
Name: impressions, Length: 343362, dtype: int64

In [36]:
views_of_id_above_5 = views_of_id.where(views_of_id > 5).dropna()

In [37]:
clicks_of_id = df_expl['reference'].value_counts()

In [38]:
clicks_of_id_above_3 = clicks_of_id.where(clicks_of_id > 3).dropna()

In [51]:
3218556 in clicks_of_id_above_3.index

True

In [39]:
len(clicks_of_id_above_3.keys())

55864

In [40]:
len(views_of_id_above_5.keys())

96405

In [42]:
len(list(set(set(clicks_of_id_above_3.keys()).union(set(views_of_id_above_5.keys())))))

115435

In [43]:
list_of_ids = list(set(set(clicks_of_id_above_3.keys()).union(set(views_of_id_above_5.keys()))))

In [44]:
dict_id_ratio = dict.fromkeys(list_of_ids)

In [53]:
for id, values in dict_id_ratio.items():
    if (id in views_of_id_above_5.index) and (id in clicks_of_id_above_3.index):
        dict_id_ratio[id] = clicks_of_id_above_3[id] / views_of_id_above_5[id]

In [57]:
dict_id_ratio_without_none = {k: dict_id_ratio[k] for k in dict_id_ratio if dict_id_ratio[k] is not None}
dict_id_ratio_without_none

{1310725: 3.5714285714285716,
 1310728: 4.166666666666667,
 3145742: 2.7777777777777777,
 6815758: 2.272727272727273,
 1835029: 0.7708333333333334,
 6815766: 0.6071428571428571,
 2359344: 2.1153846153846154,
 3932214: 2.4193548387096775,
 4456504: 8.928571428571429,
 1310776: 1.6666666666666667,
 1835065: 3.5714285714285716,
 2097216: 1.6666666666666667,
 5767234: 0.8928571428571429,
 9699406: 1.8,
 1310806: 1.0869565217391304,
 3145828: 2.272727272727273,
 3145841: 2.5,
 2097270: 1.3636363636363635,
 786551: 6.125,
 786571: 1.3157894736842106,
 2097300: 2.235955056179775,
 1310884: 5.75,
 3145895: 2.5,
 7340224: 4.166666666666667,
 6815936: 6.571428571428571,
 6553812: 1.6666666666666667,
 1835233: 1.3157894736842106,
 1310946: 0.9615384615384616,
 4718826: 1.5625,
 5767402: 1.4038461538461537,
 2097392: 6.25,
 2883832: 10.428571428571429,
 3145984: 2.272727272727273,
 3145986: 1.3157894736842106,
 3145990: 2.967741935483871,
 10748170: 4.333333333333333,
 2097426: 2.5,
 1835295: 1.5714285714285714,
 2097454: 1.7857142857142858,
 1835319: 0.21367521367521367,
 6553916: 0.9259259259259259,
 3146050: 0.7575757575757576,
 2621778: 1.9230769230769231,
 1048926: 3.3333333333333335,
 2621836: 0.9803921568627451,
 2621838: 1.4492753623188406,
 2359702: 1.0416666666666667,
 2621853: 1.9841269841269842,
 8913318: 1.8518518518518519,
 6554022: 2.272727272727273,
 3146166: 2.272727272727273,
 2359760: 4.166666666666667,
 3146198: 1.2820512820512822,
 1049048: 1.7857142857142858,
 1311198: 6.25,
 2884070: 6.5,
 1049064: 3.1333333333333333,
 2097642: 2.5,
 2621936: 1.3125,
 1311218: 3.5714285714285716,
 885853: 7.142857142857143,
 3932670: 3.8461538461538463,
 1311238: 0.4,
 1573409: 1.25,
 1311307: 1.6666666666666667,
 2097748: 1.0416666666666667,
 2396864: 1.1363636363636365,
 1311324: 2.795918367346939,
 2097798: 2.1739130434782608,
 787081: 0.9615384615384616,
 787111: 0.8125,
 2097844: 3.5714285714285716,
 1573559: 0.7575757575757576,
 9437900: 2.6315789473684212,
 4195030: 2.5,
 1311454: 2.6315789473684212,
 9175774: 1.7,
 7340836: 5.769230769230769,
 1573675: 1.5,
 2622252: 2.0,
 2097974: 1.4705882352941178,
 4719428: 0.4117647058823529,
 1049434: 1.9230769230769231,
 5768052: 8.333333333333334,
 3933044: 3.5714285714285716,
 7078786: 1.6666666666666667,
 787341: 1.4705882352941178,
 6816668: 1.56,
 3408800: 1.6666666666666667,
 6554534: 4.166666666666667,
 7340968: 2.4,
 6816692: 3.125,
 6554582: 7.142857142857143,
 3146714: 3.5714285714285716,
 2098158: 1.0,
 4719620: 0.6944444444444444,
 2360324: 2.0,
 1049626: 2.272727272727273,
 8127536: 2.272727272727273,
 3146804: 0.8333333333333334,
 2360393: 8.125,
 7865422: 0.8181818181818182,
 3146832: 3.8043478260869565,
 3146872: 3.625,
 1049728: 3.125,
 9438390: 0.78125,
 7341256: 1.7647058823529411,
 4981972: 3.5714285714285716,
 4719854: 0.8928571428571429,
 1836275: 2.0833333333333335,
 1574139: 0.875,
 1354936: 0.53125,
 1836315: 1.1904761904761905,
 9176348: 4.0,
 1049914: 2.5974025974025974,
 1049928: 2.171806167400881,
 1836365: 3.5714285714285716,
 1574227: 0.8928571428571429,
 2098520: 1.7857142857142858,
 1836397: 1.3157894736842106,
 8127856: 3.6666666666666665,
 1574277: 1.7307692307692308,
 1836443: 2.7777777777777777,
 1050014: 4.411764705882353,
 9700784: 4.6875,
 2885044: 2.7777777777777777,
 1050048: 4.888888888888889,
 4457930: 1.0526315789473684,
 1050066: 1.9230769230769231,
 1050068: 1.4705882352941178,
 2885099: 2.0833333333333335,
 2360812: 1.25,
 1574393: 0.8522727272727273,
 7341564: 1.0416666666666667,
 7865862: 2.0,
 7865900: 1.7857142857142858,
 9700922: 1.5,
 7341638: 0.8928571428571429,
 1574471: 3.125,
 4458060: 2.2,
 4458064: 2.7777777777777777,
 2360920: 0.8064516129032258,
 1836641: 1.1363636363636365,
 2360940: 2.7027027027027026,
 2885248: 2.380952380952381,
 3147401: 1.951219512195122,
 9701002: 4.545454545454546,
 8128154: 7.8125,
 3933874: 1.25,
 1574603: 1.6129032258064515,
 5506768: 0.45161290322580644,
 1836757: 4.166666666666667,
 2623190: 2.75,
 2885354: 6.25,
 8390380: 4.166666666666667,
 788211: 4.741379310344827,
 3147516: 3.5714285714285716,
 3147528: 0.5319148936170213,
 9176844: 2.8,
 6293282: 4.166666666666667,
 5506854: 2.8181818181818183,
 9176870: 2.142857142857143,
 6293302: 3.125,
 3409732: 1.0,
 1836889: 4.6875,
 4720508: 4.545454545454546,
 788371: 1.1904761904761905,
 1312669: 0.9615384615384616,
 6555570: 0.9565217391304348,
 1312693: 4.75,
 5507008: 4.571428571428571,
 2099182: 3.125,
 2099198: 1.1111111111111112,
 6555652: 3.125,
 3147797: 2.7777777777777777,
 1050662: 1.8072289156626506,
 3147852: 2.6595744680851063,
 9177176: 9.375,
 2099320: 4.166666666666667,
 2885752: 1.1363636363636365,
 2099360: 3.125,
 7866532: 2.5,
 1837237: 4.166666666666667,
 7342278: 3.125,
 7866568: 3.5714285714285716,
 1050830: 1.1363636363636365,
 2099418: 1.6666666666666667,
 1050848: 1.4285714285714286,
 2361584: 1.3888888888888888,
 4983026: 3.125,
 1050890: 1.0666666666666667,
 3148051: 0.6097560975609756,
 1837349: 0.6470588235294118,
 7342374: 2.1666666666666665,
 7342376: 1.03125,
 2361684: 4.0,
 3410262: 1.6304347826086956,
 2099554: 8.823529411764707,
 1837423: 2.7777777777777777,
 8915344: 2.4444444444444446,
 1051026: 1.9230769230769231,
 1051034: 0.3870967741935484,
 1837489: 1.9230769230769231,
 7080374: 3.125,
 2099650: 8.666666666666666,
 1313232: 1.1904761904761905,
 7342570: 0.625,
 1837559: 2.5,
 7342592: 1.0,
 7866884: 1.0,
 3148313: 1.25,
 3148328: 2.272727272727273,
 3934782: 4.166666666666667,
 2099776: 0.5102040816326531,
 3148386: 1.263157894736842,
 2624102: 5.555555555555555,
 2099816: 0.4032258064516129,
 1837683: 3.125,
 3148414: 8.333333333333334,
 3148416: 1.7241379310344827,
 5507706: 1.6129032258064515,
 6818434: 1.3888888888888888,
 3148422: 2.6041666666666665,
 3148426: 0.7457627118644068,
 3148429: 1.9230769230769231,
 3148436: 1.0,
 3148438: 4.166666666666667,
 1837721: 0.5681818181818182,
 3148464: 3.260869565217391,
 2099890: 8.0,
 1051314: 1.7857142857142858,
 3148475: 1.3157894736842106,
 8915658: 2.5,
 1837783: 1.5625,
 6556378: 3.4285714285714284,
 9964260: 20.833333333333332,
 2099952: 1.0,
 7342834: 3.125,
 1837811: 1.5454545454545454,
 2099956: 1.0,
 1837815: 1.0,
 5769978: 2.2058823529411766,
 1837825: 2.0833333333333335,
 4459266: 2.380952380952381,
 2624259: 4.166666666666667,
 1837827: 2.45,
 1837843: 1.0869565217391304,
 1837851: 0.6944444444444444,
 2624285: 0.8426966292134831,
 1313579: 2.0833333333333335,
 2624304: 6.25,
 2100018: 1.7142857142857142,
 1051444: 2.7777777777777777,
 789296: 2.4444444444444446,
 2100038: 1.2666666666666666,
 3148620: 1.056338028169014,
 2362190: 2.272727272727273,
 2362196: 2.230769230769231,
 7080788: 2.0833333333333335,
 2100060: 6.818181818181818,
 2624365: 4.166666666666667,
 2624372: 0.9615384615384616,
 2100090: 3.4285714285714284,
 1837955: 1.25,
 3148678: 0.8064516129032258,
 3148680: 2.2,
 3148690: 0.8771929824561403,
 1837987: 1.5625,
 3148712: 2.0,
 3148716: 1.3888888888888888,
 7867308: 2.7777777777777777,
 3148718: 0.5952380952380952,
 1313710: 1.1904761904761905,
 1838001: 1.3157894736842106,
 1838003: 4.166666666666667,
 5508040: 1.5,
 2624480: 4.411764705882353,
 4721650: 7.142857142857143,
 1838087: 4.166666666666667,
 1313812: 1.6666666666666667,
 9440292: 1.3888888888888888,
 6556710: 3.5714285714285716,
 1838119: 4.083333333333333,
 4983856: 3.5714285714285716,
 3148854: 4.166666666666667,
 3148856: 1.8518518518518519,
 5508160: 1.6666666666666667,
 6556738: 4.166666666666667,
 6556740: 0.9787234042553191,
 3148878: 0.4032258064516129,
 2100324: 8.333333333333334,
 3148904: 6.25,
 6556784: 0.4375,
 3148916: 3.248587570621469,
 9440372: 0.5102040816326531,
 2362496: 0.9230769230769231,
 3148936: 2.5,
 5508252: 1.0416666666666667,
 9440428: 0.6363636363636364,
 1051840: 1.3888888888888888,
 6556870: 0.8888888888888888,
 6819022: 0.7647058823529411,
 3935442: 1.0416666666666667,
 6556884: 0.8620689655172413,
 2362600: 3.4,
 2362602: 3.8461538461538463,
 3149055: 2.5,
 2362628: 0.5208333333333334,
 9964816: 8.333333333333334,
 6032676: 1.0,
 4984100: 2.7777777777777777,
 2100526: 4.166666666666667,
 3149106: 0.9047619047619048,
 1314104: 1.5625,
 789831: 0.3048780487804878,
 3935568: 4.545454545454546,
 9964882: 2.8333333333333335,
 6819172: 4.7101449275362315,
 1052006: 5.0,
 2100592: 2.4814814814814814,
 3149178: 2.7777777777777777,
 3149204: 1.6666666666666667,
 1052058: 0.591715976331361,
 7343534: 1.2352941176470589,
 2100664: 0.5555555555555556,
 7343582: 1.75,
 1052148: 0.625,
 2625018: 0.625,
 365436: 0.78125,
 2100746: 2.7777777777777777,
 1314336: 0.8620689655172413,
 2625059: 2.7027027027027026,
 6295082: 3.125,
 2100784: 0.847457627118644,
 3149388: 0.6410256410256411,
 3149404: 0.625,
 2625125: 3.409090909090909,
 2887276: 2.0833333333333335,
 1052274: 0.9259259259259259,
 1838723: 1.7857142857142858,
 8392352: 8.333333333333334,
 3149480: 13.88888888888889,
 1838773: 8.333333333333334,
 7081654: 1.5151515151515151,
 1314498: 0.6756756756756757,
 2887372: 0.6578947368421053,
 1838799: 6.25,
 6819536: 3.0,
 1838829: 4.545454545454546,
 1052398: 2.0833333333333335,
 8392450: 2.272727272727273,
 1838859: 3.6666666666666665,
 790286: 0.78125,
 1576725: 0.9523809523809523,
 4460310: 1.0,
 1838891: 0.8928571428571429,
 2887472: 0.7352941176470589,
 1838909: 7.142857142857143,
 3149659: 2.0833333333333335,
 2625380: 0.7352941176470589,
 9441128: 0.7575757575757576,
 1576815: 7.142857142857143,
 9965430: 0.9259259259259259,
 4984730: 0.5833333333333334,
 3149736: 2.090909090909091,
 1314750: 0.8148148148148148,
 2363342: 1.1363636363636365,
 2101208: 1.3157894736842106,
 7868384: 2.0833333333333335,
 1314785: 0.96,
 1314793: 2.0,
 6557694: 2.0833333333333335,
 1314823: 2.6315789473684212,
 1839129: 8.333333333333334,
 8130608: 2.7777777777777777,
 3936326: 5.75,
 4984910: 1.2195121951219512,
 6557786: 8.333333333333334,
 1052804: 3.5714285714285716,
 1052820: 3.5714285714285716,
 2101396: 1.411764705882353,
 1052842: 0.9615384615384616,
 1052844: 2.0491803278688523,
 1839279: 4.523809523809524,
 1052848: 2.272727272727273,
 9703600: 0.7407407407407407,
 1315016: 1.6818181818181819,
 1052880: 0.6024096385542169,
 1052892: 1.0769230769230769,
 1052894: 3.125,
 6295788: 2.0833333333333335,
 3150064: 2.0,
 4985074: 0.29069767441860467,
 1052942: 3.6666666666666665,
 1839377: 0.18421052631578946,
 1052958: 0.704225352112676,
 1052960: 0.6944444444444444,
 2625836: 1.8571428571428572,
 1315118: 2.7777777777777777,
 1577265: 1.375,
 4722994: 1.6666666666666667,
 1577271: 1.5625,
 3150137: 3.5714285714285716,
 3150140: 4.166666666666667,
 6295882: 2.2142857142857144,
 266602: 3.5714285714285716,
 1053040: 0.6944444444444444,
 9179512: 1.8333333333333333,
 2625920: 3.5714285714285716,
 4723080: 2.272727272727273,
 7868816: 1.4285714285714286,
 4460946: 1.0416666666666667,
 4985236: 4.6875,
 8917398: 5.833333333333333,
 4460954: 2.642857142857143,
 9965988: 6.25,
 3150258: 2.272727272727273,
 528841: 6.125,
 528856: 5.555555555555555,
 2626008: 3.5714285714285716,
 528881: 2.4,
 528891: 1.25,
 528896: 0.5172413793103449,
 1053184: 2.6785714285714284,
 528901: 3.0303030303030303,
 5771798: 3.8461538461538463,
 6558254: 1.3888888888888888,
 3150388: 2.9411764705882355,
 1053250: 2.4285714285714284,
 528966: 0.9615384615384616,
 3150408: 2.8461538461538463,
 528971: 1.293103448275862,
 1053278: 3.3783783783783785,
 6820456: 7.0,
 2364016: 5.555555555555555,
 3150456: 1.3157894736842106,
 5509766: 2.0833333333333335,
 1053338: 5.333333333333333,
 791196: 1.6666666666666667,
 529081: 2.2962962962962963,
 3150528: 3.0303030303030303,
 3150534: 1.5625,
 1577685: 0.7894736842105263,
 529111: 3.5714285714285716,
 529156: 0.49019607843137253,
 6044940: 2.0833333333333335,
 2102058: 4.166666666666667,
 3150678: 1.25,
 1577841: 0.78125,
 8754322: 1.6666666666666667,
 9442186: 1.3157894736842106,
 5004: 1.7777777777777777,
 5014: 4.12,
 5017: 2.380952380952381,
 791446: 3.5714285714285716,
 5022: 0.9333333333333333,
 1840029: 1.3888888888888888,
 529321: 2.7777777777777777,
 7345066: 1.4705882352941178,
 2102192: 5.0,
 5040: 1.9230769230769231,
 5041: 1.5625,
 529331: 4.166666666666667,
 5042: 2.0833333333333335,
 1053624: 2.6315789473684212,
 5049: 1.1363636363636365,
 5050: 1.3888888888888888,
 5051: 0.8695652173913043,
 5052: 0.8620689655172413,
 5053: 3.8461538461538463,
 5055: 4.8076923076923075,
 5059: 2.5,
 5061: 0.9259259259259259,
 5065: 1.1904761904761905,
 529356: 7.5,
 5072: 1.5833333333333333,
 6558674: 2.875,
 5075: 2.7777777777777777,
 1840085: 0.6944444444444444,
 5079: 2.7777777777777777,
 5080: 1.3888888888888888,
 3937244: 3.8461538461538463,
 5086: 1.1363636363636365,
 5094: 5.117647058823529,
 5096: 1.6666666666666667,
 5101: 1.4705882352941178,
 1053684: 10.714285714285714,
 5115: 1.9230769230769231,
 5116: 2.272727272727273,
 5118: 0.5208333333333334,
 5121: 2.5945945945945947,
 5122: 1.9230769230769231,
 5123: 2.227272727272727,
 5124: 0.7575757575757576,
 2888701: 1.7857142857142858,
 6296582: 4.166666666666667,
 5131: 0.44,
 7345164: 2.7777777777777777,
 5132: 1.0,
 5136: 1.5625,
 2102292: 2.272727272727273,
 529431: 1.7857142857142858,
 529436: 3.75,
 1053724: 4.166666666666667,
 5148: 1.6666666666666667,
 5154: 1.3157894736842106,
 5156: 1.7857142857142858,
 3937310: 1.263157894736842,
 1840165: 1.3157894736842106,
 5166: 2.9411764705882355,
 5168: 2.6296296296296298,
 5172: 1.7142857142857142,
 5176: 1.0416666666666667,
 5178: 1.4705882352941178,
 7345214: 1.25,
 5196: 1.9230769230769231,
 5198: 1.6222222222222222,
 5200: 2.64,
 5202: 4.032258064516129,
 5207: 2.0833333333333335,
 5209: 0.5555555555555556,
 5215: 1.0,
 5216: 2.2916666666666665,
 5217: 0.8888888888888888,
 5218: 1.575,
 5225: 0.9259259259259259,
 5228: 2.772727272727273,
 1578093: 2.0,
 5230: 0.6818181818181818,
 4985964: 1.625,
 5232: 0.6578947368421053,
 5233: 1.0416666666666667,
 5234: 0.6944444444444444,
 2364532: 2.3461538461538463,
 5238: 1.6666666666666667,
 529536: 5.357142857142857,
 5250: 1.6666666666666667,
 2626691: 0.6944444444444444,
 5254: 3.5714285714285716,
 5269: 2.027027027027027,
 1053848: 2.7142857142857144,
 5276: 2.7777777777777777,
 5277: 1.0416666666666667,
 5278: 4.166666666666667,
 5280: 2.5,
 5281: 2.8846153846153846,
 5282: 4.62962962962963,
 5285: 4.166666666666667,
 7869608: 1.0416666666666667,
 6821034: 1.2941176470588236,
 5295: 2.625,
 5299: 1.3888888888888888,
 5301: 2.7777777777777777,
 5303: 2.9411764705882355,
 8131766: 0.9493670886075949,
 5316: 1.3888888888888888,
 9180356: 3.125,
 7345350: 0.5208333333333334,
 5318: 0.9259259259259259,
 5327: 1.5625,
 5330: 1.0,
 7345376: 2.4193548387096775,
 5344: 0.36507936507936506,
 2626789: 3.125,
 5350: 1.0869565217391304,
 5354: 4.166666666666667,
 2626798: 2.5,
 5359: 1.25,
 9180400: 1.3333333333333333,
 5363: 0.6944444444444444,
 5365: 0.5319148936170213,
 5368: 3.588235294117647,
 5369: 1.9230769230769231,
 5373: 6.310344827586207,
 2626814: 1.0,
 5375: 0.4807692307692308,
 5376: 5.333333333333333,
 5374: 0.5681818181818182,
 5379: 2.380952380952381,
 5385: 1.6666666666666667,
 5390: 0.7837837837837838,
 5397: 0.8064516129032258,
 5401: 1.3157894736842106,
 5404: 0.9259259259259259,
 2626849: 3.3333333333333335,
 365796: 1.0,
 5412: 2.7777777777777777,
 5420: 2.5,
 1840429: 1.0416666666666667,
 5422: 2.272727272727273,
 5424: 2.272727272727273,
 529716: 2.1739130434782608,
 5431: 3.3333333333333335,
 5432: 1.9230769230769231,
 6034762: 1.3157894736842106,
 5465: 1.9230769230769231,
 5467: 1.6666666666666667,
 9966942: 3.5714285714285716,
 5470: 1.5625,
 5475: 3.5714285714285716,
 1054058: 1.2096774193548387,
 5483: 3.9473684210526314,
 5484: 6.125,
 5488: 2.9411764705882355,
 5491: 3.8461538461538463,
 5496: 2.1666666666666665,
 8918394: 1.0,
 5505: 4.545454545454546,
 2626948: 0.8928571428571429,
 5515: 1.5555555555555556,
 2626958: 1.263157894736842,
 2889110: 1.2820512820512822,
 5527: 3.806451612903226,
 5530: 1.3888888888888888,
 5531: 1.9230769230769231,
 5532: 2.0833333333333335,
 5533: 2.272727272727273,
 5535: 4.545454545454546,
 5536: 1.1904761904761905,
 5537: 2.7777777777777777,
 5541: 1.5151515151515151,
 5543: 0.8771929824561403,
 5545: 0.8333333333333334,
 5547: 1.8181818181818181,
 5548: 0.625,
 2626992: 2.0833333333333335,
 1054130: 0.7142857142857143,
 5555: 0.4576271186440678,
 5557: 0.9036144578313253,
 5558: 1.0416666666666667,
 5559: 1.4174757281553398,
 5560: 0.6410256410256411,
 1054136: 1.5454545454545454,
 5563: 0.6206896551724138,
 5564: 1.7857142857142858,
 5565: 3.3783783783783785,
 5566: 0.7142857142857143,
 5568: 5.652777777777778,
 5570: 1.8461538461538463,
 2364870: 1.4705882352941178,
 1054154: 0.5952380952380952,
 5579: 0.6666666666666666,
 5582: 1.1904761904761905,
 5583: 8.333333333333334,
 5585: 0.9433962264150944,
 5587: 1.1363636363636365,
 5588: 0.6944444444444444,
 5591: 1.1904761904761905,
 5594: 0.8333333333333334,
 5601: 1.2195121951219512,
 5602: 1.5151515151515151,
 8132074: 4.545454545454546,
 5611: 1.3888888888888888,
 5615: 1.7857142857142858,
 5616: 2.272727272727273,
 9442800: 1.263157894736842,
 5618: 2.0833333333333335,
 5622: 3.5714285714285716,
 529911: 0.25510204081632654,
 5624: 2.0833333333333335,
 5630: 2.3026315789473686,
 5635: 0.9615384615384616,
 5637: 1.5625,
 6297094: 1.105263157894737,
 1054214: 1.625,
 5641: 0.43859649122807015,
 5644: 0.6578947368421053,
 5650: 0.5208333333333334,
 5652: 2.1739130434782608,
 8394262: 2.590909090909091,
 1054234: 4.65,
 5660: 4.35,
 5665: 3.125,
 5666: 0.6,
 2364954: 6.25,
 5669: 1.1363636363636365,
 5670: 1.7857142857142858,
 5671: 0.6410256410256411,
 5672: 1.0683760683760684,
 5674: 2.3255813953488373,
 5677: 1.225,
 792106: 9.75,
 5682: 0.4807692307692308,
 5683: 0.352112676056338,
 1054260: 6.25,
 5687: 4.166666666666667,
 5689: 0.9615384615384616,
 5691: 0.7352941176470589,
 2889277: 2.7777777777777777,
 5702: 0.78125,
 5708: 2.7777777777777777,
 5709: 0.78125,
 5712: 2.076923076923077,
 5713: 0.7246376811594203,
 2627153: 2.6315789473684212,
 11015764: 1.7142857142857142,
 5718: 3.8461538461538463,
 5719: 0.5813953488372093,
 5721: 1.411764705882353,
 5726: 0.7352941176470589,
 5727: 0.9900990099009901,
 5728: 0.7246376811594203,
 5732: 1.25,
 1840739: 9.461538461538462,
 5736: 1.1363636363636365,
 5737: 0.3424657534246575,
 5739: 1.6129032258064515,
 5740: 1.7123287671232876,
 5741: 1.7857142857142858,
 5742: 2.101449275362319,
 5752: 1.6666666666666667,
 5755: 0.625,
 1316470: 1.4705882352941178,
 5763: 0.9259259259259259,
 5764: 2.7777777777777777,
 5510784: 1.6521739130434783,
 5768: 0.6190476190476191,
 2627209: 1.530612244897959,
 2627211: 1.9230769230769231,
 5772: 4.4523809523809526,
 2102924: 1.1363636363636365,
 7345804: 4.166666666666667,
 5777: 4.166666666666667,
 5778: 1.3157894736842106,
 2627219: 1.7857142857142858,
 5784: 1.1538461538461537,
 5790: 0.7575757575757576,
 5791: 0.7936507936507936,
 5793: 2.0,
 2627234: 7.8125,
 5795: 1.1904761904761905,
 5797: 3.5714285714285716,
 5798: 1.25,
 5802: 1.9230769230769231,
 2627243: 1.5957446808510638,
 2627245: 1.5384615384615385,
 4200110: 1.0416666666666667,
 5807: 1.1627906976744187,
 5804: 0.5555555555555556,
 5809: 6.0,
 5810: 2.0833333333333335,
 5812: 2.3255813953488373,
 5814: 1.0416666666666667,
 5816: 1.3888888888888888,
 5817: 3.25,
 5819: 1.175,
 5821: 1.0638297872340425,
 5825: 0.8478260869565217,
 5834: 1.6666666666666667,
 5840: 2.5,
 2365152: 2.7777777777777777,
 5866: 3.5625,
 9180908: 1.35,
 5871: 4.454545454545454,
 5887: 1.0869565217391304,
 5889: 2.7777777777777777,
 5891: 1.3171806167400881,
 5892: 0.6097560975609756,
 9443078: 3.5714285714285716,
 4986630: 0.8771929824561403,
 5897: 3.5714285714285716,
 5898: 0.45454545454545453,
 5900: 1.1666666666666667,
 9443084: 1.7142857142857142,
 5902: 0.9124087591240876,
 5903: 0.684931506849315,
 5901: 0.33962264150943394,
 5905: 1.6355140186915889,
 5906: 2.5641025641025643,
 5909: 1.0638297872340425,
 6559504: 3.7109375,

In [58]:
len(dict_id_ratio_without_none)

36834

In [71]:
pd.DataFrame.from_dict(dict_id_ratio_without_none, orient='index', columns=['clicks_views_ratio']).sort_values(by=['clicks_views_ratio'], ascending=False)

          clicks_views_ratio
10164710           25.000000
4040808            25.000000
3152397            25.000000
940846             25.000000
1277289            21.428571
148695             21.125000
579331             20.833333
771413             20.833333
1941399            20.833333
3840552            20.833333
506186             20.833333
128010             20.833333
360606             20.833333
9964260            20.833333
160903             20.500000
438706             20.500000
48976              20.000000
6923040            19.880000
2894501            19.500000
2243572            19.444444
86320              19.200000
1702517            18.750000
3050686            18.750000
1678821            18.750000
150406             18.750000
1004183            18.750000
4520026            18.750000
1395722            18.421053
1668569            18.000000
178062             17.857143
...                      ...
2196006             0.154321
58492               0.154321
18230               0.154321
55332               0.153846
103595              0.150602
103544              0.149701
1350878             0.146199
1282879             0.142857
98934               0.142857
103117              0.142857
109487              0.142857
1947653             0.138889
103589              0.138889
986971              0.135802
103467              0.132275
907759              0.130952
150138              0.126904
3883954             0.125828
866796              0.121212
6655310             0.117371
2378158             0.117188
1473741             0.113636
103645              0.111607
818231              0.095745
131842              0.094340
9489152             0.090909
1156297             0.088889
914785              0.066667
103479              0.065089
323951              0.049505

[36834 rows x 1 columns]