### UTILS

In [1]:
import pickle
import torch
import os
import random
import time
from contextlib import contextmanager
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import torch.nn.functional as F
from scipy.special import erfinv
from ordered_set import OrderedSet
import scipy
from collections import Counter
# from timezonefinder import TimezoneFinder
# from geopy.geocoders import Nominatim
# import pycountry
import datetime
import pytz



# tzf = TimezoneFinder()


activation_getter = {'iden': lambda x: x, 'relu': F.relu, 'tanh': torch.tanh, 'sigm': torch.sigmoid}


def platform2country(platform):
    '''
    return country name given platform
    '''
    
    if pycountry.countries.get(alpha_2=platform) != None:
        try:
            return pycountry.countries.get(alpha_2=platform).common_name
        except:
            return pycountry.countries.get(alpha_2=platform).name 
        
            
    else:
        return np.nan


def location2utc_offset(location):
    '''
    return the utc offset given the location
    '''
    geolocator = Nominatim(user_agent=str(location))
    # print(location)
    location = geolocator.geocode(location)
    
    if location == None:
        return np.nan
    try:
        lat = location.latitude
        lon = location.longitude
        offset_sec = datetime.datetime.now(pytz.timezone(tzf.timezone_at(lng=lon, lat=lat)))
        return offset_sec.utcoffset().total_seconds()/60/60
    except:
        return np.nan

def find_longest_repetitive_sequences(sequence):
    '''
    returns a dict that maps each element with the length of its longest repetitive sequneces in the list
    args:
        sequence: list
    
    '''
    counter = Counter()
    current_element = None

    # iterate the sequence
    for element in sequence:

        if current_element == None:
            current_element = element
            current_rep = 1
        elif element == current_element:
            current_rep += 1
        elif element != current_element:
            # update the element with the longest rep 
            if counter[current_element]  < current_rep:
                counter[current_element] = current_rep
            current_rep = 1
            current_element = element
    # update the element with the longest rep outside the loop
    if len(sequence) > 0 and counter[current_element]  < current_rep:
        counter[current_element] = current_rep

    return counter




def qcut_safe(prices, q):
    nbins=min(q, len(prices))
    result = pd.qcut(prices, nbins, labels=np.arange(nbins) )

    return result



class GaussRankScaler():

    def __init__( self ):
        self.epsilon = 1e-9
        self.lower = -1 + self.epsilon
        self.upper =  1 - self.epsilon
        self.range = self.upper - self.lower

    def fit_transform( self, X ):

        i = np.argsort( X, axis = 0 )
        j = np.argsort( i, axis = 0 )

        assert ( j.min() == 0 ).all()
        assert ( j.max() == len( j ) - 1 ).all()

        j_range = len( j ) - 1
        self.divider = j_range / self.range

        transformed = j / self.divider
        transformed = transformed - self.upper
        transformed = scipy.special.erfinv( transformed )
        ############
        # transformed = transformed - np.mean(transformed)

        return transformed
    
def seed_everything(seed=42):
    random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    np.random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)

def compute_rank(inp, to_np=False):
    sorted_inp = sorted(inp)
    out = [sorted_inp.index(i) for i in inp]
    if to_np:
        out = np.array(out)
    return out

def set_seed(seed, cuda=False):

    np.random.seed(seed)
    random.seed(seed)
    if cuda:
        torch.cuda.manual_seed(seed)
    else:
        torch.manual_seed(seed)


class CategoricalEncoder():
    '''
    This class is for those operating on large data, in which sklearn's LabelEncoder class may take too much time.
    This encoder is only suitable for 1-d array/ list. You may modify it to become n-d compatible.
    '''
    def __init__(self):
        self.f_dict = {}
        self.r_dict = {}

    def fit(self, array):
        '''
        :param array: list or np array
        :return: None
        '''

        unique_elements = OrderedSet(array)
        # unique_elements = sorted(unique_elements)
        # print(DUMMY_ITEM in unique_elements)
        # print('-1' in unique_elements)
        self.n_elements = 0
        self.f_dict = {}
        self.r_dict = {}

        for e in unique_elements:
            self.f_dict[e] = self.n_elements
            self.r_dict[self.n_elements] = e
            self.n_elements += 1


    def continue_fit(self, array):
        '''
        Do not refresh n_elements, count from the latest n_elements.
        :param array:
        :return: None
        '''
        unique_elements = set(array)
        for e in unique_elements:
            if e not in self.f_dict:
                self.f_dict[e] = self.n_elements
                self.r_dict[self.n_elements] = e
                self.n_elements += 1


    def reverse_transform(self, transformed_array, to_np=False):
        '''
        :param transformed_array: list or np array
        :return: array: np array with the same shape as input
        '''


        array = [self.r_dict[e] for e in transformed_array]
        if to_np:
            array = np.array(array)
        return array


    def transform(self, array, to_np=False):
        '''
        :param array: array list or np array
        :return: list or np array with the same shape as the input
        '''
        transformed_array = [self.f_dict[e] for e in array]
        if to_np:
            transformed_array = np.array(transformed_array)
        return transformed_array

    def fit_transform(self, array, to_np=False):
        '''
        :param array: array list or np array
        :return: list or np array with the same shape as the input
        '''
        self.fit(array)
        return self.transform(array, to_np)

def str2bool(v):
    return v.lower() in ('true')

def use_optimizer(network, params):
    if params['optimizer'] == 'adam':
        optimizer = torch.optim.Adam(network.parameters(), lr=params['learning_rate'] , weight_decay=params['weight_decay'],  eps=1e-07, amsgrad=True)
    elif params['optimizer'] == 'rmsprop':
        optimizer = torch.optim.RMSprop(network.parameters(),
                                        lr=params['learning_rate'],)
    elif params['optimizer'] == 'sgd':
        optimizer = torch.optim.SGD(network.parameters(), lr=params['learning_rate'], weight_decay=params['weight_decay'])
    return optimizer

def get_attn_key_pad_mask(seq_k, seq_q, transformed_dummy_value):
    ''' For masking out the padding part of key sequence. '''

    # Expand to fit the shape of key query attention matrix.
    len_q = seq_q.size(1)
    padding_mask = seq_k.eq(transformed_dummy_value)
    padding_mask = padding_mask.unsqueeze(1).expand(-1, len_q, -1)  # b x lq x lk

    return padding_mask

def compute_mean_reciprocal_rank(rs):
    '''
    rs: 2d array
    >>> rs = [[0, 0, 1], [0, 1, 0], [1, 0, 0]]
    >>> mean_reciprocal_rank(rs)
    0.61111111111111105
    >>> rs = np.array([[0, 0, 0], [0, 1, 0], [1, 0, 0]])
    >>> mean_reciprocal_rank(rs)
    0.5
    >>> rs = [[0, 0, 0, 1], [1, 0, 0], [1, 0, 0]]
    >>> mean_reciprocal_rank(rs)
    0.75
    '''

    rs = (np.asarray(r).nonzero()[0] for r in rs)
    return np.mean([1. / (r[0] + 1) if r.size else 0. for r in rs])

@contextmanager
def timer(name):
    t0 = time.time()
    yield
    print('[{}] done in {:.5f} s'.format(name,(time.time() - t0)))

In [2]:
DUMMY_ACTION = 'DUMMMY_A'
DUMMY_USER = -1
DUMMY_ITEM = -1
DUMMY_PRICE_RANK=25
DUMMY_IMPRESSION_INDEX = 25

In [4]:
import pandas as pd
import numpy as np
import collections
import time
from sklearn.model_selection import train_test_split
from ordered_set import OrderedSet
from tqdm import tqdm
from config import *
import xgboost as xgb
import multiprocessing
import gc

In [5]:
configuration = XGBConfiguration()

model_name='xgb_gic_lic_wosh_lf350_lr002_v2'

if configuration.sub_sample:
    model_name += '_140k'
else:
    model_name += '_all'

if configuration.use_test:
    model_name += '_ut'

seed_everything(42)

In [6]:
train = pd.read_csv('D:\\Dokumenty\\Systemy_rekomendacyjne\\additional_resources\\2019-master\\data\\train.csv',
                       sep=','
                        ,nrows=1000
                   )
train['id']= np.arange(len(train))
train[:3]

,index,session_id,timestamp,user_id,step,action_type,reference,platform,city,device,current_filters,impressions,prices,id
0,0,b6b4a3c02db0c,1541030408,4JK19KX9RU36,1,search for destination,"Londrina, Brazil",BR,"Londrina, Brazil",desktop,NaN,NaN,NaN,0
1,1,b6b4a3c02db0c,1541030410,4JK19KX9RU36,2,search for destination,"Londrina, Brazil",BR,"Londrina, Brazil",desktop,NaN,NaN,NaN,1
2,2,5b578bc20be9f,1541030412,KQ7YR1O2APO1,1,search for destination,"Vienna, Austria",RO,"Vienna, Austria",mobile,NaN,NaN,NaN,2

In [7]:
test = pd.read_csv('D:\\Dokumenty\\Systemy_rekomendacyjne\\additional_resources\\2019-master\\data\\test.csv',
                       sep=',',
                           nrows=1000
                  )
test['id'] = np.arange(len(train), len(train)+len(test))
test[:3]

,user_id,timestamp,session_id,step,action_type,reference,platform,city,device,current_filters,impressions,prices,id
0,MUOOQC23R8N9,1541453208,9c57f365a02a7,1,change of sort order,interaction sort button,ES,"Lisbon, Portugal",desktop,NaN,NaN,NaN,1000
1,L1IOIJ47C0S6,1541453208,ee9489aaeca70,1,interaction item image,2757973,BR,"Penha, Brazil",desktop,NaN,NaN,NaN,1001
2,L1IOIJ47C0S6,1541453208,ee9489aaeca70,2,interaction item image,2757973,BR,"Penha, Brazil",desktop,NaN,NaN,NaN,1002

In [8]:
item_meta = pd.read_csv('D:\\Dokumenty\\Systemy_rekomendacyjne\\data\\trivagoRecSysChallengeData2019_v2\\item_metadata.csv',
                       sep=',')
item_meta['properties'] = item_meta.properties.apply(lambda x: x.split('|'))
item_meta['item_id'] = item_meta['item_id'].apply(str)
item_meta[:3]

  item_id                                         properties
0    5101  [Satellite TV, Golf Course, Airport Shuttle, C...
1    5416  [Satellite TV, Cosmetic Mirror, Safe (Hotel), ...
2    5834  [Satellite TV, Cosmetic Mirror, Safe (Hotel), ...

In [9]:
from contextlib import contextmanager
@contextmanager
def timer(name):
    t0 = time.time()
    yield
    print('[{}] done in {:.5f} s'.format(name,(time.time() - t0)))

In [10]:
with timer("preprocessing"): 
    # change columns name
    train.rename(columns={'reference': 'item_id', 'action_type': 'action'}, inplace=True)
    test.rename(columns={'reference': 'item_id', 'action_type': 'action'}, inplace=True)

#     dla akcji typu: change of sort order, filter selec
    # concatenate the action and reference in string for    as these refernce are not actually item id
    train.loc[train.action=='change of sort order','action'] = train.loc[train.action=='change of sort order'].apply(lambda row: row.action + str(row.item_id), axis=1)
    test.loc[test.action=='change of sort order','action'] = test.loc[test.action=='change of sort order'].apply(lambda row: row.action + str(row.item_id), axis=1)

    train.loc[train.action=='filter selection','action'] = train.loc[train.action=='filter selection'].apply(lambda row: row.action + str(row.item_id), axis=1)
    test.loc[test.action=='filter selection','action'] = test.loc[test.action=='filter selection'].apply(lambda row: row.action + str(row.item_id), axis=1)
    
#     wyczyszczenie kolumny item_id, ustawienie na -1, gdzie action typu: change of sort order, filter selection, search for poi, search for destination
    # wipe out the item id associated with these actions, reason same as the above
    train.loc[train.action.str.contains('change of sort order'), 'item_id'] = DUMMY_ITEM
    test.loc[test.action.str.contains('change of sort order'), 'item_id'] = DUMMY_ITEM

    train.loc[train.action.str.contains('search for poi'), 'item_id'] = DUMMY_ITEM
    test.loc[test.action.str.contains('search for poi'), 'item_id'] = DUMMY_ITEM        

    train.loc[train.action.str.contains('filter selection'), 'item_id'] = DUMMY_ITEM
    test.loc[test.action.str.contains('filter selection'), 'item_id'] = DUMMY_ITEM        

    train.loc[train.action.str.contains('search for destination'), 'item_id'] = DUMMY_ITEM
    test.loc[test.action.str.contains('search for destination'), 'item_id'] = DUMMY_ITEM  
    
    # remove training example where clicked item is not in the impressions
    train['in_impressions'] = True
    train.loc[~train.impressions.isna(), 'in_impressions'] = train.loc[~train.impressions.isna()].apply(lambda row:row.item_id in row.impressions.split('|'), axis=1)
    train = train.loc[train.in_impressions].drop('in_impressions', axis=1).reset_index(drop=True)
    
    test['in_impressions'] = True
    test.loc[(~test.impressions.isna()) & (~test.item_id.isna()), 'in_impressions'] = test.loc[(~test.impressions.isna())& (~test.item_id.isna())].apply(lambda row:row.item_id in row.impressions.split('|'), axis=1)
    test = test.loc[test.in_impressions].drop('in_impressions', axis=1).reset_index(drop=True)
    
     # parse impressions and prices list from string to list
    train['item_id'] = train['item_id'].apply(str)
    train.loc[~train.impressions.isna(),'impressions'] = train.loc[~train.impressions.isna()].impressions.apply(lambda x: x.split('|'))
    train.loc[~train.prices.isna(), 'prices'] = train.loc[~train.prices.isna()].prices.apply(lambda x: x.split('|')).apply(lambda x: [int(p) for p in x])

    test['item_id'] = test['item_id'].apply(str)
    test.loc[~test.impressions.isna(),'impressions'] = test.loc[~test.impressions.isna()].impressions.apply(lambda x: x.split('|'))
    test.loc[~test.prices.isna(),'prices'] = test.loc[~test.prices.isna()].prices.apply(lambda x: x.split('|')).apply(lambda x: [int(p) for p in x])
    
#     wydobycie 3 ostatnich item_id, z którymi była interakcja
    # compute the last interacted item by shifted the item_id by 1 position
    train['last_item'] = np.nan
    test['last_item'] = np.nan
    
    train_shifted_item_id = [DUMMY_ITEM] + train.item_id.values[:-1].tolist()
    test_shifted_item_id = [DUMMY_ITEM] + test.item_id.values[:-1].tolist()
    
    # compute the last interacted item by shifted the item_id by 2 position
    train['last_item'] = train_shifted_item_id
    test['last_item'] = test_shifted_item_id

    train_shifted_item_id = [DUMMY_ITEM] *2 + train.item_id.values[:-2].tolist()
    test_shifted_item_id = [DUMMY_ITEM] *2  + test.item_id.values[:-2].tolist()
    
    # compute the last interacted item by shifted the item_id by 3 position
    train['second_last_item'] = train_shifted_item_id
    test['second_last_item'] = test_shifted_item_id

    train_shifted_item_id = [DUMMY_ITEM] *3 + train.item_id.values[:-3].tolist()
    test_shifted_item_id = [DUMMY_ITEM] *3  + test.item_id.values[:-3].tolist()

    train['third_last_item'] = train_shifted_item_id
    test['third_last_item'] = test_shifted_item_id
    
    # mask out the last interacted item if that interaction comes first in its session
    train['step_rank'] = train.groupby('session_id')['step'].rank(method='max', ascending=True)
    test['step_rank'] = test.groupby('session_id')['step'].rank(method='max', ascending=True)
    
    # fill the invalid shifted last n item with a constant number
    train.loc[(train.step_rank == 1) & (train.action == 'clickout item'), 'last_item'] = DUMMY_ITEM
    test.loc[(test.step_rank == 1) & (test.action == 'clickout item'), 'last_item'] = DUMMY_ITEM

    train.loc[(train.step_rank == 2) & (train.action == 'clickout item'), 'second_last_item'] = DUMMY_ITEM
    test.loc[(test.step_rank == 2) & (test.action == 'clickout item'), 'second_last_item'] = DUMMY_ITEM

    train.loc[(train.step_rank == 3) & (train.action == 'clickout item'), 'third_last_item'] = DUMMY_ITEM
    test.loc[(test.step_rank == 3) & (test.action == 'clickout item'), 'third_last_item'] = DUMMY_ITEM
    
    # ignore this
    keep_columns = ['session_id', 'user_id','item_id', 'impressions','prices', 'city', 'step', 'last_item']
    all_cat_columns = ['item_id', 'city', 'platform', 'device','country','country_platform','action','device_platform']

    
    # generate country from city
    train['country'] = train.city.apply(lambda x:x.split(',')[-1])
    test['country'] = test.city.apply(lambda x:x.split(',')[-1])
    
#     stworzenie kolumny skonkatenowanej z country oraz platform, to samo z device i platform
    # concate country and platform in string format as a new feature
    train['country_platform'] = train.apply(lambda row: row.country + row.platform, axis=1)
    test['country_platform'] = test.apply(lambda row: row.country + row.platform, axis=1)

    train['device_platform'] = train.apply(lambda row: row.device + row.platform, axis=1)
    test['device_platform'] = test.apply(lambda row: row.device + row.platform, axis=1)
    # filter out rows where reference doesn't present in impression
    # train = train.loc[train.apply(lambda row:row.item_id in row.impressions, axis=1),:]
    print("train.shape:", train.shape)
    print("test.shape:", test.shape)

train.shape: (1000, 21)
test.shape: (1000, 20)
[preprocessing] done in 0.31856 s

In [35]:
# Mapowanie session_id do listy występujących: item_id, action oraz step

# concat train and test
data = pd.concat([train, test], axis=0)
data = data.reset_index(drop=True)

# compute a dicationary that maps session id to the sequence of item ids in that session
train_session_interactions = dict(train.groupby('session_id')['item_id'].apply(list))
test_session_interactions = dict(test.groupby('session_id')['item_id'].apply(list))

# compute a dicationary that maps session id to the sequence of action in that session
train_session_actions = dict(train.groupby('session_id')['action'].apply(list))
test_session_actions = dict(test.groupby('session_id')['action'].apply(list))

# compute session session step since the "step" column in some session is not correctly order
train['sess_step'] = train.groupby('session_id')['timestamp'].rank(method='max').apply(int)
test['sess_step'] = test.groupby('session_id')['timestamp'].rank(method='max').apply(int)

D:\Instalowane\Programy\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

In [36]:
# 'time_diff" - czas między akcjami
# 'time_diff2" - czas między akcjami z pominięciem 2 wierszy (akcji)
# wyciągnięcie godziny z timestampu

data_feature = data.loc[:,['id','step','session_id', 'timestamp','platform','country']].copy()

# compute the time difference between each step
data_feature['time_diff'] = data.groupby('session_id')['timestamp'].diff()

# compute the difference of time difference between each step
data_feature['time_diff_diff'] = data_feature.groupby('session_id')['time_diff'].diff()

# compute the difference of the difference of time difference between each step
data_feature['time_diff_diff_diff'] = data_feature.groupby('session_id')['time_diff_diff'].diff()

# compute the time difference from 2 steps ahead
data_feature['time_diff_2'] = data.groupby('session_id')['timestamp'].diff().shift(1)

# compute the time difference from 3 steps ahead
data_feature['time_diff_3'] = data.groupby('session_id')['timestamp'].diff().shift(2)

data_feature['hour']= pd.to_datetime(data_feature.timestamp, unit='s').dt.hour//4

# # map platform to country
# data_feature['mapped_country'] = data_feature.platform.apply(platform2country)

# # load the precomputed country to utc offsets from geopy
# with open('../input/country2offsets_dict.p','rb') as f:
#     platform_country2offsets_dict = pickle.load(f)
# data_feature['platform2country_utc_offsets'] = data_feature.mapped_country.map(platform_country2offsets_dict)


# trasnform time difference with rank gauss
data_feature['rg_time_diff'] = GaussRankScaler().fit_transform(data_feature['time_diff'].values)

# compute the log of step
data_feature['step_log'] = np.log1p(data_feature['step'])

# drop the useless columns
# data_feature = data_feature.drop(['session_id','step','timestamp','hour','platform','country','mapped_country'], axis=1)
data_feature = data_feature.drop(['session_id','step','timestamp','hour','platform','country'], axis=1)

In [37]:
# merge train, test with data_feature
train = train.merge(data_feature, on='id', how='left')
test = test.merge(data_feature, on='id', how='left')
print("train.shape:", train.shape)
print("test.shape:", test.shape)

train.shape: (1000, 29)
test.shape: (1000, 28)

In [38]:
# compute the sequence of time difference in each session
train_session_time_diff = dict(train.groupby('session_id')['time_diff'].apply(list))
test_session_time_diff = dict(test.groupby('session_id')['time_diff'].apply(list))

In [49]:
# Utworzenie listy zawierającej enkodery dla każdej cechy, tego potrzebującej

# encode the categorical feture
cat_encoders = {}
for col in all_cat_columns:
    cat_encoders[col] = CategoricalEncoder()


all_items = []
for imp in data.loc[~data.impressions.isna()].impressions.tolist() + [data.item_id.apply(str).tolist()] :
    all_items += imp

# all_items = map(int, all_items)
unique_items = OrderedSet(all_items)
unique_actions = OrderedSet(data.action.values)

cat_encoders['item_id'].fit(list(unique_items) + [DUMMY_ITEM])
cat_encoders['action'].fit( list(unique_actions) + [DUMMY_ACTION])
for col in  ['city', 'platform', 'device','country','country_platform', 'device_platform']:
    cat_encoders[col].fit(data[col].tolist() )
    
# transform all the categorical columns to continuous integer
for col in all_cat_columns:
    train[col] = cat_encoders[col].transform(train[col].values)
    test[col] = cat_encoders[col].transform(test[col].values)

# get the encoded action
transformed_clickout_action = cat_encoders['action'].transform(['clickout item'])[0]
transformed_dummy_item = cat_encoders['item_id'].transform([DUMMY_ITEM])[0]
transformed_dummy_action = cat_encoders['action'].transform([DUMMY_ACTION])[0]
transformed_interaction_image = cat_encoders['action'].transform(['interaction item image'])[0]
transformed_interaction_deals = cat_encoders['action'].transform(['interaction item deals'])[0]
transformed_interaction_info = cat_encoders['action'].transform(['interaction item info'])[0]
transformed_interaction_rating = cat_encoders['action'].transform(['interaction item rating'])[0]

In [50]:
# lista rozpoczynająca się 30 zakodowanymi item_id dla -1 
# + lista zakodowanych item_id występujących w danej sesji w określony sposób

# transform session interactions and pad dummy in front of all of them
for session_id, item_list in train_session_interactions.items():
    train_session_interactions[session_id] = [transformed_dummy_item] * configuration.sess_length + list(cat_encoders['item_id'].transform(item_list))

for session_id, item_list in test_session_interactions.items():
    test_session_interactions[session_id] = [transformed_dummy_item] * configuration.sess_length + list(cat_encoders['item_id'].transform(item_list))
    
for session_id, action_list in train_session_actions.items():
    train_session_actions[session_id] = [transformed_dummy_action] * configuration.sess_length + list(cat_encoders['action'].transform(action_list))

for session_id, action_list in test_session_actions.items():
    test_session_actions[session_id] = [transformed_dummy_action] * configuration.sess_length + list(cat_encoders['action'].transform(action_list))

In [51]:
# import itertools
# ### compute co-occurence matrix
# implicit_train = train.loc[train.action != transformed_clickout_action, :]
# implicit_test = test.loc[test.action != transformed_clickout_action, :]

# # get all interacted items in a session
# implicit_all = pd.concat([implicit_train , implicit_test], axis=0)
# # a list of list containing items in the same session
# co_occ_items = implicit_all.groupby('session_id').item_id.apply(list).to_dict().values()
# co_occ_permutes = [list(itertools.permutations(set(items), 2)) for items in co_occ_items]

# #aggregate co-ocurrence across sessions
# co_occ_coordinates = []
# for coordinates in  co_occ_permutes:
#     co_occ_coordinates += coordinates

# #construct csr
# row, col, values = zip(*((i,j,1) for i,j in co_occ_coordinates ))
# co_occ_matrix= csr_matrix((values, (row, col)), shape=(cat_encoders['item_id'].n_elements, cat_encoders['item_id'].n_elements), dtype=np.float32)

# co_occ_matrix_csc = co_occ_matrix.tocsc()

# print("max entry: ", co_occ_matrix.max())

In [52]:
# categorically encode last, second last and third item
train['last_item'] = cat_encoders['item_id'].transform(train['last_item'].astype(str).values)
test['last_item'] = cat_encoders['item_id'].transform(test['last_item'].astype(str).values)

train['second_last_item'] = cat_encoders['item_id'].transform(train.second_last_item.astype(str).values)
test['second_last_item'] = cat_encoders['item_id'].transform(test.second_last_item.astype(str).values)

train['third_last_item'] = cat_encoders['item_id'].transform(train.third_last_item.astype(str).values)
test['third_last_item'] = cat_encoders['item_id'].transform(test.third_last_item.astype(str).values)

In [53]:
# genetate item properties features 
item_meta = item_meta.loc[item_meta.item_id.isin(unique_items),:]
# item_meta multi-hot
item_meta['item_id'] = cat_encoders['item_id'].transform(item_meta['item_id'].values)
item_meta['star'] = np.nan
item_meta.loc[item_meta.properties.apply(lambda x: '1 Star' in x), 'star'] = 1
item_meta.loc[item_meta.properties.apply(lambda x: '2 Star' in x), 'star'] = 2
item_meta.loc[item_meta.properties.apply(lambda x: '3 Star' in x), 'star'] = 3
item_meta.loc[item_meta.properties.apply(lambda x: '4 Star' in x), 'star'] = 4
item_meta.loc[item_meta.properties.apply(lambda x: '5 Star' in x), 'star'] = 5
item_meta.loc[(item_meta.star.isna()) & (item_meta.properties.apply(lambda y: 'Excellent Rating' in y) ), 'star'] = 9
item_meta.loc[(item_meta.star.isna()) & (item_meta.properties.apply(lambda y: 'Very Good Rating' in y) ), 'star'] = 8
item_meta.loc[(item_meta.star.isna()) & (item_meta.properties.apply(lambda y: 'Good Rating' in y) ), 'star'] = 7
item_meta.loc[(item_meta.star.isna()) & (item_meta.properties.apply(lambda y: 'Satisfactory Rating' in y) ), 'star'] = 6

item_meta['rating'] = np.nan
item_meta.loc[item_meta.properties.apply(lambda x: 'Satisfactory Rating' in x), 'rating'] = 7.0
item_meta.loc[item_meta.properties.apply(lambda x: 'Good Rating' in x), 'rating'] = 7.5
item_meta.loc[item_meta.properties.apply(lambda x: 'Very Good Rating' in x), 'rating'] = 8.0
item_meta.loc[item_meta.properties.apply(lambda x: 'Excellent Rating' in x), 'rating'] = 8.5

# get binary properties feature
item_properties_df = pd.DataFrame()
item_properties_df['item_id'] = item_meta.item_id
item_properties_df['num_properties'] = item_meta.properties.apply(len)
item_properties_df['star'] = item_meta.star
item_properties_df['item_Beach'] = item_meta.properties.apply(lambda x: 'Beach' in x).astype(np.float16)
item_properties_df['item_Bed & Breakfast'] = item_meta.properties.apply(lambda x: 'Bed & Breakfast' in x).astype(np.float16)
item_properties_df['rating'] = item_meta['rating']


item_star_map = item_properties_df.loc[:,['item_id','star']].set_index('item_id').to_dict()['star']
item_rating_map = item_properties_df.loc[:,['item_id','rating']].set_index('item_id').to_dict()['rating']

In [54]:
del  item_meta
gc.collect()

139

In [55]:
# # ignore filter_df , not using, consume huge memory yet increase a little
# filter_df = data.loc[ ~data.current_filters.isna(), ['id', 'current_filters']]
# filter_df['current_filters'] = filter_df.current_filters.apply(lambda x:x.split('|'))

# # filter_df.loc[filter_df.current_filters.apply(lambda x: '3 Star' in x), 'nights'] = 3
# filter_df['nights']=np.nan
# filter_df.loc[filter_df.current_filters.apply(lambda x: '2 Nights' in x), 'nights'] = 1
# filter_df.loc[filter_df.current_filters.apply(lambda x: '3 Nights' in x), 'nights'] = 2

# filter_set = list(set(np.hstack(filter_df['current_filters'].to_list())))

# cat_encoders['filters'] = CategoricalEncoder()
# cat_encoders['filters'].fit(filter_set)

# # get binary filter feature
# filters_df = pd.DataFrame()
# filters_df['id'] = filter_df.id
# filters_df['num_filters'] = filter_df.current_filters.apply(len)
# filters_df['breakfast_included'] = filter_df.current_filters.apply( lambda x: 'Breakfast Included' in x).astype(np.float16)
# filters_df['filters_Sort By Price'] = filter_df.current_filters.apply( lambda x: 'Sort by Price' in x).astype(np.float16)
# filters_df['filters_Sort By Popularity'] = filter_df.current_filters.apply( lambda x: 'Sort By Popularity' in x).astype(np.float16)

In [56]:
# zliczanie interakcji dla każdego item_id dla różnych akcji
# ile razy wystąpił item_id w impressions
# GaussRankScaler dla price

# compute interaction image count for each item across train/ test
interaction_image_item_ids = train.loc[train.action == transformed_interaction_image, :].drop_duplicates(subset=['session_id','item_id','action']).item_id.tolist() + test.loc[test.action == transformed_interaction_image, :].drop_duplicates(subset=['session_id','item_id','action']).item_id.tolist()
unique_interaction_image_items, counts = np.unique(interaction_image_item_ids, return_counts=True)
global_image_count_dict = dict(zip(unique_interaction_image_items, counts))  

# compute interaction count for each item across train/ test
interaction_item_ids = train.loc[train.action != transformed_clickout_action, :].drop_duplicates(subset=['session_id','item_id','action']).item_id.tolist() + test.loc[test.action != transformed_clickout_action, :].drop_duplicates(subset=['session_id','item_id','action']).item_id.tolist()
unique_interaction_items, counts = np.unique(interaction_item_ids, return_counts=True)
global_interaction_count_dict = dict(zip(unique_interaction_items, counts)) 

# compute interaction deals count for each item across train/ test
interaction_deals_item_ids = train.loc[train.action == transformed_interaction_deals, :].drop_duplicates(subset=['session_id','item_id','action']).item_id.tolist() + test.loc[test.action == transformed_interaction_deals, :].drop_duplicates(subset=['session_id','item_id','action']).item_id.tolist()
unique_interaction_deals_items, counts = np.unique(interaction_deals_item_ids, return_counts=True)
global_deals_count_dict = dict(zip(unique_interaction_deals_items, counts))

# compute step rank to identify the last row in each session for train/ val split
train = train.loc[train.action == transformed_clickout_action,:]
test = test.loc[test.action == transformed_clickout_action,:]
train['step_rank'] = train.groupby('session_id')['step'].rank(method='max', ascending=False)


# compute the impression count for each item - views?
item_ids = np.hstack([np.hstack(train['impressions'].values), np.hstack(test.impressions.values)])
unique_items, counts = np.unique(item_ids, return_counts=True)
impression_count_dict = dict(zip(unique_items, counts))

# compute the rank gauss transformed prices
unique_prices = np.unique(np.hstack([np.hstack(train.prices.values), np.hstack(test.prices.values)]) )
rg_unique_prices = GaussRankScaler().fit_transform(unique_prices)
price_rg_price_dict = dict(zip(unique_prices, rg_unique_prices))

print("train.shape:", train.shape)
print("test.shape:", test.shape)

train.shape: (139, 29)
test.shape: (139, 28)

In [57]:
#train/ val split
# if configuration.debug:
#     val = train.loc[train.step_rank == 1,:].iloc[:5]
# else:
val = train.loc[train.step_rank == 1,:].iloc[:50000]

val_index = val.index
train = train.loc[~train.index.isin(val_index),:]

train = train.drop('step_rank', axis=1)
val = val.drop('step_rank', axis=1)

print("train.shape:", train.shape)
print("test.shape:", test.shape)
print("val.shape:", val.shape)

train.shape: (24, 28)
test.shape: (139, 28)
val.shape: (115, 28)

In [58]:
# get the encoded nan item
transformed_nan_item = cat_encoders['item_id'].transform(['nan'])[0]

In [59]:
from collections import defaultdict, Counter
session_clickout_count_dict = {}
past_interaction_dict = {}
last_click_sess_dict = {}
last_impressions_dict = {}
sess_last_imp_idx_dict={}
sess_last_price_dict  = {}
sess_time_diff_dict ={}
sess_step_diff_dict = {}

cumulative_click_dict = defaultdict(lambda : 0)

In [61]:
# for idx, row in enumerate(tqdm(train[:2].itertuples())):
#     print(type(row))
#     print((row.index))

In [123]:
def parse_impressions(df, session_interactions, session_actions, session_time_diff, training=True):
    # parse the data into a binary classification task, generate 1 example for each item in the impression list
    df_list = []
    label_test_df_list = []
    # parse impressions for train set
    past_interaction_rows = []
    past_interaction_columns = []
    for idx, row in enumerate(tqdm(df.itertuples())):

        if row.session_id not in session_clickout_count_dict:
            session_clickout_count_dict[row.session_id] = 0

        if row.user_id not in past_interaction_dict:
            past_interaction_dict[row.user_id] = []
        
        
        sess_step = row.sess_step
        session_id = row.session_id

        # compute the categorically encoded impression list
        transformed_impressions = cat_encoders['item_id'].transform(row.impressions, to_np=True) 

        current_rows = np.zeros([len(row.impressions), 66], dtype=object)

        # compute rank of price this clickout
        price_rank = compute_rank(row.prices)

        #compute the number of interactions associated with the last interacted item in this session
        equal_last_item_indices = np.array(session_interactions[session_id][:configuration.sess_length+ sess_step -1]) == row.last_item
        last_item_interaction = len(set(np.array(session_actions[session_id][:configuration.sess_length+ sess_step -1])[equal_last_item_indices]))

        # zlicza liczbę interakcji dla każdej akcji innej niż clickout item
        #compute the local interaction count for each item id
        interaction_indices = np.array(session_actions[session_id][:configuration.sess_length+ sess_step -1]) != transformed_clickout_action
        interaction_item =  np.array(session_interactions[session_id][:configuration.sess_length+ sess_step -1])[interaction_indices]
        sess_unique_items, counts = np.unique(interaction_item, return_counts=True)
        interaction_count_dict = dict(zip(sess_unique_items, counts))

        #compute the local interaction image count for each item id
        interaction_image_indices = np.array(session_actions[session_id][:configuration.sess_length+ sess_step -1]) == transformed_interaction_image
        interaction_image_item =  np.array(session_interactions[session_id][:configuration.sess_length+ sess_step -1])[interaction_image_indices]
        sess_unique_image_items, counts = np.unique(interaction_image_item, return_counts=True)
        interaction_image_count_dict = dict(zip(sess_unique_image_items, counts))

        #compute the local interaction deals count for each item id
        interaction_deals_indices = np.array(session_actions[session_id][:configuration.sess_length+ sess_step -1]) == transformed_interaction_deals
        interaction_deals_item =  np.array(session_interactions[session_id][:configuration.sess_length+ sess_step -1])[interaction_deals_indices]
        sess_unique_deals_items, counts = np.unique(interaction_deals_item, return_counts=True)
        interaction_deals_count_dict = dict(zip(sess_unique_deals_items, counts))

        #compute the local clickout count for each item id
        interaction_clickout_indices = np.array(session_actions[session_id][:configuration.sess_length+ sess_step -1]) == transformed_clickout_action
        interaction_clickout_item =  np.array(session_interactions[session_id][:configuration.sess_length+ sess_step -1])[interaction_clickout_indices]
        sess_unique_clickout_items, counts = np.unique(interaction_clickout_item, return_counts=True)
        interaction_clickout_count_dict = dict(zip(sess_unique_clickout_items, counts))

        #compute the local interaction rating count for each item id
        interaction_rating_indices = np.array(session_actions[session_id][:configuration.sess_length+ sess_step -1]) == transformed_interaction_rating
        interaction_rating_item =  np.array(session_interactions[session_id][:configuration.sess_length+ sess_step -1])[interaction_rating_indices]
        sess_unique_rating_items, counts = np.unique(interaction_rating_item, return_counts=True)
        interaction_rating_count_dict = dict(zip(sess_unique_rating_items, counts))

        # array time_diff, bez nan, chyba
        # get the time diffference array in this session for later computing the average of it
        finite_time_diff_indices = np.isfinite(session_time_diff[session_id][:sess_step -1])
        finite_time_diff_array = np.array(session_time_diff[session_id][:sess_step -1])[finite_time_diff_indices]
        

    
        # unpad the interactions
        unpad_interactions = session_interactions[session_id][configuration.sess_length:configuration.sess_length+ sess_step -1]
        unique_interaction = pd.unique(session_interactions[session_id][:configuration.sess_length+ sess_step -1])
        
        
        # time elapse of within two steps for each item before the clickout
        item_time_elapse_dict = {}
        for it, elapse in zip(unpad_interactions[:-1], session_time_diff[session_id][1:sess_step -1]):
            if it not in item_time_elapse_dict: 
                item_time_elapse_dict[it] = [elapse]
                
            else:
                item_time_elapse_dict[it].append(elapse)

        # compute time_diff for each item in the session
        interact_diff = [unpad_interactions[::-1].index(imp) if imp in unpad_interactions else np.nan for imp in transformed_impressions]
        item_time_diff =  np.array([ sum(session_time_diff[session_id][sess_step - diff -1 :sess_step]) if np.isfinite(diff) else np.nan for diff in interact_diff])

        target_index = transformed_impressions.tolist().index(row.item_id) if training else np.nan

#         #(imp len, num items)        
#         current_co_occ = co_occ_matrix[transformed_impressions,:]

        
#         #(imp len, num unique items in the session b4 this clickout)
#         current_co_occ = current_co_occ[:,sess_unique_items].toarray()

#         # (1, num unique items in the session b4 this clickout)
#         # print(current_co_occ.dtype)

#         norm =  (1 + co_occ_matrix_csc[:, sess_unique_items].sum(axis=0).reshape(-1))

        # #(imp len, num items)        
        # imp_current_co_occ = imp_co_occ_matrix[transformed_impressions,:]

        
        # #(imp len, num unique items in the session b4 this clickout)
        # imp_current_co_occ = imp_current_co_occ[:,sess_unique_items].toarray()

        # # (1, num unique items in the session b4 this clickout)
        # # print(current_co_occ.dtype)

        # imp_norm =  (1 + imp_co_occ_matrix_csc[:, sess_unique_items].sum(axis=0).reshape(-1))

        # norm_imp_current_co_occ = imp_current_co_occ / imp_norm

        # the position of the last interacted item in the current impression list
        if row.last_item in transformed_impressions:
            last_interact_index = transformed_impressions.tolist().index(row.last_item)
        else:
            last_interact_index = np.nan

        # the position of the second last interacted item in the current impression list
        if row.second_last_item in transformed_impressions:
            second_last_interact_index = transformed_impressions.tolist().index(row.second_last_item)
        else:
            second_last_interact_index = np.nan

        # the position of the third last interacted item in the current impression list
        if row.third_last_item in transformed_impressions:
            third_last_interact_index = transformed_impressions.tolist().index(row.third_last_item)
        else:
            third_last_interact_index = np.nan

        # initialize dictionaries
        if row.session_id not in last_click_sess_dict:
            last_click_sess_dict[row.session_id] = transformed_dummy_item

        if row.session_id not in last_impressions_dict:
            last_impressions_dict[row.session_id] = None

        if row.session_id not in sess_last_imp_idx_dict:
            sess_last_imp_idx_dict[row.session_id] = DUMMY_IMPRESSION_INDEX

        if row.session_id not in sess_last_price_dict:
            sess_last_price_dict[row.session_id] = None
        
        if row.session_id not in sess_time_diff_dict:
            sess_time_diff_dict[row.session_id] = None
        
        if row.session_id not in sess_step_diff_dict:
            sess_step_diff_dict[row.session_id] = None

        
        # item id
        current_rows[:, 0] = transformed_impressions
        
        # label
        current_rows[:, 1] = transformed_impressions == row.item_id
        current_rows[:, 2] = row.session_id
        
        # whether current item id equal to the last interacted item id
        current_rows[:, 3] = transformed_impressions == row.last_item 
        current_rows[:, 4] = price_rank
        current_rows[:, 5] = row.platform
        current_rows[:, 6] = row.device
        current_rows[:, 7] = row.city
        current_rows[:, 8] = row.prices
        current_rows[:, 9] = row.country
        
        # impression index
        current_rows[:, 10] = np.arange(len(row.impressions))
        current_rows[:, 11] = row.step
        current_rows[:, 12] = row.id
        
        # last_click_item: last clickout item id
        current_rows[:, 13] = last_click_sess_dict[row.session_id]
        
        # equal_last_impressions: current impression list is eactly the same as the last one that the user encountered 
        current_rows[:, 14] = last_impressions_dict[row.session_id] == transformed_impressions.tolist() 

         
        current_rows[:, 15] = sess_last_imp_idx_dict[row.session_id]
        # last_interact_index
        current_rows[:, 16] = last_interact_index

        # price_diff
        current_rows[:, 17] = row.prices - sess_last_price_dict[row.session_id] if sess_last_price_dict[row.session_id] else np.nan

        # last_price
        current_rows[:, 18] = sess_last_price_dict[row.session_id] if sess_last_price_dict[row.session_id] else np.nan

        # price_ratio
        current_rows[:, 19] = row.prices / sess_last_price_dict[row.session_id] if sess_last_price_dict[row.session_id] else np. nan

        # clickout_time_diff
        current_rows[:, 20] = row.timestamp - sess_time_diff_dict[row.session_id] if sess_time_diff_dict[row.session_id] else np.nan

        # country_platform
        current_rows[:, 21] = row.country_platform

        # impression_count
        current_rows[:, 22] = [impression_count_dict[imp] for imp in row.impressions]
        
        # is_interacted: if that item has been interaced in the current session
        current_rows[:, 23] = [imp in session_interactions[session_id][:configuration.sess_length+ sess_step -1] for imp in transformed_impressions]
        
        # local_interaction_image_count
        current_rows[:, 24] = [interaction_image_count_dict[imp] if imp in interaction_image_count_dict else 0 for imp in transformed_impressions] 
        # local_interaction_deals_count
        current_rows[:, 25] = [interaction_deals_count_dict[imp] if imp in interaction_deals_count_dict else 0 for imp in transformed_impressions] 

        # local_interaction_clickout_count
        current_rows[:, 26] = [interaction_clickout_count_dict[imp] if imp in interaction_clickout_count_dict else 0 for imp in transformed_impressions] 

        # global_interaction_image_count
        current_rows[:, 27] = [global_image_count_dict[imp] if imp in global_image_count_dict else 0 for imp in transformed_impressions] 

        # global_interaction_deals_count
        current_rows[:, 28] = [global_deals_count_dict[imp] if imp in global_deals_count_dict else 0 for imp in transformed_impressions] 

        # is_clicked
        current_rows[:, 29] = [imp in past_interaction_dict[row.user_id] for imp in transformed_impressions]

        # click_diff - jak dawno miał interakcje z danym impressions
        current_rows[:, 30] = [past_interaction_dict[row.user_id][::-1].index(imp) if imp in past_interaction_dict[row.user_id] else np.nan for imp in transformed_impressions]

        # average of the previous features
        for i in range(31, 38):
            current_rows[:, i]  = np.mean(current_rows[:, i-8])

        # impression_avg_prices
        current_rows[:, 38] = np.mean(row.prices)
        current_rows[:, 39] = row.device_platform

        # equal_max_liic: euqal the maximum of local interaction image count
        current_rows[:, 40] = np.array(current_rows[:, 24]) == np.max(current_rows[:, 24]) if sum(current_rows[:, 24]) >0 else False

        # num_interacted_items
        current_rows[:, 41] = len(np.unique(session_interactions[session_id][:configuration.sess_length+ sess_step -1]))

        # equal_second_last_item
        current_rows[:, 42] = transformed_impressions == row.second_last_item 

        # last_action
        current_rows[:, 43] = session_actions[session_id][configuration.sess_length+ sess_step -2]

        # last_second_last_imp_idx_diff
        current_rows[:, 44] = last_interact_index - second_last_interact_index

        # predicted_next_imp_idx (the idea is to trace your eyeball, last_interact_index + (last_interact_index - second_last_interact_index))
        current_rows[:, 45] = 2 * last_interact_index - second_last_interact_index

        # list_len
        current_rows[:, 46] = len(row.impressions)
        
        # imp_idx_velocity
        current_rows[:, 47] = last_interact_index - 2 * second_last_interact_index + third_last_interact_index

        # time_diff_sess_avg
        current_rows[:, 48] = np.mean(finite_time_diff_array)
        
        # max_time_elapse
        current_rows[:, 49] = [ max(item_time_elapse_dict[imp]) if imp in item_time_elapse_dict else np.nan for imp in transformed_impressions]

        # sum_time_elapse
        current_rows[:, 50] = [ sum(item_time_elapse_dict[imp]) if imp in item_time_elapse_dict else np.nan for imp in transformed_impressions]

        # avg_time_elapse
        current_rows[:, 51] = [ np.mean(item_time_elapse_dict[imp]) if imp in item_time_elapse_dict else np.nan for imp in transformed_impressions]

        # item_time_diff  
        current_rows[:, 52] = item_time_diff

        # global_interaction_count
        current_rows[:, 53] = [global_interaction_count_dict[imp] if imp in global_interaction_count_dict else 0 for imp in transformed_impressions] 

        # average global_interaction_count
        current_rows[:, 54] = np.mean(current_rows[:, 53])

        # std of global interaction image count
        current_rows[:, 55] = np.std(current_rows[:, 27])
        
        # std of glocal interaction conut
        current_rows[:, 56] = np.std(current_rows[:, 53])

        # local_interaction_count
        current_rows[:, 57] = [interaction_count_dict[imp] if imp in interaction_count_dict else 0 for imp in transformed_impressions] 
        current_rows[:, 58] = target_index

        # target price
        current_rows[:, 59] = row.prices[target_index] if not np.isnan(target_index) else np.nan

        # normalized co-occurence statistics
#         current_rows[:, 60] = np.mean(current_co_occ/ norm, axis=1).reshape(-1)
#         current_rows[:, 61] = np.min(current_co_occ/ norm, axis=1).reshape(-1)
#         current_rows[:, 62] = np.max(current_co_occ/norm, axis=1).reshape(-1)
#         current_rows[:, 63] = np.median(current_co_occ/norm, axis=1).reshape(-1)

        # last_item_interaction
        current_rows[:, 64] = last_item_interaction

        # target price rank
        current_rows[:, 65] = price_rank[target_index] if not np.isnan(target_index) else np.nan
        # current_rows[:, 66] = np.mean(norm_imp_current_co_occ, axis=1).reshape(-1)
        # current_rows[:, 67] = np.min(norm_imp_current_co_occ, axis=1).reshape(-1)
        # current_rows[:, 68] = np.max(norm_imp_current_co_occ, axis=1).reshape(-1)
        # current_rows[:, 69] = np.median(norm_imp_current_co_occ, axis=1).reshape(-1)
        
        if training or row.item_id == transformed_nan_item:
            df_list.append(current_rows)
        else:
            label_test_df_list.append(current_rows) 
        # cumulative_click_dict[row.item_id] += 1
        past_interaction_dict[row.user_id].append(row.item_id)
        last_click_sess_dict[row.session_id] = row.item_id
        last_impressions_dict[row.session_id] = transformed_impressions.tolist()
        sess_time_diff_dict[row.session_id] = row.timestamp
        sess_step_diff_dict[row.session_id] = row.step
        if row.item_id != transformed_nan_item:
            sess_last_imp_idx_dict[row.session_id] = (transformed_impressions == row.item_id).tolist().index(True)
            sess_last_price_dict[row.session_id] = np.array(row.prices)[ transformed_impressions == row.item_id ][0]
            # cumulative_click_dict[row.item_id]  += 1
    
    data = np.vstack(df_list)
    df_columns = ['item_id', 'label', 'session_id', 'equal_last_item', 'price_rank', 'platform', 'device', 'city', 'price', 'country', 'impression_index','step', 'id','last_click_item','equal_last_impressions', 'last_click_impression','last_interact_index','price_diff','last_price','price_ratio','clickout_time_diff','country_platform','impression_count','is_interacted','local_interaction_image_count','local_interaction_deals_count','local_interaction_clickout_count','global_interaction_image_count','global_interaction_deals_count','is_clicked','click_diff', 'avg_is_interacted','avg_liic', 'avg_lidc','avg_licc','avg_giic','avg_gdc','avg_is_clicked','impression_avg_prices','device_platform','equal_max_liic','num_interacted_items','equal_second_last_item','last_action','last_second_last_imp_idx_diff','predicted_next_imp_idx', 'list_len','imp_idx_velocity','time_diff_sess_avg','max_time_elapse','sum_time_elapse','avg_time_elapse','item_time_diff','global_interaction_count','avg_gic','std_giic','std_gic','local_interaction_count','target_index','target_price','co_occ_mean_norm','co_occ_min_norm','co_occ_max_norm','co_occ_median_norm','last_item_interaction','target_price_rank']
    dtype_dict = {"item_id":"int32", "label": "int8", "equal_last_item":"int8", "step":"int16", "price_rank": "int32","impression_index":"int32", "platform":"int32","device":"int32","city":"int32", "id":"int32", "country":"int32", "price":"int16", "last_click_item":"int32", "equal_last_impressions":"int8", 'last_click_impression':'int16', 'last_interact_index':'float32', 'price_diff':'float16','last_price':'float16','price_ratio':'float32','clickout_time_diff':'float16','country_platform':'int32','impression_count':'int32','is_interacted':'int8','local_interaction_image_count':'int32','local_interaction_deals_count':'int32','local_interaction_clickout_count':'int32','global_interaction_image_count':'int32','global_interaction_deals_count':'int32','is_clicked':'int8','click_diff':'float32'\
                , 'avg_is_interacted':'float16' ,'avg_liic':'float16', 'avg_lidc':'float32','avg_licc':'float32','avg_giic':'float32','avg_gdc':'float32','avg_is_clicked':'float32','impression_avg_prices':'float32','device_platform':'int32','equal_max_liic':'int8','num_interacted_items':'int32','equal_second_last_item':'int8','last_action':'int32','last_second_last_imp_idx_diff':'float32', 'predicted_next_imp_idx': 'float32','list_len':'int16','imp_idx_velocity':'float32','time_diff_sess_avg':'float32','max_time_elapse':'float32','sum_time_elapse':'float32','avg_time_elapse':'float32','item_time_diff':'float32','global_interaction_count':'float32','avg_gic':'float32','std_giic':'float32','std_gic':'float32','local_interaction_count':'int32','target_index':'float32','target_price':'float32','co_occ_mean_norm':'float32','co_occ_min_norm':'float32','co_occ_max_norm':'float32','co_occ_median_norm':'float32','last_item_interaction':'int32','target_price_rank':'float32'} 
    df = pd.DataFrame(data, columns=df_columns)
    df = df.astype(dtype=dtype_dict )
    if training:
        return df
    else:
        label_test = np.vstack(label_test_df_list)
        label_test = pd.DataFrame(label_test, columns=df_columns)
        label_test = label_test.astype(dtype= dtype_dict)
        return df, label_test

In [63]:
train.sort_values('timestamp',inplace=True)
val.sort_values('timestamp',inplace=True)
test.sort_values('timestamp',inplace=True)

In [122]:
# print("sorted!!")
train = parse_impressions(train, train_session_interactions, train_session_actions, train_session_time_diff)
val = parse_impressions(val, train_session_interactions, train_session_actions, train_session_time_diff)
test, label_test = parse_impressions(test, test_session_interactions, test_session_actions, test_session_time_diff, training=False)

print("train.shape:", train.shape)
print("test.shape:", test.shape)
print("val.shape:", val.shape)
print("label_test.shape:", label_test.shape)

0it [00:00, ?it/s]

30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 112, 112, 113, 113, 113]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=21, index=21, session_id='6c4ba6d174134', timestamp=1541030436, user_id='CJ32S9QQ04RI', step=1, action=2, item_id=109, platform=5, city=16, device=1, current_filters=nan, impressions=['3143733', '103507', '5452024', '103600', '4775550', '2266812', '508561', '95011', '153936', '8162422', '980287', '103458', '1816153', '103672', '2111996', '2430542', '4774596', '1816151', '906417', '3132670', '824196', '103495', '103620', '8165060', '8350208'], prices=[164, 251, 188, 149, 133, 404, 113, 156, 84, 102, 126, 406, 94, 254, 127, 102, 127, 93, 132, 172, 192, 133, 216, 152, 120], id=21, last_item=5321, second_last_item=5321, third_last_item=5321, country=11, country_platform=12, device_platform=7, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=21.0, rg_time_diff=0.5835711016153999, step_log=0.6931471805599453)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 134, 5321, 1421]
[5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321]
[5433 5321]
Pandas(Index=23, index=23, session_id='dab0a59d898da', timestamp=1541030440, user_id='YXAK2A5U45VR', step=2, action=2, item_id=134, platform=3, city=6, device=1, current_filters=nan, impressions=['101012', '44161', '44348', '44344', '44690', '101006', '43499', '44167', '43774', '121124', '44545', '44342', '43603', '3123886', '1319714', '43498', '43655', '44337', '1285722', '960121', '44374', '44089', '43621', '43965', '44303'], prices=[37, 90, 71, 105, 161, 192, 114, 65, 161, 141, 73, 126, 100, 112, 118, 122, 107, 78, 231, 179, 86, 98, 128, 131, 96], id=23, last_item=5322, second_last_item=5321, third_last_item=5321, country=4, country_platform=4, device_platform=5, sess_step=2, time_diff=16.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.35331884552772413, step_log=1.0986122886681098)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 259, 259, 260, 261]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=75, index=75, session_id='21befe700aa7c', timestamp=1541030463, user_id='GPIQ7XR9K6MJ', step=1, action=2, item_id=259, platform=2, city=34, device=0, current_filters=nan, impressions=['67646', '1017983', '138068', '395501', '138007', '138063', '619681', '843491', '60787', '844436', '69317', '2223930', '7904994', '1198670', '2245752', '138067', '1017999', '66280', '138064', '69376', '1139814', '4973242', '1017981', '1198376', '961795'], prices=[71, 71, 44, 124, 79, 60, 56, 62, 48, 65, 68, 87, 97, 49, 88, 77, 57, 88, 52, 115, 149, 80, 78, 96, 88], id=75, last_item=5321, second_last_item=5323, third_last_item=5323, country=15, country_platform=16, device_platform=3, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.6986086019287104, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 287, 284, 284]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=95, index=95, session_id='afb99bef2f373', timestamp=1541030467, user_id='OPR0TY285KKP', step=1, action=2, item_id=287, platform=3, city=38, device=1, current_filters=nan, impressions=['3182924', '3135340', '3135343', '35169', '42836', '2561635', '35173', '4894814', '1400592', '35171', '979341', '3163718', '5155260', '943991', '1702439', '3757420', '3045134', '1017018', '43029', '2875932', '7171360', '10811256', '10865636', '10884168', '9994480'], prices=[95, 41, 37, 52, 43, 31, 45, 28, 70, 91, 125, 96, 115, 37, 36, 49, 40, 18, 128, 289, 31, 265, 265, 189, 114], id=95, last_item=5321, second_last_item=109, third_last_item=109, country=8, country_platform=8, device_platform=5, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.6470182477990317, step_log=0.6931471805599453)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 395, 395, 395]
[5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321]
[5433 5321]
Pandas(Index=137, index=137, session_id='730dbf90f28bb', timestamp=1541030477, user_id='LP2AMI5H1P2K', step=2, action=2, item_id=395, platform=4, city=25, device=1, current_filters=nan, impressions=['1250027', '1368776', '4088790', '1981249', '7030280', '3167664', '1981215', '2018159', '7807744', '103275', '8408886', '6019012', '3831066', '9995698', '8308940', '2894302', '6748650', '6938724', '103259', '1838153', '119306', '4574134', '2228070', '103248', '1351820'], prices=[27, 54, 41, 23, 16, 26, 12, 11, 40, 202, 34, 25, 31, 49, 56, 23, 49, 25, 139, 117, 59, 31, 40, 45, 24], id=137, last_item=5321, second_last_item=5321, third_last_item=5321, country=5, country_platform=5, device_platform=6, sess_step=2, time_diff=23.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=2.0, rg_time_diff=0.40450508851862943, step_log=1.0986122886681098)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 395, 395, 395]
[5321, 395]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 395]
[5433 5321  395]
Pandas(Index=145, index=145, session_id='730dbf90f28bb', timestamp=1541030480, user_id='LP2AMI5H1P2K', step=3, action=2, item_id=395, platform=4, city=25, device=1, current_filters=nan, impressions=['1250027', '1368776', '4088790', '1981249', '7030280', '3167664', '1981215', '2018159', '7807744', '103275', '8408886', '6019012', '3831066', '9995698', '8308940', '2894302', '6748650', '6938724', '103259', '1838153', '119306', '4574134', '2228070', '103248', '1351820'], prices=[27, 54, 41, 23, 16, 26, 12, 11, 40, 202, 34, 25, 31, 49, 56, 23, 49, 25, 139, 117, 59, 31, 40, 45, 24], id=145, last_item=421, second_last_item=521, third_last_item=5321, country=5, country_platform=5, device_platform=6, sess_step=3, time_diff=3.0, time_diff_diff=-20.0, time_diff_diff_diff=nan, time_diff_2=27.0, time_diff_3=0.0, rg_time_diff=0.06971640020044548, step_log=1.3862943611198906)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 470, 470, 475, 475, 475]
[5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321]
[5433 5321]
Pandas(Index=151, index=151, session_id='c1159dd77b548', timestamp=1541030482, user_id='FOM5X2ET44EK', step=2, action=2, item_id=470, platform=3, city=22, device=1, current_filters=nan, impressions=['948643', '1346370', '34350', '42663', '2196006', '100302', '43160', '42620', '2759726', '1693345', '2383711', '34345', '995577', '9694870', '3222602', '3385586', '8940514', '42342', '7180454', '995609', '3500744', '2880592', '9675972', '43114', '6670002'], prices=[110, 376, 238, 95, 88, 132, 298, 36, 88, 43, 87, 30, 33, 15, 55, 56, 56, 37, 64, 29, 63, 41, 37, 42, 243], id=151, last_item=5321, second_last_item=5321, third_last_item=445, country=8, country_platform=8, device_platform=5, sess_step=2, time_diff=31.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=3.0, rg_time_diff=0.44054677300349204, step_log=1.0986122886681098)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 470, 470, 475, 475, 475]
[5321, 470]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 470]
[5433 5321  470]
Pandas(Index=173, index=173, session_id='c1159dd77b548', timestamp=1541030486, user_id='FOM5X2ET44EK', step=3, action=2, item_id=470, platform=3, city=22, device=1, current_filters=nan, impressions=['948643', '1346370', '34350', '42663', '2196006', '100302', '43160', '42620', '2759726', '1693345', '2383711', '34345', '995577', '9694870', '3222602', '3385586', '8940514', '42342', '7180454', '995609', '3500744', '2880592', '9675972', '43114', '6670002'], prices=[110, 376, 238, 95, 88, 132, 298, 36, 88, 43, 87, 30, 33, 15, 55, 56, 56, 37, 64, 29, 63, 41, 37, 42, 243], id=173, last_item=5329, second_last_item=5327, third_last_item=5321, country=8, country_platform=8, device_platform=5, sess_step=3, time_diff=4.0, time_diff_diff=-27.0, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.09650245499810313, step_log=1.3862943611198906)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 555, 555, 533]
[5321, 555]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 555]
[5433 5321  555]
Pandas(Index=176, index=176, session_id='6b55590fb1df5', timestamp=1541030487, user_id='I5UULR2BQMXY', step=3, action=2, item_id=555, platform=2, city=20, device=1, current_filters=nan, impressions=['402151', '73454', '1963891', '152282', '68944', '55563', '68900', '56517', '5977202', '152279', '1276149', '152280', '77589', '63348', '58473', '3102222', '79263', '64541', '1237763', '5476840', '940956', '62817', '102307', '62818', '64514'], prices=[367, 64, 179, 198, 169, 138, 98, 76, 66, 150, 270, 57, 170, 119, 130, 146, 74, 89, 147, 123, 352, 259, 237, 125, 290], id=176, last_item=581, second_last_item=395, third_last_item=5321, country=15, country_platform=16, device_platform=14, sess_step=3, time_diff=38.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=10.0, time_diff_3=6.0, rg_time_diff=0.47443468930889615, step_log=1.3862943611198906)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 555, 555, 533]
[5321, 555]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 555]
[5433 5321  555]
Pandas(Index=177, index=177, session_id='6b55590fb1df5', timestamp=1541030487, user_id='I5UULR2BQMXY', step=2, action=2, item_id=555, platform=2, city=20, device=1, current_filters=nan, impressions=['402151', '73454', '1963891', '152282', '68944', '55563', '68900', '56517', '5977202', '152279', '1276149', '152280', '77589', '63348', '58473', '3102222', '79263', '64541', '1237763', '5476840', '940956', '62817', '102307', '62818', '64514'], prices=[367, 64, 179, 198, 169, 138, 98, 76, 66, 150, 270, 57, 170, 119, 130, 146, 74, 89, 147, 123, 352, 259, 237, 125, 290], id=177, last_item=555, second_last_item=5321, third_last_item=395, country=15, country_platform=16, device_platform=14, sess_step=3, time_diff=0.0, time_diff_diff=-38.0, time_diff_diff_diff=nan, time_diff_2=38.0, time_diff_3=10.0, rg_time_diff=-0.17328977252723005, step_log=1.0986122886681098)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 185, 185, 185, 185]
[185, 185]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 185, 185]
[5433  185]
Pandas(Index=214, index=214, session_id='52b4184549d38', timestamp=1541030501, user_id='H147K5X0M08L', step=3, action=2, item_id=185, platform=2, city=28, device=0, current_filters=nan, impressions=['43120', '804296', '35158', '101455', '844266', '42400', '101452', '42489', '35167', '1390390', '1370232', '35152', '35151', '3409732', '42783', '35159', '10939302', '101451', '43061', '101456', '1335401', '843996', '152946', '1355549', '10149966'], prices=[165, 182, 174, 225, 215, 369, 66, 124, 235, 224, 83, 227, 302, 151, 135, 464, 349, 113, 158, 134, 732, 96, 226, 164, 164], id=214, last_item=113, second_last_item=113, third_last_item=5321, country=8, country_platform=18, device_platform=3, sess_step=3, time_diff=7.0, time_diff_diff=7.0, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=25.0, rg_time_diff=0.12793170101401716, step_log=1.3862943611198906)

11it [00:00, 106.06it/s]

30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2277, 2277, 470, 470, 470, 470, 470, 470]
[2277, 2277]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2277, 2277]
[5433 2277]
Pandas(Index=246, index=246, session_id='c46caf82e4cfc', timestamp=1541030504, user_id='251AFZASCPNY', step=3, action=2, item_id=470, platform=3, city=22, device=0, current_filters=nan, impressions=['948643', '100302', '34351', '34337', '740596', '43174', '42894', '42363', '1350878', '34338', '42334', '42952', '5653536', '42402', '34343', '42450', '34348', '18230', '34342', '1346370', '34350', '43160', '42446', '2196006'], prices=[70, 93, 31, 53, 28, 44, 90, 54, 169, 55, 38, 46, 34, 87, 44, 170, 81, 108, 40, 392, 34, 138, 33, 57], id=246, last_item=964, second_last_item=964, third_last_item=5321, country=8, country_platform=8, device_platform=11, sess_step=3, time_diff=3.0, time_diff_diff=3.0, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.061701795572124296, step_log=1.3862943611198906)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 720, 720, 719]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=268, index=268, session_id='5db881b372567', timestamp=1541030508, user_id='MEMNU8Y87VYL', step=1, action=2, item_id=720, platform=11, city=67, device=0, current_filters=nan, impressions=['4440394', '105357', '101888', '101901', '2304018', '101895', '796746', '8140220', '101894', '105366', '101899', '101886', '109160', '4498136', '101892', '4386348', '1710457', '101891', '109159', '109155', '368421', '1199874', '1479831', '101882', '2922431'], prices=[95, 109, 113, 102, 115, 101, 95, 76, 115, 106, 105, 92, 74, 98, 109, 103, 104, 69, 122, 92, 106, 56, 106, 72, 92], id=268, last_item=5321, second_last_item=712, third_last_item=1007, country=18, country_platform=21, device_platform=18, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=33.0, rg_time_diff=0.7495332289834281, step_log=0.6931471805599453)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 799, 801]
[5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321]
[5433 5321]
Pandas(Index=271, index=271, session_id='c3ab0a7dd5987', timestamp=1541030509, user_id='BI7OPK1TOHG0', step=2, action=2, item_id=799, platform=10, city=37, device=0, current_filters=nan, impressions=['1090284', '180596', '930213', '1321522', '1323046', '1204178', '1478241', '784396', '180166', '5123012', '1238687', '220661', '181541', '181516', '3140341', '477476', '180771', '520176', '1333374', '180191', '181941', '4465932', '181871', '973043', '377416'], prices=[121, 213, 55, 116, 96, 203, 119, 42, 207, 68, 60, 91, 169, 154, 418, 89, 129, 95, 76, 88, 204, 120, 123, 62, 82], id=271, last_item=768, second_last_item=5321, third_last_item=720, country=17, country_platform=20, device_platform=17, sess_step=2, time_diff=45.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=57.0, time_diff_3=nan, rg_time_diff=0.4957514187080529, step_log=1.0986122886681098)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 817, 820]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=275, index=275, session_id='e2cd4a48cf65d', timestamp=1541030510, user_id='FXFSX09BGZ70', step=1, action=2, item_id=817, platform=16, city=71, device=1, current_filters=nan, impressions=['8280226', '8238358', '2812948', '7851766', '8256252'], prices=[92, 35, 35, 21, 92], id=275, last_item=5321, second_last_item=5336, third_last_item=5336, country=25, country_platform=32, device_platform=29, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=0.0, rg_time_diff=0.6524277257263719, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1104, 1105]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=439, index=439, session_id='e310846a86334', timestamp=1541030535, user_id='GI2JSAT3093L', step=1, action=2, item_id=1104, platform=2, city=90, device=1, current_filters=nan, impressions=['72581', '18260', '60120', '60214', '3842430', '67267', '396326', '2827862', '9335008', '75495', '67250', '78270', '65165', '5788824', '384506', '6322944', '71082', '57745', '57416', '71708', '6434516', '5121048', '60683', '61860', '442396'], prices=[95, 84, 80, 85, 103, 141, 114, 103, 64, 119, 62, 105, 127, 89, 87, 95, 89, 148, 77, 79, 103, 89, 49, 85, 96], id=439, last_item=5321, second_last_item=2154, third_last_item=5336, country=15, country_platform=16, device_platform=14, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.5626367408315907, step_log=0.6931471805599453)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1204, 1204, 1204, 1204]
[1204]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1204]
[5433 1204]
Pandas(Index=469, index=469, session_id='95bbc5d155a7e', timestamp=1541030539, user_id='FK3WQXDLINIT', step=1, action=2, item_id=1204, platform=23, city=98, device=1, current_filters=nan, impressions=['1056094', '2884070', '35281', '80760', '1005807', '35277', '35283', '439371', '914597', '1946391', '1886331', '1503093', '971589', '2548232', '9198018', '1548189', '35268', '1360729', '35269', '5663676', '35278', '80785', '378581', '7109756', '34258'], prices=[33, 39, 47, 91, 66, 27, 39, 96, 77, 60, 85, 76, 55, 57, 36, 72, 58, 129, 81, 75, 73, 108, 114, 76, 269], id=469, last_item=5321, second_last_item=5337, third_last_item=5337, country=30, country_platform=44, device_platform=39, sess_step=2, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.6063095262148154, step_log=0.6931471805599453)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1204, 1204, 1204, 1204]
[1204]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1204]
[5433 1204]
Pandas(Index=470, index=470, session_id='95bbc5d155a7e', timestamp=1541030539, user_id='FK3WQXDLINIT', step=2, action=2, item_id=1204, platform=23, city=98, device=1, current_filters=nan, impressions=['1056094', '2884070', '35281', '80760', '1005807', '35277', '35283', '439371', '914597', '1946391', '1886331', '1503093', '971589', '2548232', '9198018', '1548189', '35268', '1360729', '35269', '5663676', '35278', '80785', '378581', '7109756', '34258'], prices=[33, 39, 47, 91, 66, 27, 39, 96, 77, 60, 85, 76, 55, 57, 36, 72, 58, 129, 81, 75, 73, 108, 114, 76, 269], id=470, last_item=1204, second_last_item=5321, third_last_item=5337, country=30, country_platform=44, device_platform=39, sess_step=2, time_diff=0.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=0.0, rg_time_diff=-0.1587064478993034, step_log=1.0986122886681098)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 1313, 1313]
[5321, 1313]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 1313]
[5433 5321 1313]
Pandas(Index=483, index=483, session_id='386135db7e257', timestamp=1541030543, user_id='ZXDUZ7BVPFCY', step=2, action=2, item_id=1313, platform=10, city=61, device=1, current_filters=nan, impressions=['6031716', '6405716', '6692702', '2625816', '5072118', '2626160', '1664609', '2625818', '7964732', '2626168', '6874372', '11193850', '5800502'], prices=[44, 34, 33, 41, 57, 48, 53, 64, 57, 31, 27, 42, 44], id=483, last_item=5341, second_last_item=5321, third_last_item=5321, country=17, country_platform=20, device_platform=20, sess_step=3, time_diff=47.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=21.0, rg_time_diff=0.5037188799498312, step_log=1.0986122886681098)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1410, 1410, 1410, 1410]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=538, index=538, session_id='8f81080d71569', timestamp=1541030552, user_id='QR045W70VKZ3', step=1, action=2, item_id=1410, platform=25, city=112, device=1, current_filters=nan, impressions=['1314005', '2809180', '2080036', '6402926', '1103070', '4626938', '4659618', '6787016'], prices=[68, 34, 44, 50, 97, 64, 71, 45], id=538, last_item=5321, second_last_item=5321, third_last_item=5341, country=31, country_platform=49, device_platform=42, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=68.0, time_diff_3=nan, rg_time_diff=1.2545148736234564, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1497, 1498]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=571, index=571, session_id='293edac5e36f6', timestamp=1541030558, user_id='WY55N2C724K4', step=1, action=2, item_id=1497, platform=11, city=119, device=1, current_filters=nan, impressions=['3116818', '54952', '724986', '4493674', '5203238', '54985', '55140', '102475', '5002590', '54994', '3115936', '54950', '6918406', '2396954', '109072', '1145555', '54897', '55018', '55120', '3750328', '1180062', '54796', '109075', '6846692', '55079'], prices=[95, 125, 124, 350, 187, 106, 168, 103, 64, 101, 93, 56, 108, 106, 87, 81, 107, 109, 89, 155, 72, 89, 69, 87, 69], id=571, last_item=5321, second_last_item=1493, third_last_item=5346, country=18, country_platform=21, device_platform=21, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=10.0, time_diff_3=46.0, rg_time_diff=1.2256315238056252, step_log=0.6931471805599453)

21it [00:00, 101.71it/s]

30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1410, 1410, 1410, 1410]
[1410]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1410]
[5433 1410]
Pandas(Index=572, index=572, session_id='8f81080d71569', timestamp=1541030558, user_id='QR045W70VKZ3', step=2, action=2, item_id=1410, platform=25, city=112, device=1, current_filters=nan, impressions=['1314005', '2809180', '2080036', '6402926', '1103070', '4626938', '4659618', '6787016'], prices=[68, 34, 44, 50, 97, 64, 71, 45], id=572, last_item=1497, second_last_item=5321, third_last_item=1493, country=31, country_platform=49, device_platform=42, sess_step=2, time_diff=6.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=10.0, rg_time_diff=0.11713060243377298, step_log=1.0986122886681098)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1410, 1410, 1410, 1410]
[1410, 1410]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1410, 1410]
[5433 1410]
Pandas(Index=594, index=594, session_id='8f81080d71569', timestamp=1541030561, user_id='QR045W70VKZ3', step=3, action=2, item_id=1410, platform=25, city=112, device=1, current_filters=nan, impressions=['1314005', '2809180', '2080036', '6402926', '1103070', '4626938', '4659618', '6787016'], prices=[68, 34, 44, 50, 97, 64, 71, 45], id=594, last_item=5321, second_last_item=1569, third_last_item=5321, country=31, country_platform=49, device_platform=42, sess_step=3, time_diff=3.0, time_diff_diff=-3.0, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=40.0, rg_time_diff=0.07952431099162198, step_log=1.3862943611198906)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 118, 118]
[5321, 5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321]
[5433 5321]
Pandas(Index=902, index=902, session_id='8544fbda6bc3c', timestamp=1541030594, user_id='SL6SPK7RIL1C', step=3, action=2, item_id=118, platform=5, city=16, device=1, current_filters=nan, impressions=['8162422', '1506339', '818501', '7213390', '4849214', '103640', '4774596', '917345', '103495', '1031940', '1148728', '1953975', '10141376', '3978950', '3060180', '7743258', '4774542', '661646', '10051400', '5619840', '8165232', '1816151', '6806086', '5816570', '1250199'], prices=[63, 59, 94, 70, 116, 110, 90, 70, 86, 86, 63, 55, 80, 93, 36, 66, 70, 73, 186, 78, 76, 70, 90, 63, 61], id=902, last_item=2351, second_last_item=5356, third_last_item=5321, country=11, country_platform=12, device_platform=7, sess_step=3, time_diff=18.0, time_diff_diff=-14.0, time_diff_diff_diff=nan, time_diff_2=40.0, time_diff_3=0.0, rg_time_diff=0.3674540141433176, step_log=1.3862943611198906)

24it [00:00, 95.12it/s]
0it [00:00, ?it/s]

30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 6]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=5, index=5, session_id='90ccf1b651b92', timestamp=1541030423, user_id='F0NEAMNR1WK0', step=1, action=2, item_id=6, platform=0, city=4, device=1, current_filters=nan, impressions=['507861', '2176280', '8280296', '1830637', '1944129', '7315132', '1669587', '6450704', '1887971', '2771364', '2874560', '8184784', '7880000', '1638907', '2226102', '8269412', '1431081', '3217450', '1889223', '1885013', '8902246', '1946951', '6452918', '6084136', '3951644'], prices=[214, 81, 158, 117, 152, 54, 105, 113, 88, 96, 79, 99, 79, 196, 102, 106, 143, 80, 96, 84, 95, 117, 79, 61, 85], id=5, last_item=5321, second_last_item=5321, third_last_item=5321, country=0, country_platform=0, device_platform=4, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.6376416491574827, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 25]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=8, index=8, session_id='d3aa2789c8973', timestamp=1541030425, user_id='EA6D53DNLIU0', step=1, action=2, item_id=25, platform=4, city=7, device=1, current_filters=nan, impressions=['2128208', '2892128', '1135230', '8410646', '2784325', '1351828', '674016', '8113288', '3910198', '103263', '8131766', '496141', '2100784', '4040332', '1837709', '5927890', '2776330', '4253394', '2683660', '3864648', '8400372', '6177190', '3144024', '9205012', '3804384'], prices=[83, 18, 31, 67, 175, 78, 112, 31, 26, 93, 19, 64, 16, 68, 38, 52, 31, 45, 16, 38, 74, 35, 36, 51, 72], id=8, last_item=5321, second_last_item=5321, third_last_item=6, country=5, country_platform=5, device_platform=6, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.6244376863204539, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 50]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=9, index=9, session_id='413d03546ec94', timestamp=1541030425, user_id='QR0O86CIA0J6', step=1, action=2, item_id=50, platform=0, city=8, device=0, current_filters=nan, impressions=['2832624', '2898616', '7717092', '9662278', '7342374', '3241666', '9319588', '507876', '2031407', '4169690', '104725', '6552296', '4607830', '6046356', '4077602', '3199092', '4667048', '7176884', '8595488', '8303068', '8298948', '4511196', '7255094', '5419968', '5478866'], prices=[56, 81, 56, 38, 63, 38, 51, 54, 35, 40, 37, 36, 41, 46, 42, 28, 37, 23, 50, 23, 50, 41, 38, 41, 19], id=9, last_item=5321, second_last_item=5321, third_last_item=5321, country=0, country_platform=0, device_platform=0, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.6231292618218868, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 75]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=11, index=11, session_id='5c5bf8f275c87', timestamp=1541030426, user_id='6354V79E008Z', step=1, action=2, item_id=75, platform=0, city=10, device=1, current_filters=nan, impressions=['1963063', '2550302', '1673799', '2846254', '1668529', '1827829', '2779389', '2200580', '1887365', '6246574', '2777738', '8011040', '7946006', '2603658', '4031920', '9022428', '5945462', '9178482', '8454324', '4501398', '2837208'], prices=[42, 61, 68, 45, 53, 75, 44, 43, 106, 75, 40, 39, 66, 37, 34, 55, 53, 53, 47, 45, 21], id=11, last_item=5321, second_last_item=50, third_last_item=25, country=0, country_platform=0, device_platform=4, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.6403091839806337, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 97]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=13, index=13, session_id='0ddb9d1b7648b', timestamp=1541030429, user_id='3MM8QFFTK2OX', step=1, action=2, item_id=97, platform=3, city=12, device=1, current_filters=nan, impressions=['2349076', '2552514', '2019273', '1846017', '7159866', '8768470', '2828571', '2685752', '3898458', '7250252', '4024924', '8775800', '7721912'], prices=[54, 39, 72, 41, 55, 70, 24, 22, 51, 94, 25, 59, 24], id=13, last_item=5321, second_last_item=75, third_last_item=5321, country=8, country_platform=8, device_platform=5, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.6166188646047567, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 159]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=33, index=33, session_id='93330a9429917', timestamp=1541030450, user_id='NLW7BMYYRF5I', step=1, action=2, item_id=159, platform=2, city=21, device=0, current_filters=nan, impressions=['2319408', '8285', '8289', '67396', '2805648', '149706', '6192908', '149695', '61359', '60108', '79255', '73252', '8284', '55525', '2738364', '7183426', '8317', '1238812', '64693', '15579', '1290651', '67374', '907759', '69622', '57480'], prices=[166, 83, 63, 290, 255, 32, 79, 75, 264, 104, 76, 176, 45, 95, 63, 70, 75, 79, 123, 82, 216, 44, 89, 63, 200], id=33, last_item=5321, second_last_item=5323, third_last_item=5323, country=15, country_platform=16, device_platform=3, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=0.0, rg_time_diff=0.7058679823083226, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 184]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=57, index=57, session_id='f2d80ae297816', timestamp=1541030457, user_id='0WBTHYFL4A8T', step=1, action=2, item_id=184, platform=2, city=28, device=1, current_filters=nan, impressions=['42489', '804296', '1370232', '101452', '35152', '42400', '101455', '6175194', '3869542', '3409732', '1167205', '1390390', '101448', '35167', '101456', '5706168', '4380174', '43061', '9172424', '2123760', '10146808', '152946', '1293064', '35157', '4388568'], prices=[332, 275, 128, 135, 354, 866, 342, 132, 815, 285, 1349, 566, 127, 592, 303, 1614, 68, 1236, 372, 94, 5721, 518, 172, 1418, 587], id=57, last_item=5321, second_last_item=212, third_last_item=109, country=8, country_platform=18, device_platform=14, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=nan, rg_time_diff=0.762091885333075, step_log=0.6931471805599453)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 212, 212, 212]
[212, 212]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 212, 212]
[5433  212]
Pandas(Index=59, index=59, session_id='ad426ee0e24a4', timestamp=1541030459, user_id='CB7BWYPZ9N0Q', step=3, action=2, item_id=212, platform=0, city=27, device=1, current_filters=nan, impressions=['1656477', '2771502', '6542484', '1056384', '2319566', '3210926', '2368268', '1656947', '6570200', '3865946', '3084238', '2646156', '1859237', '8746166', '4010588', '3984674', '4051328', '2570000', '1998479', '2673286', '3951108', '3178923', '2363543', '7351442', '2676938'], prices=[54, 63, 66, 173, 61, 65, 42, 106, 51, 37, 36, 55, 48, 107, 46, 30, 23, 69, 77, 41, 32, 59, 51, 83, 53], id=59, last_item=686, second_last_item=184, third_last_item=5321, country=0, country_platform=0, device_platform=4, sess_step=3, time_diff=3.0, time_diff_diff=3.0, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.07417276541585005, step_log=1.3862943611198906)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 234]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=63, index=63, session_id='ab6d76a12a9b9', timestamp=1541030462, user_id='2HHP4Y144PIE', step=1, action=2, item_id=234, platform=3, city=32, device=1, current_filters=nan, impressions=['2844050', '42957', '349366', '1631625', '9226736', '4729416', '5043316', '1702743', '127662', '1841577', '972823', '9171052', '2799542', '2246816', '4711920', '2685746', '647461', '4173036', '7180312', '3484826', '1009061', '7180570', '936335', '8336818', '5086548'], prices=[25, 45, 33, 20, 30, 22, 30, 37, 48, 22, 44, 13, 28, 22, 18, 26, 17, 26, 35, 30, 39, 30, 36, 45, 39], id=63, last_item=5321, second_last_item=5324, third_last_item=5321, country=8, country_platform=8, device_platform=5, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=21.0, rg_time_diff=0.7015034815901241, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 309]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=99, index=99, session_id='71fa935f4d935', timestamp=1541030469, user_id='092XCVGZX8C9', step=1, action=2, item_id=309, platform=8, city=42, device=1, current_filters=nan, impressions=['2094536', '46983', '2643592', '1075908', '19333', '19331', '945391', '47896', '894629', '4092092', '47016', '3184268', '1839505', '1331556', '6428054', '19340', '629336', '1709295', '894627', '2095832', '629331', '2196838', '1824191', '2155068', '19341'], prices=[138, 101, 82, 203, 116, 158, 152, 95, 61, 68, 72, 94, 81, 98, 95, 141, 90, 73, 96, 113, 93, 68, 85, 234, 85], id=99, last_item=5321, second_last_item=521, third_last_item=5321, country=10, country_platform=10, device_platform=10, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.6914221161002024, step_log=0.6931471805599453)
30
5
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 5321, 336]
[5321, 5321, 5321, 5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 5321]
[5433 5321]
Pandas(Index=101, index=101, session_id='5b578bc20be9f', timestamp=1541030470, user_id='KQ7YR1O2APO1', step=5, action=2, item_id=336, platform=1, city=1, device=1, current_filters='Sort By Rating', impressions=['1033206', '1901997', '35587', '2759190', '2882490', '3750966', '2290794', '2438679', '3983518', '1755327', '2438480', '2703116', '2788036', '5111556', '6237608', '9248246', '9512888', '9622932', '35638', '159307', '984591', '2200766', '3380070', '4027434', '4743560'], prices=[45, 70, 80, 75, 85, 84, 84, 84, 80, 78, 71, 83, 63, 84, 72, 69, 72, 73, 80, 50, 81, 53, 80, 76, 69], id=101, last_item=363, second_last_item=309, third_last_item=5321, country=1, country_platform=1, device_platform=1, sess_step=5, time_diff=15.0, time_diff_diff=15.0, time_diff_diff_diff=15.0, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.35131114274444997, step_log=1.791759469228055)

11it [00:00, 105.04it/s]

30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 363, 363]
[363]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 363]
[5433  363]
Pandas(Index=107, index=107, session_id='713adad4927e3', timestamp=1541030472, user_id='GF8ANZZ3H9TI', step=2, action=2, item_id=363, platform=0, city=43, device=1, current_filters=nan, impressions=['965967', '3805414', '2784958', '4648454', '4501352', '8467488', '6405988', '9437848', '6692058', '7781972', '5601364'], prices=[43, 37, 61, 45, 47, 57, 114, 43, 54, 72, 57], id=107, last_item=5321, second_last_item=5321, third_last_item=5321, country=0, country_platform=0, device_platform=4, sess_step=2, time_diff=2.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.036813439235517685, step_log=1.0986122886681098)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 370]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=127, index=127, session_id='23298155453fc', timestamp=1541030474, user_id='R4BICMYW1GQT', step=1, action=2, item_id=370, platform=3, city=49, device=0, current_filters=nan, impressions=['6900984', '8396328', '684696', '3503586', '954615', '60380', '63047', '983023', '972689', '562286', '349066', '102451', '890489', '2224538', '42816', '102453', '79808', '3516456', '4876920', '3492094', '35150', '382871', '42506', '10105458', '10449272'], prices=[41, 80, 55, 62, 44, 66, 93, 55, 62, 83, 67, 75, 52, 41, 141, 58, 71, 110, 57, 34, 83, 79, 75, 81, 49], id=127, last_item=5321, second_last_item=5325, third_last_item=5325, country=8, country_platform=8, device_platform=11, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.7387352095922525, step_log=0.6931471805599453)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 424, 421]
[424]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 424]
[5433  424]
Pandas(Index=144, index=144, session_id='0fbc6b02f642e', timestamp=1541030479, user_id='T4DD3RUMCCVA', step=2, action=2, item_id=421, platform=0, city=24, device=1, current_filters=nan, impressions=['326951', '3879908', '1244915', '2732748', '2566271', '1244941', '8334508', '1707955', '939524', '3971286', '4076758', '9370838', '1861059', '3971290', '4083296', '6543944', '1244839', '1245022', '2918677', '7102290', '1244933', '1245038', '2516836', '2603992', '3794688'], prices=[430, 83, 181, 78, 37, 71, 595, 43, 45, 27, 90, 22, 34, 27, 18, 61, 36, 57, 25, 16, 72, 83, 40, 41, 23], id=144, last_item=521, second_last_item=5321, third_last_item=521, country=0, country_platform=0, device_platform=4, sess_step=2, time_diff=27.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.43089828328393515, step_log=1.0986122886681098)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 445, 445]
[445]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 445]
[5433  445]
Pandas(Index=148, index=148, session_id='87170d867e6c1', timestamp=1541030481, user_id='3FRL3WP6IVO5', step=2, action=2, item_id=445, platform=7, city=19, device=1, current_filters=nan, impressions=['9339506', '3134284', '97907', '1105744', '94842', '148761', '159006', '344701', '1369129', '1767221', '2733719', '3143258', '4927560', '5971670', '2373570', '2156874', '6438708', '2179296', '3926800', '104122', '2303000', '1654403', '4504944', '2328012', '104142'], prices=[82, 206, 183, 88, 195, 212, 186, 205, 369, 368, 327, 107, 441, 188, 63, 279, 228, 227, 173, 259, 163, 156, 155, 190, 54], id=148, last_item=5321, second_last_item=5321, third_last_item=395, country=14, country_platform=15, device_platform=15, sess_step=2, time_diff=35.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=4.0, rg_time_diff=0.4633873872669442, step_log=1.0986122886681098)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 499]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=160, index=160, session_id='d8a73b3ac0480', timestamp=1541030483, user_id='JS305SOFT1L5', step=1, action=2, item_id=499, platform=13, city=53, device=1, current_filters=nan, impressions=['997601', '6861464', '2212472', '3810902', '997621', '320801', '2036851', '5478836', '2212566', '8748012', '1358678', '5452706', '6454130', '1851073', '997591', '1982309', '1755329', '9517828', '8955638', '1099964', '1099972', '1357603', '3835812', '2297102', '9670536'], prices=[63, 104, 87, 60, 34, 58, 37, 36, 99, 12, 23, 164, 26, 58, 52, 50, 89, 12, 20, 43, 38, 41, 108, 29, 29], id=160, last_item=5321, second_last_item=99, third_last_item=99, country=21, country_platform=26, device_platform=23, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.7146786700040496, step_log=0.6931471805599453)
30
5
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 521, 521, 521, 521, 521, 521]
[521, 521, 521, 521]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 521, 521, 521, 521]
[5433  521]
Pandas(Index=167, index=167, session_id='73aaba45abc79', timestamp=1541030484, user_id='ORQ6U0KAMD2Q', step=5, action=2, item_id=521, platform=2, city=40, device=0, current_filters=nan, impressions=['69511', '69865', '3867636', '8258580', '2217944', '824256', '8931332', '9294098', '9252332', '10491954', '10869444'], prices=[55, 89, 61, 70, 84, 141, 106, 212, 75, 123, 92], id=167, last_item=964, second_last_item=964, third_last_item=964, country=15, country_platform=16, device_platform=3, sess_step=5, time_diff=6.0, time_diff_diff=6.0, time_diff_diff_diff=6.0, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.11623177799442386, step_log=1.791759469228055)
30
4
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 395, 395, 395]
[5321, 395, 395]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 395, 395]
[5433 5321  395]
Pandas(Index=174, index=174, session_id='730dbf90f28bb', timestamp=1541030486, user_id='LP2AMI5H1P2K', step=4, action=2, item_id=395, platform=4, city=25, device=1, current_filters=nan, impressions=['1250027', '1368776', '4088790', '1981249', '7030280', '3167664', '1981215', '2018159', '7807744', '103275', '8408886', '6019012', '3831066', '9995698', '8308940', '2894302', '6748650', '6938724', '103259', '1838153', '119306', '4574134', '2228070', '103248', '1351820'], prices=[27, 54, 41, 23, 16, 26, 12, 11, 40, 202, 34, 25, 31, 49, 56, 23, 49, 25, 139, 117, 59, 31, 40, 45, 24], id=174, last_item=470, second_last_item=5329, third_last_item=5327, country=5, country_platform=5, device_platform=6, sess_step=4, time_diff=6.0, time_diff_diff=3.0, time_diff_diff_diff=23.0, time_diff_2=4.0, time_diff_3=0.0, rg_time_diff=0.12072780849937997, step_log=1.6094379124341003)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 556]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=195, index=195, session_id='59a238401511a', timestamp=1541030494, user_id='9ADK7QUMYRSG', step=1, action=2, item_id=556, platform=8, city=58, device=1, current_filters=nan, impressions=['629776', '907839', '19667', '1940585', '7195132', '85747', '2548028', '342481', '46565', '85758', '46841', '2501720', '492406', '452216', '85804', '381206', '46809', '664506', '138572', '46855', '1418998', '1199662', '946997', '1176737', '342696'], prices=[166, 90, 60, 59, 90, 108, 62, 161, 92, 71, 69, 75, 63, 49, 64, 69, 51, 83, 65, 59, 102, 68, 70, 87, 73], id=195, last_item=5321, second_last_item=185, third_last_item=964, country=10, country_platform=10, device_platform=10, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=nan, rg_time_diff=0.6101603235246322, step_log=0.6931471805599453)
30
6
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 581, 581, 581]
[5321, 5321, 5321, 581, 581]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 581, 581]
[5433 5321  581]
Pandas(Index=198, index=198, session_id='1d72f54410c94', timestamp=1541030495, user_id='5IYN7UUCMPDY', step=6, action=2, item_id=581, platform=11, city=52, device=1, current_filters='Sort by Price', impressions=['1460483', '7111178', '516871', '4081158', '2325788', '1119647', '153054', '1020583', '4362288', '54830', '1253855', '153053', '102028', '667411', '976903', '1237456', '1364174', '54840', '5435116', '102019', '611211', '1020573', '1020579', '1020593', '1253854'], prices=[28, 39, 40, 41, 44, 47, 49, 49, 50, 51, 51, 51, 53, 53, 53, 53, 53, 55, 56, 56, 56, 56, 56, 56, 56], id=198, last_item=5321, second_last_item=185, third_last_item=556, country=18, country_platform=21, device_platform=21, sess_step=6, time_diff=8.0, time_diff_diff=8.0, time_diff_diff_diff=18.0, time_diff_2=nan, time_diff_3=0.0, rg_time_diff=0.13514889670317753, step_log=1.9459101490553132)
30
19
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 112, 112, 113, 113, 113]
[109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 112, 112, 113, 113]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 112, 112, 113, 113]
[5433  109  112  113]
Pandas(Index=233, index=233, session_id='6c4ba6d174134', timestamp=1541030502, user_id='CJ32S9QQ04RI', step=19, action=2, item_id=113, platform=5, city=16, device=1, current_filters=nan, impressions=['3143733', '103507', '5452024', '103600', '4775550', '2266812', '508561', '95011', '153936', '8162422', '980287', '103458', '1816153', '103672', '2111996', '2430542', '4774596', '1816151', '906417', '3132670', '824196', '103495', '103620', '8165060', '8350208'], prices=[164, 251, 188, 149, 133, 404, 113, 156, 84, 102, 126, 406, 94, 254, 127, 102, 127, 93, 132, 172, 192, 133, 216, 152, 120], id=233, last_item=2054, second_last_item=5330, third_last_item=5330, country=11, country_platform=12, device_platform=7, sess_step=19, time_diff=2.0, time_diff_diff=2.0, time_diff_diff_diff=27.0, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.03858930262699271, step_log=2.995732273553991)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 618]
[5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321]
[5433 5321]
Pandas(Index=234, index=234, session_id='30abf535ccb64', timestamp=1541030502, user_id='T38IH0LTKIAK', step=2, action=2, item_id=618, platform=10, city=47, device=1, current_filters=nan, impressions=['2709396', '2811190', '2223658', '1993195', '2120928', '1883877', '2248510', '2441838', '1375612', '2732952', '1245006', '977414', '9051692', '2315632', '9255322', '5473450', '4148648', '3797000', '3384433', '4104242', '2160800', '478616', '5071516', '2672911', '1827951'], prices=[41, 35, 50, 42, 47, 37, 29, 38, 70, 93, 42, 39, 47, 41, 38, 152, 36, 25, 79, 46, 56, 82, 35, 17, 64], id=234, last_item=113, second_last_item=5321, third_last_item=5330, country=0, country_platform=24, device_platform=20, sess_step=2, time_diff=31.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=2.0, time_diff_3=0.0, rg_time_diff=0.4416238751191278, step_log=1.0986122886681098)

22it [00:00, 103.56it/s]

30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 651]
[5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321]
[5433 5321]
Pandas(Index=243, index=243, session_id='eb948b62169fb', timestamp=1541030504, user_id='UO6DEU1KN6G7', step=2, action=2, item_id=651, platform=3, city=48, device=1, current_filters=nan, impressions=['2455862', '5116230', '42864', '932875', '9234374', '2645140', '936559', '42931', '42692', '1363450', '349091', '2564824', '3148690', '2628052', '2233644', '42662', '8183468', '3479202', '10154074', '5970348', '4342578', '43133', '2552826', '4954872', '7145594'], prices=[87, 181, 117, 31, 91, 64, 34, 38, 69, 54, 32, 20, 70, 47, 13, 56, 48, 48, 25, 65, 48, 44, 21, 25, 44], id=243, last_item=964, second_last_item=5321, third_last_item=2154, country=8, country_platform=8, device_platform=5, sess_step=2, time_diff=32.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=10.0, rg_time_diff=0.4470248604938419, step_log=1.0986122886681098)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 686, 687]
[686]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 686]
[5433  686]
Pandas(Index=260, index=260, session_id='51fb9449bdfda', timestamp=1541030506, user_id='Y2N0EVYEN7RK', step=2, action=2, item_id=687, platform=7, city=29, device=0, current_filters=nan, impressions=['47062', '922489', '1246842', '46952', '365796', '19512', '19588', '365001', '6340248', '19444', '1388342', '18795', '46587', '529756', '1242666', '19583', '401536', '7859934', '19709', '46232', '557266', '47996', '7676650', '85806', '2195996'], prices=[54, 56, 55, 69, 47, 212, 541, 93, 181, 207, 240, 85, 41, 145, 271, 63, 135, 60, 62, 90, 193, 71, 51, 232, 82], id=260, last_item=5335, second_last_item=5321, third_last_item=99, country=10, country_platform=19, device_platform=9, sess_step=2, time_diff=48.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.5105993684237213, step_log=1.0986122886681098)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 711, 712]
[711]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 711]
[5433  711]
Pandas(Index=266, index=266, session_id='14095b67c6955', timestamp=1541030507, user_id='4K9X8DMND3II', step=2, action=2, item_id=712, platform=5, city=16, device=1, current_filters=nan, impressions=['93654', '5452024', '103571', '1320401', '103600', '95011', '103458', '103507', '103582', '153936', '508561', '980287', '1146871', '3143733', '4775550', '8162422', '1816153', '103672', '2111996', '2430542', '9857032', '4774596', '1816151', '906417', '3132670'], prices=[192, 188, 101, 196, 149, 156, 406, 251, 166, 84, 113, 126, 125, 164, 133, 102, 94, 254, 127, 102, 187, 127, 93, 132, 172], id=266, last_item=1007, second_last_item=5321, third_last_item=971, country=11, country_platform=12, device_platform=7, sess_step=2, time_diff=33.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=27.0, rg_time_diff=0.45681306398338356, step_log=1.0986122886681098)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 742]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=269, index=269, session_id='d0962cb33f0cb', timestamp=1541030508, user_id='11OYMK42449C', step=1, action=2, item_id=742, platform=0, city=68, device=1, current_filters=nan, impressions=['499361', '1668523', '1564425', '512066', '511476', '4625138', '962853', '2035539', '2025379', '2033761', '2570332', '2273220', '1668511', '3191757', '2604115', '1012043', '2348468', '3938730', '2811476', '2785396', '1668519', '1668521', '2681116', '3248446', '1244845'], prices=[451, 53, 41, 48, 40, 31, 48, 36, 40, 40, 43, 63, 41, 36, 36, 83, 47, 20, 34, 35, 39, 46, 23, 21, 23], id=269, last_item=5321, second_last_item=5321, third_last_item=712, country=0, country_platform=0, device_platform=4, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.735681548607694, step_log=0.6931471805599453)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 768]
[5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321]
[5433 5321]
Pandas(Index=270, index=270, session_id='9fc0ecced0dd8', timestamp=1541030509, user_id='D34X26VKHHQ6', step=2, action=2, item_id=768, platform=0, city=23, device=1, current_filters=nan, impressions=['1723713', '508116', '5964878', '2353034', '2087440', '1995467', '1814881', '2251776', '508696', '5614420', '1045690', '1776237', '1648513', '962075', '506346', '2488114', '1655703', '7259976', '1045654', '1710127', '3206185', '2249736', '3242950', '2423362', '887399'], prices=[116, 164, 107, 102, 82, 51, 95, 88, 74, 138, 120, 45, 50, 120, 95, 53, 88, 111, 61, 105, 121, 56, 125, 90, 105], id=270, last_item=742, second_last_item=5321, third_last_item=5321, country=0, country_platform=0, device_platform=4, sess_step=2, time_diff=57.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.5256759499729035, step_log=1.0986122886681098)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 828]
[5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321]
[5433 5321]
Pandas(Index=278, index=278, session_id='59e5a740c2972', timestamp=1541030511, user_id='KRHAR2C2HTDV', step=2, action=2, item_id=828, platform=14, city=54, device=0, current_filters=nan, impressions=['348401', '897961', '5106732', '110238', '101377', '101409', '2402018', '101372', '96977', '4944908', '7114460', '95275', '116290', '5659228', '95870', '101373', '2581356', '3507482', '101404', '93319', '101390', '101399', '110239', '1306152', '101369'], prices=[84, 74, 74, 126, 56, 38, 50, 44, 68, 46, 64, 113, 62, 49, 48, 48, 83, 62, 60, 104, 159, 69, 86, 62, 66], id=278, last_item=1033, second_last_item=5321, third_last_item=817, country=5, country_platform=27, device_platform=24, sess_step=2, time_diff=27.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=51.0, rg_time_diff=0.43196635169164965, step_log=1.0986122886681098)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 851]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=292, index=292, session_id='60d7a4ee06689', timestamp=1541030512, user_id='X1HSMLBCCIH0', step=1, action=2, item_id=851, platform=3, city=72, device=1, current_filters=nan, impressions=['2247952', '2830064', '5430180', '10666456', '1833823', '4000084', '8437788', '2813870', '1020675', '4657520', '6274952', '8265136', '6977066', '8962374', '5501748', '6689600', '9687218', '6681730', '6780240', '9317198'], prices=[19, 18, 10, 18, 16, 16, 18, 15, 18, 17, 15, 14, 8, 17, 19, 19, 14, 16, 16, 13], id=292, last_item=5321, second_last_item=2054, third_last_item=5330, country=8, country_platform=8, device_platform=5, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.6758578430485448, step_log=0.6931471805599453)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 867, 867, 867]
[867, 867]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 867, 867]
[5433  867]
Pandas(Index=295, index=295, session_id='09fa9c29ca53f', timestamp=1541030513, user_id='9ZYSWK83784C', step=3, action=2, item_id=867, platform=0, city=74, device=1, current_filters=nan, impressions=['1669781', '2018433', '3931100', '6954356', '8240192', '7358644', '1091698', '1776319', '2353616', '2717774', '3198026', '4063060', '6684888', '8136382', '9426838'], prices=[81, 165, 91, 68, 68, 136, 126, 226, 124, 136, 95, 68, 83, 91, 142], id=295, last_item=1480, second_last_item=2054, third_last_item=5321, country=0, country_platform=0, device_platform=4, sess_step=3, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=0.0, rg_time_diff=0.6828914950343028, step_log=1.3862943611198906)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 882]
[5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321]
[5433 5321]
Pandas(Index=302, index=302, session_id='005292b32376c', timestamp=1541030513, user_id='64N58VIP4IA4', step=2, action=2, item_id=882, platform=0, city=47, device=1, current_filters=nan, impressions=['1189712', '4723144', '853216', '1084138', '154217', '2672828', '1330207', '152438', '104569', '1457493', '929055', '6312250', '104545', '1241170', '326681', '929581', '1006983', '478616', '928781', '104832', '477921', '1333392', '104937', '104890', '479006'], prices=[176, 92, 64, 29, 89, 97, 370, 70, 68, 151, 67, 130, 46, 41, 77, 240, 48, 233, 173, 497, 105, 63, 74, 60, 53], id=302, last_item=2154, second_last_item=5321, third_last_item=867, country=0, country_platform=0, device_platform=4, sess_step=2, time_diff=17.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=10.0, rg_time_diff=0.36542582462497747, step_log=1.0986122886681098)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 287, 284, 284]
[287, 284]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 287, 284]
[5433  287  284]
Pandas(Index=304, index=304, session_id='afb99bef2f373', timestamp=1541030514, user_id='OPR0TY285KKP', step=3, action=2, item_id=284, platform=3, city=38, device=1, current_filters=nan, impressions=['3182924', '3135340', '3135343', '35169', '42836', '2561635', '35173', '4894814', '1400592', '35171', '979341', '3163718', '5155260', '943991', '1702439', '3757420', '3045134', '1017018', '43029', '2875932', '7171360', '10811256', '10865636', '10884168', '9994480'], prices=[95, 41, 37, 52, 43, 31, 45, 28, 70, 91, 125, 96, 115, 37, 36, 49, 40, 18, 128, 289, 31, 265, 265, 189, 114], id=304, last_item=964, second_last_item=882, third_last_item=5321, country=8, country_platform=8, device_platform=5, sess_step=3, time_diff=19.0, time_diff_diff=-9.0, time_diff_diff_diff=nan, time_diff_2=10.0, time_diff_3=17.0, rg_time_diff=0.3776408963358227, step_log=1.3862943611198906)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 906]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=308, index=308, session_id='fb8e754ac0c50', timestamp=1541030515, user_id='5JMV097XQ3OP', step=1, action=2, item_id=906, platform=11, city=78, device=1, current_filters=nan, impressions=['536851', '175247', '1367592', '171467', '691821', '362671', '966485', '2787020', '503171', '175267', '1309216', '966475', '1031776', '888689', '1161538', '2045239', '2077026', '9763048', '4731352', '10364422', '1279138', '2895592'], prices=[1004, 248, 147, 189, 377, 242, 368, 326, 275, 377, 78, 746, 108, 470, 89, 1057, 79, 1025, 134, 120, 50, 476], id=308, last_item=5321, second_last_item=5321, third_last_item=964, country=27, country_platform=35, device_platform=21, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=nan, rg_time_diff=0.6456717866325203, step_log=0.6931471805599453)

33it [00:00, 104.30it/s]

30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 928, 928]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=320, index=320, session_id='f22208b45282a', timestamp=1541030516, user_id='XP0ZA762RR61', step=1, action=2, item_id=928, platform=13, city=80, device=1, current_filters=nan, impressions=['2212698', '5458982', '3532752', '3463408', '5010144', '595406', '2629306', '1388828', '4669238', '4105146', '1985343', '399536', '595421', '714341', '9448386', '2709926', '2762675', '4418286', '1173292', '1101190', '6621660', '5098328', '5115654', '2379600', '1107534'], prices=[53, 104, 118, 80, 57, 130, 308, 281, 100, 274, 76, 219, 85, 67, 250, 74, 138, 98, 83, 60, 89, 96, 91, 99, 103], id=320, last_item=5321, second_last_item=5335, third_last_item=99, country=21, country_platform=26, device_platform=23, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.651071784760718, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 954]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=328, index=328, session_id='20e28faaa4463', timestamp=1541030517, user_id='SNZAI7RPSTD5', step=1, action=2, item_id=954, platform=2, city=82, device=1, current_filters=nan, impressions=['70488', '360086', '950709', '9081668', '956937', '64516', '9061276'], prices=[123, 168, 116, 225, 168, 406, 133], id=328, last_item=5321, second_last_item=5335, third_last_item=5321, country=15, country_platform=16, device_platform=14, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=0.0, rg_time_diff=0.6606143200645922, step_log=0.6931471805599453)
30
24
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964]
[964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964, 964]
[5433  964]
Pandas(Index=332, index=332, session_id='f3373cc53eaea', timestamp=1541030518, user_id='V0I0YFXZC4MF', step=24, action=2, item_id=964, platform=6, city=36, device=2, current_filters=nan, impressions=['2636628', '1111790', '2421134', '347236', '2851711', '43892', '5138848', '2618044', '44376'], prices=[88, 44, 44, 56, 74, 60, 47, 78, 74], id=332, last_item=971, second_last_item=1546, third_last_item=1546, country=4, country_platform=11, device_platform=8, sess_step=24, time_diff=4.0, time_diff_diff=4.0, time_diff_diff_diff=4.0, time_diff_2=11.0, time_diff_3=0.0, rg_time_diff=0.08666685128382655, step_log=3.2188758248682006)
30
16
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 3517, 971, 971, 971, 971, 971, 971, 971, 971, 971, 971, 971, 971, 971, 971]
[5321, 3517, 971, 971, 971, 971, 971, 971, 971, 971, 971, 971, 971, 971, 971]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 3517, 971, 971, 971, 971, 971, 971, 971, 971, 971, 971, 971, 971, 971]
[5433 5321 3517  971]
Pandas(Index=346, index=346, session_id='90fdaae2c58dc', timestamp=1541030519, user_id='RE84XPQB447X', step=16, action=2, item_id=971, platform=2, city=3, device=0, current_filters='Best Value', impressions=['8887828', '8414618', '1231946', '7323680', '5125642', '4154712', '6758274', '4541864', '7768768', '10487598', '2512412', '9518474', '9360870', '100023', '8110690', '9337874', '7193594', '10822588', '10254310', '10958274', '13435', '5671916', '4097746', '6691344', '10388196'], prices=[98, 119, 105, 98, 145, 120, 156, 145, 180, 125, 168, 138, 138, 270, 96, 92, 125, 128, 133, 138, 220, 155, 280, 184, 185], id=346, last_item=1655, second_last_item=5321, third_last_item=971, country=3, country_platform=3, device_platform=3, sess_step=16, time_diff=1.0, time_diff_diff=1.0, time_diff_diff_diff=1.0, time_diff_2=14.0, time_diff_3=51.0, rg_time_diff=0.021726839636950896, step_log=2.833213344056216)
30
7
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 5321, 1007, 1007, 1007]
[5321, 5321, 5321, 5321, 1007, 1007]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 5321, 1007, 1007]
[5433 5321 1007]
Pandas(Index=369, index=369, session_id='1b3f48619ca08', timestamp=1541030523, user_id='M4C6HQG2R2A9', step=7, action=2, item_id=1007, platform=0, city=41, device=0, current_filters='Focus on Rating', impressions=['2786069', '2827524', '3131705', '529011', '2519562', '172677', '4776548', '323766', '323806', '1369336', '155723', '323826', '4565024', '1709475', '3133294', '2255858', '1745195', '323646', '194326', '4898318', '4084764', '429771', '327091', '3925760', '3810252'], prices=[145, 78, 88, 109, 167, 158, 110, 89, 107, 108, 152, 101, 116, 136, 89, 103, 140, 219, 94, 127, 73, 139, 102, 93, 134], id=369, last_item=5321, second_last_item=1033, third_last_item=1033, country=20, country_platform=23, device_platform=0, sess_step=7, time_diff=16.0, time_diff_diff=16.0, time_diff_diff_diff=43.0, time_diff_2=22.0, time_diff_3=0.0, rg_time_diff=0.35231463910226946, step_log=2.0794415416798357)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 1019]
[5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321]
[5433 5321]
Pandas(Index=381, index=381, session_id='eb794a076fefd', timestamp=1541030527, user_id='B8Y4YM8WSPWT', step=2, action=2, item_id=1019, platform=6, city=75, device=1, current_filters=nan, impressions=['367081', '542246', '3533796', '316436', '317001', '4344814', '427036', '2803160', '4297116', '2506189'], prices=[95, 87, 40, 53, 80, 69, 74, 81, 83, 42], id=381, last_item=5335, second_last_item=5321, third_last_item=470, country=15, country_platform=34, device_platform=31, sess_step=2, time_diff=14.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=10.0, time_diff_3=0.0, rg_time_diff=0.3303964977203286, step_log=1.0986122886681098)
30
27
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99]
[99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99]
[5433   99]
Pandas(Index=385, index=385, session_id='11e5e4e589615', timestamp=1541030527, user_id='PYI2QHTWE5KO', step=27, action=2, item_id=99, platform=3, city=12, device=0, current_filters=nan, impressions=['1846017', '2349076', '2552514', '7159866', '2828571', '2019273', '2685752', '3898458', '8768470', '4024924', '7250252', '7721912', '8775800'], prices=[41, 54, 39, 55, 24, 72, 28, 51, 70, 25, 94, 24, 59], id=385, last_item=1546, second_last_item=1546, third_last_item=1546, country=8, country_platform=8, device_platform=11, sess_step=27, time_diff=11.0, time_diff_diff=11.0, time_diff_diff_diff=11.0, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.3068417661674411, step_log=3.332204510175204)
30
13
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 1033, 1033, 1033, 1033, 1033, 1033, 1033, 1033, 1033, 1033, 1033, 1033, 1033, 1033, 1033, 1033, 1033, 1033, 1033, 1033]
[5321, 1033, 1033, 1033, 1033, 1033, 1033, 1033, 1033, 1033, 1033, 1033]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 1033, 1033, 1033, 1033, 1033, 1033, 1033, 1033, 1033, 1033, 1033]
[5433 5321 1033]
Pandas(Index=389, index=389, session_id='ec20ec58a12fd', timestamp=1541030529, user_id='20T9QJYRK77K', step=13, action=2, item_id=1033, platform=2, city=31, device=1, current_filters=nan, impressions=['4681630', '66002', '76209', '55437', '396856', '2140996', '58009', '60911', '75035', '72462', '60349', '79060', '385456', '4981070', '977753', '73497', '8951140', '78203', '75036', '73559', '67933', '64579', '75037', '1354130', '77354'], prices=[130, 124, 70, 194, 98, 175, 71, 67, 106, 106, 89, 90, 90, 130, 128, 154, 88, 78, 63, 82, 79, 128, 113, 57, 64], id=389, last_item=5337, second_last_item=5337, third_last_item=1546, country=15, country_platform=16, device_platform=14, sess_step=13, time_diff=8.0, time_diff_diff=8.0, time_diff_diff_diff=8.0, time_diff_2=0.0, time_diff_3=16.0, rg_time_diff=0.144190324698732, step_log=2.6390573296152584)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1054]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=413, index=413, session_id='309644ed98800', timestamp=1541030530, user_id='YENE1ELQ0UNP', step=1, action=2, item_id=1054, platform=5, city=86, device=0, current_filters=nan, impressions=['1054190', '1522391', '106189', '106148', '5910036', '8770772', '3539422', '103593', '2180920', '346976', '1053448', '3539872', '1049114', '4850062', '5832800', '1394073', '3169382', '2044469', '928307', '566266', '3539800', '922895', '1170209', '1738977', '370131'], prices=[164, 80, 80, 100, 66, 66, 57, 133, 74, 108, 79, 93, 85, 76, 73, 78, 47, 75, 51, 140, 77, 104, 103, 67, 100], id=413, last_item=5321, second_last_item=5336, third_last_item=5336, country=11, country_platform=12, device_platform=22, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.5761249109652945, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1082]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=425, index=425, session_id='dc0fe2d9f5b48', timestamp=1541030533, user_id='KJZ36WFKZ52C', step=1, action=2, item_id=1082, platform=11, city=35, device=0, current_filters=nan, impressions=['2595209', '14677', '54982', '54901', '14675', '14211', '54902', '109040', '54953', '54981', '5790318', '5121996', '55039', '5817010', '54798', '55093', '54803', '7179508', '325981', '55051', '4393938', '2438214', '109021', '596891', '109038'], prices=[126, 183, 168, 113, 200, 200, 166, 149, 159, 138, 112, 123, 178, 115, 140, 154, 181, 106, 155, 190, 90, 116, 99, 67, 101], id=425, last_item=5321, second_last_item=5321, third_last_item=5321, country=18, country_platform=21, device_platform=18, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.5823255896015649, step_log=0.6931471805599453)

43it [00:00, 101.80it/s]

30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1129]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=440, index=440, session_id='dc21fffe0bc27', timestamp=1541030535, user_id='2ZJT3X9VXAUJ', step=1, action=2, item_id=1129, platform=19, city=91, device=0, current_filters=nan, impressions=['7875360', '7126898', '3534986', '352416', '1952071', '7243590', '1625363', '5656778', '95185', '97748', '105653', '1156735', '1216906', '1552471', '2508762', '3136154', '4770336', '7195380', '1832403', '2713384', '2402373', '105671', '363316', '105672', '1810893'], prices=[71, 94, 49, 31, 135, 128, 74, 43, 231, 164, 164, 47, 154, 78, 62, 158, 89, 78, 622, 57, 193, 299, 83, 137, 50], id=440, last_item=5321, second_last_item=5336, third_last_item=2154, country=28, country_platform=38, device_platform=34, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=0.0, rg_time_diff=0.5810818816960075, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1154]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=449, index=449, session_id='27ff8143867f0', timestamp=1541030536, user_id='M9VP63SSDK32', step=1, action=2, item_id=1154, platform=20, city=95, device=1, current_filters=nan, impressions=['52563', '244871', '6397', '6352', '53231', '51312', '51456', '53062', '53399', '1701973', '7934150', '7158228', '464471', '52532', '148268', '51173', '6375', '6368', '52311', '51211', '3144380', '81709', '7901016', '1349906', '6381'], prices=[75, 321, 245, 569, 71, 82, 75, 134, 176, 262, 50, 224, 89, 80, 69, 90, 56, 345, 126, 63, 421, 99, 90, 109, 67], id=449, last_item=5321, second_last_item=5340, third_last_item=5321, country=19, country_platform=39, device_platform=35, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=nan, rg_time_diff=0.6336572733417439, step_log=0.6931471805599453)
30
4
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 555, 555, 533]
[5321, 555, 555]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 555, 555]
[5433 5321  555]
Pandas(Index=452, index=452, session_id='6b55590fb1df5', timestamp=1541030537, user_id='I5UULR2BQMXY', step=4, action=2, item_id=533, platform=2, city=20, device=1, current_filters=nan, impressions=['402151', '73454', '1963891', '152282', '68944', '55563', '68900', '56517', '5977202', '152279', '1276149', '152280', '77589', '63348', '58473', '3102222', '79263', '64541', '1237763', '5476840', '940956', '62817', '102307', '62818', '64514'], prices=[367, 64, 179, 198, 169, 138, 98, 76, 66, 150, 270, 57, 170, 119, 130, 146, 74, 89, 147, 123, 352, 259, 237, 125, 290], id=452, last_item=5321, second_last_item=5339, third_last_item=1154, country=15, country_platform=16, device_platform=14, sess_step=4, time_diff=50.0, time_diff_diff=50.0, time_diff_diff_diff=88.0, time_diff_2=nan, time_diff_3=0.0, rg_time_diff=0.5117508136972144, step_log=1.6094379124341003)
30
5
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 1180, 1180, 1180]
[5321, 5321, 1180, 1180]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 1180, 1180]
[5433 5321 1180]
Pandas(Index=461, index=461, session_id='35aedb415c97a', timestamp=1541030538, user_id='CFXVGUXBIULG', step=5, action=2, item_id=1180, platform=2, city=77, device=1, current_filters=nan, impressions=['69103', '63295', '65184', '68039', '354611', '77384', '60335', '62353', '961097', '71785', '67308', '68044', '78141', '68041', '64254', '63045', '68043', '73010', '3865726', '2269004', '67059', '76110', '61285', '61557', '69245'], prices=[70, 119, 276, 57, 63, 41, 61, 95, 129, 76, 63, 69, 105, 92, 71, 79, 86, 71, 124, 131, 45, 54, 95, 104, 67], id=461, last_item=5321, second_last_item=5337, third_last_item=5337, country=15, country_platform=16, device_platform=14, sess_step=5, time_diff=8.0, time_diff_diff=8.0, time_diff_diff_diff=22.0, time_diff_2=nan, time_diff_3=0.0, rg_time_diff=0.13785893857010653, step_log=1.791759469228055)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1229]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=471, index=471, session_id='6c26e45791903', timestamp=1541030539, user_id='02WCP0B2T48F', step=1, action=2, item_id=1229, platform=2, city=99, device=1, current_filters=nan, impressions=['44932', '7107198', '43946', '5861070', '88549', '43822', '1449201', '5757802', '9786608', '44356', '44153', '44117', '10037782', '43651', '44423', '1281700', '44664', '44680', '44780', '44237', '43459', '43594', '5635212', '44759', '10016526'], prices=[47, 109, 138, 109, 91, 106, 134, 43, 171, 101, 70, 134, 87, 82, 65, 141, 100, 84, 141, 211, 45, 588, 175, 83, 224], id=471, last_item=5321, second_last_item=1204, third_last_item=5337, country=4, country_platform=45, device_platform=14, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=nan, rg_time_diff=0.6075911227820694, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1254]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=477, index=477, session_id='64cb0f57a08ec', timestamp=1541030541, user_id='S2LQFHEVY0U2', step=1, action=2, item_id=1254, platform=2, city=102, device=2, current_filters=nan, impressions=['8578', '8568', '8549', '8582', '8602', '8588', '32727', '55677', '58492', '72426', '1217148', '2793224', '10700660', '8618', '63477', '9287896', '1094242', '6723510', '102082', '8530', '67144', '6049310', '8614', '1369070', '8544'], prices=[50, 50, 56, 50, 108, 53, 227, 85, 90, 87, 117, 173, 119, 72, 119, 261, 165, 235, 79, 141, 99, 83, 80, 129, 79], id=477, last_item=5321, second_last_item=5321, third_last_item=1655, country=15, country_platform=16, device_platform=2, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=2.0, rg_time_diff=1.1629156969017258, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1284]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=478, index=478, session_id='9b402dee0a629', timestamp=1541030541, user_id='CG0AHXZ65CDA', step=1, action=2, item_id=1284, platform=2, city=51, device=1, current_filters=nan, impressions=['8642', '1285525', '8628', '986971', '1104798', '1811137', '8772', '8796', '2835834', '8716', '8722', '8738', '8744', '8809', '8815', '1364388', '8653', '3132652', '8792', '8652', '8818', '8682', '1455521', '5816800', '8650'], prices=[217, 200, 236, 350, 191, 151, 175, 134, 299, 208, 163, 170, 140, 175, 158, 177, 172, 236, 183, 215, 204, 225, 284, 256, 238], id=478, last_item=5321, second_last_item=5321, third_last_item=5321, country=15, country_platform=16, device_platform=14, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=1.1733262621769716, step_log=0.6931471805599453)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 1313, 1313]
[5321, 1313]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 1313]
[5433 5321 1313]
Pandas(Index=485, index=485, session_id='386135db7e257', timestamp=1541030543, user_id='ZXDUZ7BVPFCY', step=3, action=2, item_id=1313, platform=10, city=61, device=1, current_filters=nan, impressions=['6031716', '6405716', '6692702', '2625816', '5072118', '2626160', '1664609', '2625818', '7964732', '2626168', '6874372', '11193850', '5800502'], prices=[44, 34, 33, 41, 57, 48, 53, 64, 57, 31, 27, 42, 44], id=485, last_item=5342, second_last_item=1313, third_last_item=5321, country=17, country_platform=20, device_platform=20, sess_step=3, time_diff=0.0, time_diff_diff=-47.0, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=47.0, rg_time_diff=-0.14781342407973044, step_log=1.3862943611198906)
30
4
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 185, 185, 185, 185]
[185, 185, 185]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 185, 185, 185]
[5433  185]
Pandas(Index=491, index=491, session_id='52b4184549d38', timestamp=1541030544, user_id='H147K5X0M08L', step=4, action=2, item_id=185, platform=2, city=28, device=0, current_filters=nan, impressions=['43120', '804296', '35158', '101455', '844266', '42400', '101452', '42489', '35167', '1390390', '1370232', '35152', '35151', '3409732', '42783', '35159', '10939302', '101451', '43061', '101456', '1335401', '843996', '152946', '1355549', '10149966'], prices=[165, 182, 174, 225, 215, 369, 66, 124, 235, 224, 83, 227, 302, 151, 135, 464, 349, 113, 158, 134, 732, 96, 226, 164, 164], id=491, last_item=2154, second_last_item=5321, third_last_item=2154, country=8, country_platform=18, device_platform=3, sess_step=4, time_diff=43.0, time_diff_diff=36.0, time_diff_diff_diff=29.0, time_diff_2=0.0, time_diff_3=nan, rg_time_diff=0.4900987244359823, step_log=1.6094379124341003)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 1323]
[5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321]
[5433 5321]
Pandas(Index=493, index=493, session_id='c277ca58ba683', timestamp=1541030546, user_id='DT256AR2XSH7', step=2, action=2, item_id=1323, platform=16, city=76, device=0, current_filters=nan, impressions=['3568656', '5870422', '8136696', '7953226', '9431130', '6918920', '9250072', '8437838', '9079220', '9243738', '9429828', '9753148'], prices=[40, 42, 32, 10, 11, 38, 16, 60, 203, 179, 110, 87], id=493, last_item=5338, second_last_item=5321, third_last_item=2154, country=25, country_platform=32, device_platform=32, sess_step=2, time_diff=33.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=11.0, time_diff_3=43.0, rg_time_diff=0.4546303968282544, step_log=1.0986122886681098)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 1332]
[5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321]
[5433 5321]
Pandas(Index=495, index=495, session_id='e9b93097fe7aa', timestamp=1541030546, user_id='WYB6KIXGPCDM', step=2, action=2, item_id=1332, platform=10, city=30, device=0, current_filters=nan, impressions=['6338722', '2680548', '1054978', '2891218', '2816074', '1198706', '3132756', '2328968', '2858081', '3498588', '5841682', '1177976', '2673518', '1723413', '2031211', '4276254', '5028864', '218936', '2832868', '3947496', '2030315', '1564603', '1004007', '1351027', '3185772'], prices=[78, 55, 75, 41, 79, 36, 55, 69, 33, 108, 81, 71, 39, 114, 56, 43, 60, 45, 77, 44, 29, 46, 81, 48, 42], id=495, last_item=5335, second_last_item=5321, third_last_item=5338, country=17, country_platform=20, device_platform=17, sess_step=2, time_diff=86.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=10.0, time_diff_3=33.0, rg_time_diff=0.5517514602375171, step_log=1.0986122886681098)

54it [00:00, 101.33it/s]

30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1235]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=496, index=496, session_id='c040d3f0060b7', timestamp=1541030546, user_id='NWWJSEGXU68Y', step=1, action=2, item_id=1235, platform=6, city=99, device=1, current_filters=nan, impressions=['1449201', '7107198', '44548', '3135017', '5861070', '44076', '44681', '44355', '6227386', '44372', '44153', '43371', '43946', '88550', '44493', '1021779', '44922', '43459', '44423', '101001', '44680', '44790', '88688', '44781', '44544'], prices=[107, 97, 134, 93, 103, 27, 102, 114, 73, 146, 70, 128, 138, 51, 77, 140, 93, 48, 65, 72, 75, 93, 134, 147, 83], id=496, last_item=5321, second_last_item=5335, third_last_item=1323, country=4, country_platform=11, device_platform=31, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=86.0, time_diff_3=10.0, rg_time_diff=1.1839975546816004, step_log=0.6931471805599453)
30
4
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 1371]
[5321, 5321, 5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321]
[5433 5321]
Pandas(Index=534, index=534, session_id='43c4322e9cbc4', timestamp=1541030552, user_id='O16KSM0PUEAE', step=4, action=2, item_id=1371, platform=5, city=92, device=0, current_filters='Best Value', impressions=['2230286', '3134856', '7754674', '5145928', '1956013', '2292840', '2100196', '1438139', '787111', '2102190', '346886', '3536784', '7739988'], prices=[43, 78, 81, 34, 63, 70, 85, 46, 85, 89, 83, 72, 137], id=534, last_item=5344, second_last_item=5344, third_last_item=470, country=11, country_platform=12, device_platform=22, sess_step=4, time_diff=10.0, time_diff_diff=10.0, time_diff_diff_diff=17.0, time_diff_2=0.0, time_diff_3=56.0, rg_time_diff=0.2826620848869001, step_log=1.6094379124341003)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 1390]
[5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321]
[5433 5321]
Pandas(Index=537, index=537, session_id='31ef33fa031b6', timestamp=1541030552, user_id='LS01KKCEXUTM', step=2, action=2, item_id=1390, platform=0, city=55, device=1, current_filters=nan, impressions=['5640586', '1560261', '1887101', '1240766', '1348600', '2030955', '586771', '588596', '997745', '1560263', '1266075', '512136', '2273390', '585331', '2027493', '6142702', '4031640', '1827521', '2771340', '2454104', '2063186', '1708049', '1652507', '1299897', '2312188'], prices=[91, 119, 97, 158, 153, 127, 175, 120, 206, 201, 129, 157, 93, 165, 197, 105, 160, 134, 134, 105, 367, 93, 95, 129, 116], id=537, last_item=5321, second_last_item=5321, third_last_item=1371, country=0, country_platform=0, device_platform=4, sess_step=2, time_diff=68.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=10.0, rg_time_diff=0.5386221436947376, step_log=1.0986122886681098)
30
4
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 134, 5321, 1421]
[5321, 134, 5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 134, 5321]
[5433 5321  134]
Pandas(Index=545, index=545, session_id='dab0a59d898da', timestamp=1541030554, user_id='YXAK2A5U45VR', step=4, action=2, item_id=1421, platform=3, city=6, device=1, current_filters='Excellent Rating', impressions=['44690', '44344', '44342', '43499', '101006', '3123886', '43498', '960121', '121124', '43965', '1319714', '43603', '44343', '1285722', '44863', '43771', '44827', '928767', '43990', '44156', '1297788', '44338', '1800653', '3054411', '5216430'], prices=[161, 105, 126, 114, 192, 112, 122, 179, 141, 131, 118, 100, 95, 231, 140, 193, 135, 146, 149, 182, 103, 123, 220, 221, 167], id=545, last_item=2154, second_last_item=5321, third_last_item=2154, country=4, country_platform=4, device_platform=5, sess_step=4, time_diff=76.0, time_diff_diff=38.0, time_diff_diff_diff=16.0, time_diff_2=0.0, time_diff_3=2.0, rg_time_diff=0.54456673363435, step_log=1.6094379124341003)
30
4
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1204, 1204, 1204, 1204]
[1204, 1204, 1204]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1204, 1204, 1204]
[5433 1204]
Pandas(Index=549, index=549, session_id='95bbc5d155a7e', timestamp=1541030555, user_id='FK3WQXDLINIT', step=4, action=2, item_id=1204, platform=23, city=98, device=1, current_filters=nan, impressions=['1056094', '2884070', '35281', '80760', '1005807', '35277', '35283', '439371', '914597', '1946391', '1886331', '1503093', '971589', '2548232', '9198018', '1548189', '35268', '1360729', '35269', '5663676', '35278', '80785', '378581', '7109756', '34258'], prices=[33, 39, 47, 91, 66, 27, 39, 96, 77, 60, 85, 76, 55, 57, 36, 72, 58, 129, 81, 75, 73, 108, 114, 76, 269], id=549, last_item=5345, second_last_item=5321, third_last_item=2154, country=30, country_platform=44, device_platform=39, sess_step=4, time_diff=3.0, time_diff_diff=-10.0, time_diff_diff_diff=-23.0, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.06259189703673411, step_log=1.6094379124341003)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1429]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=550, index=550, session_id='1a2cb558e4822', timestamp=1541030555, user_id='EJTPU37XVP9D', step=1, action=2, item_id=1429, platform=26, city=116, device=1, current_filters=nan, impressions=['83359', '481466', '149839', '82286', '48503', '1328741', '1216234', '49362', '12233', '100048', '12263', '48643', '12090', '50478', '12227', '11933', '11920', '12192', '929963', '12256', '12265', '50648', '50042', '99842', '50221'], prices=[123, 107, 104, 88, 137, 187, 169, 110, 81, 57, 93, 272, 113, 163, 106, 79, 121, 192, 131, 145, 169, 107, 462, 84, 173], id=550, last_item=5321, second_last_item=5345, third_last_item=5321, country=3, country_platform=50, device_platform=43, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=3.0, time_diff_3=nan, rg_time_diff=1.2377578283763324, step_log=0.6931471805599453)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 799, 801]
[5321, 799]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 799]
[5433 5321  799]
Pandas(Index=554, index=554, session_id='c3ab0a7dd5987', timestamp=1541030556, user_id='BI7OPK1TOHG0', step=3, action=2, item_id=801, platform=10, city=37, device=0, current_filters=nan, impressions=['1090284', '180596', '930213', '1321522', '1323046', '1204178', '1478241', '784396', '180166', '5123012', '1238687', '220661', '181541', '181516', '3140341', '477476', '180771', '520176', '1333374', '180191', '181941', '4465932', '181871', '973043', '377416'], prices=[121, 213, 55, 116, 96, 203, 119, 42, 207, 68, 60, 91, 169, 154, 418, 89, 129, 95, 76, 88, 204, 120, 123, 62, 82], id=554, last_item=1881, second_last_item=1881, third_last_item=5321, country=17, country_platform=20, device_platform=17, sess_step=3, time_diff=47.0, time_diff_diff=2.0, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=nan, rg_time_diff=0.502576771953098, step_log=1.3862943611198906)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1454]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=562, index=562, session_id='c2f6655d4e3aa', timestamp=1541030556, user_id='TP3MWPSSGS6R', step=1, action=2, item_id=1454, platform=0, city=118, device=1, current_filters=nan, impressions=['2039433', '2501476', '2710194', '2680834', '2028413', '1144762', '2273490', '2924161', '2677944', '2799296', '507826', '2710882', '3051036', '4479498', '9785720', '2811686', '2571906', '2681016', '2673542', '2778098', '2510376', '2273630', '2362872', '6474438', '4129204'], prices=[79, 102, 52, 93, 41, 68, 41, 42, 63, 38, 57, 27, 29, 27, 29, 38, 54, 64, 42, 75, 75, 226, 36, 59, 57], id=562, last_item=5321, second_last_item=720, third_last_item=5335, country=0, country_platform=0, device_platform=4, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=48.0, rg_time_diff=1.229633534163703, step_log=0.6931471805599453)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1480, 1493]
[1480]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1480]
[5433 1480]
Pandas(Index=569, index=569, session_id='af794994fd450', timestamp=1541030558, user_id='FTT0AG78WDL7', step=2, action=2, item_id=1493, platform=17, city=73, device=1, current_filters=nan, impressions=['2309450', '4647504', '1640003', '4983898', '2345516', '4807564', '4085588', '1016003', '1998347', '3892776', '1527753', '3177430', '2712051', '1175636', '5107260', '8288010', '6442890'], prices=[40, 40, 92, 49, 33, 30, 35, 47, 49, 34, 35, 27, 39, 36, 25, 40, 30], id=569, last_item=5346, second_last_item=5321, third_last_item=5346, country=26, country_platform=33, device_platform=30, sess_step=2, time_diff=46.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.49915828193005757, step_log=1.0986122886681098)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1521]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=586, index=586, session_id='06a5101e774e6', timestamp=1541030559, user_id='LNMO18IGWIP3', step=1, action=2, item_id=1521, platform=3, city=121, device=1, current_filters=nan, impressions=['2882116', '4531872', '3844110', '1487861', '3135398', '42362', '42918', '4727262', '43032', '3252445', '4651186', '43135', '42434', '1625915', '2397140', '3176670', '6239004', '3491382', '3248058', '43017', '3144108', '42393', '385326', '1491341', '3969140'], prices=[33, 35, 36, 43, 54, 52, 53, 78, 81, 57, 47, 55, 101, 43, 47, 52, 70, 58, 54, 55, 61, 54, 47, 49, 43], id=586, last_item=5321, second_last_item=5347, third_last_item=5321, country=8, country_platform=8, device_platform=5, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=1.117382621333532, step_log=0.6931471805599453)
30
26
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 1546, 1546, 1546, 1546, 1546, 1546, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1549, 1549, 1549, 1549, 1549, 1549, 1549, 1549, 1549, 1549, 1549, 1549, 1549, 1549]
[5321, 1546, 1546, 1546, 1546, 1546, 1546, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 1546, 1546, 1546, 1546, 1546, 1546, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547, 1547]
[5433 5321 1546 1547]
Pandas(Index=589, index=589, session_id='508f89052e428', timestamp=1541030560, user_id='T59PG6YUDY5R', step=26, action=2, item_id=1549, platform=0, city=45, device=1, current_filters=nan, impressions=['7770070', '2436946', '3387958', '2899803', '4054726', '3581776', '2645579', '3487706', '4545180', '3469314', '5074844', '4823600', '5220292', '8947714', '8408782', '5756940', '7735824'], prices=[52, 60, 85, 76, 34, 55, 58, 62, 45, 59, 46, 46, 45, 13, 18, 25, 31], id=589, last_item=5347, second_last_item=1655, third_last_item=1521, country=0, country_platform=0, device_platform=4, sess_step=26, time_diff=3.0, time_diff_diff=3.0, time_diff_diff_diff=3.0, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.06081179186708857, step_log=3.295836866004329)

65it [00:00, 102.42it/s]

30
5
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 5321, 1569]
[5321, 5321, 5321, 5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 5321]
[5433 5321]
Pandas(Index=592, index=592, session_id='4fe40cb96a3d2', timestamp=1541030560, user_id='OZT9NAKEQMNW', step=5, action=2, item_id=1569, platform=8, city=26, device=0, current_filters='Sort by Price', impressions=['5148390', '892233', '2208510', '5842768', '5837014', '137512', '41958', '1033596', '2628242', '8403260', '149717', '4087002', '1054624', '8271090', '6448348', '10588590', '14024', '5888194', '9366736', '927037', '2459696', '4068978', '10113736', '3135551', '8760006'], prices=[21, 36, 52, 52, 55, 64, 74, 75, 77, 79, 81, 81, 83, 83, 83, 84, 87, 86, 92, 92, 95, 95, 96, 97, 98], id=592, last_item=1910, second_last_item=1910, third_last_item=1549, country=16, country_platform=17, device_platform=16, sess_step=5, time_diff=40.0, time_diff_diff=40.0, time_diff_diff_diff=44.0, time_diff_2=0.0, time_diff_3=nan, rg_time_diff=0.4811189128253575, step_log=1.791759469228055)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1594]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=615, index=615, session_id='600cdac0d499f', timestamp=1541030562, user_id='CNPCQXST2UH1', step=1, action=2, item_id=1594, platform=0, city=124, device=1, current_filters=nan, impressions=['2862434', '4344566', '3227065', '3875030', '2828683', '4037596', '5824850', '2813110', '2038343', '2424638', '2680840', '2858025', '6200338', '8301088', '8502432'], prices=[222, 56, 39, 182, 63, 319, 36, 54, 137, 269, 154, 41, 65, 233, 56], id=615, last_item=5321, second_last_item=5344, third_last_item=5341, country=0, country_platform=0, device_platform=4, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=10.0, rg_time_diff=1.0649059520097657, step_log=0.6931471805599453)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1603, 1603]
[1603]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1603]
[5433 1603]
Pandas(Index=616, index=616, session_id='6429807213aa2', timestamp=1541030562, user_id='10YWLZJ8Z210', step=2, action=2, item_id=1603, platform=5, city=123, device=0, current_filters=nan, impressions=['1955777', '7355902', '381666', '1722377', '508161', '1711865', '9392730', '1521923', '346801', '1952629', '1172829', '1932079', '1010793', '1010797', '1098502', '2777999', '1010809', '1010813', '4096668', '10494890', '2198394', '4117622', '1887017', '1886359', '1981699'], prices=[80, 80, 53, 55, 54, 57, 56, 93, 58, 63, 48, 62, 80, 65, 62, 49, 63, 73, 55, 66, 53, 31, 49, 98, 78], id=616, last_item=1594, second_last_item=5321, third_last_item=5344, country=11, country_platform=12, device_platform=22, sess_step=2, time_diff=0.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=0.0, rg_time_diff=-1.0127444138989112, step_log=1.0986122886681098)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1628]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=617, index=617, session_id='3e8108e9ed9ee', timestamp=1541030563, user_id='WM9HLPIROTDL', step=1, action=2, item_id=1628, platform=13, city=125, device=1, current_filters=nan, impressions=['1251243', '54425', '5518614', '54096', '54105', '54239', '54240', '99416', '148681', '529156', '395056', '6559504', '8513668', '3148936', '99408', '1011295', '3759850', '99417', '1775957', '99412', '54496', '99424', '1812485', '1105472', '54132'], prices=[37, 51, 33, 210, 126, 135, 145, 195, 105, 114, 59, 69, 134, 73, 99, 140, 56, 183, 93, 95, 108, 104, 258, 117, 123], id=617, last_item=5321, second_last_item=1594, third_last_item=5344, country=34, country_platform=54, device_platform=23, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=nan, rg_time_diff=1.0676699746475316, step_log=0.6931471805599453)
30
27
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 5321, 5321, 5321, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655]
[5321, 5321, 5321, 5321, 5321, 5321, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 5321, 5321, 5321, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655, 1655]
[5433 5321 1655]
Pandas(Index=618, index=618, session_id='eb524efcd7bc9', timestamp=1541030563, user_id='1BPL57EV423O', step=27, action=2, item_id=1655, platform=9, city=57, device=1, current_filters='Sort by Price', impressions=['483816', '4436860', '40373', '1063546', '1275496', '655601', '676016', '2432707', '2612714', '851356', '6756', '6781', '6785', '1272432', '1771561', '2143896', '6755', '130909', '1515725', '118415', '1932657', '2609912', '3096154', '3812812', '40562'], prices=[39, 43, 51, 75, 77, 79, 80, 81, 81, 82, 83, 85, 85, 85, 86, 88, 89, 89, 89, 90, 90, 90, 90, 90, 94], id=618, last_item=1628, second_last_item=1603, third_last_item=1594, country=22, country_platform=28, device_platform=25, sess_step=27, time_diff=4.0, time_diff_diff=4.0, time_diff_diff_diff=4.0, time_diff_2=nan, time_diff_3=0.0, rg_time_diff=0.08309452134595809, step_log=3.332204510175204)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1678]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=620, index=620, session_id='0df5cc73c3f35', timestamp=1541030564, user_id='8YH628HR4T49', step=1, action=2, item_id=1678, platform=10, city=88, device=1, current_filters=nan, impressions=['5970378', '183266', '183276', '1544745', '1104184', '1216944', '6235440', '1841929', '164432', '165124', '2635950', '2791019', '2556593', '3916290', '3493644', '164405', '2814348', '3165296', '1185474', '185291', '5416604', '185301', '1457587', '517571', '507871'], prices=[24, 67, 45, 26, 218, 52, 121, 48, 63, 82, 22, 27, 159, 47, 150, 961, 37, 43, 169, 35, 37, 192, 64, 29, 52], id=620, last_item=5321, second_last_item=1655, third_last_item=1628, country=17, country_platform=20, device_platform=20, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=10.0, time_diff_3=4.0, rg_time_diff=1.0704504078689319, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1725, 1725, 1725, 1725, 1725, 1725, 1725, 1725, 1725, 1725]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=631, index=631, session_id='e97ad2ca8777d', timestamp=1541030565, user_id='VQ02TLDHHW8V', step=1, action=2, item_id=1725, platform=0, city=127, device=1, current_filters=nan, impressions=['2326194', '1321131', '109324', '7773394', '2179366', '2196150', '104905', '2053269', '116406', '2097974', '111530', '9774742', '1776269', '2631196', '1829443', '147209', '1239510', '132249', '2030423', '2074932', '2085906', '9842734', '326726', '2650834', '7825940'], prices=[71, 80, 95, 119, 66, 53, 45, 51, 151, 75, 74, 56, 47, 89, 32, 39, 195, 77, 45, 49, 46, 45, 71, 32, 54], id=631, last_item=5321, second_last_item=5321, third_last_item=5321, country=0, country_platform=0, device_platform=4, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.7652693162642198, step_log=0.6931471805599453)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 1704]
[5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321]
[5433 5321]
Pandas(Index=627, index=627, session_id='7a3f6b6e61457', timestamp=1541030565, user_id='957LMVE7WFZF', step=2, action=2, item_id=1704, platform=4, city=113, device=1, current_filters=nan, impressions=['2013035', '1018669', '3873416', '4491140', '1978597', '3893376', '5969264', '2362564', '7306762', '2033173', '5760086', '8926744', '11102708', '6785746', '6711480', '6306882', '8940866', '9347384', '9325860', '7141382', '7850606', '9759498'], prices=[49, 33, 21, 37, 60, 30, 18, 20, 59, 24, 14, 76, 11, 56, 76, 14, 76, 56, 21, 16, 76, 55], id=627, last_item=470, second_last_item=5321, third_last_item=5321, country=5, country_platform=5, device_platform=6, sess_step=2, time_diff=12.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=14.0, time_diff_3=nan, rg_time_diff=0.31367563965116874, step_log=1.0986122886681098)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 1751]
[5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321]
[5433 5321]
Pandas(Index=634, index=634, session_id='867c1c60951e8', timestamp=1541030566, user_id='NO9T9GAYQC0L', step=2, action=2, item_id=1751, platform=10, city=83, device=1, current_filters=nan, impressions=['1104340', '1330334', '1639441', '137196', '1474549', '936809', '218976', '1322768', '1277546', '1268270', '1254224', '2777017', '1254206', '2303062', '2006405', '3193850', '3247982', '2047019', '5999528', '4481468', '1254214', '9350378', '3163158', '1172589', '4281222'], prices=[198, 128, 115, 105, 97, 159, 230, 65, 41, 140, 28, 98, 32, 115, 107, 34, 19, 35, 177, 81, 32, 35, 28, 32, 53], id=634, last_item=5321, second_last_item=5321, third_last_item=1725, country=17, country_platform=20, device_platform=20, sess_step=2, time_diff=48.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=2.0, time_diff_3=nan, rg_time_diff=0.5094492754931804, step_log=1.0986122886681098)
30
6
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1777, 1777, 1775, 1776, 1776, 1775]
[1777, 1777, 1775, 1776, 1776]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1777, 1777, 1775, 1776, 1776]
[5433 1777 1775 1776]
Pandas(Index=661, index=661, session_id='d26984645d59c', timestamp=1541030568, user_id='SZ63RMQN5TJE', step=6, action=2, item_id=1775, platform=24, city=63, device=1, current_filters=nan, impressions=['2030807', '3253016', '3816082', '3583466', '2291584', '493931', '3134218', '3556430', '512031', '5831426', '3932178', '3154623', '5164832', '1205154', '104145', '3134211', '7785448', '1357250', '3899422', '3184548', '4600102', '3367262', '3833312', '8502310', '1357296'], prices=[23, 38, 27, 30, 141, 45, 34, 72, 51, 34, 15, 62, 27, 98, 74, 19, 110, 64, 28, 35, 45, 33, 8, 76, 107], id=661, last_item=5346, second_last_item=5346, third_last_item=5346, country=14, country_platform=47, device_platform=40, sess_step=6, time_diff=10.0, time_diff_diff=10.0, time_diff_diff_diff=10.0, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.23430914044913567, step_log=1.9459101490553132)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 1823]
[5321, 5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321]
[5433 5321]
Pandas(Index=671, index=671, session_id='5a0295824e8ba', timestamp=1541030570, user_id='5BKYS6JUDJ1G', step=3, action=2, item_id=1823, platform=11, city=107, device=0, current_filters=nan, impressions=['668981', '668946', '1395521', '387161', '1435100', '2144692', '1824797', '594481', '521236', '1420500', '387441', '1709029', '2124418', '2153904', '1397058', '3895222', '101807', '1831769', '668901', '2940814', '10159572', '2876356', '8978470', '9874256', '10307478'], prices=[362, 113, 102, 130, 197, 123, 131, 118, 106, 151, 165, 140, 132, 148, 115, 59, 69, 118, 104, 91, 208, 79, 148, 122, 620], id=671, last_item=5335, second_last_item=5349, third_last_item=5321, country=18, country_platform=21, device_platform=18, sess_step=3, time_diff=20.0, time_diff_diff=19.0, time_diff_diff_diff=nan, time_diff_2=14.0, time_diff_3=26.0, rg_time_diff=0.38379072438501854, step_log=1.3862943611198906)

76it [00:00, 103.48it/s]

30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1825, 1825, 1825, 1825, 1825]
[1825]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1825]
[5433 1825]
Pandas(Index=676, index=676, session_id='136bbc9a8e1df', timestamp=1541030570, user_id='HW3JCL2KCKQ5', step=2, action=2, item_id=1825, platform=28, city=128, device=1, current_filters=nan, impressions=['908501', '15256', '95749', '17751', '81107', '18349', '6801664', '1695323', '25882', '101718', '132104', '4275286', '95748', '2161540', '7151220', '55248', '9283', '13844', '9275', '14802', '1374606', '1036356', '5681254', '15382', '18271'], prices=[52, 45, 45, 57, 124, 110, 35, 33, 118, 189, 125, 199, 60, 191, 62, 154, 73, 80, 44, 39, 125, 125, 85, 164, 64], id=676, last_item=5335, second_last_item=5321, third_last_item=5349, country=35, country_platform=55, device_platform=47, sess_step=2, time_diff=4.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=21.0, rg_time_diff=0.0982926984494285, step_log=1.0986122886681098)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 1863, 1863]
[5321, 1863]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 1863]
[5433 5321 1863]
Pandas(Index=678, index=678, session_id='25bf4e438485a', timestamp=1541030571, user_id='SQPO1K88313N', step=3, action=2, item_id=1863, platform=5, city=56, device=1, current_filters=nan, impressions=['1519063', '954519', '103484', '1320590', '1049914', '8805412', '1472993', '3539818', '103656', '6163642', '1049928', '6806728', '6806398', '1532635', '103452', '891093', '5951518', '4715472', '1127559', '1131661', '1207055', '346826', '3424700', '4276406'], prices=[127, 164, 212, 129, 165, 94, 123, 213, 196, 138, 93, 109, 150, 265, 254, 300, 125, 66, 422, 338, 125, 198, 178, 328], id=678, last_item=475, second_last_item=1825, third_last_item=5321, country=11, country_platform=12, device_platform=7, sess_step=3, time_diff=3.0, time_diff_diff=-77.0, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=4.0, rg_time_diff=0.07863207863174468, step_log=1.3862943611198906)
30
6
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 470, 470, 475, 475, 475]
[5321, 470, 470, 475, 475]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 470, 470, 475, 475]
[5433 5321  470  475]
Pandas(Index=679, index=679, session_id='c1159dd77b548', timestamp=1541030571, user_id='FOM5X2ET44EK', step=6, action=2, item_id=475, platform=3, city=22, device=1, current_filters=nan, impressions=['948643', '1346370', '34350', '42663', '2196006', '100302', '43160', '42620', '2759726', '1693345', '2383711', '34345', '995577', '9694870', '3222602', '3385586', '8940514', '42342', '7180454', '995609', '3500744', '2880592', '9675972', '43114', '6670002'], prices=[110, 376, 238, 95, 88, 132, 298, 36, 88, 43, 87, 30, 33, 15, 55, 56, 56, 37, 64, 29, 63, 41, 37, 42, 243], id=679, last_item=1863, second_last_item=475, third_last_item=1825, country=8, country_platform=8, device_platform=5, sess_step=6, time_diff=1.0, time_diff_diff=1.0, time_diff_diff_diff=85.0, time_diff_2=3.0, time_diff_3=0.0, rg_time_diff=0.02261394588365841, step_log=1.9459101490553132)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1881, 1881, 1881]
[1881, 1881]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1881, 1881]
[5433 1881]
Pandas(Index=682, index=682, session_id='491d4b6bcf818', timestamp=1541030571, user_id='UBZEMQR1X1YU', step=3, action=2, item_id=1881, platform=12, city=117, device=1, current_filters=nan, impressions=['17085', '3381906', '4697502', '1434428', '17553', '17594', '2941930', '5845202', '150160', '8173546', '17066', '484941', '6001568', '2200778', '3183770', '2466776', '16855', '17056', '896349', '2759696', '3229758', '915817', '16886', '3131976', '17002'], prices=[64, 58, 69, 59, 51, 55, 55, 50, 52, 94, 64, 46, 111, 120, 75, 61, 51, 73, 68, 144, 59, 79, 110, 48, 94], id=682, last_item=5351, second_last_item=5350, third_last_item=5321, country=32, country_platform=51, device_platform=44, sess_step=3, time_diff=16.0, time_diff_diff=16.0, time_diff_diff_diff=nan, time_diff_2=33.0, time_diff_3=nan, rg_time_diff=0.3543237650546241, step_log=1.3862943611198906)
30
4
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1910, 1910, 1910, 1910]
[1910, 1910, 1910]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1910, 1910, 1910]
[5433 1910]
Pandas(Index=683, index=683, session_id='400484196b4fa', timestamp=1541030571, user_id='4AXJARGVXPJT', step=4, action=2, item_id=1910, platform=11, city=122, device=0, current_filters=nan, impressions=['180016', '4985468', '7136380', '1523381', '1326895', '7895312', '5434848', '1863281', '7979904', '1700559', '4554100', '1471959', '6865112', '3199841', '628786', '9992366', '5628634', '8195982', '9808726', '10148978', '9939352', '9436320', '9922576', '8271350'], prices=[241, 167, 198, 180, 93, 202, 113, 129, 282, 134, 307, 98, 374, 189, 229, 154, 61, 358, 740, 202, 358, 154, 166, 1048], id=683, last_item=1881, second_last_item=5351, third_last_item=5350, country=33, country_platform=52, device_platform=18, sess_step=4, time_diff=1.0, time_diff_diff=-9.0, time_diff_diff_diff=-19.0, time_diff_2=16.0, time_diff_3=33.0, rg_time_diff=0.013744254426889438, step_log=1.6094379124341003)
30
4
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 1923, 5321, 5321, 5321]
[5321, 5321, 5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321]
[5433 5321]
Pandas(Index=697, index=697, session_id='8497a41734156', timestamp=1541030572, user_id='3XT0FXWCCCH0', step=4, action=2, item_id=1923, platform=0, city=51, device=1, current_filters='Good Rating|Free WiFi (Combined)', impressions=['8733', '149587', '1364388', '2835834', '1455521', '3137056', '8792', '1104798', '2298566', '149599', '8665', '102097', '8825', '68636', '8653', '149589', '3480558', '2632669', '3240336', '102120', '8628', '8822', '8758', '1169991', '1170045'], prices=[155, 113, 113, 187, 161, 125, 117, 146, 135, 137, 116, 116, 188, 180, 116, 194, 120, 119, 128, 110, 144, 358, 147, 129, 138], id=697, last_item=5341, second_last_item=5341, third_last_item=5344, country=15, country_platform=25, device_platform=4, sess_step=4, time_diff=3.0, time_diff_diff=-1.0, time_diff_diff_diff=67.0, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.07773997144898066, step_log=1.6094379124341003)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1941]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=733, index=733, session_id='ce1053806c7a3', timestamp=1541030576, user_id='BN0B7IQBM8JZ', step=1, action=2, item_id=1941, platform=3, city=133, device=1, current_filters=nan, impressions=['3213754', '399666', '2423413', '5887116', '42543', '4544008', '2685824', '1481527', '1796831', '943407', '8446228', '2798335', '10679444', '6675146', '7058674', '5823050', '2423440', '2828736', '4746456', '7366860', '7677220', '9013254', '10076480', '11205096'], prices=[39, 274, 58, 59, 285, 70, 109, 133, 88, 79, 70, 48, 352, 209, 196, 273, 59, 64, 202, 63, 87, 148, 231, 109], id=733, last_item=5321, second_last_item=2154, third_last_item=2154, country=8, country_platform=8, device_platform=5, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=6.0, time_diff_3=0.0, rg_time_diff=1.0992128169407658, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1965]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=748, index=748, session_id='40086cab66f26', timestamp=1541030577, user_id='9DKC0XDI5SW3', step=1, action=2, item_id=1965, platform=2, city=134, device=1, current_filters=nan, impressions=['59482', '835876', '353726', '62087', '3132582', '72594', '62235', '56542', '56703', '63704', '68175', '68177', '79374', '5418262', '59601', '6025464', '60352', '68176', '72865', '9108276', '9041470', '59079', '8702734', '9577942', '1232342'], prices=[73, 80, 53, 119, 53, 129, 151, 141, 87, 138, 45, 134, 111, 155, 55, 84, 61, 44, 117, 177, 354, 44, 221, 354, 89], id=748, last_item=5321, second_last_item=2054, third_last_item=1825, country=15, country_platform=16, device_platform=14, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=1.5161859187834428, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1993]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=764, index=764, session_id='d6320407e2917', timestamp=1541030578, user_id='I3GLTXI7S5Q7', step=1, action=2, item_id=1993, platform=0, city=64, device=0, current_filters=nan, impressions=['5659850', '104809', '105014', '95794', '104565', '104706', '104528', '104880', '477971', '104650', '97505', '2924213', '5763334', '95685', '111534', '2281300', '326731', '104648', '104811', '104776', '130772', '478096', '104800', '4327354', '104949'], prices=[131, 65, 145, 34, 54, 162, 55, 145, 37, 189, 100, 57, 97, 76, 53, 65, 388, 66, 56, 123, 67, 65, 42, 70, 72], id=764, last_item=5321, second_last_item=5321, third_last_item=5354, country=0, country_platform=0, device_platform=0, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=1.0, rg_time_diff=1.5847744415438416, step_log=0.6931471805599453)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1104, 1105]
[1104]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1104]
[5433 1104]
Pandas(Index=772, index=772, session_id='e310846a86334', timestamp=1541030579, user_id='GI2JSAT3093L', step=2, action=2, item_id=1105, platform=2, city=90, device=1, current_filters=nan, impressions=['72581', '18260', '60120', '60214', '3842430', '67267', '396326', '65165', '75495', '78270', '2827862', '57745', '71082', '384506', '60683', '67245', '67250', '67243', '442396', '972655', '67254', '71708', '74205', '5788824', '6434516'], prices=[209, 118, 121, 114, 109, 132, 158, 162, 130, 136, 114, 152, 98, 101, 60, 68, 67, 84, 163, 59, 66, 82, 90, 118, 135], id=772, last_item=820, second_last_item=5321, third_last_item=5321, country=15, country_platform=16, device_platform=14, sess_step=2, time_diff=44.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=69.0, time_diff_3=nan, rg_time_diff=0.4934865580691819, step_log=1.0986122886681098)

86it [00:00, 99.74it/s]

30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 817, 820]
[817]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 817]
[5433  817]
Pandas(Index=771, index=771, session_id='e2cd4a48cf65d', timestamp=1541030579, user_id='FXFSX09BGZ70', step=2, action=2, item_id=820, platform=16, city=71, device=1, current_filters=nan, impressions=['8280226', '8238358', '2812948', '7851766', '8256252'], prices=[92, 35, 35, 21, 92], id=771, last_item=2017, second_last_item=5321, third_last_item=2169, country=25, country_platform=32, device_platform=29, sess_step=2, time_diff=69.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=10.0, rg_time_diff=0.5398080067578629, step_log=1.0986122886681098)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2017]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=770, index=770, session_id='7496228483668', timestamp=1541030579, user_id='9VEN8TCAN15Z', step=1, action=2, item_id=2017, platform=0, city=137, device=1, current_filters=nan, impressions=['2891371', '2799226', '9608258', '6942234', '4945218', '8268380', '7703394', '6473470', '9027884', '4623230', '3133112', '7091532', '10692210'], prices=[32, 32, 31, 57, 50, 31, 37, 14, 20, 24, 30, 28, 31], id=770, last_item=5321, second_last_item=2169, third_last_item=2169, country=0, country_platform=0, device_platform=4, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=10.0, time_diff_3=0.0, rg_time_diff=1.6194003174325984, step_log=0.6931471805599453)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 2033]
[5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321]
[5433 5321]
Pandas(Index=780, index=780, session_id='e53dc1121c3e2', timestamp=1541030581, user_id='0E0NQGKMUC3U', step=2, action=2, item_id=2033, platform=2, city=101, device=1, current_filters=nan, impressions=['6062680', '73874', '383106', '57489', '404641', '64152', '58336', '2705832', '2653296'], prices=[126, 58, 102, 100, 107, 126, 135, 149, 62], id=780, last_item=5351, second_last_item=5321, third_last_item=5351, country=15, country_platform=16, device_platform=14, sess_step=2, time_diff=41.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=nan, rg_time_diff=0.4855990292487804, step_log=1.0986122886681098)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 1855]
[5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321]
[5433 5321]
Pandas(Index=800, index=800, session_id='6865e6e314a39', timestamp=1541030583, user_id='A7DA09XVR2NX', step=2, action=2, item_id=1855, platform=5, city=56, device=1, current_filters=nan, impressions=['3539818', '103452', '1519063', '1127559', '8805412', '954519', '1500391', '3247218', '1320590', '1472993', '3424700', '6806398', '8498246', '3539480', '103656', '106481', '10553986', '1006145', '103501', '2478435', '103503', '103554', '8162422', '158721', '103600'], prices=[655, 607, 425, 1251, 228, 516, 268, 763, 425, 467, 629, 295, 183, 94, 401, 317, 219, 241, 255, 166, 636, 423, 1284, 484, 265], id=800, last_item=5352, second_last_item=5321, third_last_item=5321, country=11, country_platform=12, device_platform=7, sess_step=2, time_diff=86.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=10.0, time_diff_3=0.0, rg_time_diff=0.5529544521589733, step_log=1.0986122886681098)
30
34
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054]
[5321, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054, 2054]
[5433 5321 2054]
Pandas(Index=801, index=801, session_id='6a12b4719d714', timestamp=1541030583, user_id='FRFWT67AGU20', step=34, action=2, item_id=2054, platform=6, city=11, device=2, current_filters=nan, impressions=['4841720', '4909160', '3976932', '5970482', '41377', '41328', '41382', '41351', '41223', '41164', '41114', '95143', '41310', '5703598', '41267', '1206973', '41159', '41297', '1502171', '4493482', '3088504', '41305', '6002906', '41383', '41178'], prices=[78, 114, 67, 157, 114, 109, 75, 108, 142, 84, 50, 101, 79, 107, 94, 105, 93, 132, 53, 71, 89, 64, 240, 124, 64], id=801, last_item=1855, second_last_item=5352, third_last_item=2133, country=7, country_platform=7, device_platform=8, sess_step=34, time_diff=7.0, time_diff_diff=7.0, time_diff_diff_diff=7.0, time_diff_2=86.0, time_diff_3=10.0, rg_time_diff=0.12973472153405236, step_log=3.5553480614894135)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 2082]
[5321, 5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321]
[5433 5321]
Pandas(Index=813, index=813, session_id='4df44b36e668f', timestamp=1541030584, user_id='2569GMO3JQXG', step=3, action=2, item_id=2082, platform=10, city=110, device=1, current_filters=nan, impressions=['2308056', '3810272', '477331', '477291', '178846', '2686952', '3140339', '178866', '5154260', '1236969', '6641166', '1456521', '1775701', '3244554', '1767261', '2631242', '1087788', '932589', '884687', '1887969', '1345288', '903533', '1962389', '1383780', '2025993'], prices=[69, 62, 61, 37, 73, 124, 61, 121, 75, 75, 94, 87, 74, 92, 75, 62, 172, 116, 60, 54, 244, 137, 82, 64, 115], id=813, last_item=5356, second_last_item=5356, third_last_item=5321, country=17, country_platform=20, device_platform=20, sess_step=3, time_diff=34.0, time_diff_diff=16.0, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=25.0, rg_time_diff=0.4590000923950162, step_log=1.3862943611198906)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 720, 720, 719]
[720, 720]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 720, 720]
[5433  720]
Pandas(Index=816, index=816, session_id='5db881b372567', timestamp=1541030585, user_id='MEMNU8Y87VYL', step=3, action=2, item_id=719, platform=11, city=67, device=0, current_filters=nan, impressions=['4440394', '105357', '101888', '101901', '2304018', '101895', '796746', '8140220', '101894', '105366', '101899', '101886', '109160', '4498136', '101892', '4386348', '1710457', '101891', '109159', '109155', '368421', '1199874', '1479831', '101882', '2922431'], prices=[95, 109, 113, 102, 115, 101, 95, 76, 115, 106, 105, 92, 74, 98, 109, 103, 104, 69, 122, 92, 106, 56, 106, 72, 92], id=816, last_item=2154, second_last_item=2154, third_last_item=5321, country=18, country_platform=21, device_platform=18, sess_step=3, time_diff=29.0, time_diff_diff=-19.0, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=10.0, rg_time_diff=0.4373215763777875, step_log=1.3862943611198906)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2106]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=819, index=819, session_id='1bcdeae99615c', timestamp=1541030586, user_id='2YMHAXHA1192', step=1, action=2, item_id=2106, platform=5, city=140, device=0, current_filters=nan, impressions=['1133645', '2113136', '2100112', '7113020', '1277267', '7342962', '693401', '2100068', '1025916', '6552118', '346921', '2318158', '521451', '2891982', '2566244', '1025918', '2035085', '818226', '9368946', '1522647', '3543170', '7895184', '1308072', '5830678', '3544232'], prices=[63, 49, 47, 38, 15, 63, 78, 67, 61, 70, 78, 39, 80, 42, 45, 39, 43, 59, 78, 31, 33, 73, 12, 27, 35], id=819, last_item=5321, second_last_item=5321, third_last_item=719, country=11, country_platform=12, device_platform=22, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=10.0, time_diff_3=nan, rg_time_diff=1.6875271805225651, step_log=0.6931471805599453)
30
5
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 2133, 2133, 2133]
[5321, 5321, 2133, 2133]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 2133, 2133]
[5433 5321 2133]
Pandas(Index=831, index=831, session_id='9e7fd351bce43', timestamp=1541030588, user_id='Q5RI88CWFE46', step=5, action=2, item_id=2133, platform=6, city=62, device=0, current_filters=nan, impressions=['44218', '44778', '1033716', '44004', '44364', '43546', '938444', '9129248', '44228', '43619', '43666', '3491696', '44460', '44663', '44692', '6678294', '544511', '1992207', '9943598', '981411', '103387', '2557285', '43941', '43448', '1253061'], prices=[97, 93, 77, 99, 91, 100, 100, 60, 83, 100, 87, 59, 80, 70, 91, 67, 72, 46, 100, 73, 97, 73, 81, 96, 87], id=831, last_item=2308, second_last_item=2407, third_last_item=5321, country=4, country_platform=11, device_platform=12, sess_step=5, time_diff=6.0, time_diff_diff=6.0, time_diff_diff_diff=87.0, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.11533314131982514, step_log=1.791759469228055)
30
34
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154]
[5321, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154, 2154]
[5433 5321 2154]
Pandas(Index=833, index=833, session_id='7171268931987', timestamp=1541030589, user_id='K7QY7ZYP4ZLA', step=34, action=2, item_id=2154, platform=0, city=5, device=1, current_filters=nan, impressions=['519611', '4981186', '1330644', '3374339', '3923682', '503926', '521226', '5450726', '493336', '2717979', '1431411', '2023759', '2258650', '314051', '1945437', '493421', '713866', '2572242', '1115123', '6438270', '1853177', '2328448', '1179940', '1853173', '3197192'], prices=[128, 107, 97, 268, 160, 76, 261, 40, 110, 85, 122, 67, 147, 109, 67, 117, 298, 45, 85, 42, 61, 63, 53, 55, 158], id=833, last_item=5357, second_last_item=2133, third_last_item=2308, country=0, country_platform=0, device_platform=4, sess_step=34, time_diff=5.0, time_diff_diff=5.0, time_diff_diff_diff=15.0, time_diff_2=17.0, time_diff_3=6.0, rg_time_diff=0.10725360904373799, step_log=3.5553480614894135)

96it [00:00, 98.72it/s]

30
4
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1410, 1410, 1410, 1410]
[1410, 1410, 1410]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1410, 1410, 1410]
[5433 1410]
Pandas(Index=834, index=834, session_id='8f81080d71569', timestamp=1541030589, user_id='QR045W70VKZ3', step=4, action=2, item_id=1410, platform=25, city=112, device=1, current_filters=nan, impressions=['1314005', '2809180', '2080036', '6402926', '1103070', '4626938', '4659618', '6787016'], prices=[68, 34, 44, 50, 97, 64, 71, 45], id=834, last_item=2154, second_last_item=5357, third_last_item=2133, country=31, country_platform=49, device_platform=42, sess_step=4, time_diff=28.0, time_diff_diff=25.0, time_diff_diff_diff=28.0, time_diff_2=5.0, time_diff_3=17.0, rg_time_diff=0.4362485327422981, step_log=1.6094379124341003)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2179]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=837, index=837, session_id='bc4ad70ee3986', timestamp=1541030590, user_id='TV0WT25H6U8Z', step=1, action=2, item_id=2179, platform=4, city=143, device=1, current_filters=nan, impressions=['3869998', '6468120', '9130052', '8750722', '1785953', '1747171', '3490392', '6654796', '1462039', '3857428', '3388706', '2550720', '1459147', '2529004', '3840592', '4962758', '8462138', '1834305', '1930219', '2566109', '3385404', '9174704', '4114480', '8979064', '5177400'], prices=[16, 26, 22, 29, 17, 15, 18, 22, 24, 19, 12, 29, 21, 24, 16, 21, 17, 27, 17, 24, 24, 24, 29, 26, 27], id=837, last_item=5321, second_last_item=5357, third_last_item=1410, country=38, country_platform=60, device_platform=6, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=8.0, time_diff_3=0.0, rg_time_diff=1.8751771102336094, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2223]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=841, index=841, session_id='852ccd0b18fbe', timestamp=1541030590, user_id='SGUY5C66QE76', step=1, action=2, item_id=2223, platform=0, city=144, device=1, current_filters=nan, impressions=['1033788', '1886403', '2053770', '2273088', '2053868', '1313710', '7711244', '109329', '502906', '109327', '1883993', '1827941', '2025497', '1993101', '1883957', '1323012', '2020391', '2246384', '5752192', '4761654', '4101214', '8588144', '9464402', '5483368', '7203984'], prices=[89, 111, 105, 64, 71, 86, 54, 151, 224, 105, 90, 56, 27, 102, 83, 105, 147, 68, 68, 63, 36, 79, 66, 52, 36], id=841, last_item=5321, second_last_item=5335, third_last_item=5321, country=0, country_platform=0, device_platform=4, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=10.0, rg_time_diff=1.8212640552240753, step_log=0.6931471805599453)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1497, 1498]
[1497]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1497]
[5433 1497]
Pandas(Index=849, index=849, session_id='293edac5e36f6', timestamp=1541030591, user_id='WY55N2C724K4', step=2, action=2, item_id=1498, platform=11, city=119, device=1, current_filters=nan, impressions=['3116818', '54952', '724986', '4493674', '5203238', '54985', '55140', '102475', '5002590', '54994', '3115936', '54950', '6918406', '2396954', '109072', '1145555', '54897', '55018', '55120', '3750328', '1180062', '54796', '109075', '6846692', '55079'], prices=[95, 125, 124, 350, 187, 106, 168, 103, 64, 101, 93, 56, 108, 106, 87, 81, 107, 109, 89, 155, 72, 89, 69, 87, 69], id=849, last_item=1725, second_last_item=5321, third_last_item=5321, country=18, country_platform=21, device_platform=21, sess_step=2, time_diff=33.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=26.0, time_diff_3=nan, rg_time_diff=0.4513644902722699, step_log=1.0986122886681098)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2285]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=883, index=883, session_id='4d6ee7f795b03', timestamp=1541030592, user_id='8LZTRBQXTSRW', step=1, action=2, item_id=2285, platform=0, city=27, device=1, current_filters=nan, impressions=['6080002', '2026235', '4813956', '4282900', '6819022', '2744422', '2517706', '6333948', '8007030', '9504252', '8576928', '9439068', '9447812', '6034534', '9609064', '9067948', '9451192', '8407634', '11143840', '10203002', '7979934', '9326422', '8381954', '9637790', '9600028'], prices=[96, 109, 66, 52, 41, 78, 59, 111, 136, 218, 237, 392, 88, 119, 64, 746, 475, 997, 105, 89, 137, 107, 104, 139, 171], id=883, last_item=5321, second_last_item=5350, third_last_item=2169, country=0, country_platform=0, device_platform=4, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=1.846880266867961, step_log=0.6931471805599453)
30
8
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2277, 2277, 470, 470, 470, 470, 470, 470]
[2277, 2277, 470, 470, 470, 470, 470]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2277, 2277, 470, 470, 470, 470, 470]
[5433 2277  470]
Pandas(Index=876, index=876, session_id='c46caf82e4cfc', timestamp=1541030592, user_id='251AFZASCPNY', step=8, action=2, item_id=470, platform=3, city=22, device=0, current_filters=nan, impressions=['42497', '948643', '100302', '5653536', '740596', '42952', '18230', '42894', '34337', '1346370', '42363', '42620', '34343', '34346', '995511', '42450', '43160', '34348', '34342', '42334', '42446', '899539', '43174', '43153', '42402'], prices=[102, 113, 148, 81, 50, 95, 217, 285, 125, 994, 127, 87, 93, 120, 163, 282, 329, 192, 93, 95, 64, 90, 102, 168, 122], id=876, last_item=2252, second_last_item=1549, third_last_item=1549, country=8, country_platform=8, device_platform=11, sess_step=8, time_diff=27.0, time_diff_diff=13.0, time_diff_diff_diff=25.0, time_diff_2=14.0, time_diff_3=0.0, rg_time_diff=0.42983119708454376, step_log=2.1972245773362196)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2229]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=857, index=857, session_id='e3d0f71ac9614', timestamp=1541030592, user_id='T9I9K312OIXK', step=1, action=2, item_id=2229, platform=17, city=116, device=1, current_filters=nan, impressions=['149766', '11914', '106221', '149848', '3142642', '149806', '2479332', '32793', '50648', '32725', '48892', '11925', '48504', '12752', '49329', '11898', '48512', '12289', '12233', '1180152', '2196326', '17905', '12231', '149793', '1193990'], prices=[186, 120, 55, 179, 316, 435, 125, 147, 122, 234, 220, 161, 169, 162, 278, 99, 161, 188, 99, 187, 199, 147, 100, 221, 320], id=857, last_item=5321, second_last_item=5355, third_last_item=5355, country=3, country_platform=62, device_platform=30, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=2.0, time_diff_3=0.0, rg_time_diff=1.7561641449779484, step_log=0.6931471805599453)
30
5
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 5321, 2252]
[5321, 5321, 5321, 5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 5321]
[5433 5321]
Pandas(Index=875, index=875, session_id='4ddfc5dc24547', timestamp=1541030592, user_id='B4GOKEHVZTGQ', step=5, action=2, item_id=2252, platform=5, city=135, device=0, current_filters='Best Value', impressions=['3440216', '6718740', '3888308', '2347920', '4231308', '2265642', '3544876', '3155074', '3544578', '2519964', '2128086', '9235376', '2128084', '5192692', '2504268', '4053114', '1121275', '3544970', '8772226', '2012941', '8976046', '9507826', '2013007', '2012989', '2012927'], prices=[237, 137, 164, 207, 78, 94, 101, 117, 117, 124, 337, 110, 203, 142, 142, 150, 152, 228, 54, 193, 73, 70, 388, 301, 203], id=875, last_item=1549, second_last_item=1549, third_last_item=1549, country=11, country_platform=12, device_platform=22, sess_step=5, time_diff=14.0, time_diff_diff=14.0, time_diff_diff_diff=15.0, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.32841990387213327, step_log=1.791759469228055)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2308, 2308]
[2308]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2308]
[5433 2308]
Pandas(Index=891, index=891, session_id='25271297b9c2e', timestamp=1541030593, user_id='X23T5M0XY5U1', step=2, action=2, item_id=2308, platform=11, city=142, device=1, current_filters=nan, impressions=['2874140', '105492', '4511628', '3937440', '2671274', '3938964', '2897734', '2815618', '6644584', '6479266'], prices=[59, 74, 49, 41, 108, 41, 85, 80, 69, 28], id=891, last_item=5359, second_last_item=5321, third_last_item=5360, country=18, country_platform=21, device_platform=21, sess_step=2, time_diff=5.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.1090478138256389, step_log=1.0986122886681098)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 2318]
[5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321]
[5433 5321]
Pandas(Index=892, index=892, session_id='d7878fb98f1f7', timestamp=1541030593, user_id='TASWHUFQJQTU', step=2, action=2, item_id=2318, platform=5, city=87, device=0, current_filters=nan, impressions=['5213138', '1714243', '2022593', '3890640', '1159655', '2022421', '7493770', '2022791', '2022539', '3544458', '5419212', '1150863', '1121944', '4705926', '5410758', '3544930', '496046', '1107466', '3544982', '3544688'], prices=[102, 78, 312, 77, 855, 340, 206, 661, 676, 135, 77, 237, 110, 110, 254, 462, 294, 313, 62, 169], id=892, last_item=2308, second_last_item=5321, third_last_item=5360, country=11, country_platform=12, device_platform=22, sess_step=2, time_diff=62.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=5.0, time_diff_3=0.0, rg_time_diff=0.5350736036672256, step_log=1.0986122886681098)

106it [00:01, 98.30it/s]

30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 2351]
[5321, 5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321]
[5433 5321]
Pandas(Index=901, index=901, session_id='68e8bf6644593', timestamp=1541030594, user_id='221QBQ570YW4', step=3, action=2, item_id=2351, platform=3, city=111, device=0, current_filters=nan, impressions=['1954371', '67865', '66179', '57485', '881845', '687611', '426596', '10259770', '6488328', '441426', '5479518', '2635335', '71310', '376996', '893913', '2353934', '60242', '7925550', '71015', '67537', '60758', '3844108', '9270038', '1109080', '77050'], prices=[163, 264, 264, 220, 281, 135, 177, 211, 415, 211, 180, 102, 273, 49, 218, 332, 132, 203, 141, 62, 75, 840, 135, 141, 211], id=901, last_item=5356, second_last_item=5356, third_last_item=5321, country=15, country_platform=48, device_platform=11, sess_step=3, time_diff=40.0, time_diff_diff=38.0, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.48000190195977177, step_log=1.3862943611198906)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2390]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=907, index=907, session_id='05333e456364a', timestamp=1541030594, user_id='V4RMTQZXVREX', step=1, action=2, item_id=2390, platform=0, city=145, device=1, current_filters=nan, impressions=['2681146', '2681784', '2777078', '3165450', '9673054', '2673706', '2604532', '7134460', '7936484', '2505774', '8938478', '2510298', '2681330', '1776199', '2672894', '8017376', '3871390', '1253389', '8414512', '8199126', '9241752', '9432568', '9421110', '7352806'], prices=[39, 41, 47, 48, 106, 45, 26, 34, 66, 50, 42, 45, 68, 38, 45, 59, 45, 28, 57, 47, 57, 47, 90, 158], id=907, last_item=5321, second_last_item=5356, third_last_item=5356, country=0, country_platform=0, device_platform=4, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=1.2998033124900794, step_log=0.6931471805599453)
30
4
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 118, 118]
[5321, 5321, 118]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 118]
[5433 5321  118]
Pandas(Index=910, index=910, session_id='8544fbda6bc3c', timestamp=1541030595, user_id='SL6SPK7RIL1C', step=4, action=2, item_id=118, platform=5, city=16, device=1, current_filters=nan, impressions=['8162422', '1506339', '818501', '7213390', '4849214', '103640', '4774596', '917345', '103495', '1031940', '1148728', '1953975', '10141376', '3978950', '3060180', '7743258', '4774542', '661646', '10051400', '5619840', '8165232', '1816151', '6806086', '5816570', '1250199'], prices=[63, 59, 94, 70, 116, 110, 90, 70, 86, 86, 63, 55, 80, 93, 36, 66, 70, 73, 186, 78, 76, 70, 90, 63, 61], id=910, last_item=5361, second_last_item=5361, third_last_item=2390, country=11, country_platform=12, device_platform=7, sess_step=4, time_diff=1.0, time_diff_diff=-17.0, time_diff_diff_diff=-3.0, time_diff_2=0.0, time_diff_3=nan, rg_time_diff=0.0146311032407134, step_log=1.6094379124341003)
30
4
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 259, 259, 260, 261]
[259, 259, 260]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 259, 259, 260]
[5433  259  260]
Pandas(Index=911, index=911, session_id='21befe700aa7c', timestamp=1541030596, user_id='GPIQ7XR9K6MJ', step=4, action=2, item_id=261, platform=2, city=34, device=0, current_filters=nan, impressions=['67646', '1017983', '138068', '395501', '138007', '138063', '619681', '843491', '60787', '844436', '69317', '2223930', '7904994', '1198670', '2245752', '138067', '1017999', '66280', '138064', '69376', '1139814', '4973242', '1017981', '1198376', '961795'], prices=[71, 71, 44, 124, 79, 60, 56, 62, 48, 65, 68, 87, 97, 49, 88, 77, 57, 88, 52, 115, 149, 80, 78, 96, 88], id=911, last_item=118, second_last_item=5361, third_last_item=5361, country=15, country_platform=16, device_platform=3, sess_step=4, time_diff=4.0, time_diff_diff=-124.0, time_diff_diff_diff=-251.0, time_diff_2=1.0, time_diff_3=0.0, rg_time_diff=0.0822017737021789, step_log=1.6094379124341003)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2407, 2407]
[2407]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2407]
[5433 2407]
Pandas(Index=913, index=913, session_id='dc126d0be613c', timestamp=1541030596, user_id='7YT28O84QBCC', step=2, action=2, item_id=2407, platform=12, city=141, device=1, current_filters=nan, impressions=['9782', '5787596', '116462', '10106016', '7815350', '9181882', '9783', '6351648', '8994590', '9781'], prices=[143, 1175, 1468, 1613, 512, 79, 398, 4745, 68, 759], id=913, last_item=5321, second_last_item=5321, third_last_item=118, country=37, country_platform=59, device_platform=44, sess_step=2, time_diff=8.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=31.0, time_diff_3=4.0, rg_time_diff=0.14147548745842423, step_log=1.0986122886681098)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 2421]
[5321, 5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321]
[5433 5321]
Pandas(Index=920, index=920, session_id='e7394f95b3ee6', timestamp=1541030598, user_id='IHFK502ILRWJ', step=3, action=2, item_id=2421, platform=21, city=96, device=1, current_filters='Hotel|Resort|Focus on Distance', impressions=['933159', '1960817', '42137', '42313', '42085', '42130', '42132', '42294', '42089', '42135', '921237', '1613235', '42100', '2720517', '2626657', '42276', '4345706', '42128', '42262', '42127', '42161', '15460', '8335912', '42302', '100644'], prices=[106, 314, 282, 116, 160, 122, 319, 193, 283, 271, 96, 98, 130, 268, 159, 110, 82, 180, 168, 270, 64, 167, 121, 229, 93], id=920, last_item=5321, second_last_item=5363, third_last_item=5321, country=29, country_platform=41, device_platform=36, sess_step=3, time_diff=61.0, time_diff_diff=61.0, time_diff_diff_diff=nan, time_diff_2=26.0, time_diff_3=0.0, rg_time_diff=0.5303630668670516, step_log=1.3862943611198906)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 2442]
[5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321]
[5433 5321]
Pandas(Index=961, index=961, session_id='67f3d86fd50e1', timestamp=1541030600, user_id='F00Y8YPFBW30', step=2, action=2, item_id=2442, platform=6, city=104, device=2, current_filters=nan, impressions=['4472556', '44880', '101057', '44118', '43377', '92300', '87922', '3134934', '44902', '3856952', '1832363', '92084', '92302'], prices=[456, 330, 272, 276, 245, 307, 168, 166, 469, 148, 245, 218, 260], id=961, last_item=5365, second_last_item=5321, third_last_item=5365, country=4, country_platform=11, device_platform=8, sess_step=2, time_diff=53.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=nan, rg_time_diff=0.5210118173322499, step_log=1.0986122886681098)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2455]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=963, index=963, session_id='06e75db3a9275', timestamp=1541030601, user_id='SQ35WMWF5ZD5', step=1, action=2, item_id=2455, platform=0, city=47, device=1, current_filters=nan, impressions=['1649739', '478616', '478256', '1457493', '2024817', '2676984', '3378782', '6638614', '2729222', '2571721', '3148436', '2782226', '4920810', '1411164', '4331280', '4583216', '104507', '1330207', '2121018', '861491', '4608960', '1862179', '1993165', '2648456', '977412'], prices=[69, 75, 68, 23, 28, 21, 19, 14, 20, 16, 19, 16, 13, 64, 28, 27, 36, 106, 25, 81, 23, 88, 31, 35, 43], id=963, last_item=5321, second_last_item=2442, third_last_item=5365, country=0, country_platform=0, device_platform=4, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=10.0, time_diff_3=53.0, rg_time_diff=1.3680429805277372, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1736]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=979, index=979, session_id='164fd17e70706', timestamp=1541030602, user_id='BBSFIXHTW5FF', step=1, action=2, item_id=1736, platform=0, city=127, device=1, current_filters=nan, impressions=['834526', '1321131', '2326194', '5977428', '7773394', '9774742', '104905', '4501964', '147209', '109324', '3247834', '2085906', '9842734', '903569', '1343166', '3523314', '8256346', '1239512', '962275', '2053269', '2179366', '478081', '2536810', '478086', '1852611'], prices=[215, 118, 107, 75, 135, 53, 45, 114, 49, 102, 41, 46, 50, 39, 114, 43, 60, 38, 56, 71, 37, 43, 27, 37, 37], id=979, last_item=5321, second_last_item=1725, third_last_item=2169, country=0, country_platform=0, device_platform=4, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=1.3738508018306184, step_log=0.6931471805599453)

115it [00:01, 100.18it/s]
0it [00:00, ?it/s]

30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2508]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=6, user_id='ZZLBJK50TFPS', timestamp=1541453209, session_id='5c2ef481c5164', step=1, action=2, item_id=2508, platform=29, city=116, device=1, current_filters=nan, impressions=['14610', '12076', '12245', '12299', '49977', '12075', '49261', '1201264', '32725', '2009673', '99968', '82322', '2267432', '11914', '49533', '49607', '48481', '2179674', '48405', '50648', '918913', '1061826', '5180114', '6452196', '4452280'], prices=[1916, 476, 830, 2086, 546, 682, 731, 736, 1656, 696, 926, 856, 488, 688, 1415, 670, 958, 625, 688, 625, 373, 504, 596, 462, 792], id=1006, last_item=5321, second_last_item=2617, third_last_item=3314, step_rank=1.0, country=3, country_platform=67, device_platform=51, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=nan, rg_time_diff=1.437768704264794, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=9, user_id='U9MAV55LZMOR', timestamp=1541453209, session_id='0dd5544c71728', step=1, action=2, item_id=5368, platform=2, city=158, device=1, current_filters=nan, impressions=['366186', '56563', '3741160', '63568', '3478738', '3137008', '67846', '56346', '77063', '77251', '59179', '67848', '111276', '488051', '63586', '1499781', '74152', '899821', '5952044', '1258360', '71467', '74519', '3399692', '222936', '69547'], prices=[69, 68, 46, 39, 69, 47, 48, 52, 74, 70, 44, 34, 57, 69, 37, 70, 88, 39, 38, 57, 41, 54, 69, 87, 37], id=1009, last_item=5321, second_last_item=5321, third_last_item=2508, step_rank=1.0, country=15, country_platform=16, device_platform=14, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=1.4173559963781919, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2541]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=11, user_id='Y56NLUTDYB8Q', timestamp=1541453210, session_id='b287747dac524', step=1, action=2, item_id=2541, platform=8, city=159, device=0, current_filters=nan, impressions=['880913', '3218556', '664366', '1535885', '2552990', '46985', '46686', '2627682', '2195678', '47012', '2396136', '18422', '46845', '46278', '4207122', '1321090', '18460', '46305', '1334735', '46694', '47115', '2529342', '46850', '18425', '970119'], prices=[185, 321, 165, 140, 83, 130, 85, 86, 153, 83, 65, 143, 116, 121, 98, 274, 157, 170, 122, 147, 209, 73, 198, 111, 132], id=1011, last_item=5321, second_last_item=5368, third_last_item=5367, step_rank=1.0, country=10, country_platform=10, device_platform=16, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=nan, rg_time_diff=1.4108068583024322, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2568]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=13, user_id='YBUFQ291BIGI', timestamp=1541453211, session_id='78fc8ef807c57', step=1, action=2, item_id=2568, platform=2, city=116, device=2, current_filters=nan, impressions=['4414496', '85891', '4340866', '2786013', '1754309', '3145768', '135550', '4456088', '100033', '100134', '49381', '85876', '99807', '49330', '130737', '8140550', '2901004', '15583', '50700', '3133692', '2671006', '85874', '85856', '926579', '594921'], prices=[162, 89, 81, 53, 69, 113, 141, 117, 57, 235, 100, 126, 49, 131, 47, 166, 47, 135, 177, 114, 86, 161, 152, 63, 100], id=1013, last_item=5321, second_last_item=2541, third_last_item=5367, step_rank=1.0, country=3, country_platform=3, device_platform=2, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=1.398060330352197, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2593]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=14, user_id='67J2PP0IG8Y6', timestamp=1541453211, session_id='0ca01ab6fb354', step=1, action=2, item_id=2593, platform=0, city=160, device=0, current_filters=nan, impressions=['7567880', '5972382', '104513', '152560', '2454130', '104710', '2567472', '104938', '153723', '1425051', '4970148', '1589381', '3222236', '522036', '7157462', '104770', '478461', '104514', '6046752', '323901', '3186913', '104651', '2627267', '104712', '104806'], prices=[112, 59, 110, 56, 37, 61, 56, 67, 50, 42, 20, 43, 51, 46, 79, 50, 52, 42, 37, 55, 54, 137, 83, 61, 125], id=1014, last_item=5321, second_last_item=5321, third_last_item=2541, step_rank=1.0, country=0, country_platform=0, device_platform=0, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=1.3918537274119125, step_log=0.6931471805599453)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2617, 2617, 5368]
[2617, 2617]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2617, 2617]
[5433 2617]
Pandas(Index=15, user_id='VXIWZ3NF0WHF', timestamp=1541453212, session_id='be1b5623b2e12', step=3, action=2, item_id=5368, platform=30, city=155, device=2, current_filters=nan, impressions=['4412788', '53876', '3147220', '929429', '148127', '53835', '1753149', '3133488', '14773', '8992496', '53834', '1152231', '53859', '53924', '53969', '1321404', '53939', '53915', '53983', '92807', '53856', '1771279', '5815686', '7142064', '53937'], prices=[122, 144, 195, 100, 92, 117, 72, 107, 268, 166, 171, 657, 147, 148, 181, 187, 153, 150, 167, 255, 147, 254, 121, 132, 152], id=1015, last_item=2593, second_last_item=2568, third_last_item=5321, step_rank=3.0, country=40, country_platform=66, device_platform=50, sess_step=3, time_diff=4.0, time_diff_diff=4.0, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.08934754612943155, step_log=1.3862943611198906)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=16, user_id='2VZWKE7NWP8C', timestamp=1541453213, session_id='7daf68934bfef', step=1, action=2, item_id=5368, platform=2, city=161, device=1, current_filters=nan, impressions=['57189', '404846', '164156', '111309', '148435', '77409', '10322864', '855546', '63218', '9673378', '68995', '441916', '68989', '63549', '10694174', '61728', '1314701', '10087808', '60806', '75002', '69019', '69016', '66297', '149908', '75001'], prices=[115, 166, 115, 97, 111, 87, 200, 101, 114, 160, 98, 97, 102, 112, 44, 61, 133, 178, 111, 106, 104, 134, 105, 42, 190], id=1016, last_item=5321, second_last_item=2593, third_last_item=2568, step_rank=1.0, country=15, country_platform=16, device_platform=14, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=4.0, time_diff_3=nan, rg_time_diff=1.3857525414731604, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=20, user_id='YAD78TVUR09A', timestamp=1541453216, session_id='1d988e8ec0a64', step=1, action=2, item_id=5368, platform=32, city=163, device=1, current_filters=nan, impressions=['15964', '7434', '7279', '94114', '95048', '100915', '6466618', '95350', '1373416', '2190096', '7319', '7287', '7160', '85112', '7986954', '94088', '7154', '7433', '438796', '110739', '3387288', '114528', '11081092', '122967', '7232262'], prices=[128, 196, 166, 224, 101, 306, 101, 143, 623, 362, 252, 277, 242, 135, 319, 106, 179, 145, 56, 81, 175, 128, 631, 119, 58], id=1020, last_item=5321, second_last_item=5321, third_last_item=5321, step_rank=1.0, country=22, country_platform=70, device_platform=53, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.8271039557362581, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2691]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=21, user_id='5A92LLOFQJ76', timestamp=1541453216, session_id='83e52bb1d06d4', step=1, action=2, item_id=2691, platform=8, city=164, device=0, current_filters=nan, impressions=['966805', '454766', '3831028', '1309932', '47148', '47972', '1328473', '1362542', '343046', '2456656', '845221', '401451', '1569801', '2009143', '1079830', '632331', '2473446', '632326', '1244521', '7779668', '1328475', '1929663', '7799826', '1327050', '1138119'], prices=[79, 54, 53, 37, 58, 67, 58, 31, 55, 50, 84, 94, 106, 44, 55, 81, 82, 59, 89, 149, 48, 43, 46, 87, 85], id=1021, last_item=5321, second_last_item=5321, third_last_item=5321, step_rank=1.0, country=10, country_platform=10, device_platform=16, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.8288638877245026, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2713]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=22, user_id='HCM1QOOF81O2', timestamp=1541453217, session_id='48d7727d4d55b', step=1, action=2, item_id=2713, platform=9, city=165, device=2, current_filters=nan, impressions=['86986', '40395', '99033', '32952', '82013', '82016', '99039', '82014', '83078', '99042', '99035', '99038', '39999', '80921', '86909', '40332', '86917', '86970', '1962917', '32936', '86968', '3132994', '91661', '809511', '7787634'], prices=[57, 76, 94, 60, 75, 86, 68, 86, 86, 91, 91, 78, 63, 58, 46, 77, 69, 166, 214, 66, 63, 51, 44, 240, 118], id=1022, last_item=5321, second_last_item=5368, third_last_item=5321, step_rank=1.0, country=22, country_platform=28, device_platform=54, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.8306289693290567, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=23, user_id='6EC3MQPWB5OA', timestamp=1541453217, session_id='cfa803f10d6d9', step=1, action=2, item_id=5368, platform=15, city=166, device=1, current_filters=nan, impressions=['109994', '363881', '436766', '109997', '936331', '19817', '46029', '1413032', '46184', '46161', '46094', '448196', '124809', '344741', '32655', '943701', '468671', '19815', '1474435', '46101', '1277956', '46045', '4415256', '85706', '1652957'], prices=[99, 89, 149, 114, 99, 137, 84, 98, 105, 108, 125, 115, 310, 189, 89, 89, 87, 129, 120, 109, 85, 99, 75, 99, 90], id=1023, last_item=5321, second_last_item=2691, third_last_item=5368, step_rank=1.0, country=23, country_platform=29, device_platform=55, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.8323992418373309, step_log=0.6931471805599453)

11it [00:00, 106.05it/s]

30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=24, user_id='PC3K486NASTS', timestamp=1541453217, session_id='26ae80da84843', step=1, action=2, item_id=5368, platform=10, city=167, device=0, current_filters=nan, impressions=['2813583', '8927002', '2812010', '4274890', '4274898', '4284726', '9358826'], prices=[36, 53, 57, 61, 61, 61, 88], id=1024, last_item=5321, second_last_item=2713, third_last_item=2691, step_rank=1.0, country=17, country_platform=20, device_platform=17, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.834174747032414, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=39, user_id='PE3W0TFH468N', timestamp=1541453218, session_id='b082600e5f653', step=1, action=2, item_id=5368, platform=0, city=169, device=1, current_filters=nan, impressions=['4120638', '2028485', '5837110', '9819932', '2781912', '2036461', '3243870', '2250256', '2567054', '3200360', '4801680', '4558890', '1122656', '2024565', '2035485', '4915424', '5831766', '6511090', '6531758', '9242098', '7705656', '8982576'], prices=[90, 48, 225, 74, 104, 63, 56, 56, 66, 74, 38, 31, 25, 36, 34, 34, 78, 49, 35, 47, 34, 34], id=1039, last_item=5321, second_last_item=3314, third_last_item=3314, step_rank=1.0, country=0, country_platform=0, device_platform=4, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.8522271601870313, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=51, user_id='J912TWKDU6QM', timestamp=1541453221, session_id='79424b3732cbc', step=1, action=2, item_id=5368, platform=6, city=174, device=1, current_filters=nan, impressions=['3166358', '1285724', '103379', '347426', '7107198', '2342180', '103421', '5467202', '43594', '1449201', '5861070', '2306446', '103369', '10037782', '44355', '44922', '6847198', '9634484', '2327084', '43770', '2643800', '44493', '44548', '88672', '44372'], prices=[43, 69, 73, 77, 114, 80, 68, 80, 346, 126, 108, 47, 77, 66, 140, 86, 161, 143, 59, 147, 57, 86, 138, 75, 168], id=1051, last_item=5321, second_last_item=5321, third_last_item=5321, step_rank=1.0, country=4, country_platform=11, device_platform=31, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.8708528188330641, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=52, user_id='I91O2PDHF2F5', timestamp=1541453222, session_id='84225439e3bbf', step=1, action=2, item_id=5368, platform=3, city=175, device=0, current_filters=nan, impressions=['4868870', '6538232', '1797067', '4985074', '42880', '1257131', '34363', '42389', '1848773', '893651', '4681614', '2218036', '42929', '489071', '42886', '5452918', '6321852', '349166', '1265777', '399556', '4179190', '2793731', '1713647', '1237890', '42700'], prices=[59, 80, 74, 68, 64, 81, 67, 53, 50, 93, 72, 42, 50, 38, 54, 55, 113, 33, 28, 49, 45, 56, 53, 55, 34], id=1052, last_item=5321, second_last_item=5321, third_last_item=5321, step_rank=1.0, country=8, country_platform=8, device_platform=11, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.8670794559716056, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2835]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=57, user_id='GHZDHFU5IHXB', timestamp=1541453222, session_id='396c91e2eb56a', step=1, action=2, item_id=2835, platform=8, city=159, device=2, current_filters=nan, impressions=['3755574', '12708', '115868', '921023', '18454', '884185', '12712', '12643', '12650', '48073', '1715765', '2627686', '12646', '2341022', '12645', '630196', '46305', '1504047', '1710667', '46800', '18439', '925457', '12647', '48072', '46812'], prices=[354, 260, 236, 147, 176, 256, 411, 315, 242, 266, 338, 148, 223, 123, 158, 153, 170, 141, 249, 125, 217, 118, 219, 244, 163], id=1057, last_item=5321, second_last_item=5321, third_last_item=5321, step_rank=1.0, country=10, country_platform=10, device_platform=37, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=0.0, rg_time_diff=0.8614652756353699, step_log=0.6931471805599453)
30
4
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 2856, 2857]
[5321, 5321, 5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321]
[5433 5321]
Pandas(Index=59, user_id='BOLB6OCXFQLW', timestamp=1541453223, session_id='d00d2e9066331', step=4, action=2, item_id=2856, platform=30, city=155, device=2, current_filters='Best Value', impressions=['1106804', '1753149', '1825401', '53834', '8992496', '1204106', '7129916', '3133488', '53833', '53922', '53969', '53876', '1321404', '53846', '53855', '93616', '53929', '53954', '93625', '53856', '152781', '6207346', '1273207', '148126', '53955'], prices=[127, 174, 171, 314, 326, 190, 192, 225, 261, 229, 372, 388, 282, 218, 301, 119, 232, 384, 232, 249, 230, 167, 249, 301, 341], id=1059, last_item=5321, second_last_item=2835, third_last_item=5321, step_rank=4.0, country=40, country_platform=66, device_platform=50, sess_step=4, time_diff=3.0, time_diff_diff=3.0, time_diff_diff_diff=13.0, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.0723898757051198, step_log=1.6094379124341003)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=64, user_id='X61L8I2E2U32', timestamp=1541453224, session_id='a8206f4ba4497', step=1, action=2, item_id=5368, platform=8, city=181, device=2, current_filters=nan, impressions=['138309', '46612', '1153462', '126363', '152836', '148968', '18747', '18755', '1363523', '18752', '46553', '18750', '47142', '938576', '48001', '47808', '6003238', '148972', '48056', '18756', '46601', '46473', '47823', '627441', '152838'], prices=[136, 160, 115, 174, 56, 130, 163, 174, 102, 176, 182, 165, 137, 102, 126, 166, 283, 149, 154, 125, 136, 133, 67, 136, 102], id=1064, last_item=5321, second_last_item=5371, third_last_item=5372, step_rank=1.0, country=10, country_platform=10, device_platform=37, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=0.0, rg_time_diff=0.7684622752416571, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=65, user_id='E33A2Y079ZXB', timestamp=1541453224, session_id='b46d2a3cb9e6e', step=1, action=2, item_id=2, platform=0, city=4, device=0, current_filters=nan, impressions=['8280296', '507861', '1431081', '5849628', '1944129', '655716', '2001005', '6789900', '9857656', '104719', '8184784', '3810222', '2516286', '2771364', '1352538', '6130544', '7880000', '2330448', '4773508', '2828162', '4574394', '8738256', '2874560', '1776047', '4015530'], prices=[149, 162, 142, 163, 121, 212, 108, 75, 192, 200, 96, 85, 127, 92, 133, 119, 65, 121, 246, 47, 148, 180, 81, 137, 186], id=1065, last_item=5321, second_last_item=5321, third_last_item=5371, step_rank=1.0, country=0, country_platform=0, device_platform=0, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.7700646457793108, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=66, user_id='3KD83JN2J6L6', timestamp=1541453224, session_id='f37693acacc5e', step=1, action=2, item_id=5368, platform=33, city=182, device=1, current_filters=nan, impressions=['6236736', '6228584', '4560382', '95688', '3085957', '6865146', '9076112', '2898774', '2439588', '1346414', '37141', '38298', '37121', '80927', '37118', '110860', '80887', '37132', '112477', '1491939', '7012', '37148', '37117', '37135', '152989'], prices=[98, 77, 116, 55, 189, 109, 71, 71, 104, 58, 95, 85, 92, 97, 153, 91, 65, 100, 40, 71, 48, 95, 196, 50, 39], id=1066, last_item=5321, second_last_item=5368, third_last_item=5321, step_rank=1.0, country=22, country_platform=80, device_platform=62, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.7716709805298273, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=67, user_id='68JA8MUJCWD2', timestamp=1541453225, session_id='45a6c59c569d0', step=1, action=2, item_id=5368, platform=3, city=183, device=2, current_filters=nan, impressions=['163445', '991823', '2774868', '197266', '4050224', '41228', '225661', '1107306', '197261', '1711453', '8335200', '8449518', '5974424', '5517152', '5877784'], prices=[238, 128, 67, 52, 76, 114, 101, 132, 95, 93, 208, 207, 82, 82, 177], id=1067, last_item=5321, second_last_item=2, third_last_item=5368, step_rank=1.0, country=7, country_platform=81, device_platform=63, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.773281307487483, step_log=0.6931471805599453)

21it [00:00, 103.60it/s]

30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 2956]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=68, user_id='L99256TEN5QM', timestamp=1541453225, session_id='6072408e453cc', step=1, action=2, item_id=2956, platform=2, city=184, device=1, current_filters=nan, impressions=['9903484', '60147', '74830', '73604', '60682', '1022827', '60819', '4440068', '71266', '57875', '813306', '65387', '73605', '64901', '899865', '77021', '61018', '62733', '831461', '67305', '78498', '153152', '64337', '58131', '3147142'], prices=[158, 251, 175, 162, 102, 281, 132, 135, 161, 288, 221, 154, 196, 218, 235, 142, 153, 259, 189, 207, 110, 135, 117, 281, 591], id=1068, last_item=5321, second_last_item=5368, third_last_item=2, step_rank=1.0, country=15, country_platform=16, device_platform=14, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.7748956549387181, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=70, user_id='HJLJJ16SV70Z', timestamp=1541453225, session_id='075170e7b89c3', step=1, action=2, item_id=5368, platform=2, city=185, device=1, current_filters=nan, impressions=['147368', '6810824', '5812954', '3578004', '7333050', '4475984', '1960797', '98257', '9882016', '48311', '1364494', '107863', '48251', '6274114', '111614', '5742058', '5100088', '48223', '15905', '3785178', '48224', '107525', '81408', '342036', '7542'], prices=[90, 94, 76, 64, 61, 95, 129, 52, 61, 48, 33, 34, 99, 88, 57, 113, 97, 83, 251, 218, 63, 97, 156, 44, 92], id=1070, last_item=5321, second_last_item=2956, third_last_item=5368, step_rank=1.0, country=33, country_platform=82, device_platform=14, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.7797631075887609, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=75, user_id='YBHJD0V7VY2Y', timestamp=1541453226, session_id='4e9a5c3da9dc8', step=1, action=2, item_id=5368, platform=15, city=189, device=1, current_filters=nan, impressions=['46087', '1022993', '6001842', '46148', '10365900', '46061', '5041870', '7286174', '436756', '344806', '46041', '1361340', '640641', '4670074', '1404642', '344791', '11018394', '4528296', '4054474'], prices=[185, 160, 145, 263, 600, 94, 374, 264, 294, 102, 86, 119, 173, 124, 120, 281, 85, 193, 120], id=1075, last_item=5321, second_last_item=5321, third_last_item=5321, step_rank=1.0, country=23, country_platform=29, device_platform=55, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.791266697077588, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3037, 3034]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=78, user_id='06IDQEUU0AF2', timestamp=1541453227, session_id='8164bbaddb575', step=1, action=2, item_id=3037, platform=0, city=170, device=1, current_filters=nan, impressions=['4744374', '1658719', '3051038', '2277390', '745041', '477981', '2677895', '2344168', '1962949', '2352972', '1668435', '2828912', '1269129', '4418618', '3112332', '1412050', '2383508', '4084638', '2794992', '2503210', '2643962', '6475398', '3854914', '2248594', '953311'], prices=[21, 26, 21, 20, 59, 24, 33, 36, 58, 29, 31, 28, 49, 45, 42, 44, 31, 36, 35, 27, 65, 59, 68, 41, 166], id=1078, last_item=5321, second_last_item=5321, third_last_item=5368, step_rank=1.0, country=0, country_platform=0, device_platform=4, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.8183801286906485, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=90, user_id='5RIYPNEA1T0Z', timestamp=1541453228, session_id='0d8a58790e8ec', step=1, action=2, item_id=5368, platform=18, city=194, device=0, current_filters=nan, impressions=['1986215', '1858971', '4968904', '7203696', '1987345', '7109798', '1987077'], prices=[95, 53, 74, 58, 60, 87, 318], id=1090, last_item=5321, second_last_item=5321, third_last_item=5321, step_rank=1.0, country=40, country_platform=87, device_platform=33, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=0.0, rg_time_diff=0.8080732434475276, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3056]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=101, user_id='P505A2N8WN7B', timestamp=1541453229, session_id='5cb6de3e02c42', step=1, action=2, item_id=3056, platform=22, city=197, device=1, current_filters=nan, impressions=['878996', '97422', '114709', '116532', '119299', '119818', '116367', '3219306', '1773705', '112975', '1042494', '818021', '97429', '1167152', '1205040', '97476', '2151898', '97424', '3831058', '3178696', '881839', '852606', '115176', '1205044', '944807'], prices=[140, 297, 87, 227, 169, 128, 108, 201, 263, 318, 100, 228, 147, 128, 157, 109, 166, 242, 123, 112, 205, 167, 79, 160, 107], id=1101, last_item=5321, second_last_item=5321, third_last_item=5321, step_rank=1.0, country=46, country_platform=88, device_platform=67, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=nan, rg_time_diff=0.7979352439505533, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3083, 3082]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=106, user_id='2RXCLWDXCSZV', timestamp=1541453230, session_id='74bd7f1ce82eb', step=1, action=2, item_id=3083, platform=12, city=198, device=1, current_filters=nan, impressions=['82971', '1640221', '643136', '11182328', '6665012'], prices=[624, 295, 243, 475, 62], id=1106, last_item=5321, second_last_item=5367, third_last_item=5367, step_rank=1.0, country=32, country_platform=51, device_platform=44, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.7962614655094639, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3086]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=116, user_id='FNEW5T5H1GO9', timestamp=1541453232, session_id='939910bb116b5', step=1, action=2, item_id=3086, platform=33, city=205, device=1, current_filters=nan, impressions=['4479572', '944361', '942067', '2133142', '4366726', '4580586', '6660596', '4353658', '1198492', '3770630', '5685078', '1148422', '7706738', '7978576', '4110960', '3378056', '5505354', '5544092', '1471761', '3187640', '2245584', '4697696', '2781923', '6318244'], prices=[88, 81, 74, 91, 94, 60, 92, 160, 112, 57, 105, 63, 300, 49, 52, 84, 45, 63, 63, 36, 63, 107, 58, 60], id=1116, last_item=5321, second_last_item=5376, third_last_item=3171, step_rank=1.0, country=41, country_platform=71, device_platform=62, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=2.0, rg_time_diff=0.972378808858491, step_log=0.6931471805599453)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3110, 3110, 5368, 3110]
[3110, 3110]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3110, 3110]
[5433 3110]
Pandas(Index=118, user_id='N7Y2KOZ7Y23T', timestamp=1541453232, session_id='1975d185be5ef', step=3, action=2, item_id=5368, platform=36, city=193, device=1, current_filters=nan, impressions=['6301824', '1179508', '1288370', '2565685', '8905422', '7201414', '1885593', '1370170', '9238904', '5741752', '1560005', '1885495', '8996776', '4036324', '1885485', '4022192', '4073794', '2565745', '5151600', '2949950', '3950130', '3586220', '1823021', '3994006', '8464694'], prices=[18, 23, 36, 60, 46, 48, 20, 66, 27, 45, 46, 20, 23, 21, 37, 19, 66, 57, 27, 50, 56, 32, 37, 24, 40], id=1118, last_item=3162, second_last_item=3086, third_last_item=5321, step_rank=3.0, country=42, country_platform=76, device_platform=60, sess_step=3, time_diff=4.0, time_diff_diff=4.0, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.09739749868468009, step_log=1.3862943611198906)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3140, 3140, 5368]
[3140, 3140]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3140, 3140]
[5433 3140]
Pandas(Index=120, user_id='XV1HI5C0OSJZ', timestamp=1541453232, session_id='9730953e5e3ce', step=3, action=2, item_id=5368, platform=35, city=192, device=1, current_filters=nan, impressions=['935451', '1236935', '1236853', '102667', '1217640', '924741', '1816207', '918593', '98700', '98702', '102874', '1222048', '102658', '102663', '1826789', '1890497', '1946223', '2650552', '2785044', '1337776', '486901', '1329096', '1236565', '1627585'], prices=[74, 86, 67, 120, 158, 52, 92, 112, 50, 65, 41, 77, 101, 329, 130, 52, 59, 67, 43, 71, 54, 75, 72, 84], id=1120, last_item=3162, second_last_item=5368, third_last_item=5321, step_rank=3.0, country=26, country_platform=86, device_platform=66, sess_step=3, time_diff=4.0, time_diff_diff=4.0, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=4.0, rg_time_diff=0.09381824553655824, step_log=1.3862943611198906)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3162, 3162, 3162]
[3162, 3162]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3162, 3162]
[5433 3162]
Pandas(Index=121, user_id='1HXBU8574JO1', timestamp=1541453232, session_id='fe585397bc561', step=3, action=2, item_id=3162, platform=2, city=206, device=1, current_filters=nan, impressions=['66172', '355686', '949889', '376311', '70512', '78348', '61036', '2024273', '359186', '70519', '380306', '844621'], prices=[122, 70, 69, 61, 91, 70, 89, 60, 282, 140, 98, 133], id=1121, last_item=5368, second_last_item=3162, third_last_item=5321, step_rank=3.0, country=15, country_platform=16, device_platform=14, sess_step=3, time_diff=0.0, time_diff_diff=0.0, time_diff_diff_diff=nan, time_diff_2=4.0, time_diff_3=0.0, rg_time_diff=-0.7387352095922525, step_log=1.3862943611198906)

32it [00:00, 101.17it/s]

30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3197, 5368, 3197, 3197, 3197, 3197]
[3197]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3197]
[5433 3197]
Pandas(Index=123, user_id='4WK8BPN2GOXW', timestamp=1541453233, session_id='f4e49b42ebcf5', step=2, action=2, item_id=5368, platform=0, city=64, device=1, current_filters=nan, impressions=['478011', '2068758', '2627243', '918935', '929539', '925941', '104881', '5849680', '1130489', '1208722', '8128170', '1994909', '924697', '903277', '2734473', '1770325', '1713735', '1947769', '4528384', '1471997', '4986828', '3882130', '2005245', '4595526', '1921529'], prices=[23, 18, 21, 21, 20, 16, 16, 21, 19, 22, 18, 22, 21, 17, 19, 17, 10, 15, 19, 18, 18, 22, 22, 23, 17], id=1123, last_item=3171, second_last_item=5321, third_last_item=5368, step_rank=2.0, country=0, country_platform=0, device_platform=4, sess_step=2, time_diff=15.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=2.0, time_diff_3=0.0, rg_time_diff=0.339323483763417, step_log=1.0986122886681098)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3223]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=126, user_id='41IPTEZ2TDMF', timestamp=1541453233, session_id='2ad2db46df9fd', step=1, action=2, item_id=3223, platform=0, city=208, device=0, current_filters=nan, impressions=['4093448', '3982746', '2084884', '2020331', '953803', '1852507', '2095388', '4065152', '5146060', '10073196', '1887809', '3133266', '3751040', '4946448', '611526', '8416822', '2632410', '1013459', '4760162', '6784062', '1771365', '326666', '4417828', '890787', '3887018'], prices=[54, 26, 44, 44, 36, 28, 45, 34, 41, 56, 37, 44, 38, 30, 40, 42, 55, 42, 70, 67, 38, 38, 48, 46, 32], id=1126, last_item=5321, second_last_item=5321, third_last_item=5368, step_rank=1.0, country=0, country_platform=0, device_platform=0, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=5.0, rg_time_diff=0.9792721920990985, step_log=0.6931471805599453)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3171, 3171, 3171]
[3171, 3171]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3171, 3171]
[5433 3171]
Pandas(Index=122, user_id='S5YSEPLUIZTQ', timestamp=1541453233, session_id='3d72c8267c9a1', step=3, action=2, item_id=3171, platform=12, city=202, device=1, current_filters=nan, impressions=['470891', '9352', '32898', '96903', '9821', '548951', '15472', '80645', '147471', '1105782', '1330564', '1786075', '2002555', '2049583', '2784493', '3176924', '3498146', '6433328', '2855674', '5182704', '80507', '80671', '8930764', '2239398', '9860'], prices=[48, 58, 105, 43, 40, 36, 244, 175, 80, 118, 88, 79, 147, 113, 107, 146, 48, 75, 64, 116, 159, 48, 48, 162, 142], id=1122, last_item=3162, second_last_item=5368, third_last_item=5321, step_rank=3.0, country=38, country_platform=90, device_platform=44, sess_step=3, time_diff=2.0, time_diff_diff=2.0, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=4.0, rg_time_diff=0.051027794690731015, step_log=1.3862943611198906)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3255, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=136, user_id='2LV6036FOZ47', timestamp=1541453236, session_id='4a0af3a5f92d3', step=1, action=2, item_id=3255, platform=9, city=211, device=1, current_filters=nan, impressions=['149345', '7148', '7156', '15729', '100915', '1043318', '15726', '15728', '7434', '94103', '132484', '7279', '7280', '127481', '15730', '159861', '180211', '95350', '7162', '137629', '122967', '94114', '9840', '3387288', '1202530'], prices=[177, 290, 184, 221, 306, 237, 300, 336, 326, 165, 322, 504, 188, 119, 236, 137, 190, 159, 468, 564, 414, 200, 284, 210, 108], id=1136, last_item=5321, second_last_item=5379, third_last_item=1165, step_rank=1.0, country=22, country_platform=28, device_platform=25, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=10.0, time_diff_3=9.0, rg_time_diff=0.995729414361765, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=157, user_id='D4LXP7W0W16Y', timestamp=1541453240, session_id='9cb2aebd50c86', step=1, action=2, item_id=5368, platform=8, city=220, device=1, current_filters=nan, impressions=['85751', '9812252', '9556582', '7044412', '1520419', '8666780', '1197932', '9399566', '5434386', '3925070', '7099688', '8188956', '9057680', '1132161', '1702679', '6998076', '5880718', '5900430', '6893210', '11069024', '5589244', '11029088', '6111036', '8244952', '9701136'], prices=[163, 119, 116, 160, 114, 126, 166, 257, 126, 91, 97, 74, 80, 107, 80, 103, 114, 80, 149, 437, 91, 158, 223, 159, 233], id=1157, last_item=5321, second_last_item=3881, third_last_item=5321, step_rank=1.0, country=10, country_platform=10, device_platform=10, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=13.0, rg_time_diff=1.0053809315238074, step_log=0.6931471805599453)
30
7
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 5321, 5321, 5321, 5368]
[5321, 5321, 5321, 5321, 5321, 5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 5321, 5321, 5321]
[5433 5321]
Pandas(Index=158, user_id='MUOOQC23R8N9', timestamp=1541453240, session_id='9c57f365a02a7', step=7, action=2, item_id=5368, platform=9, city=18, device=0, current_filters='Sort by Price', impressions=['6042380', '6815758', '8311074', '100386', '2538808', '7805462', '7855806', '9606100', '4341360', '9231630', '4959722', '7852044', '3240462', '4343094', '7717982', '9182732', '149015', '152872', '1220130', '2096980', '2238938', '2686055', '3915052', '4503066', '7024154'], prices=[22, 22, 23, 25, 25, 25, 25, 25, 27, 27, 28, 28, 29, 29, 29, 29, 30, 30, 30, 30, 30, 30, 30, 30, 30], id=1158, last_item=5368, second_last_item=5321, third_last_item=3881, step_rank=7.0, country=13, country_platform=65, device_platform=13, sess_step=7, time_diff=12.0, time_diff_diff=12.0, time_diff_diff_diff=22.0, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.31465428846028753, step_log=2.0794415416798357)
30
18
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314]
[3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314, 3314]
[5433 3314]
Pandas(Index=176, user_id='L1IOIJ47C0S6', timestamp=1541453242, session_id='ee9489aaeca70', step=18, action=2, item_id=3314, platform=0, city=146, device=0, current_filters=nan, impressions=['2757973', '3985724', '5082716', '2312102', '134201', '1776289', '2005151', '9356860', '1947653', '2576152', '8994022', '2670033', '2063186', '9155440', '6176972', '5952238', '2757532', '3066124', '2550994', '2757025', '2852632', '3995834', '3053700', '3101452', '5476434'], prices=[101, 62, 81, 49, 32, 41, 42, 24, 49, 43, 56, 36, 144, 22, 40, 48, 47, 45, 31, 42, 40, 33, 28, 38, 28], id=1176, last_item=4553, second_last_item=4553, third_last_item=4553, step_rank=18.0, country=0, country_platform=0, device_platform=0, sess_step=18, time_diff=4.0, time_diff_diff=4.0, time_diff_diff_diff=14.0, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.08488041551323489, step_log=2.9444389791664403)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=177, user_id='YWFLP8MNY722', timestamp=1541453242, session_id='b02c26b94bfa4', step=1, action=2, item_id=5368, platform=11, city=222, device=1, current_filters=nan, impressions=['2207564', '2441000', '1356748', '2877940', '884711', '105194', '3053692', '1253756'], prices=[63, 54, 63, 60, 80, 65, 88, 69], id=1177, last_item=5321, second_last_item=4553, third_last_item=4553, step_rank=1.0, country=18, country_platform=21, device_platform=21, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=4.0, time_diff_3=0.0, rg_time_diff=0.9610910037441829, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3346, 3355, 3355, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=182, user_id='MZITMZQARCM5', timestamp=1541453244, session_id='95e17b451c454', step=1, action=2, item_id=3346, platform=8, city=225, device=1, current_filters=nan, impressions=['12589', '12583', '14644', '857741', '2396278', '12605', '853456', '12608', '12587', '18479', '925325', '48078', '12594', '109915', '12613', '893467', '14762', '46969', '1976493', '5209538', '12604', '12611', '47372', '6733562', '18485'], prices=[170, 256, 319, 106, 170, 318, 319, 377, 160, 291, 282, 239, 170, 158, 277, 325, 129, 170, 226, 238, 267, 287, 126, 227, 242], id=1182, last_item=5321, second_last_item=5383, third_last_item=5321, step_rank=1.0, country=10, country_platform=10, device_platform=10, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=22.0, time_diff_3=0.0, rg_time_diff=0.896008593557974, step_log=0.6931471805599453)
30
4
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 3371, 5368]
[5321, 5321, 5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321]
[5433 5321]
Pandas(Index=184, user_id='EYHNNJB4TQ12', timestamp=1541453245, session_id='e588b932e8d2a', step=4, action=2, item_id=3371, platform=34, city=171, device=1, current_filters='Sort by Price', impressions=['9421888', '2553036', '1760747', '4013268', '164917', '10076904', '102884', '41169', '41186', '238656', '373061', '1387546', '1257667', '6002880', '4371790', '1638949', '6323476', '41258', '41370', '41314', '1495729'], prices=[44, 47, 70, 73, 76, 77, 82, 91, 96, 99, 103, 105, 108, 108, 110, 112, 114, 115, 116, 139, 141], id=1184, last_item=1165, second_last_item=3346, third_last_item=5321, step_rank=4.0, country=7, country_platform=72, device_platform=57, sess_step=4, time_diff=23.0, time_diff_diff=23.0, time_diff_diff_diff=26.0, time_diff_2=10.0, time_diff_3=nan, rg_time_diff=0.40868936803342687, step_log=1.6094379124341003)

42it [00:00, 99.10it/s]

30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 3393, 5321]
[5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321]
[5433 5321]
Pandas(Index=190, user_id='BR27X4XGEK89', timestamp=1541453245, session_id='648230faf612a', step=2, action=2, item_id=3393, platform=16, city=221, device=2, current_filters=nan, impressions=['9433978', '4678476', '1500637', '2441955', '2772569', '2626992', '103353', '406946', '1960971', '103350', '4700312', '5735888', '2123698', '2724682', '3142572', '1627111', '2756094', '515436', '2646856', '6445660', '5948952', '3102990', '3135080', '512206', '1472157'], prices=[41, 12, 18, 14, 29, 103, 40, 39, 26, 71, 13, 14, 39, 37, 46, 46, 18, 22, 19, 41, 13, 51, 53, 37, 32], id=1190, last_item=1165, second_last_item=5321, third_last_item=5321, step_rank=2.0, country=25, country_platform=32, device_platform=71, sess_step=2, time_diff=5.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.10187508811204246, step_log=1.0986122886681098)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3417]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=197, user_id='22NFMJ4323HQ', timestamp=1541453246, session_id='df24b6c0da5cf', step=1, action=2, item_id=3417, platform=18, city=228, device=1, current_filters=nan, impressions=['5071', '733241', '4003514', '1555933', '3177630', '16001', '159140', '5079274', '1289546', '3945834', '764576', '7116036', '9863', '11163416', '52655', '5088', '53201', '51674', '86252', '6318442', '5065048', '2416301', '434286', '9160432', '1246925'], prices=[37, 79, 68, 76, 69, 95, 69, 59, 40, 49, 85, 42, 79, 63, 69, 53, 50, 85, 127, 75, 85, 54, 60, 120, 67], id=1197, last_item=5321, second_last_item=5384, third_last_item=1165, step_rank=1.0, country=19, country_platform=36, device_platform=59, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=nan, rg_time_diff=0.9120702209687983, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=203, user_id='2VQ49SABE2VB', timestamp=1541453247, session_id='49a7c6f8474fd', step=1, action=2, item_id=5368, platform=0, city=59, device=1, current_filters=nan, impressions=['2550922', '2424572', '2062118', '2273630', '1144762', '1949635', '2680850', '2273490', '2501538', '2710882', '3164811', '507826', '2710194', '2571906', '3243016', '2924161', '2349484', '2811686', '2680834', '2603280', '2771250', '1668173', '5069064', '2501476', '1668717'], prices=[45, 36, 38, 95, 66, 37, 39, 43, 63, 25, 47, 65, 36, 54, 40, 47, 35, 38, 92, 60, 45, 49, 29, 71, 83], id=1203, last_item=5321, second_last_item=5381, third_last_item=5321, step_rank=1.0, country=0, country_platform=0, device_platform=4, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=9.0, rg_time_diff=0.9544342208786615, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=217, user_id='DUNTB41VPEQO', timestamp=1541453249, session_id='4acfbb7e5590d', step=1, action=2, item_id=5368, platform=13, city=232, device=1, current_filters=nan, impressions=['2563076', '508001', '521616', '2158108', '320786', '407696', '476161', '1019645', '1719357', '2049187', '2213104', '2563376', '2628155', '3184606', '3500866', '5710586', '6852746', '2261368', '320736', '3135652', '2177904', '516306', '1030480', '203861', '476171'], prices=[56, 59, 50, 42, 108, 140, 37, 43, 11, 40, 156, 64, 281, 32, 147, 77, 79, 32, 62, 22, 97, 63, 33, 212, 34], id=1217, last_item=5321, second_last_item=5367, third_last_item=5367, step_rank=1.0, country=21, country_platform=26, device_platform=23, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=10.0, time_diff_3=0.0, rg_time_diff=0.9456879868105723, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3499]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=234, user_id='DGB46UP1F1R2', timestamp=1541453250, session_id='a124e3bc942a9', step=1, action=2, item_id=3499, platform=26, city=235, device=1, current_filters=nan, impressions=['1882515', '3811128', '624261', '175412', '1647200', '6226518', '5755048', '6300150', '348226', '1315409', '5163458', '152802', '475481', '3193949', '9438484', '939346', '103308', '3507922', '2729380', '5128426', '152804', '321336', '7671132', '938794', '5117946'], prices=[60, 133, 78, 211, 77, 58, 109, 378, 122, 217, 115, 104, 100, 63, 110, 45, 146, 155, 397, 101, 298, 299, 126, 96, 113], id=1234, last_item=5321, second_last_item=5374, third_last_item=1129, step_rank=1.0, country=54, country_platform=102, device_platform=43, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.9265205916894842, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3597, 3597, 3598]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=242, user_id='AFV8FWHV1KJ3', timestamp=1541453251, session_id='80c012ced98b0', step=1, action=2, item_id=3597, platform=18, city=237, device=1, current_filters=nan, impressions=['122197', '336886', '10290502', '8888224', '122196', '9561860', '8452062', '9114802', '9486884', '8897944', '9164504', '10562768', '10430052', '8921694', '124016', '3902600', '7015556', '6509210', '8978176', '9087968', '10425060', '10379130', '8864310', '10424704', '11007252'], prices=[262, 179, 112, 163, 145, 103, 338, 355, 255, 355, 242, 214, 172, 181, 199, 229, 197, 133, 159, 162, 142, 131, 189, 125, 214], id=1242, last_item=5321, second_last_item=5321, third_last_item=3548, step_rank=1.0, country=19, country_platform=36, device_platform=59, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=2.0, time_diff_3=3.0, rg_time_diff=0.9413686170190658, step_log=0.6931471805599453)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3574, 3574, 5368]
[3574, 3574]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3574, 3574]
[5433 3574]
Pandas(Index=241, user_id='U0LMPAJ632UD', timestamp=1541453251, session_id='0f7396507a212', step=3, action=2, item_id=5368, platform=12, city=234, device=1, current_filters=nan, impressions=['1037828', '588211', '1491999', '2609052', '387351', '1995351', '4714254', '947431', '3199982', '2790150', '2145200', '1102282', '2824878', '5435804', '2582416', '3205392', '5436626', '10195932', '6975416', '6831260', '6448054', '9154866', '8649920', '9959484', '10021306'], prices=[62, 37, 600, 63, 52, 48, 55, 55, 50, 45, 69, 88, 45, 58, 68, 45, 44, 60, 51, 60, 288, 65, 130, 91, 85], id=1241, last_item=5321, second_last_item=3548, third_last_item=5321, step_rank=3.0, country=32, country_platform=51, device_platform=44, sess_step=3, time_diff=2.0, time_diff_diff=2.0, time_diff_diff_diff=nan, time_diff_2=3.0, time_diff_3=nan, rg_time_diff=0.03326239769731031, step_log=1.3862943611198906)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3548]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=239, user_id='90JUFOYD26YD', timestamp=1541453251, session_id='403f85d106081', step=1, action=2, item_id=3548, platform=39, city=236, device=0, current_filters=nan, impressions=['5018536', '3553948', '1593823', '7882292', '7723384', '1838589', '7848330', '2746830', '7363526', '8102712', '2629508', '8161684', '1836177', '3152836', '2032945', '2470750', '8997860', '3940340', '7706852', '1837753', '3579792', '1257161', '3940860', '9003816', '8318906'], prices=[60, 45, 22, 48, 52, 98, 66, 20, 62, 83, 18, 70, 536, 48, 80, 98, 40, 20, 73, 48, 34, 45, 30, 58, 24], id=1239, last_item=5321, second_last_item=5387, third_last_item=5368, step_rank=1.0, country=55, country_platform=105, device_platform=74, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=2.0, rg_time_diff=0.9328336948862987, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3539, 3539, 3539, 3539, 3539]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=238, user_id='D7YRM4ONDLDY', timestamp=1541453251, session_id='0727806bc1ef6', step=1, action=2, item_id=3539, platform=30, city=202, device=1, current_filters=nan, impressions=['1670395', '2105026', '1723091', '80507', '80545', '80627', '80671', '147473', '147474', '1786075', '2123866', '3176924', '3366988', '4010856', '7758738', '8324396', '9018956', '2002555', '2432716', '1922723', '15550', '9521788', '80567', '80516', '1330564'], prices=[33, 36, 61, 159, 118, 43, 48, 108, 78, 79, 68, 152, 45, 83, 67, 49, 15, 149, 90, 79, 100, 72, 65, 47, 88], id=1238, last_item=5321, second_last_item=5368, third_last_item=5321, step_rank=1.0, country=38, country_platform=104, device_platform=73, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=2.0, time_diff_3=nan, rg_time_diff=0.9307210794740539, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=236, user_id='9T9G5H6H3IVZ', timestamp=1541453251, session_id='e96ac94a53d6e', step=1, action=2, item_id=5368, platform=8, city=3, device=1, current_filters=nan, impressions=['2450306', '1473305', '14082', '99932', '13435', '14088', '883697', '5005660', '100023', '923601', '341666', '231736', '1231946', '341226', '149255', '565196', '8414618', '6398796', '4124684', '8136052', '6328964', '9201876', '8461916', '8207214', '8471102'], prices=[115, 166, 138, 159, 130, 114, 190, 96, 334, 145, 88, 131, 119, 93, 132, 86, 146, 120, 281, 131, 254, 137, 118, 112, 187], id=1236, last_item=5321, second_last_item=3499, third_last_item=1129, step_rank=1.0, country=3, country_platform=103, device_platform=10, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=34.0, time_diff_3=nan, rg_time_diff=0.9286167394320195, step_log=0.6931471805599453)

52it [00:00, 97.14it/s]

30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1279, 5368]
[1279]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1279]
[5433 1279]
Pandas(Index=249, user_id='ZLX4ODP074FY', timestamp=1541453252, session_id='37d5b748a9202', step=2, action=2, item_id=5368, platform=8, city=51, device=0, current_filters=nan, impressions=['8642', '986971', '2835834', '8628', '1811137', '61700', '1455521', '1104798', '1285525', '8813', '2861604', '3132652', '8134318', '10032092', '10064344', '8772', '2300750', '8729', '8793', '8738', '8771', '8777', '2499104', '2891353', '3120550'], prices=[218, 348, 338, 316, 228, 234, 342, 278, 207, 240, 404, 409, 247, 349, 234, 214, 451, 372, 334, 246, 330, 1008, 442, 211, 254], id=1249, last_item=3881, second_last_item=5321, third_last_item=3881, step_rank=2.0, country=15, country_platform=37, device_platform=16, sess_step=2, time_diff=12.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.31269759132156594, step_log=1.0986122886681098)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=260, user_id='RFYWGE7QYGYB', timestamp=1541453253, session_id='c584105b21418', step=1, action=2, item_id=5368, platform=3, city=240, device=1, current_filters=nan, impressions=['42878', '43038', '2282646', '3239488', '42352', '43139', '6554582', '513161', '4129338', '9497900', '43066', '157658', '2809306', '2042953', '377611', '9489568', '2550850', '397601', '2675548', '6338300', '1321222', '6992906', '2677270', '42708', '5959650'], prices=[69, 70, 60, 48, 67, 46, 35, 54, 53, 21, 71, 66, 23, 79, 59, 21, 32, 52, 27, 35, 50, 14, 24, 37, 33], id=1260, last_item=5321, second_last_item=5388, third_last_item=5383, step_rank=1.0, country=8, country_platform=8, device_platform=5, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=nan, rg_time_diff=0.920280490207656, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=262, user_id='W066H61PJWCS', timestamp=1541453253, session_id='2542763204020', step=1, action=2, item_id=5368, platform=31, city=242, device=2, current_filters=nan, impressions=['15197', '27038', '41056', '27050', '27052', '27042', '27032', '27045', '27049', '27024', '27039', '27030', '27056', '27054', '2174488', '790991', '27046', '15227', '1319076', '1036084', '1943397', '3441778', '8111532', '8112318', '3960304'], prices=[161, 157, 130, 261, 118, 288, 202, 174, 175, 514, 177, 308, 181, 108, 156, 140, 183, 184, 249, 132, 69, 218, 152, 157, 203], id=1262, last_item=5321, second_last_item=5368, third_last_item=5388, step_rank=1.0, country=56, country_platform=106, device_platform=75, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.9161599163574932, step_log=0.6931471805599453)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 3689]
[5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321]
[5433 5321]
Pandas(Index=270, user_id='8GZOLI30YKW9', timestamp=1541453254, session_id='71c0c8f8ed8ea', step=2, action=2, item_id=3689, platform=11, city=204, device=0, current_filters=nan, impressions=['43354', '4865120', '741841', '7744896', '3149758', '5750100', '5835624', '1811073', '927799', '1359536', '7164004', '3214246', '2155250', '5108846', '2671154', '5518646', '4796860', '4552228', '2231502', '5035238', '5211712', '480821', '4764482', '3213386', '1941645'], prices=[173, 147, 258, 120, 249, 186, 47, 206, 110, 145, 126, 111, 130, 155, 130, 202, 91, 150, 172, 65, 166, 169, 100, 122, 351], id=1270, last_item=5321, second_last_item=5321, third_last_item=4319, step_rank=2.0, country=48, country_platform=91, device_platform=18, sess_step=2, time_diff=22.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=0.0, rg_time_diff=0.40346123377840654, step_log=1.0986122886681098)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=273, user_id='265GYCF48NVT', timestamp=1541453254, session_id='b49971ab50ee6', step=1, action=2, item_id=5368, platform=12, city=245, device=1, current_filters=nan, impressions=['13994', '50340', '5122550', '10685048', '534986', '6682244', '3785506', '86152', '49282', '14082', '626446', '149255', '48457', '13435', '15067', '49693', '99874', '883697', '86027', '231736', '395041', '48493', '99801', '141220', '6473688'], prices=[278, 99, 59, 66, 68, 146, 98, 107, 71, 226, 41, 166, 80, 188, 88, 46, 79, 204, 61, 117, 61, 90, 60, 88, 140], id=1273, last_item=5321, second_last_item=5391, third_last_item=3689, step_rank=1.0, country=3, country_platform=108, device_platform=44, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=31.0, rg_time_diff=0.8979910294731449, step_log=0.6931471805599453)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1129, 1129, 5368]
[1129, 1129]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 1129, 1129]
[5433 1129]
Pandas(Index=281, user_id='K3LR9KDM6HIE', timestamp=1541453255, session_id='c8020919bd08e', step=3, action=2, item_id=5368, platform=19, city=91, device=1, current_filters=nan, impressions=['7875360', '3534986', '7126898', '1952071', '105672', '95185', '98375', '105653', '105676', '1125819', '1236765', '1832403', '1922351', '2101832', '5737714', '7195380', '2378829', '363316', '2398008', '1558601', '1207438', '953757', '3533526', '1041050', '3812544'], prices=[78, 46, 102, 154, 61, 231, 203, 133, 126, 288, 87, 339, 287, 408, 65, 82, 50, 88, 227, 60, 93, 71, 278, 85, 77], id=1281, last_item=4190, second_last_item=4190, third_last_item=5321, step_rank=3.0, country=28, country_platform=38, device_platform=72, sess_step=3, time_diff=5.0, time_diff_diff=5.0, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.10097924911912481, step_log=1.3862943611198906)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=295, user_id='B9DJ9GICCTOD', timestamp=1541453256, session_id='5593872028ad9', step=1, action=2, item_id=5368, platform=2, city=248, device=1, current_filters=nan, impressions=['71794', '68108', '76815', '1005253', '68113', '68099', '2618062', '152306', '66431', '5060392', '77158', '70060', '5121410', '55603', '375771', '6537622', '942621', '68086', '77930', '2311812', '61249', '157960', '63884', '78347', '152302'], prices=[95, 166, 66, 51, 82, 61, 268, 66, 125, 200, 74, 171, 174, 63, 58, 455, 82, 74, 105, 262, 210, 170, 280, 97, 78], id=1295, last_item=5321, second_last_item=3820, third_last_item=1165, step_rank=1.0, country=15, country_platform=16, device_platform=14, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=nan, rg_time_diff=1.022736556325754, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=311, user_id='8UQ4QG7AZ7ZQ', timestamp=1541453258, session_id='18a8f61a4e147', step=1, action=2, item_id=5368, platform=40, city=253, device=1, current_filters=nan, impressions=['196441', '499866', '429761', '323881', '2727724', '908799', '2633030', '9339538', '866811', '520321', '1157538', '1389564', '4124784', '492551', '6096216', '6391308', '5498402', '8944968', '8210040', '4052320', '6664026', '1394770', '2095690', '3133312', '3133310'], prices=[173, 176, 130, 87, 35, 108, 69, 61, 63, 90, 112, 115, 35, 65, 44, 105, 55, 51, 80, 61, 77, 55, 44, 75, 89], id=1311, last_item=5321, second_last_item=4731, third_last_item=4731, step_rank=1.0, country=20, country_platform=107, device_platform=77, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=7.0, time_diff_3=0.0, rg_time_diff=0.9933453136540631, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3799]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=316, user_id='LKB7BRFLMWYY', timestamp=1541453259, session_id='e382cc1da426c', step=1, action=2, item_id=3799, platform=20, city=17, device=1, current_filters=nan, impressions=['6122992', '18176', '54589', '54593', '883665', '14873', '54536', '1689597', '3132878', '1383987', '2398840', '14871', '54583', '2438614', '54765', '138879', '14857', '1288622', '3150678', '2219158', '18333', '54580', '54749', '5113314', '15033'], prices=[285, 138, 122, 152, 75, 77, 140, 59, 132, 140, 179, 160, 75, 123, 190, 199, 183, 150, 125, 147, 94, 186, 113, 74, 99], id=1316, last_item=5321, second_last_item=3906, third_last_item=5394, step_rank=1.0, country=12, country_platform=113, device_platform=35, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=nan, rg_time_diff=0.9862599203632143, step_log=0.6931471805599453)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3820, 5368]
[3820]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3820]
[5433 3820]
Pandas(Index=328, user_id='3FJ0OAQCQCYU', timestamp=1541453259, session_id='3ba7cf6013ef0', step=2, action=2, item_id=5368, platform=9, city=247, device=2, current_filters=nan, impressions=['1347484', '110949', '4258950', '99053', '85244', '94711', '115332', '1227456', '4831500', '126861', '110939', '99045', '110926', '129309', '9189352', '1305992', '2827384', '1533229', '110932', '1459973', '2570414', '125307', '4685516', '2828879', '86487'], prices=[35, 63, 68, 24, 59, 36, 49, 97, 50, 38, 54, 41, 36, 44, 114, 111, 27, 33, 39, 39, 64, 44, 48, 42, 64], id=1328, last_item=5367, second_last_item=5321, third_last_item=5367, step_rank=2.0, country=22, country_platform=28, device_platform=54, sess_step=2, time_diff=4.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.091135387316594, step_log=1.0986122886681098)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=331, user_id='OLEWURYYXWMM', timestamp=1541453260, session_id='c94a39e48a805', step=1, action=2, item_id=5368, platform=36, city=254, device=1, current_filters=nan, impressions=['2881964', '2684235', '4881386', '2808508', '6977438', '6646100', '5160576', '9381512', '3199669', '6992218', '8737728'], prices=[13, 20, 18, 35, 13, 14, 32, 29, 19, 33, 24], id=1331, last_item=5321, second_last_item=5321, third_last_item=5368, step_rank=1.0, country=58, country_platform=114, device_platform=60, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=4.0, time_diff_3=33.0, rg_time_diff=0.9588626278437073, step_log=0.6931471805599453)

63it [00:00, 98.32it/s]

30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3856, 3856, 3856]
[3856, 3856]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3856, 3856]
[5433 3856]
Pandas(Index=352, user_id='Q0CLYL25MB0D', timestamp=1541453261, session_id='8e97114eb7e74', step=3, action=2, item_id=3856, platform=33, city=226, device=0, current_filters=nan, impressions=['1016411', '1066248', '2273920', '607351', '2891322', '7532814', '1085676', '2027033', '1142393', '1133071', '1016409', '3855928', '1226658', '1297156', '3119208', '1279744', '949745', '1875621', '4070392', '1288867', '4256688', '8314020', '9655450', '5627340', '4518406'], prices=[60, 111, 135, 81, 111, 51, 93, 35, 100, 21, 84, 98, 104, 43, 77, 56, 196, 59, 37, 56, 56, 23, 26, 58, 35], id=1352, last_item=4035, second_last_item=5391, third_last_item=5321, step_rank=3.0, country=41, country_platform=71, device_platform=56, sess_step=3, time_diff=6.0, time_diff_diff=-4.0, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.12342775983724144, step_log=1.3862943611198906)
30
14
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 3881, 3881, 3881, 3881, 3881, 3881, 3881, 3881, 3881, 3881, 3881, 3881, 3881]
[5321, 3881, 3881, 3881, 3881, 3881, 3881, 3881, 3881, 3881, 3881, 3881, 3881]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 3881, 3881, 3881, 3881, 3881, 3881, 3881, 3881, 3881, 3881, 3881, 3881]
[5433 5321 3881]
Pandas(Index=356, user_id='MTW5300Y7R3W', timestamp=1541453262, session_id='b163e320d9366', step=14, action=2, item_id=3881, platform=18, city=156, device=0, current_filters=nan, impressions=['1522673', '5037', '5036', '5023', '5021', '159349', '921425', '5040', '53312', '147427', '5029', '5048', '5645454', '5022', '5027', '922409', '5043', '1218514', '147429', '5046', '3515626', '430951', '936403', '4466814', '5028'], prices=[65, 99, 124, 127, 156, 72, 89, 171, 173, 84, 164, 85, 190, 100, 138, 74, 91, 47, 94, 79, 134, 277, 184, 98, 127], id=1356, last_item=5387, second_last_item=5396, third_last_item=5391, step_rank=14.0, country=19, country_platform=36, device_platform=33, sess_step=14, time_diff=2.0, time_diff_diff=2.0, time_diff_diff_diff=10.0, time_diff_2=2.0, time_diff_3=0.0, rg_time_diff=0.035925595305829464, step_log=2.70805020110221)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3906, 5368]
[3906]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3906]
[5433 3906]
Pandas(Index=361, user_id='8O3BKN0PDHQI', timestamp=1541453262, session_id='29f9855a67df1', step=2, action=2, item_id=5368, platform=2, city=96, device=1, current_filters=nan, impressions=['2346006', '42309', '42125', '16117', '2179866', '1175598', '9051714', '42108', '151812', '921237', '42093', '105814', '8335912', '108023', '42291', '42143', '8204770', '1584817', '5188258', '1328329', '42090', '42091', '42101', '1387348', '42109'], prices=[107, 92, 131, 121, 89, 132, 100, 112, 168, 79, 85, 126, 84, 79, 149, 96, 161, 68, 89, 92, 84, 140, 67, 126, 178], id=1361, last_item=3982, second_last_item=5321, third_last_item=5397, step_rank=2.0, country=29, country_platform=112, device_platform=14, sess_step=2, time_diff=4.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=38.0, time_diff_3=nan, rg_time_diff=0.0875602759374891, step_log=1.0986122886681098)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=387, user_id='96WZ35KYD4J8', timestamp=1541453263, session_id='27cda08aa7730', step=1, action=2, item_id=5368, platform=33, city=260, device=1, current_filters=nan, impressions=['1261360', '3102478', '4802248', '1261583', '1378166', '1455633', '1016507', '8126750', '4058210', '1261364', '1949695', '2441867', '3948454', '4699814', '2626148', '1499139', '9260962', '6416050', '1527953'], prices=[42, 56, 108, 36, 34, 39, 44, 51, 56, 33, 31, 39, 52, 24, 37, 35, 88, 28, 19], id=1387, last_item=5321, second_last_item=5389, third_last_item=5389, step_rank=1.0, country=41, country_platform=71, device_platform=62, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.8765598072786546, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=372, user_id='W9E96G8VTT85', timestamp=1541453263, session_id='999c27a82c752', step=1, action=2, item_id=5368, platform=6, city=259, device=2, current_filters=nan, impressions=['42892', '2675586', '615271', '3477894', '3479190', '3479192', '2877024', '5751722', '6966242', '9143018', '8735008', '10205228'], prices=[106, 30, 54, 42, 39, 31, 59, 78, 31, 158, 191, 219], id=1372, last_item=5321, second_last_item=5383, third_last_item=5383, step_rank=1.0, country=8, country_platform=119, device_platform=8, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.8063720564863214, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4010]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=406, user_id='V9187WYZN0Q8', timestamp=1541453264, session_id='1fd6d159ba7ca', step=1, action=2, item_id=4010, platform=18, city=265, device=1, current_filters=nan, impressions=['7003', '94584', '7000', '13046', '13303', '15991', '15442', '15968', '9605', '13301', '16008', '7001', '6447808', '7219', '182016', '94573', '7224', '133054', '113785', '7223', '94058', '40043', '6124340', '6996', '15682'], prices=[100, 96, 126, 286, 201, 162, 142, 178, 122, 278, 102, 156, 50, 104, 142, 43, 172, 98, 114, 187, 113, 178, 175, 128, 102], id=1406, last_item=5321, second_last_item=5321, third_last_item=4152, step_rank=1.0, country=22, country_platform=97, device_platform=59, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.8377416251425419, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3996]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=402, user_id='BO8MS5LT942Y', timestamp=1541453264, session_id='319e142ac5a95', step=1, action=2, item_id=3996, platform=2, city=264, device=2, current_filters=nan, impressions=['44219', '44208', '44646', '843606', '321456', '399146', '1281180', '43449', '44386', '5704998', '44453', '44884', '44370', '44196', '43358', '44532', '153232', '3215344', '44174', '1291248', '44123', '44476', '44080', '43612', '44387'], prices=[72, 83, 66, 37, 36, 65, 63, 46, 54, 35, 32, 87, 57, 73, 79, 57, 63, 51, 63, 46, 35, 66, 40, 31, 73], id=1402, last_item=5321, second_last_item=5321, third_last_item=5321, step_rank=1.0, country=4, country_platform=45, device_platform=2, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.8431322614507778, step_log=0.6931471805599453)
30
4
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 3982, 3982, 3982]
[5321, 3982, 3982]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 3982, 3982]
[5433 5321 3982]
Pandas(Index=396, user_id='LG8R04UK1FRD', timestamp=1541453264, session_id='6233995d86dd0', step=4, action=2, item_id=3982, platform=8, city=180, device=1, current_filters=nan, impressions=['2530750', '1364710', '2826684', '12618', '5206872', '7126736', '18904', '12615', '12616', '2707162', '706646', '47392', '46715', '18910', '934069', '2333066', '1384141', '933215', '3252506', '631931', '3820896', '18913', '152873', '1359184', '12620'], prices=[67, 92, 77, 101, 46, 84, 103, 144, 146, 78, 192, 123, 147, 101, 118, 112, 120, 144, 129, 92, 46, 90, 166, 43, 94], id=1396, last_item=5321, second_last_item=5389, third_last_item=4165, step_rank=4.0, country=10, country_platform=10, device_platform=10, sess_step=4, time_diff=2.0, time_diff_diff=2.0, time_diff_diff_diff=40.0, time_diff_2=nan, time_diff_3=0.0, rg_time_diff=0.047472496735974846, step_log=1.6094379124341003)
30
5
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 2856, 2857]
[5321, 5321, 5321, 2856]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 2856]
[5433 5321 2856]
Pandas(Index=416, user_id='BOLB6OCXFQLW', timestamp=1541453265, session_id='d00d2e9066331', step=5, action=2, item_id=2857, platform=30, city=155, device=2, current_filters='Best Value', impressions=['1106804', '1753149', '1825401', '53834', '8992496', '1204106', '7129916', '3133488', '53833', '53922', '53969', '53876', '1321404', '53846', '53855', '93616', '53929', '53954', '93625', '53856', '152781', '6207346', '1273207', '148126', '53955'], prices=[127, 174, 171, 314, 326, 190, 192, 225, 261, 229, 372, 388, 282, 218, 301, 119, 232, 384, 232, 249, 230, 167, 249, 301, 341], id=1416, last_item=5321, second_last_item=4152, third_last_item=5321, step_rank=5.0, country=40, country_platform=66, device_platform=50, sess_step=5, time_diff=42.0, time_diff_diff=39.0, time_diff_diff_diff=36.0, time_diff_2=nan, time_diff_3=0.0, rg_time_diff=0.48784640745024516, step_log=1.791759469228055)
30
9
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 4035, 4035, 4035, 4035, 4035, 4035, 4035, 5368]
[5321, 4035, 4035, 4035, 4035, 4035, 4035, 4035]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 4035, 4035, 4035, 4035, 4035, 4035, 4035]
[5433 5321 4035]
Pandas(Index=423, user_id='MA5KI0J1OFR6', timestamp=1541453266, session_id='4c39baeed892d', step=9, action=2, item_id=5368, platform=2, city=216, device=1, current_filters=nan, impressions=['72775', '66753', '982807', '153662', '939494', '153664', '78876', '63498', '78893', '74080', '69998', '69201', '60283', '66757', '838296', '66762', '2584344', '56761', '61675', '824951', '78509', '76863', '66759', '833911', '982789'], prices=[59, 44, 48, 60, 51, 39, 50, 52, 48, 43, 56, 59, 60, 54, 49, 46, 55, 42, 53, 44, 43, 47, 54, 47, 44], id=1423, last_item=5397, second_last_item=5387, third_last_item=5387, step_rank=9.0, country=15, country_platform=16, device_platform=14, sess_step=9, time_diff=5.0, time_diff_diff=5.0, time_diff_diff_diff=5.0, time_diff_2=1.0, time_diff_3=0.0, rg_time_diff=0.10546009453266486, step_log=2.302585092994046)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4060]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=428, user_id='GYFSL6JSZE8E', timestamp=1541453266, session_id='85c457cc8c023', step=1, action=2, item_id=4060, platform=2, city=268, device=2, current_filters=nan, impressions=['2575017', '102361', '102366', '930335', '3091758', '1838891', '3871754', '130318', '7984738', '97026', '102360', '6694032', '933541', '951051', '5121656', '2854654', '3797344', '7918290', '1954165', '5406062', '1278493', '1838895', '5080738', '102348', '2052209'], prices=[169, 164, 213, 76, 159, 151, 217, 190, 49, 168, 136, 241, 113, 126, 246, 98, 154, 75, 86, 188, 150, 129, 146, 152, 163], id=1428, last_item=5321, second_last_item=5392, third_last_item=5392, step_rank=1.0, country=60, country_platform=124, device_platform=2, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=1.4520736907730223, step_log=0.6931471805599453)

74it [00:00, 98.89it/s]

30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=442, user_id='KV2CBP2MA4YV', timestamp=1541453267, session_id='7895aef8a5f35', step=1, action=2, item_id=5368, platform=15, city=166, device=1, current_filters=nan, impressions=['936331', '19817', '46184', '46161', '1413032', '46094', '448196', '344741', '109994', '1474435', '468671', '19815', '46101', '46045', '5857346', '6452284', '6033592'], prices=[99, 137, 105, 108, 98, 125, 115, 189, 99, 120, 87, 129, 109, 99, 192, 179, 135], id=1442, last_item=5321, second_last_item=4226, third_last_item=4226, step_rank=1.0, country=23, country_platform=29, device_platform=55, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=10.0, time_diff_3=0.0, rg_time_diff=1.3623260092804004, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4111]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=454, user_id='DHZVW0PW8W9V', timestamp=1541453268, session_id='3863ab1bf01ed', step=1, action=2, item_id=4111, platform=20, city=271, device=0, current_filters=nan, impressions=['4051912', '113268', '649071', '127388', '1682937', '4058062', '1722151', '9400680', '6421334', '4091146', '7331456', '96781', '94201', '2892757', '1094726', '4094450', '2825392', '6841248', '9481188', '2165012', '2548388', '6154672', '6327038', '10397508'], prices=[49, 59, 66, 70, 105, 80, 146, 81, 80, 71, 92, 44, 73, 19, 79, 80, 65, 102, 97, 75, 75, 68, 58, 45], id=1454, last_item=5321, second_last_item=5384, third_last_item=5384, step_rank=1.0, country=22, country_platform=125, device_platform=48, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=13.0, time_diff_3=0.0, rg_time_diff=1.3297659805444155, step_log=0.6931471805599453)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 4114]
[5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321]
[5433 5321]
Pandas(Index=460, user_id='G4575T85K617', timestamp=1541453268, session_id='5ac40c5c23895', step=2, action=2, item_id=4114, platform=0, city=195, device=1, current_filters=nan, impressions=['1334288', '2188552', '2772562', '1001261', '1184398', '2053936', '682946', '94956', '913037', '132252', '106421', '2235114', '903599', '903601', '104952', '109313', '326811', '6452316', '448986', '104910', '1366476', '2058260', '2095676', '1104194', '1375150'], prices=[328, 221, 73, 250, 287, 167, 325, 1243, 239, 296, 239, 202, 191, 184, 272, 307, 242, 429, 188, 242, 247, 219, 173, 317, 295], id=1460, last_item=4731, second_last_item=5321, third_last_item=4731, step_rank=2.0, country=0, country_platform=0, device_platform=4, sess_step=2, time_diff=39.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.4766580272227205, step_log=1.0986122886681098)
30
6
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 4152, 4152, 4152]
[5321, 5321, 5321, 4152, 4152]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 4152, 4152]
[5433 5321 4152]
Pandas(Index=473, user_id='01TTN4TZ769E', timestamp=1541453270, session_id='cb3f61b30edc3', step=6, action=2, item_id=4152, platform=8, city=51, device=0, current_filters='Focus on Distance', impressions=['4916380', '9446232', '8708', '9552324', '3480558', '4985600', '1451293', '911743', '6475414', '5710478', '2141006', '3153172', '8773', '5782696', '8711', '8837', '921869', '7775148', '1334408', '4844848', '3150207', '918537', '8817', '63865', '7121388'], prices=[254, 285, 167, 232, 158, 332, 161, 190, 311, 283, 226, 365, 216, 422, 208, 360, 240, 161, 363, 178, 191, 256, 344, 218, 157], id=1473, last_item=5321, second_last_item=5321, third_last_item=5321, step_rank=6.0, country=15, country_platform=37, device_platform=16, sess_step=6, time_diff=6.0, time_diff_diff=6.0, time_diff_diff_diff=23.0, time_diff_2=nan, time_diff_3=33.0, rg_time_diff=0.11263834260315118, step_log=1.9459101490553132)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4165, 4165]
[4165]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4165]
[5433 4165]
Pandas(Index=483, user_id='YCT6RC7NJ46L', timestamp=1541453271, session_id='f082553e50302', step=2, action=2, item_id=4165, platform=17, city=261, device=1, current_filters=nan, impressions=['2027433', '2591485', '492521', '998309', '3515894', '998303', '2248554', '3059228', '2423944', '5822404', '7814532', '2330376', '2355968', '4115586', '2639232', '2246168', '2646946', '2642114', '9175164', '1313206', '1962551', '2441974', '9184630', '2710200', '4705044'], prices=[38, 63, 66, 76, 40, 67, 72, 44, 40, 27, 99, 90, 34, 36, 35, 60, 63, 47, 50, 55, 72, 25, 30, 43, 36], id=1483, last_item=5321, second_last_item=5321, third_last_item=5368, step_rank=2.0, country=26, country_platform=33, device_platform=30, sess_step=2, time_diff=8.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=2.0, rg_time_diff=0.13424599234477144, step_log=1.0986122886681098)
30
5
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 3371, 5368]
[5321, 5321, 5321, 3371]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 3371]
[5433 5321 3371]
Pandas(Index=480, user_id='EYHNNJB4TQ12', timestamp=1541453271, session_id='e588b932e8d2a', step=5, action=2, item_id=5368, platform=34, city=171, device=1, current_filters='Sort by Price', impressions=['9421888', '2553036', '1760747', '4013268', '164917', '10076904', '102884', '41169', '41186', '238656', '373061', '1387546', '1257667', '6002880', '4371790', '1638949', '6323476', '41258', '41370', '41314', '1495729'], prices=[44, 47, 70, 73, 76, 77, 82, 91, 96, 99, 103, 105, 108, 108, 110, 112, 114, 115, 116, 139, 141], id=1480, last_item=5397, second_last_item=5321, third_last_item=5321, step_rank=5.0, country=7, country_platform=72, device_platform=57, sess_step=5, time_diff=26.0, time_diff_diff=3.0, time_diff_diff_diff=-20.0, time_diff_2=2.0, time_diff_3=0.0, rg_time_diff=0.42451035185926417, step_log=1.791759469228055)
30
7
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4190, 4190, 4190, 4190, 4190, 4190, 4201]
[4190, 4190, 4190, 4190, 4190, 4190]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4190, 4190, 4190, 4190, 4190, 4190]
[5433 4190]
Pandas(Index=492, user_id='J67O7PKD66TU', timestamp=1541453272, session_id='28ae93cf0a0be', step=7, action=2, item_id=4201, platform=21, city=246, device=1, current_filters=nan, impressions=['1594751', '2066476', '2654928', '1336671', '1191790', '2593142', '4118300', '1562799', '1331223', '8214264', '1562505', '1562631', '1533829', '1562669', '5948496', '1109224', '1556597', '2588084', '1562643', '3070960', '1562671', '6008328', '2904506', '4083470', '2010601'], prices=[55, 40, 48, 140, 84, 57, 62, 40, 75, 50, 60, 60, 80, 60, 163, 64, 60, 60, 90, 99, 75, 60, 80, 39, 49], id=1492, last_item=5380, second_last_item=5321, third_last_item=5396, step_rank=7.0, country=33, country_platform=109, device_platform=36, sess_step=7, time_diff=17.0, time_diff_diff=17.0, time_diff_diff_diff=17.0, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.3613784260127575, step_log=2.0794415416798357)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4212]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=494, user_id='8AT59QM9P5VM', timestamp=1541453272, session_id='2ed97acd258ac', step=1, action=2, item_id=4212, platform=2, city=276, device=0, current_filters=nan, impressions=['67153', '753006', '56558', '816851', '60237', '833161', '599351', '70269', '60211', '8589896', '9124078', '4943604', '10377778', '56911', '10519298'], prices=[28, 30, 41, 22, 44, 56, 19, 60, 21, 192, 351, 22, 228, 31, 197], id=1494, last_item=5321, second_last_item=4201, third_last_item=5380, step_rank=1.0, country=15, country_platform=16, device_platform=3, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=10.0, time_diff_3=17.0, rg_time_diff=1.7762294718375082, step_log=0.6931471805599453)
30
11
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4226, 4226, 4226, 4226, 4226, 4226, 4226, 4226, 4226, 4226, 5368, 4226, 4226, 4226, 4226, 4226, 4226]
[4226, 4226, 4226, 4226, 4226, 4226, 4226, 4226, 4226, 4226]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4226, 4226, 4226, 4226, 4226, 4226, 4226, 4226, 4226, 4226]
[5433 4226]
Pandas(Index=495, user_id='TC69W10I3YP3', timestamp=1541453272, session_id='a09467048a5e4', step=11, action=2, item_id=5368, platform=0, city=270, device=1, current_filters=nan, impressions=['2356386', '3152158', '3243192', '3165738', '3061988', '3882088', '3167644', '3810608', '3242128', '1420921', '3221026', '3133118', '3505882', '2313022', '9002234', '4991036', '3224394', '3148422', '3148416', '3133102', '3142776', '2440492', '3367032', '3184572', '2646112'], prices=[56, 39, 27, 27, 27, 21, 26, 40, 34, 45, 26, 36, 56, 58, 21, 48, 33, 32, 30, 53, 27, 38, 32, 41, 27], id=1495, last_item=4212, second_last_item=5321, third_last_item=4201, step_rank=11.0, country=0, country_platform=0, device_platform=4, sess_step=11, time_diff=5.0, time_diff_diff=5.0, time_diff_diff_diff=5.0, time_diff_2=nan, time_diff_3=10.0, rg_time_diff=0.10815062439582096, step_log=2.4849066497880004)
30
6
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 5321, 5321, 5368, 5321, 5321, 5321]
[5321, 5321, 5321, 5321, 5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 5321, 5321]
[5433 5321]
Pandas(Index=499, user_id='9AZEAIV7KITA', timestamp=1541453273, session_id='c994536241002', step=6, action=2, item_id=5368, platform=10, city=129, device=0, current_filters='Free WiFi (Combined)|Air Conditioning|Kitchen|Reception (24/7)|Restaurant', impressions=['1932087', '705071', '218136', '137195', '219026', '1270183', '9416724', '4143782', '8269232', '1621755', '4658764', '2824500', '3132753', '1769691', '4082846', '7891870', '8938770', '6283622', '1054998', '2383954', '3990140', '4682800', '5411626', '1669267', '3946306'], prices=[24, 112, 106, 129, 131, 19, 36, 49, 43, 93, 44, 54, 60, 23, 50, 41, 36, 36, 25, 29, 47, 30, 31, 32, 44], id=1499, last_item=5401, second_last_item=5388, third_last_item=5377, step_rank=6.0, country=17, country_platform=20, device_platform=17, sess_step=6, time_diff=15.0, time_diff_diff=8.0, time_diff_diff_diff=4.0, time_diff_2=46.0, time_diff_3=10.0, rg_time_diff=0.34830488392045716, step_log=1.9459101490553132)

84it [00:00, 98.14it/s]

30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=513, user_id='SQ4EY9KC4O2O', timestamp=1541453274, session_id='243b4f053f713', step=1, action=2, item_id=5368, platform=0, city=278, device=1, current_filters=nan, impressions=['3950624', '313616', '1710653', '1555637', '9004316', '1654267', '519801', '1130829', '2124014', '908571', '1394840', '2369087', '1157950', '1088680', '505976', '10114862', '1452733', '1885959', '1387960', '1051034', '106925', '1157904', '1446837', '3822122', '1314785'], prices=[29, 26, 38, 74, 19, 38, 49, 32, 40, 42, 27, 23, 33, 51, 44, 35, 44, 35, 26, 37, 38, 36, 32, 37, 42], id=1513, last_item=5321, second_last_item=5404, third_last_item=5400, step_rank=1.0, country=0, country_platform=0, device_platform=4, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=21.0, rg_time_diff=1.9847586467000649, step_log=0.6931471805599453)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4319, 4319, 5368]
[4319, 4319]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4319, 4319]
[5433 4319]
Pandas(Index=519, user_id='DBDW8O9K9Y3G', timestamp=1541453275, session_id='357319e01cfcf', step=3, action=2, item_id=5368, platform=33, city=219, device=0, current_filters=nan, impressions=['5816446', '1503323', '2180552', '1875629', '102943', '6537352', '5506768', '1008151', '5522156', '115948', '1511993', '5518300', '3515046', '116036', '9848166', '1330702', '2219924', '7128266', '3071118', '6023346', '9608480', '931555', '234611', '1871287', '350336'], prices=[45, 82, 62, 37, 62, 47, 65, 82, 42, 62, 46, 46, 75, 65, 72, 46, 51, 29, 35, 66, 39, 39, 46, 45, 44], id=1519, last_item=5321, second_last_item=5321, third_last_item=5321, step_rank=3.0, country=41, country_platform=71, device_platform=56, sess_step=3, time_diff=21.0, time_diff_diff=21.0, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.3951417099410705, step_log=1.3862943611198906)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4327, 4327, 4327]
[4327, 4327]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4327, 4327]
[5433 4327]
Pandas(Index=528, user_id='YMWFI5RT15JV', timestamp=1541453276, session_id='4871922b8bfc1', step=3, action=2, item_id=4327, platform=18, city=282, device=1, current_filters=nan, impressions=['51385', '185416', '4507310', '184466', '17782', '185431', '1753725', '185856', '186081', '6745532', '3854338', '130821', '2733218', '1144433', '729706', '7812700', '2653483', '10267852', '6806080', '955221', '9721620', '8115786', '190366', '50961', '10525110'], prices=[175, 68, 65, 85, 96, 70, 80, 78, 80, 91, 95, 84, 65, 56, 96, 70, 59, 51, 69, 79, 105, 61, 88, 60, 80], id=1528, last_item=5387, second_last_item=3082, third_last_item=5321, step_rank=3.0, country=19, country_platform=36, device_platform=59, sess_step=3, time_diff=0.0, time_diff_diff=0.0, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=46.0, rg_time_diff=-1.1112442781037273, step_log=1.3862943611198906)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3083, 3082]
[3083]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3083]
[5433 3083]
Pandas(Index=526, user_id='2RXCLWDXCSZV', timestamp=1541453276, session_id='74bd7f1ce82eb', step=2, action=2, item_id=3082, platform=12, city=198, device=1, current_filters=nan, impressions=['82971', '1640221', '643136', '11182328', '6665012'], prices=[624, 295, 243, 475, 62], id=1526, last_item=4327, second_last_item=5321, third_last_item=5387, step_rank=2.0, country=32, country_platform=51, device_platform=44, sess_step=2, time_diff=46.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=nan, rg_time_diff=0.5014359735869275, step_log=1.0986122886681098)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=560, user_id='76RLNV6PVIKJ', timestamp=1541453277, session_id='c581f69e7663e', step=1, action=2, item_id=5368, platform=5, city=106, device=1, current_filters=nan, impressions=['5849390', '9820016', '3075594', '3208454', '5816724', '1708997', '9418588', '7679832', '9326352', '2074806', '1250321', '9636452', '4594114', '1882561', '5706186', '1121356', '2146064', '6894090', '9800478', '1180594', '8107522', '1202294', '5818310', '9529668', '3217724'], prices=[120, 176, 248, 108, 93, 406, 100, 256, 169, 200, 227, 130, 142, 201, 1295, 133, 193, 181, 69, 128, 93, 179, 146, 145, 351], id=1560, last_item=5321, second_last_item=4226, third_last_item=4226, step_rank=1.0, country=11, country_platform=12, device_platform=7, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=1.5343455347465724, step_log=0.6931471805599453)
30
4
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3346, 3355, 3355, 5368]
[3346, 3355, 3355]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3346, 3355, 3355]
[5433 3346 3355]
Pandas(Index=561, user_id='MZITMZQARCM5', timestamp=1541453277, session_id='95e17b451c454', step=4, action=2, item_id=5368, platform=8, city=225, device=1, current_filters=nan, impressions=['12589', '12583', '14644', '857741', '2396278', '12605', '853456', '12608', '12587', '925325', '18479', '14762', '893467', '48078', '12613', '12594', '109915', '5209538', '46969', '1976493', '12604', '12611', '47372', '6733562', '18485'], prices=[170, 256, 319, 106, 170, 318, 319, 377, 160, 282, 291, 129, 325, 239, 277, 170, 158, 238, 170, 226, 267, 287, 126, 227, 242], id=1561, last_item=5368, second_last_item=4226, third_last_item=4226, step_rank=4.0, country=10, country_platform=10, device_platform=10, sess_step=4, time_diff=2.0, time_diff_diff=2.0, time_diff_diff_diff=33.0, time_diff_2=nan, time_diff_3=0.0, rg_time_diff=0.032374771868349535, step_log=1.6094379124341003)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4384, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=565, user_id='203PFPC7PSFW', timestamp=1541453277, session_id='1a0383738419a', step=1, action=2, item_id=4384, platform=0, city=241, device=1, current_filters=nan, impressions=['104802', '104804', '104867', '1162971', '104773', '5032060', '5106602', '104939', '104889', '3219548', '109319', '97610', '127102', '104888', '104957', '5121984', '109320', '957851', '104649', '929707', '722191', '109317', '2369290', '106540', '722206'], prices=[56, 55, 60, 57, 83, 66, 66, 103, 48, 49, 77, 53, 87, 56, 53, 29, 70, 46, 55, 40, 76, 46, 27, 46, 29], id=1565, last_item=5321, second_last_item=4226, third_last_item=4226, step_rank=1.0, country=0, country_platform=0, device_platform=4, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=1.2903153294935739, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=568, user_id='I7JL7Q4ZCSVB', timestamp=1541453277, session_id='ca3cc44f4a4fe', step=1, action=2, item_id=5368, platform=10, city=70, device=0, current_filters=nan, impressions=['104498', '3132935', '93683', '105004', '478266', '1771271', '755686', '2519958', '2299740', '2634014', '1079804', '982755', '106416', '4041850', '2145104', '5806894', '928697', '97601', '478371', '1331758', '3244076', '1771549', '1993467', '479136', '478141'], prices=[96, 54, 102, 34, 83, 28, 48, 44, 51, 51, 37, 94, 53, 44, 46, 94, 112, 80, 65, 42, 28, 40, 49, 29, 31], id=1568, last_item=5321, second_last_item=5321, third_last_item=4384, step_rank=1.0, country=0, country_platform=24, device_platform=17, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=7.0, rg_time_diff=1.285657161372691, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4427]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=569, user_id='8AQA0UVF6E38', timestamp=1541453277, session_id='51520a9576df2', step=1, action=2, item_id=4427, platform=0, city=286, device=0, current_filters=nan, impressions=['8472774', '5926160', '4669922', '3485610', '584691', '4308690', '2811310', '2825940', '4247932', '2857943', '4668644', '8902096', '1889501', '5808934', '4192586', '8985788', '2717620', '5416082', '5667222', '8337506'], prices=[55, 34, 60, 49, 66, 54, 39, 57, 32, 78, 36, 15, 53, 32, 26, 38, 51, 32, 134, 47], id=1569, last_item=5321, second_last_item=5407, third_last_item=5321, step_rank=1.0, country=0, country_platform=0, device_platform=0, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=1.1461050773038826, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=574, user_id='MY1SJ2J13XE5', timestamp=1541453278, session_id='48c40c59bb78a', step=1, action=2, item_id=5368, platform=44, city=287, device=1, current_filters=nan, impressions=['4182500', '9986118', '1129732', '955141', '343651', '2703762', '2201146', '8405630', '2713546', '2346328', '1235983', '692396', '4525990', '2889938', '3440242', '6921774', '6003544', '1067016', '2639796', '8788840', '7315342', '3166153', '692391', '2703754', '2277820'], prices=[10, 16, 32, 45, 26, 16, 17, 18, 11, 30, 65, 132, 15, 32, 14, 28, 43, 27, 17, 23, 16, 12, 34, 27, 77], id=1574, last_item=5321, second_last_item=5384, third_last_item=4731, step_rank=1.0, country=62, country_platform=132, device_platform=83, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=41.0, time_diff_3=0.0, rg_time_diff=1.1021908449969469, step_log=0.6931471805599453)

94it [00:00, 96.21it/s]

30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4472, 4472, 5368]
[4472, 4472]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4472, 4472]
[5433 4472]
Pandas(Index=586, user_id='A0QYP6RQ4GRI', timestamp=1541453279, session_id='473fc5f2cacec', step=3, action=2, item_id=5368, platform=29, city=269, device=1, current_filters=nan, impressions=['924863', '99746', '50248', '48394', '141363', '1503425', '49774', '556606', '99869', '49146', '1288605', '99747', '393216', '2952396', '5417302', '1214850', '627371', '99820', '658361', '141364', '6575614', '4947946', '659886', '394876', '894181'], prices=[82, 59, 65, 79, 35, 79, 65, 56, 50, 70, 65, 61, 59, 81, 68, 38, 46, 42, 49, 55, 81, 81, 55, 36, 58], id=1586, last_item=5395, second_last_item=5395, third_last_item=5321, step_rank=3.0, country=3, country_platform=67, device_platform=51, sess_step=3, time_diff=12.0, time_diff_diff=12.0, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.31661339798536886, step_log=1.3862943611198906)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=592, user_id='E58KG5XCFO1L', timestamp=1541453280, session_id='9cbe8aaa9b721', step=1, action=2, item_id=5368, platform=10, city=292, device=0, current_filters=nan, impressions=['3486886', '1842927', '16813', '4470968', '25837', '7741486', '34960', '5211724', '7090494', '110500', '1712537', '9281406', '2087354', '6537872', '7000860', '2420344', '34951', '3497648', '2902726', '7986580', '34957', '4128478', '1320444', '1324122', '3135695'], prices=[128, 226, 86, 61, 208, 160, 84, 130, 151, 86, 130, 149, 92, 84, 133, 65, 195, 182, 93, 113, 121, 96, 134, 204, 102], id=1592, last_item=5321, second_last_item=5321, third_last_item=5395, step_rank=1.0, country=13, country_platform=135, device_platform=17, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=3.0, rg_time_diff=1.1299183478217263, step_log=0.6931471805599453)
30
12
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 5321, 5321, 5321, 5321, 5321, 5321, 5321, 5321, 4521]
[5321, 5321, 5321, 5321, 5321, 5321, 5321, 5321, 5321, 5321, 5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 5321, 5321, 5321, 5321, 5321, 5321, 5321, 5321]
[5433 5321]
Pandas(Index=608, user_id='Y0ETLPGTGD2A', timestamp=1541453281, session_id='249b8b0d07289', step=12, action=2, item_id=4521, platform=10, city=157, device=0, current_filters='Hostel|Hotel|Hostal (ES)|Motel|Resort', impressions=['2594608', '40726', '152984', '40487', '100542', '40475', '40340', '727426', '971883', '40141', '754631', '40232', '40339', '40489', '100527', '7670534', '1980819', '110816', '747491', '1220378', '40479', '40044', '6696556', '5206310', '716286'], prices=[88, 109, 117, 162, 112, 95, 74, 107, 247, 89, 141, 83, 48, 150, 104, 109, 106, 111, 56, 170, 60, 201, 99, 123, 157], id=1608, last_item=5400, second_last_item=5400, third_last_item=5400, step_rank=12.0, country=22, country_platform=96, device_platform=17, sess_step=12, time_diff=17.0, time_diff_diff=17.0, time_diff_diff_diff=17.0, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.36238916105348934, step_log=2.5649493574615367)
30
12
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4553, 4553, 4553, 4553, 4553, 4553, 4553, 4553, 4553, 4553, 4553, 4569]
[4553, 4553, 4553, 4553, 4553, 4553, 4553, 4553, 4553, 4553, 4553]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4553, 4553, 4553, 4553, 4553, 4553, 4553, 4553, 4553, 4553, 4553]
[5433 4553]
Pandas(Index=609, user_id='UVKPT0WWED2B', timestamp=1541453281, session_id='dd495f4487032', step=12, action=2, item_id=4569, platform=8, city=203, device=1, current_filters=nan, impressions=['2878396', '12568', '12569', '12564', '3981996', '12558', '2049875', '1363672', '1824633', '7012464', '137995', '342806', '46704', '634641', '12580', '2325996', '8340412', '12566', '12579', '795871', '147867', '12563', '1204716', '6006350', '47804'], prices=[67, 72, 51, 97, 95, 115, 109, 75, 102, 103, 89, 74, 64, 56, 95, 107, 66, 90, 109, 98, 96, 113, 124, 80, 90], id=1609, last_item=4521, second_last_item=5400, third_last_item=5400, step_rank=12.0, country=10, country_platform=10, device_platform=10, sess_step=12, time_diff=40.0, time_diff_diff=40.0, time_diff_diff_diff=40.0, time_diff_2=17.0, time_diff_3=0.0, rg_time_diff=0.4822371255805451, step_log=2.5649493574615367)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4571, 4571, 5368]
[4571]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4571]
[5433 4571]
Pandas(Index=614, user_id='5TS4KDST4IT8', timestamp=1541453282, session_id='a46f06fcb0450', step=2, action=2, item_id=4571, platform=31, city=202, device=1, current_filters=nan, impressions=['9064286', '3769748', '80675', '116046', '9860', '9350', '1315118', '2431096', '1330564', '80507', '80531', '80549', '80561', '80652', '101521', '147472', '998205', '2002555', '5075438', '93439', '15472', '9127398', '3365342', '1723091', '1105782'], prices=[126, 121, 127, 93, 169, 130, 125, 171, 80, 157, 93, 220, 113, 98, 41, 58, 49, 128, 91, 164, 220, 86, 106, 54, 92], id=1614, last_item=5380, second_last_item=5321, third_last_item=5400, step_rank=2.0, country=38, country_platform=122, device_platform=70, sess_step=2, time_diff=18.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=10.0, time_diff_3=0.0, rg_time_diff=0.3705019832493978, step_log=1.0986122886681098)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3255, 5368]
[3255]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3255]
[5433 3255]
Pandas(Index=619, user_id='2LV6036FOZ47', timestamp=1541453283, session_id='4a0af3a5f92d3', step=2, action=2, item_id=5368, platform=9, city=211, device=1, current_filters=nan, impressions=['149345', '7148', '7156', '15729', '100915', '1043318', '15726', '15728', '7434', '94103', '132484', '7279', '7280', '127481', '15730', '159861', '180211', '95350', '7162', '137629', '122967', '94114', '9840', '3387288', '1202530'], prices=[177, 290, 184, 221, 306, 237, 300, 336, 326, 165, 322, 504, 188, 119, 236, 137, 190, 159, 468, 564, 414, 200, 284, 210, 108], id=1619, last_item=5402, second_last_item=5321, third_last_item=5409, step_rank=2.0, country=22, country_platform=28, device_platform=25, sess_step=2, time_diff=47.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=10.0, rg_time_diff=0.5060070488566041, step_log=1.0986122886681098)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4589, 5368]
[4589]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4589]
[5433 4589]
Pandas(Index=624, user_id='EP46UHVW1ULV', timestamp=1541453283, session_id='19bedb3e5e723', step=2, action=2, item_id=5368, platform=29, city=258, device=1, current_filters=nan, impressions=['4035678', '4015092', '746401', '9323386', '9743648', '6636742', '7362658', '7057488', '7036144', '10224900', '9232294', '11165006', '9651728', '9002866'], prices=[85, 79, 45, 60, 25, 36, 50, 40, 35, 57, 29, 46, 48, 50], id=1624, last_item=5402, second_last_item=5321, third_last_item=5403, step_rank=2.0, country=52, country_platform=118, device_platform=51, sess_step=2, time_diff=21.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.39410562846220876, step_log=1.0986122886681098)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4603, 4614]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=642, user_id='Z57TSPQ4OBBA', timestamp=1541453284, session_id='b7ee050a2cca4', step=1, action=2, item_id=4603, platform=8, city=294, device=0, current_filters=nan, impressions=['1552643', '3053252', '12396', '18686', '12443', '2045293', '12395', '12426', '1824213', '3477474', '12411', '18711', '12397', '12429', '12389', '18693', '7740904', '3533818', '12398', '109865', '1475831', '5170130', '99099', '407671', '12444'], prices=[216, 412, 219, 429, 617, 559, 441, 456, 106, 383, 248, 308, 319, 480, 205, 185, 349, 782, 494, 237, 329, 662, 298, 829, 911], id=1642, last_item=5321, second_last_item=5321, third_last_item=5321, step_rank=1.0, country=10, country_platform=10, device_platform=16, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=3.0, time_diff_3=39.0, rg_time_diff=1.1494154806923453, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=644, user_id='OZ9UQDYUI48J', timestamp=1541453285, session_id='02888d421eca3', step=1, action=2, item_id=5368, platform=28, city=299, device=1, current_filters=nan, impressions=['1108691', '140044', '2789716', '130794', '6812020', '2902604', '106128', '4918220', '160083', '140046', '7019700', '161320', '2780702', '160088', '912637', '5754832'], prices=[58, 58, 88, 102, 40, 76, 86, 83, 96, 102, 116, 63, 65, 81, 118, 50], id=1644, last_item=5321, second_last_item=4603, third_last_item=5408, step_rank=1.0, country=19, country_platform=137, device_platform=47, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=nan, rg_time_diff=1.241882013202094, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=645, user_id='G0ZV9U76DQC2', timestamp=1541453285, session_id='b44d104db372c', step=1, action=2, item_id=5368, platform=34, city=159, device=0, current_filters=nan, impressions=['12693', '12707', '12682', '18422', '12688', '12650', '12712', '46319', '48166', '1340407', '1412769', '1670405', '1770455', '4493164', '2627686', '6514376', '3133824', '18372', '880913', '46294', '46485', '48099', '12703', '97419', '48076'], prices=[91, 361, 122, 123, 107, 239, 321, 507, 214, 158, 292, 239, 232, 234, 204, 225, 202, 131, 279, 230, 292, 193, 237, 198, 262], id=1645, last_item=5321, second_last_item=5408, third_last_item=4603, step_rank=1.0, country=10, country_platform=138, device_platform=86, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=0.0, rg_time_diff=1.1527512698930664, step_log=0.6931471805599453)

104it [00:01, 96.55it/s]

30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4664]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=680, user_id='M99Z7IYKDX4I', timestamp=1541453286, session_id='e2fa79e8a8202', step=1, action=2, item_id=4664, platform=37, city=302, device=1, current_filters=nan, impressions=['1240081', '5647680', '37714', '9500346', '8276346', '3184770', '5482466', '37711', '2029079', '4500498', '5773306', '94475', '1293576', '9504042', '4957186', '942927', '1298549', '1413728', '96783', '486771', '5188184', '10131972', '1875551', '13348', '80263'], prices=[72, 74, 173, 208, 113, 57, 135, 81, 48, 53, 38, 127, 40, 120, 41, 29, 125, 25, 103, 92, 93, 50, 63, 144, 130], id=1680, last_item=5321, second_last_item=5413, third_last_item=5412, step_rank=1.0, country=44, country_platform=78, device_platform=61, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=nan, rg_time_diff=1.2675613271830313, step_log=0.6931471805599453)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4710, 5368]
[4710]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4710]
[5433 4710]
Pandas(Index=683, user_id='J05VQQSBLJ1F', timestamp=1541453287, session_id='1ff08a6ce6ae5', step=2, action=2, item_id=5368, platform=8, city=14, device=0, current_filters=nan, impressions=['449896', '12544', '12521', '12536', '1943615', '5467618', '5213780', '2239640', '12516', '2157462', '12540', '47638', '129527', '147730', '12523', '397951', '4414488', '46254', '47131', '894967', '12543', '12530', '12522', '397546', '47785'], prices=[119, 211, 199, 64, 80, 143, 129, 154, 163, 198, 213, 74, 67, 77, 137, 129, 89, 197, 195, 182, 185, 63, 167, 257, 92], id=1683, last_item=5321, second_last_item=5321, third_last_item=4664, step_rank=2.0, country=10, country_platform=10, device_platform=16, sess_step=2, time_diff=17.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=30.0, time_diff_3=0.0, rg_time_diff=0.36340063706033027, step_log=1.0986122886681098)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4714, 4714]
[4714]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4714]
[5433 4714]
Pandas(Index=702, user_id='A1KJ423CA1ZD', timestamp=1541453289, session_id='a2aaeb6ba72dd', step=2, action=2, item_id=4714, platform=8, city=159, device=1, current_filters=nan, impressions=['46317', '47141', '880913', '1321090', '5806508', '47158', '3218556', '47101', '46305', '46694', '664366', '9370388', '98743', '18456', '46850', '968575', '12695', '32783', '47079', '1819741', '98735', '630306', '46294', '18427', '2398847'], prices=[144, 131, 222, 237, 173, 154, 547, 161, 48, 45, 50, 56, 45, 109, 135, 71, 156, 162, 246, 256, 211, 128, 342, 296, 150], id=1702, last_item=5395, second_last_item=5321, third_last_item=4731, step_rank=2.0, country=10, country_platform=10, device_platform=10, sess_step=2, time_diff=42.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=10.0, time_diff_3=0.0, rg_time_diff=0.48897194581251174, step_log=1.0986122886681098)
30
12
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4731, 4731, 4731, 4731, 4731, 4731, 4731, 4731, 4731, 4731, 4731, 4731]
[4731, 4731, 4731, 4731, 4731, 4731, 4731, 4731, 4731, 4731, 4731]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4731, 4731, 4731, 4731, 4731, 4731, 4731, 4731, 4731, 4731, 4731]
[5433 4731]
Pandas(Index=710, user_id='EX1VQTO5OT3T', timestamp=1541453289, session_id='21cb9e0ffefca', step=12, action=2, item_id=4731, platform=35, city=252, device=1, current_filters=nan, impressions=['8250', '8249', '1955219', '67404', '67406', '562626', '67380', '14646', '8257', '14378', '58374', '152749', '79789', '56981', '833751', '136732', '61229', '61418', '79476', '67424', '74725', '56973', '3500822', '3528204', '67425'], prices=[118, 118, 162, 87, 51, 69, 64, 243, 169, 183, 52, 95, 55, 78, 34, 47, 57, 59, 97, 97, 39, 115, 188, 107, 103], id=1710, last_item=5395, second_last_item=5395, third_last_item=5395, step_rank=12.0, country=15, country_platform=111, device_platform=66, sess_step=12, time_diff=1.0, time_diff_diff=1.0, time_diff_diff_diff=11.0, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.02971219483702271, step_log=2.5649493574615367)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4758]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=711, user_id='MATJWTFCR6G1', timestamp=1541453290, session_id='f9c40bff6e027', step=1, action=2, item_id=4758, platform=11, city=305, device=2, current_filters=nan, impressions=['80533', '111182', '7210084', '1273458', '2817304', '111175', '1995075', '94631', '927717', '1952213', '741746', '4904572', '2435620', '650121', '2713500', '1994711', '1357556', '4540858', '5844732', '5478788', '2387724', '111201', '987329', '4129440', '1836427'], prices=[129, 85, 29, 67, 43, 69, 26, 78, 79, 60, 20, 43, 53, 35, 36, 33, 32, 79, 36, 21, 32, 53, 132, 41, 61], id=1711, last_item=5321, second_last_item=5395, third_last_item=5395, step_rank=1.0, country=38, country_platform=140, device_platform=28, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=1.0, time_diff_3=0.0, rg_time_diff=1.1698278510347875, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4782]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=718, user_id='GWS6DHKC64ZN', timestamp=1541453291, session_id='d68e5377e12d7', step=1, action=2, item_id=4782, platform=18, city=307, device=1, current_filters=nan, impressions=['152574', '5902', '53269', '2012947', '13658', '5909', '1151451', '2152342', '51040', '2322200', '5906', '3133527', '2287354', '16271', '5936', '6868818', '5894', '51465', '52553', '8744686', '9042240', '5934', '5905', '406951', '2161756'], prices=[108, 188, 82, 134, 213, 56, 80, 58, 94, 216, 83, 93, 118, 179, 106, 105, 188, 79, 69, 130, 91, 178, 78, 196, 103], id=1718, last_item=5321, second_last_item=4941, third_last_item=4820, step_rank=1.0, country=19, country_platform=36, device_platform=59, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=18.0, time_diff_3=0.0, rg_time_diff=1.0433574611070449, step_log=0.6931471805599453)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4820, 4820, 4820]
[4820, 4820]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4820, 4820]
[5433 4820]
Pandas(Index=722, user_id='2W35BUJ8W20G', timestamp=1541453292, session_id='2ab64fa71e06a', step=3, action=2, item_id=4820, platform=29, city=116, device=1, current_filters=nan, impressions=['906695', '2341566', '49670', '12038', '82440', '1269929', '1321528', '12063', '11966', '1910679', '10309084', '49034', '11983', '82539', '50459', '4449200', '12172', '8835114', '50576', '12137', '82332', '12186', '10414086', '6951856', '10463450'], prices=[250, 336, 264, 211, 261, 332, 289, 223, 256, 226, 313, 326, 405, 454, 211, 526, 298, 618, 364, 320, 148, 329, 462, 426, 445], id=1722, last_item=5321, second_last_item=5397, third_last_item=5321, step_rank=3.0, country=3, country_platform=67, device_platform=51, sess_step=3, time_diff=2.0, time_diff_diff=2.0, time_diff_diff_diff=nan, time_diff_2=47.0, time_diff_3=0.0, rg_time_diff=0.043030050785566876, step_log=1.3862943611198906)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4384, 5368]
[4384]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4384]
[5433 4384]
Pandas(Index=732, user_id='203PFPC7PSFW', timestamp=1541453292, session_id='1a0383738419a', step=2, action=2, item_id=5368, platform=0, city=241, device=1, current_filters=nan, impressions=['104802', '104804', '104867', '1162971', '104773', '5032060', '5106602', '104939', '104889', '3219548', '109319', '97610', '127102', '104888', '104957', '5121984', '109320', '957851', '104649', '929707', '722191', '109317', '2369290', '106540', '722206'], prices=[56, 55, 60, 57, 83, 66, 66, 103, 48, 49, 77, 53, 87, 56, 53, 29, 70, 46, 55, 40, 76, 46, 27, 46, 29], id=1732, last_item=3197, second_last_item=5321, third_last_item=5321, step_rank=2.0, country=0, country_platform=0, device_platform=4, sess_step=2, time_diff=15.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=57.0, time_diff_3=0.0, rg_time_diff=0.34630420663246875, step_log=1.0986122886681098)
30
7
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 5321, 5321, 5321, 5368]
[5321, 5321, 5321, 5321, 5321, 5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 5321, 5321, 5321]
[5433 5321]
Pandas(Index=738, user_id='XPOO4F5PGVRK', timestamp=1541453293, session_id='60f1213239716', step=7, action=2, item_id=5368, platform=8, city=159, device=0, current_filters='Best Value', impressions=['46683', '46686', '149085', '664366', '4392864', '46845', '2396136', '2529342', '46262', '1172704', '6171602', '46985', '1340407', '906859', '1032962', '3366712', '81697', '2627686', '18456', '98769', '46574', '47012', '47124', '3147401', '1251638'], prices=[56, 73, 100, 146, 62, 154, 98, 119, 153, 65, 162, 165, 179, 251, 159, 187, 183, 287, 175, 143, 210, 164, 174, 232, 271], id=1738, last_item=5402, second_last_item=5380, third_last_item=5380, step_rank=7.0, country=10, country_platform=10, device_platform=16, sess_step=7, time_diff=22.0, time_diff_diff=22.0, time_diff_diff_diff=24.0, time_diff_2=10.0, time_diff_3=0.0, rg_time_diff=0.4013761560842284, step_log=2.0794415416798357)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 4850]
[5321, 5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321]
[5433 5321]
Pandas(Index=740, user_id='4FM30783N21T', timestamp=1541453293, session_id='4c8ce1a06eded', step=3, action=2, item_id=4850, platform=3, city=102, device=0, current_filters='4 Star', impressions=['8589', '102080', '8588', '893927', '1258697', '8518', '8602', '8618', '796756', '8543', '3145532', '8595', '8577', '8599', '8619', '8573', '8582', '8590', '8597', '77124', '8523', '8550', '4897252', '8591', '64376'], prices=[93, 69, 117, 93, 143, 150, 68, 129, 78, 124, 80, 122, 96, 121, 88, 95, 93, 138, 76, 127, 102, 159, 100, 119, 145], id=1740, last_item=5402, second_last_item=5368, third_last_item=5321, step_rank=3.0, country=15, country_platform=48, device_platform=11, sess_step=3, time_diff=33.0, time_diff_diff=0.0, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=22.0, rg_time_diff=0.45354068680858906, step_log=1.3862943611198906)

114it [00:01, 97.07it/s]

30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4867, 5368]
[4867]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4867]
[5433 4867]
Pandas(Index=741, user_id='NS51O96JPR0R', timestamp=1541453293, session_id='98646f2f9083c', step=2, action=2, item_id=5368, platform=0, city=139, device=0, current_filters=nan, impressions=['393591', '104632', '5008004', '2759718', '104828', '9317618', '9772462', '6953508', '3795382', '4504514', '5174478', '104902', '1754159', '2083424', '2061814', '9473574', '4089430', '9386646', '5122358', '1245372', '2790558', '4567728', '9761738', '1668407', '2535386'], prices=[327, 181, 44, 67, 68, 67, 30, 68, 40, 53, 67, 81, 39, 65, 33, 25, 34, 40, 37, 35, 39, 31, 23, 40, 44], id=1741, last_item=4850, second_last_item=5321, third_last_item=5368, step_rank=2.0, country=0, country_platform=0, device_platform=0, sess_step=2, time_diff=14.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=33.0, time_diff_3=0.0, rg_time_diff=0.32940787905327196, step_log=1.0986122886681098)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=762, user_id='BT78FK24LOMD', timestamp=1541453294, session_id='6c913c01160ac', step=1, action=2, item_id=5368, platform=8, city=310, device=1, current_filters='Car Park', impressions=['1535467', '3477372', '18921', '2373358', '147193', '3753094', '18937', '18920', '18917', '1370330', '18922', '946177', '147196', '18927', '47634', '3152296', '18936', '48101', '18923', '32750', '18938', '7805360', '18932', '138217', '147197'], prices=[72, 51, 57, 31, 57, 62, 98, 57, 49, 67, 69, 71, 56, 79, 74, 57, 71, 67, 63, 32, 113, 81, 90, 33, 51], id=1762, last_item=5321, second_last_item=5321, third_last_item=5417, step_rank=1.0, country=10, country_platform=10, device_platform=10, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=10.0, rg_time_diff=0.7206146306377939, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=783, user_id='ZFFQQD2NJP6E', timestamp=1541453296, session_id='6201f9a2cf1aa', step=1, action=2, item_id=5368, platform=29, city=311, device=1, current_filters=nan, impressions=['754886', '5661044', '1284422', '124123', '2833534', '113453', '5831336', '2558792', '1708379', '6749518', '2882426', '7380630', '10843586', '9536492', '10861400', '9373668'], prices=[78, 68, 75, 103, 96, 235, 65, 84, 68, 258, 84, 135, 152, 90, 203, 100], id=1783, last_item=5321, second_last_item=5412, third_last_item=5387, step_rank=1.0, country=3, country_platform=67, device_platform=51, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=10.0, rg_time_diff=0.6633629266366458, step_log=0.6931471805599453)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4571, 4571, 5368]
[4571, 4571]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4571, 4571]
[5433 4571]
Pandas(Index=802, user_id='5TS4KDST4IT8', timestamp=1541453296, session_id='a46f06fcb0450', step=3, action=2, item_id=5368, platform=31, city=202, device=1, current_filters=nan, impressions=['9064286', '3769748', '80675', '116046', '9860', '9350', '1315118', '2431096', '1330564', '80507', '80531', '80549', '80561', '80652', '101521', '147472', '998205', '2002555', '5075438', '93439', '9127398', '1723091', '15472', '1105782', '3365342'], prices=[126, 121, 127, 93, 169, 130, 125, 171, 80, 157, 93, 220, 113, 98, 41, 58, 49, 128, 91, 164, 86, 54, 220, 92, 106], id=1802, last_item=5412, second_last_item=5420, third_last_item=5321, step_rank=3.0, country=38, country_platform=122, device_platform=70, sess_step=3, time_diff=14.0, time_diff_diff=-4.0, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=nan, rg_time_diff=0.33534934079598844, step_log=1.3862943611198906)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4941, 4941, 5368]
[4941, 4941]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4941, 4941]
[5433 4941]
Pandas(Index=810, user_id='0ESRCQ2PO1ZK', timestamp=1541453296, session_id='e395908f0b5c5', step=3, action=2, item_id=5368, platform=9, city=306, device=0, current_filters=nan, impressions=['40000', '654081', '153643', '1719221', '2433682', '40269', '1090076', '80934', '128253', '1315662', '40554', '99348', '150316', '206666', '40105', '40837', '211461', '99347', '40266', '1070548', '5726738', '6568664', '319841', '40268', '157253'], prices=[129, 60, 115, 40, 110, 65, 43, 103, 58, 216, 119, 99, 60, 110, 90, 105, 66, 73, 63, 50, 90, 44, 53, 52, 79], id=1810, last_item=5411, second_last_item=5412, third_last_item=5321, step_rank=3.0, country=22, country_platform=28, device_platform=13, sess_step=3, time_diff=6.0, time_diff_diff=6.0, time_diff_diff_diff=nan, time_diff_2=10.0, time_diff_3=0.0, rg_time_diff=0.1198282176651584, step_log=1.3862943611198906)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3597, 3597, 3598]
[3597, 3597]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3597, 3597]
[5433 3597]
Pandas(Index=832, user_id='AFV8FWHV1KJ3', timestamp=1541453297, session_id='80c012ced98b0', step=3, action=2, item_id=3598, platform=18, city=237, device=1, current_filters=nan, impressions=['122197', '336886', '10290502', '8888224', '122196', '9561860', '8452062', '9114802', '9486884', '8897944', '9164504', '10562768', '10430052', '8921694', '124016', '3902600', '7015556', '6509210', '8978176', '9087968', '10425060', '10379130', '8864310', '10424704', '11007252'], prices=[262, 179, 112, 163, 145, 103, 338, 355, 255, 355, 242, 214, 172, 181, 199, 229, 197, 133, 159, 162, 142, 131, 189, 125, 214], id=1832, last_item=5321, second_last_item=5321, third_last_item=5321, step_rank=3.0, country=19, country_platform=36, device_platform=59, sess_step=3, time_diff=41.0, time_diff_diff=36.0, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=2.0, rg_time_diff=0.48447717835606324, step_log=1.3862943611198906)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=833, user_id='5V7C06GBK1ZA', timestamp=1541453297, session_id='0ea43b0883b5c', step=1, action=2, item_id=5368, platform=12, city=314, device=1, current_filters=nan, impressions=['20370', '20447', '20275', '20257', '20353', '20381', '20380', '20256', '20288', '20294', '20429', '45143', '102502', '1450171', '20356', '45625', '20268', '20323', '20423', '3828714', '3997560', '6273896', '20261', '3533408', '20398'], prices=[60, 56, 100, 110, 60, 72, 59, 153, 114, 130, 81, 146, 94, 143, 54, 53, 140, 125, 63, 206, 94, 89, 108, 239, 82], id=1833, last_item=5321, second_last_item=5321, third_last_item=5321, step_rank=1.0, country=32, country_platform=51, device_platform=44, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=41.0, time_diff_3=0.0, rg_time_diff=0.5650738145439762, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=839, user_id='TC26K72MOJE6', timestamp=1541453298, session_id='7aeb62bd8e78f', step=1, action=2, item_id=5368, platform=12, city=315, device=1, current_filters=nan, impressions=['958313', '45247', '82554', '1995217', '2010787', '126446', '126448', '1328356', '82967', '2301778', '3090882', '10008074', '126443', '558341', '5475172', '5826734', '126447', '4496874', '2318100', '2089240', '7704874', '2439268', '1199418', '7036174', '1976623'], prices=[138, 530, 218, 74, 200, 396, 315, 149, 261, 200, 82, 137, 404, 144, 600, 600, 234, 1000, 87, 110, 300, 147, 167, 120, 125], id=1839, last_item=5321, second_last_item=485, third_last_item=5321, step_rank=1.0, country=32, country_platform=51, device_platform=44, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=10.0, time_diff_3=nan, rg_time_diff=0.5748900889879, step_log=0.6931471805599453)
30
4
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 5008]
[5321, 5321, 5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321]
[5433 5321]
Pandas(Index=877, user_id='W1P1MXMXS9FF', timestamp=1541453301, session_id='be6ce41a3ef85', step=4, action=2, item_id=5008, platform=6, city=54, device=0, current_filters='Best Value', impressions=['6269106', '1884063', '6556934', '1985229', '2516252', '101409', '3144036', '9644396', '95870', '4944908', '6170636', '103256', '474796', '110232', '10134040', '110223', '1010279', '2232946', '4918872', '101404', '1945525', '9252860', '3135250', '2568955', '3135329'], prices=[15, 18, 28, 22, 15, 33, 21, 28, 39, 40, 23, 43, 30, 39, 29, 21, 15, 15, 28, 52, 34, 13, 42, 24, 26], id=1877, last_item=5425, second_last_item=5391, third_last_item=5391, step_rank=4.0, country=5, country_platform=100, device_platform=12, sess_step=4, time_diff=52.0, time_diff_diff=52.0, time_diff_diff_diff=52.0, time_diff_2=13.0, time_diff_3=0.0, rg_time_diff=0.5186882368103972, step_log=1.6094379124341003)
30
4
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 5368]
[5321, 5321, 5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321]
[5433 5321]
Pandas(Index=878, user_id='AL2BXGXYRAZL', timestamp=1541453301, session_id='5348be0d1a26b', step=4, action=2, item_id=5368, platform=5, city=281, device=1, current_filters='Business Hotel|Hotel', impressions=['1026480', '103560', '1026526', '1026482', '984375', '3890516', '1197154', '1028840', '1026550', '3542080', '673916', '1178482'], prices=[67, 93, 54, 93, 71, 58, 63, 67, 410, 93, 70, 58], id=1878, last_item=5008, second_last_item=5425, third_last_item=5391, step_rank=4.0, country=11, country_platform=12, device_platform=7, sess_step=4, time_diff=25.0, time_diff_diff=25.0, time_diff_diff_diff=25.0, time_diff_2=52.0, time_diff_3=13.0, rg_time_diff=0.4202709293298164, step_log=1.6094379124341003)
30
5
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 5321, 5043]
[5321, 5321, 5321, 5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 5321]
[5433 5321]
Pandas(Index=884, user_id='0DEE2BAA42GJ', timestamp=1541453302, session_id='b9fe245363adc', step=5, action=2, item_id=5043, platform=37, city=255, device=1, current_filters='Sort by Price', impressions=['1272192', '2552454', '4073410', '1032310', '2233772', '2672188', '2158560', '3747780', '152682', '1255682', '1274394', '4341488', '4602234', '5594640', '1459923', '3178342', '2817376', '1650341', '2313828', '2550844', '4062650', '5484818', '1333107', '2503114', '1942835'], prices=[7, 7, 9, 10, 10, 10, 11, 11, 12, 12, 12, 12, 13, 13, 14, 14, 15, 15, 16, 16, 16, 17, 18, 18, 18], id=1884, last_item=5321, second_last_item=5403, third_last_item=5403, step_rank=5.0, country=44, country_platform=78, device_platform=61, sess_step=5, time_diff=7.0, time_diff_diff=7.0, time_diff_diff_diff=13.0, time_diff_2=nan, time_diff_3=0.0, rg_time_diff=0.1261295118937836, step_log=1.791759469228055)

125it [00:01, 98.79it/s]

30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=896, user_id='Z1P7JSI0CXLA', timestamp=1541453302, session_id='f5944a12ace50', step=1, action=2, item_id=5368, platform=10, city=320, device=1, current_filters=nan, impressions=['325366', '171647', '171622', '1254610', '325286', '1209040', '1255389', '171597', '8798012', '495256', '885275', '506836', '2560944', '220621', '2882044', '888481', '2860916', '811616', '5824670', '2200602', '4873000', '4688542', '2680580', '4689366', '682806'], prices=[77, 74, 93, 51, 71, 101, 27, 47, 84, 41, 85, 61, 26, 84, 36, 52, 19, 270, 74, 37, 93, 67, 25, 39, 33], id=1896, last_item=5321, second_last_item=5427, third_last_item=4559, step_rank=1.0, country=17, country_platform=20, device_platform=20, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=nan, rg_time_diff=0.7605089258892411, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4873]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=897, user_id='NHAFW2LC482B', timestamp=1541453302, session_id='16011c431f9ca', step=1, action=2, item_id=4873, platform=0, city=139, device=1, current_filters=nan, impressions=['104632', '6953508', '5174478', '1244689', '2759718', '3145614', '393591', '3148521', '1244743', '1244673', '2352488', '1827867', '9772462', '9317618', '4647190', '9601108', '2178474', '2551566', '2790558', '10128466', '4089430', '2655962', '3145610', '3221814', '11240344'], prices=[181, 68, 67, 114, 67, 53, 327, 71, 78, 88, 63, 91, 30, 67, 112, 73, 70, 55, 39, 46, 34, 32, 57, 58, 56], id=1897, last_item=5321, second_last_item=5380, third_last_item=5427, step_rank=1.0, country=0, country_platform=0, device_platform=4, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=0.0, rg_time_diff=0.7589297686041049, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=911, user_id='XWZPG3FKYO7G', timestamp=1541453303, session_id='dd59848571527', step=1, action=2, item_id=5368, platform=33, city=322, device=1, current_filters=nan, impressions=['41861', '3135558', '349876', '9636562', '41858', '99241', '41921', '41997', '41873', '4054626', '2174784', '8281158', '6671260', '3086745', '41876', '3883608', '2670934', '941947', '10459300', '41950', '1417464', '8314268', '1835025', '1374572', '349821'], prices=[187, 146, 62, 152, 182, 93, 152, 119, 191, 67, 52, 37, 52, 141, 131, 69, 114, 65, 179, 220, 135, 42, 157, 62, 109], id=1911, last_item=5321, second_last_item=5409, third_last_item=5409, step_rank=1.0, country=16, country_platform=146, device_platform=62, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=0.0, rg_time_diff=0.6716695727013766, step_log=0.6931471805599453)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3037, 3034]
[3037]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3037]
[5433 3037]
Pandas(Index=912, user_id='06IDQEUU0AF2', timestamp=1541453303, session_id='8164bbaddb575', step=2, action=2, item_id=3034, platform=0, city=170, device=1, current_filters=nan, impressions=['4744374', '1658719', '3051038', '2277390', '745041', '477981', '2677895', '2344168', '1962949', '2352972', '1668435', '2828912', '1269129', '4418618', '3112332', '1412050', '2383508', '4084638', '2794992', '2503210', '2643962', '6475398', '3854914', '2248594', '953311'], prices=[21, 26, 21, 20, 59, 24, 33, 36, 58, 29, 31, 28, 49, 45, 42, 44, 31, 36, 35, 27, 65, 59, 68, 41, 166], id=1912, last_item=5368, second_last_item=5321, third_last_item=5409, step_rank=2.0, country=0, country_platform=0, device_platform=4, sess_step=2, time_diff=76.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=nan, time_diff_3=nan, rg_time_diff=0.5433747461122208, step_log=1.0986122886681098)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5174]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=925, user_id='F60WAEHIV3BN', timestamp=1541453305, session_id='158ec5fdcab5c', step=1, action=2, item_id=5174, platform=3, city=326, device=1, current_filters=nan, impressions=['34556', '34557', '34558', '34559', '34561', '34562', '42441', '42632', '42737', '42748', '42792', '42797', '42799', '42802', '42942', '43052', '43062', '43099', '43113', '43187', '149352', '396671', '397981', '448601', '901855'], prices=[174, 54, 69, 79, 29, 80, 55, 143, 43, 200, 68, 79, 58, 54, 61, 36, 99, 53, 69, 38, 45, 57, 47, 24, 39], id=1925, last_item=5321, second_last_item=5260, third_last_item=5260, step_rank=1.0, country=8, country_platform=8, device_platform=5, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.695725384300305, step_log=0.6931471805599453)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5368]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=919, user_id='9Q19DNV03CBM', timestamp=1541453305, session_id='bbc9c1298b2ad', step=1, action=2, item_id=5368, platform=3, city=324, device=1, current_filters=nan, impressions=['1630953', '9373110', '3132113', '367961', '103333', '551871', '1532391', '2178008', '5922758', '477741', '2222526', '1963809', '2758101', '922301', '924521', '1245748', '2181818', '103321', '3905914', '3175812', '1820307', '103356', '363651', '3939302', '2306328'], prices=[52, 49, 57, 44, 69, 47, 79, 35, 179, 38, 59, 72, 37, 50, 68, 213, 93, 135, 54, 78, 75, 81, 65, 70, 120], id=1919, last_item=5321, second_last_item=5428, third_last_item=5372, step_rank=1.0, country=25, country_platform=148, device_platform=5, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=nan, rg_time_diff=0.6786632453899802, step_log=0.6931471805599453)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5184]
[5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321]
[5433 5321]
Pandas(Index=952, user_id='311YJPZGPI34', timestamp=1541453306, session_id='4fff91ae78331', step=2, action=2, item_id=5184, platform=18, city=295, device=0, current_filters='Car Park', impressions=['980639', '3853730', '5158484', '132011', '5195428', '5217', '149491', '920215', '2529604', '53091', '924407', '3150064', '14220', '3469190', '5250', '107334', '980633', '52267', '5273', '1330947', '5285', '980629', '149490', '921379', '53020'], prices=[24, 66, 47, 17, 94, 262, 73, 63, 51, 68, 67, 60, 59, 78, 75, 64, 65, 57, 58, 57, 60, 87, 55, 80, 71], id=1952, last_item=5419, second_last_item=5321, third_last_item=5412, step_rank=2.0, country=19, country_platform=36, device_platform=33, sess_step=2, time_diff=25.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.41604656011936253, step_log=1.0986122886681098)
30
4
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 5207]
[5321, 5321, 5321]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321]
[5433 5321]
Pandas(Index=960, user_id='67GCLP5QLFTL', timestamp=1541453307, session_id='90e11f574abf1', step=4, action=2, item_id=5207, platform=1, city=1, device=1, current_filters='Sort by Price', impressions=['1770209', '9337432', '9370970', '14364', '35653', '1698675', '3505748', '107042', '2407016', '251872', '7902078', '2861774', '1890503', '5114498', '1708777', '35547', '2297952', '6833094', '725016', '920957', '9155040', '1267420', '2242822', '2707422', '2836265'], prices=[41, 45, 47, 48, 48, 49, 50, 52, 53, 56, 56, 57, 58, 60, 60, 60, 61, 61, 61, 62, 62, 62, 63, 63, 63], id=1960, last_item=5412, second_last_item=472, third_last_item=5412, step_rank=4.0, country=1, country_platform=1, device_platform=1, sess_step=4, time_diff=13.0, time_diff_diff=13.0, time_diff_diff_diff=13.0, time_diff_2=0.0, time_diff_3=10.0, rg_time_diff=0.32545981166250265, step_log=1.6094379124341003)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5232, 5232, 5232]
[5232, 5232]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5232, 5232]
[5433 5232]
Pandas(Index=965, user_id='NAMMTRB23LBO', timestamp=1541453307, session_id='15b37fd294fe0', step=3, action=2, item_id=5232, platform=0, city=327, device=1, current_filters=nan, impressions=['2009571', '6734654', '2064124', '2261664', '2030883', '6845244', '9428562', '7369280', '3247864', '10897542', '6326576', '6299822', '9698086', '6026908', '9438342', '7993412'], prices=[207, 479, 358, 211, 293, 551, 188, 139, 229, 220, 192, 174, 269, 288, 124, 100], id=1965, last_item=3539, second_last_item=3539, third_last_item=5321, step_rank=3.0, country=0, country_platform=0, device_platform=4, sess_step=3, time_diff=1.0, time_diff_diff=1.0, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=21.0, rg_time_diff=0.027050039018847116, step_log=1.3862943611198906)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 3348]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=978, user_id='47DRPLRYUHTO', timestamp=1541453308, session_id='7c61bf7f5a8b9', step=1, action=2, item_id=3348, platform=8, city=225, device=0, current_filters=nan, impressions=['14644', '12589', '12583', '6272366', '925325', '6626868', '12587', '18489', '893467', '12611', '1251624', '12594', '14762', '153009', '153010', '12610', '12605', '342836', '12606', '853456', '18479', '12582', '46281', '5209538', '109915'], prices=[180, 133, 152, 159, 146, 191, 127, 158, 122, 211, 113, 115, 112, 134, 176, 189, 169, 159, 95, 164, 186, 102, 110, 176, 111], id=1978, last_item=5321, second_last_item=5414, third_last_item=5384, step_rank=1.0, country=10, country_platform=10, device_platform=16, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=0.0, rg_time_diff=0.5662948713362722, step_log=0.6931471805599453)

135it [00:01, 98.07it/s]

30
10
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 5321, 5404, 5321, 5321, 5321, 5297, 5297]
[5321, 5321, 5321, 5321, 5404, 5321, 5321, 5321, 5297]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5321, 5321, 5321, 5321, 5404, 5321, 5321, 5321, 5297]
[5433 5321 5404 5297]
Pandas(Index=996, user_id='KJHA48TLPE4B', timestamp=1541453309, session_id='ba870fe896c9e', step=10, action=2, item_id=5297, platform=33, city=219, device=1, current_filters='Sort by Price', impressions=['1214732', '2862500', '2818066', '2036955', '5828952', '1214722', '6441418', '991391', '4058366', '933537', '3578602', '1875615', '7014392', '7716132', '1765699', '11088266', '1235395', '2198950', '6511874', '7883588', '1479157', '2243314', '4481892', '2221572'], prices=[10, 15, 16, 19, 20, 21, 21, 21, 22, 22, 22, 23, 23, 23, 23, 23, 24, 24, 24, 24, 25, 25, 25, 25], id=1996, last_item=5321, second_last_item=5167, third_last_item=5368, step_rank=10.0, country=41, country_platform=71, device_platform=62, sess_step=10, time_diff=6.0, time_diff_diff=-13.0, time_diff_diff_diff=-32.0, time_diff_2=8.0, time_diff_3=nan, rg_time_diff=0.1108427209705958, step_log=2.3978952727983707)
30
3
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5260, 5260, 5368]
[5260, 5260]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5260, 5260]
[5433 5260]
Pandas(Index=993, user_id='AMKALRK1YTL5', timestamp=1541453309, session_id='5d4800bd54cbb', step=3, action=2, item_id=5368, platform=9, city=325, device=1, current_filters=nan, impressions=['810746', '9579', '6957', '2762563', '157116', '176147', '940656', '2318342', '1830161', '107715', '1846691', '5441724', '40310', '1919937', '2898484', '4266080', '9153300', '4040394', '9140004', '10391254', '10391324', '10803446', '110650', '40750', '4754484'], prices=[82, 104, 48, 85, 90, 57, 75, 55, 55, 88, 80, 60, 174, 35, 120, 100, 127, 178, 40, 109, 143, 85, 104, 75, 74], id=1993, last_item=5321, second_last_item=5417, third_last_item=5321, step_rank=3.0, country=22, country_platform=28, device_platform=25, sess_step=3, time_diff=4.0, time_diff_diff=4.0, time_diff_diff_diff=nan, time_diff_2=2.0, time_diff_3=15.0, rg_time_diff=0.09560756590173414, step_log=1.3862943611198906)
30
1
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5167]
[]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433]
[5433]
Pandas(Index=994, user_id='QJ294O0ZOHT0', timestamp=1541453309, session_id='90eab12543ddf', step=1, action=2, item_id=5167, platform=3, city=326, device=0, current_filters=nan, impressions=['42802', '6623552', '42792', '1236111', '34557', '43113', '42820', '43099', '6092742', '34555', '34556', '34562', '42736', '8448492', '42748', '34558', '1493537', '397981', '42797', '4876860', '10059558', '149351', '42478', '7220130', '42799'], prices=[52, 49, 71, 61, 54, 71, 72, 32, 123, 206, 170, 97, 53, 53, 63, 72, 74, 61, 56, 50, 52, 29, 48, 57, 55], id=1994, last_item=5321, second_last_item=5321, third_last_item=5417, step_rank=1.0, country=8, country_platform=8, device_platform=11, sess_step=1, time_diff=nan, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=4.0, time_diff_3=2.0, rg_time_diff=0.614029302136678, step_log=0.6931471805599453)
30
2
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4603, 4614]
[4603]
[5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 5433, 4603]
[5433 4603]
Pandas(Index=998, user_id='Z57TSPQ4OBBA', timestamp=1541453309, session_id='b7ee050a2cca4', step=2, action=2, item_id=4614, platform=8, city=294, device=0, current_filters=nan, impressions=['1552643', '3053252', '12396', '18686', '12443', '2045293', '12395', '12426', '1824213', '3477474', '12411', '18711', '12397', '12429', '12389', '18693', '7740904', '3533818', '12398', '109865', '1475831', '5170130', '99099', '407671', '12444'], prices=[216, 412, 219, 429, 617, 559, 441, 456, 106, 383, 248, 308, 319, 480, 205, 185, 349, 782, 494, 237, 329, 662, 298, 829, 911], id=1998, last_item=5321, second_last_item=5321, third_last_item=5321, step_rank=2.0, country=10, country_platform=10, device_platform=16, sess_step=2, time_diff=25.0, time_diff_diff=nan, time_diff_diff_diff=nan, time_diff_2=0.0, time_diff_3=6.0, rg_time_diff=0.4223887427243947, step_log=1.0986122886681098)

139it [00:01, 97.87it/s]

train.shape: (516, 66)
test.shape: (1565, 66)
val.shape: (2570, 66)
label_test.shape: (1666, 66)

In [141]:
# if configuration.use_test:
#     train = pd.concat([train, label_test], axis=0)
    
print("train.shape:", train.shape)
print("test.shape:", test.shape)
print("val.shape:", val.shape)

train.shape: (516, 66)
test.shape: (1565, 66)
val.shape: (2570, 66)

In [143]:
print("test before merge", test.shape)
train = train.merge(item_properties_df, on="item_id", how="left")
val = val.merge(item_properties_df, on="item_id", how="left")
test = test.merge(item_properties_df, on="item_id", how="left")


print("test ", test.shape)
# train = train.merge(filters_df, on='id', how="left")
# val = val.merge(filters_df, on='id', how="left")
# test = test.merge(filters_df, on='id', how="left")


# print("test ", test.shape)
# print("test before merge data_feature", test.shape)

test before merge (1565, 66)
test  (1565, 71)

In [144]:
train = train.merge(data_feature, on='id', how="left")
val = val.merge(data_feature, on='id', how="left")
test = test.merge(data_feature, on='id', how="left")

print("train.shape:", train.shape)
print("test.shape:", test.shape)
print("val.shape:", val.shape)

train.shape: (516, 78)
test.shape: (1565, 78)
val.shape: (2570, 78)

In [145]:
# del filters_df
del data_feature
del data
gc.collect()

294

In [146]:
# target encoding
agg_cols = [ 'price_rank', 'city', 'platform', 'device', 'country', 'impression_index','star']
for c in agg_cols:
    gp = train.groupby(c)['label']
    mean = gp.mean()
    train[f'{c}_label_avg'] = train[c].map(mean)
    val[f'{c}_label_avg'] = val[c].map(mean)
    test[f'{c}_label_avg'] = test[c].map(mean)

In [147]:
agg_cols = ['city','impression_index', 'platform']
for c in agg_cols:
    gp = train.groupby(c)['price']
    mean = gp.mean()
    train[f'{c}_price_avg'] = train[c].map(mean)
    val[f'{c}_price_avg'] = val[c].map(mean)
    test[f'{c}_price_avg'] = test[c].map(mean)

In [148]:
agg_cols = ['city']
for c in agg_cols:
    gp = train.groupby(c)['rg_time_diff']
    mean = gp.mean()
    train[f'{c}_td_avg'] = train[c].map(mean)
    val[f'{c}_td_avg'] = val[c].map(mean)
    test[f'{c}_td_avg'] = test[c].map(mean)

In [149]:
train['rg_price'] = train.price.map(price_rg_price_dict)
val['rg_price'] = val.price.map(price_rg_price_dict)
test['rg_price'] = test.price.map(price_rg_price_dict)

In [150]:
#price cut within city

data = pd.concat([train,val,test], axis=0).reset_index()
data = data.loc[:,['city','price']].drop_duplicates(['city','price'])
data['city_price_bin'] = data.groupby('city').price.apply(lambda x: qcut_safe(x, q = 40).astype(str))
data['city_price_bin'] = data.apply( lambda x: str(x.city) + x.city_price_bin,axis=1)
data['city_price_bin'] = data['city_price_bin'].factorize()[0]

In [151]:
train = train.merge(data,  on=['city','price'], how='left')
val = val.merge(data,  on=['city','price'], how='left')
test = test.merge(data,  on=['city','price'], how='left')

print("train", train.shape)
print("val", val.shape)
print("test", test.shape)
# test = test.merge(item_properties_df, on="item_id", how="left")

train (516, 91)
val (2570, 91)
test (1565, 91)

In [152]:
data_drop_columns= ['label', 'session_id', 'step', 'id']
data_drop_columns+= ['target_index','target_price','target_price_rank']
# data_drop_columns+= ['avg_lidc','avg_licc']

train_label = train.label

val_label = val.label

In [154]:
d_train = xgb.DMatrix(data=train.drop(data_drop_columns, axis=1), label=train_label.values, silent=True, nthread=-1, feature_names=train.drop(data_drop_columns, axis=1).columns.tolist())
d_val = xgb.DMatrix(data=val.drop(data_drop_columns, axis=1), label=val_label.values, silent=True, nthread= -1, feature_names=train.drop(data_drop_columns, axis=1).columns.tolist())
d_test = xgb.DMatrix(test.drop(data_drop_columns, axis=1), nthread=-1, feature_names=train.drop(data_drop_columns, axis=1).columns.tolist())

In [155]:
cat_cols = [ 'item_id', "price_rank", 'city', 'platform', 'device', 'country', 'impression_index','star','last_click_impression','last_click_item','last_interact_index','country_platform']

for col in cat_cols:
    if (train[col] < 0).sum() > 0:
        print("contains negative ", col)

In [156]:
del  train
gc.collect()

159

In [157]:
params={
    'eta': 0.02,  # 0.03,
  "booster": "gbtree",
  'tree_method':'hist',
  'max_leaves': 350, 
  'max_depth': 10,  # 18
  "nthread": multiprocessing.cpu_count() -1,
  'subsample': 0.9,
  'colsample_bytree': 0.8,
  'colsample_bylevel': 0.8,
  'min_child_weight': 2,
  'alpha': 1,
  'objective': 'binary:logistic',
  'eval_metric': 'logloss',
  'random_state': 5478,
  'verbosity': 0,
}

In [158]:
watchlist = [ (d_train, 'train'), (d_val, 'valid')]
clf = xgb.train(
    params=params,
    dtrain=d_train,
    num_boost_round=50000, #11927
    evals= watchlist,
    early_stopping_rounds=500,
    verbose_eval=500,
    # categorical_feature= cat_cols
)

[0]	train-logloss:0.675696	valid-logloss:0.676206
Multiple eval metrics have been passed: 'valid-logloss' will be used for early stopping.

Will train until valid-logloss hasn't improved in 500 rounds.
[500]	train-logloss:0.009446	valid-logloss:0.206726
Stopping. Best iteration:
[146]	train-logloss:0.036199	valid-logloss:0.176897

In [159]:
def evaluate(val_df, clf, d_val):
    val_df['scores'] = clf.predict(d_val)
    grouped_val = val_df.groupby('session_id')
    rss = []
    for _, group in grouped_val:

        scores = group.scores
        sorted_arg = np.flip(np.argsort(scores))
        rss.append( group['label'].values[sorted_arg])
        
    mrr = compute_mean_reciprocal_rank(rss)
    return mrr

mrr = evaluate(val, clf, d_val)

print("Val MRR score: ", mrr)

Val MRR score:  0.5565912858885608

In [160]:
imp = clf.get_score( importance_type='gain')
imp_df = pd.DataFrame.from_dict(imp, orient='index').reset_index()

imp_df.columns=['name','importance']
imp_df.sort_values('importance', ascending=False, inplace=True)



print(imp_df.head(20))

                              name  importance
3                    is_interacted   19.161229
2                       is_clicked   17.411168
4                       click_diff   13.283170
8            last_click_impression    4.805091
10        global_interaction_count    3.333767
1                      price_ratio    2.698560
0                 impression_index    1.197605
5                 country_platform    1.114625
6       impression_index_label_avg    0.813311
11                      price_diff    0.549449
9   global_interaction_image_count    0.226105
7             price_rank_label_avg    0.131746

In [169]:
predictions = []
session_ids = []

test['score'] = clf.predict(d_test)
save_test = test.copy()
save_test['item_id'] = cat_encoders['item_id'].reverse_transform(save_test.item_id.values)
with open(f'{model_name}_test_score.p', 'wb') as f:
    pickle.dump( save_test.loc[:,['score', 'session_id', 'item_id', 'step']],f, protocol=4)

In [170]:
grouped_test = test.groupby('session_id')
for session_id, group in grouped_test:
    scores = group['score']
    sorted_arg = np.flip(np.argsort(scores))
    sorted_item_ids = group['item_id'].values[sorted_arg]
    sorted_item_ids = cat_encoders['item_id'].reverse_transform(sorted_item_ids)
    sorted_item_string = ' '.join([str(i) for i in sorted_item_ids])
    predictions.append(sorted_item_string)
    session_ids.append(session_id)
        
prediction_df = pd.DataFrame()
prediction_df['session_id'] = session_ids
prediction_df['item_recommendations'] = predictions

In [ ]:
print("pred df shape", prediction_df.shape)
sub_df = pd.read_csv('D:\\Dokumenty\\Systemy_rekomendacyjne\\data\\submission_popular.csv')
sub_df.drop('item_recommendations', axis=1, inplace=True)
sub_df = sub_df.merge(prediction_df, on="session_id")
# sub_df['item_recommendations'] = predictions

sub_df.to_csv(f'D:\\Dokumenty\\Systemy_rekomendacyjne\\additional_resources\\2019-master\\data\\{model_name}_1mln_all.csv', index=None)

### WYNIKI
1mln trening, wszystko test - MRR: 0.6666014120446141<br>
100k trening, wszystko test - MRR: 0.64919857565502<br>
10k trening, wszystko test - MRR: 0.6182944544861741<br>
1k trening, wszystko test - MRR: ~0.51<br>

### UWAGI

In [ ]:
import collections
train = pd.read_csv('D:\\Dokumenty\\Systemy_rekomendacyjne\\additional_resources\\2019-master\\data\\train.csv',
                       sep=','
#                         ,nrows=100000
                   )
train['id']= np.arange(len(train))
train['in_impressions'] = True
train.loc[~train.impressions.isna(), 'in_impressions'] = train.loc[~train.impressions.isna()].apply(lambda row:row.reference in row.impressions.split('|'), axis=1)
collections.Counter(train['in_impressions'])