In [1]:
import pandas as pd
import numpy as np

In [ ]:
test_set_org = pd.read_csv('D:\\Dokumenty\\Systemy_rekomendacyjne\\data\\trivagoRecSysChallengeData2019_v2\\test.csv',
                       sep=',',
                      nrows=1000)
test_set_org[:30]

In [ ]:
test_set_org.iloc[2,10]

In [32]:
train_set_org = pd.read_csv('D:\\Dokumenty\\Systemy_rekomendacyjne\\data\\trivagoRecSysChallengeData2019_v2\\train.csv',
                       sep=',',
                        index_col=False)

In [3]:
train_set_org[:3]

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices
0,00RL8Z82B2Z1,aff3928535f48,1541037460,1,search for poi,Newtown,AU,"Sydney, Australia",mobile,NaN,NaN,NaN
1,00RL8Z82B2Z1,aff3928535f48,1541037522,2,interaction item image,666856,AU,"Sydney, Australia",mobile,NaN,NaN,NaN
2,00RL8Z82B2Z1,aff3928535f48,1541037522,3,interaction item image,666856,AU,"Sydney, Australia",mobile,NaN,NaN,NaN

In [ ]:
submission_popular_org = pd.read_csv('D:\\Dokumenty\\Systemy_rekomendacyjne\\data\\trivagoRecSysChallengeData2019_v2\\submission_popular.csv',
                       sep=',',
                      nrows=10)

In [ ]:
submission_popular_org[:3]

In [ ]:
item_metadata_org = pd.read_csv('D:\\Dokumenty\\Systemy_rekomendacyjne\\data\\trivagoRecSysChallengeData2019_v2\\item_metadata.csv',
                       sep=',',
                      nrows=10)

In [ ]:
item_metadata_org[:3]

In [40]:
train_set = train_set_org
train_set['counter'] = range(len(train_set))
# train_set['counter'] = train_set['counter']
x = train_set[train_set['action_type']=='clickout item'].groupby('session_id').last()
# train_set = train_set.set_index(['session_id','timestamp'])
x.iloc[:,4] = np.nan
# x = x.reset_index()
# x = x.set_index(['session_id','timestamp'])
x = x.sort_values(['session_id'])
x[:10]

,user_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices,counter
session_id,,,,,,,,,,,,
00000510f1adc,WT30CXPIG450,1541064087,1,clickout item,NaN,IN,"Ganpatipule, India",desktop,NaN,2661832|9222426|7051844|4079190|5752778|468398...,46|26|16|38|12|20|21|27|13|21|36|9|144|19|8|19...,11819900
00003f3b20954,CITFOTN2IT5P,1541097696,1,clickout item,NaN,ES,"La Manga, Spain",mobile,NaN,87132|886881|486611|979325|87173|87175|149508|...,330|187|437|159|499|324|476|381|424|159|144|19...,6046312
000056cd97ce2,0TBXPQCK401O,1541484101,4,clickout item,NaN,MY,"Port Dickson, Malaysia",desktop,NaN,3811810|496141|674016|1153426|1339848|8400372|...,187|78|100|51|150|81|44|36|53|104|93|48|38|52|...,5149863
000066611146f,XRIOQ0R1CHLT,1541332330,3,clickout item,NaN,BE,"Obak√∂y, Turkey",desktop,Hotel|Resort,5479306|97126|2195126|4163966|8415348|7829686|...,96|81|87|122|50|21|90|177|81|144|122|44|66|121...,15666071
0000be39860d7,X931R6LTG2RE,1541104090,53,clickout item,NaN,US,"Chattanooga, USA",desktop,NaN,1221442|3485396|3396928|2870208|2626700|315318...,171|218|132|209|202|60|123|145|154|174|218|48|...,8092380
0000c0fb51e11,SMEARDEG4VRK,1541240887,3,clickout item,NaN,MY,"Desaru, Malaysia",mobile,NaN,673981|4907322|1788201|10369176|4956312|826687...,89|77|211|122|51|18|55|58|949|52|101|107,5520265
0000c8490c155,C7G6RE64H25Q,1541349405,2,clickout item,NaN,MX,"Monterrey, Mexico",mobile,NaN,42757|42944|6626164|42507|42387|43166|42832|34...,80|52|50|62|39|67|96|111|91|43|82|86|58|44|107...,15018244
0000d4284ff9b,GF1RRZKHM34J,1541269878,3,clickout item,NaN,BR,"Porto de Galinhas, Brazil",mobile,NaN,4590810|2223124|1330644|2023759|2328448|315968...,72|60|93|67|49|182|112|52|97|181|126|120|157|1...,4894748
0000de36576fe,J87GWRE76LO2,1541155776,1,clickout item,NaN,CH,"Makadi Bay, Egypt",desktop,NaN,9286|132104|4275286|2014135|95114|4042714|9808...,92|172|197|151|67|96|404|113|136|189|138|444|1...,10295889
0000fd3bf7543,R1TQCU5WC8IQ,1541042615,1,clickout item,NaN,JP,"Kobe, Japan",mobile,NaN,1667695|1585055|1015427|1638445|1533033|347091...,287|591|289|305|258|400|251|321|329|169|371|19...,12609992

In [41]:
train_set = train_set.sort_values(['session_id'])
train_set[:10]

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices,counter
11819900,WT30CXPIG450,00000510f1adc,1541064087,1,clickout item,7281198,IN,"Ganpatipule, India",desktop,NaN,2661832|9222426|7051844|4079190|5752778|468398...,46|26|16|38|12|20|21|27|13|21|36|9|144|19|8|19...,11819900
6046312,CITFOTN2IT5P,00003f3b20954,1541097696,1,clickout item,979325,ES,"La Manga, Spain",mobile,NaN,87132|886881|486611|979325|87173|87175|149508|...,330|187|437|159|499|324|476|381|424|159|144|19...,6046312
5149863,0TBXPQCK401O,000056cd97ce2,1541484101,4,clickout item,3811810,MY,"Port Dickson, Malaysia",desktop,NaN,3811810|496141|674016|1153426|1339848|8400372|...,187|78|100|51|150|81|44|36|53|104|93|48|38|52|...,5149863
5149862,0TBXPQCK401O,000056cd97ce2,1541483924,3,clickout item,3811810,MY,"Port Dickson, Malaysia",desktop,NaN,3811810|496141|674016|1153426|1339848|8400372|...,187|78|100|51|150|81|44|36|53|104|93|48|38|52|...,5149862
5149861,0TBXPQCK401O,000056cd97ce2,1541483874,2,search for item,3811810,MY,"Port Dickson, Malaysia",desktop,NaN,NaN,NaN,5149861
5149860,0TBXPQCK401O,000056cd97ce2,1541483846,1,search for item,2784325,MY,"Port Dickson, Malaysia",desktop,NaN,NaN,NaN,5149860
15666069,XRIOQ0R1CHLT,000066611146f,1541332305,1,filter selection,Hotel,BE,"Obak√∂y, Turkey",desktop,Hotel|Resort,NaN,NaN,15666069
15666071,XRIOQ0R1CHLT,000066611146f,1541332330,3,clickout item,5479306,BE,"Obak√∂y, Turkey",desktop,Hotel|Resort,5479306|97126|2195126|4163966|8415348|7829686|...,96|81|87|122|50|21|90|177|81|144|122|44|66|121...,15666071
15666070,XRIOQ0R1CHLT,000066611146f,1541332305,2,filter selection,Resort,BE,"Obak√∂y, Turkey",desktop,Hotel|Resort,NaN,NaN,15666070
10817788,MSD74FLNTFNE,00008c1f39c46,1541302369,2,search for item,3501822,JP,"Gero, Japan",mobile,NaN,NaN,NaN,10817788

In [42]:
train_set = train_set.reset_index()
x = x.reset_index()
train_set[:10]

,index,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices,counter
0,11819900,WT30CXPIG450,00000510f1adc,1541064087,1,clickout item,7281198,IN,"Ganpatipule, India",desktop,NaN,2661832|9222426|7051844|4079190|5752778|468398...,46|26|16|38|12|20|21|27|13|21|36|9|144|19|8|19...,11819900
1,6046312,CITFOTN2IT5P,00003f3b20954,1541097696,1,clickout item,979325,ES,"La Manga, Spain",mobile,NaN,87132|886881|486611|979325|87173|87175|149508|...,330|187|437|159|499|324|476|381|424|159|144|19...,6046312
2,5149863,0TBXPQCK401O,000056cd97ce2,1541484101,4,clickout item,3811810,MY,"Port Dickson, Malaysia",desktop,NaN,3811810|496141|674016|1153426|1339848|8400372|...,187|78|100|51|150|81|44|36|53|104|93|48|38|52|...,5149863
3,5149862,0TBXPQCK401O,000056cd97ce2,1541483924,3,clickout item,3811810,MY,"Port Dickson, Malaysia",desktop,NaN,3811810|496141|674016|1153426|1339848|8400372|...,187|78|100|51|150|81|44|36|53|104|93|48|38|52|...,5149862
4,5149861,0TBXPQCK401O,000056cd97ce2,1541483874,2,search for item,3811810,MY,"Port Dickson, Malaysia",desktop,NaN,NaN,NaN,5149861
5,5149860,0TBXPQCK401O,000056cd97ce2,1541483846,1,search for item,2784325,MY,"Port Dickson, Malaysia",desktop,NaN,NaN,NaN,5149860
6,15666069,XRIOQ0R1CHLT,000066611146f,1541332305,1,filter selection,Hotel,BE,"Obak√∂y, Turkey",desktop,Hotel|Resort,NaN,NaN,15666069
7,15666071,XRIOQ0R1CHLT,000066611146f,1541332330,3,clickout item,5479306,BE,"Obak√∂y, Turkey",desktop,Hotel|Resort,5479306|97126|2195126|4163966|8415348|7829686|...,96|81|87|122|50|21|90|177|81|144|122|44|66|121...,15666071
8,15666070,XRIOQ0R1CHLT,000066611146f,1541332305,2,filter selection,Resort,BE,"Obak√∂y, Turkey",desktop,Hotel|Resort,NaN,NaN,15666070
9,10817788,MSD74FLNTFNE,00008c1f39c46,1541302369,2,search for item,3501822,JP,"Gero, Japan",mobile,NaN,NaN,NaN,10817788

In [43]:
x= x.set_index(['session_id', 'timestamp'])
train_set = train_set.set_index(['session_id', 'timestamp'])
train_set[:10]

                             index       user_id  step       action_type  \
session_id    timestamp
00000510f1adc 1541064087  11819900  WT30CXPIG450     1     clickout item
00003f3b20954 1541097696   6046312  CITFOTN2IT5P     1     clickout item
000056cd97ce2 1541484101   5149863  0TBXPQCK401O     4     clickout item
              1541483924   5149862  0TBXPQCK401O     3     clickout item
              1541483874   5149861  0TBXPQCK401O     2   search for item
              1541483846   5149860  0TBXPQCK401O     1   search for item
000066611146f 1541332305  15666069  XRIOQ0R1CHLT     1  filter selection
              1541332330  15666071  XRIOQ0R1CHLT     3     clickout item
              1541332305  15666070  XRIOQ0R1CHLT     2  filter selection
00008c1f39c46 1541302369  10817788  MSD74FLNTFNE     2   search for item

                         reference platform                    city   device  \
session_id    timestamp
00000510f1adc 1541064087   7281198       IN      Ganpatipule, India  desktop
00003f3b20954 1541097696    979325       ES         La Manga, Spain   mobile
000056cd97ce2 1541484101   3811810       MY  Port Dickson, Malaysia  desktop
              1541483924   3811810       MY  Port Dickson, Malaysia  desktop
              1541483874   3811810       MY  Port Dickson, Malaysia  desktop
              1541483846   2784325       MY  Port Dickson, Malaysia  desktop
000066611146f 1541332305     Hotel       BE          Obak√∂y, Turkey  desktop
              1541332330   5479306       BE          Obak√∂y, Turkey  desktop
              1541332305    Resort       BE          Obak√∂y, Turkey  desktop
00008c1f39c46 1541302369   3501822       JP             Gero, Japan   mobile

                         current_filters  \
session_id    timestamp
00000510f1adc 1541064087             NaN
00003f3b20954 1541097696             NaN
000056cd97ce2 1541484101             NaN
              1541483924             NaN
              1541483874             NaN
              1541483846             NaN
000066611146f 1541332305    Hotel|Resort
              1541332330    Hotel|Resort
              1541332305    Hotel|Resort
00008c1f39c46 1541302369             NaN

                                                                impressions  \
session_id    timestamp
00000510f1adc 1541064087  2661832|9222426|7051844|4079190|5752778|468398...
00003f3b20954 1541097696  87132|886881|486611|979325|87173|87175|149508|...
000056cd97ce2 1541484101  3811810|496141|674016|1153426|1339848|8400372|...
              1541483924  3811810|496141|674016|1153426|1339848|8400372|...
              1541483874                                                NaN
              1541483846                                                NaN
000066611146f 1541332305                                                NaN
              1541332330  5479306|97126|2195126|4163966|8415348|7829686|...
              1541332305                                                NaN
00008c1f39c46 1541302369                                                NaN

                                                                     prices  \
session_id    timestamp
00000510f1adc 1541064087  46|26|16|38|12|20|21|27|13|21|36|9|144|19|8|19...
00003f3b20954 1541097696  330|187|437|159|499|324|476|381|424|159|144|19...
000056cd97ce2 1541484101  187|78|100|51|150|81|44|36|53|104|93|48|38|52|...
              1541483924  187|78|100|51|150|81|44|36|53|104|93|48|38|52|...
              1541483874                                                NaN
              1541483846                                                NaN
000066611146f 1541332305                                                NaN
              1541332330  96|81|87|122|50|21|90|177|81|144|122|44|66|121...
              1541332305                                                NaN
00008c1f39c46 1541302369                                                NaN

                           counter
session_id    timestamp
00000510f1adc 1541064087  11819900
00003f3b20954 1541097696   6046312
000056cd97ce2 1541484101   5149863
              1541483924   5149862
              1541483874   5149861
              1541483846   5149860
000066611146f 1541332305  15666069
              1541332330  15666071
              1541332305  15666070
00008c1f39c46 1541302369  10817788

In [44]:
train_set.loc[train_set['counter'].isin(x['counter'].values)] = x
train_set[:10]

                               index       user_id  step       action_type  \
session_id    timestamp
00000510f1adc 1541064087         NaN  WT30CXPIG450     1     clickout item
00003f3b20954 1541097696         NaN  CITFOTN2IT5P     1     clickout item
000056cd97ce2 1541484101         NaN  0TBXPQCK401O     4     clickout item
              1541483924   5149862.0  0TBXPQCK401O     3     clickout item
              1541483874   5149861.0  0TBXPQCK401O     2   search for item
              1541483846   5149860.0  0TBXPQCK401O     1   search for item
000066611146f 1541332305  15666069.0  XRIOQ0R1CHLT     1  filter selection
              1541332330         NaN  XRIOQ0R1CHLT     3     clickout item
              1541332305  15666070.0  XRIOQ0R1CHLT     2  filter selection
00008c1f39c46 1541302369  10817788.0  MSD74FLNTFNE     2   search for item

                         reference platform                    city   device  \
session_id    timestamp
00000510f1adc 1541064087       NaN       IN      Ganpatipule, India  desktop
00003f3b20954 1541097696       NaN       ES         La Manga, Spain   mobile
000056cd97ce2 1541484101       NaN       MY  Port Dickson, Malaysia  desktop
              1541483924   3811810       MY  Port Dickson, Malaysia  desktop
              1541483874   3811810       MY  Port Dickson, Malaysia  desktop
              1541483846   2784325       MY  Port Dickson, Malaysia  desktop
000066611146f 1541332305     Hotel       BE          Obak√∂y, Turkey  desktop
              1541332330       NaN       BE          Obak√∂y, Turkey  desktop
              1541332305    Resort       BE          Obak√∂y, Turkey  desktop
00008c1f39c46 1541302369   3501822       JP             Gero, Japan   mobile

                         current_filters  \
session_id    timestamp
00000510f1adc 1541064087             NaN
00003f3b20954 1541097696             NaN
000056cd97ce2 1541484101             NaN
              1541483924             NaN
              1541483874             NaN
              1541483846             NaN
000066611146f 1541332305    Hotel|Resort
              1541332330    Hotel|Resort
              1541332305    Hotel|Resort
00008c1f39c46 1541302369             NaN

                                                                impressions  \
session_id    timestamp
00000510f1adc 1541064087  2661832|9222426|7051844|4079190|5752778|468398...
00003f3b20954 1541097696  87132|886881|486611|979325|87173|87175|149508|...
000056cd97ce2 1541484101  3811810|496141|674016|1153426|1339848|8400372|...
              1541483924  3811810|496141|674016|1153426|1339848|8400372|...
              1541483874                                                NaN
              1541483846                                                NaN
000066611146f 1541332305                                                NaN
              1541332330  5479306|97126|2195126|4163966|8415348|7829686|...
              1541332305                                                NaN
00008c1f39c46 1541302369                                                NaN

                                                                     prices  \
session_id    timestamp
00000510f1adc 1541064087  46|26|16|38|12|20|21|27|13|21|36|9|144|19|8|19...
00003f3b20954 1541097696  330|187|437|159|499|324|476|381|424|159|144|19...
000056cd97ce2 1541484101  187|78|100|51|150|81|44|36|53|104|93|48|38|52|...
              1541483924  187|78|100|51|150|81|44|36|53|104|93|48|38|52|...
              1541483874                                                NaN
              1541483846                                                NaN
000066611146f 1541332305                                                NaN
              1541332330  96|81|87|122|50|21|90|177|81|144|122|44|66|121...
              1541332305                                                NaN
00008c1f39c46 1541302369                                                NaN

                           counter
session_id    timestamp
00000510f1adc 1541064087  11819900
00003f3b20954 1541097696   6046312
000056cd97ce2 1541484101   5149863
              1541483924   5149862
              1541483874   5149861
              1541483846   5149860
000066611146f 1541332305  15666069
              1541332330  15666071
              1541332305  15666070
00008c1f39c46 1541302369  10817788

In [45]:
train_set.sort_values(['session_id', 'step'])[100:]

                               index       user_id  step  \
session_id    timestamp
00011005327e1 1541539804   4300732.0  M7K6U5Q4ZNBM    23
              1541539804   4300733.0  M7K6U5Q4ZNBM    24
              1541539804   4300734.0  M7K6U5Q4ZNBM    25
              1541539804   4300735.0  M7K6U5Q4ZNBM    26
              1541539814   4300736.0  M7K6U5Q4ZNBM    27
              1541539819   4300737.0  M7K6U5Q4ZNBM    28
              1541539943         NaN  M7K6U5Q4ZNBM    29
000130c2690b4 1541224805   3936124.0  0G4P8FP6ORNN     1
              1541224908         NaN  0G4P8FP6ORNN     2
000138ab4f789 1541444149  14276895.0  WDBP226XSN9E     1
              1541444181  14276896.0  WDBP226XSN9E     2
              1541444181  14276897.0  WDBP226XSN9E     3
              1541444181  14276898.0  WDBP226XSN9E     4
              1541444221  14276899.0  WDBP226XSN9E     5
              1541444297  14276900.0  WDBP226XSN9E     6
              1541444452  14276901.0  WDBP226XSN9E     7
              1541444556  14276902.0  WDBP226XSN9E     8
              1541444570  14276903.0  WDBP226XSN9E     9
              1541444570  14276904.0  WDBP226XSN9E    10
              1541444609  14276905.0  WDBP226XSN9E    11
              1541444703  14276906.0  WDBP226XSN9E    12
              1541444742  14276907.0  WDBP226XSN9E    13
              1541446184  14276908.0  WDBP226XSN9E    14
              1541446208  14276909.0  WDBP226XSN9E    15
              1541446323  14276910.0  WDBP226XSN9E    16
              1541446487  14276911.0  WDBP226XSN9E    17
              1541446592  14276912.0  WDBP226XSN9E    18
              1541446596  14276913.0  WDBP226XSN9E    19
              1541446596  14276914.0  WDBP226XSN9E    20
              1541446690  14276915.0  WDBP226XSN9E    21
...                              ...           ...   ...
s8u671odd7ckk 1541376835   5947949.0  T0QB3YFIHKA3     5
              1541376835   5947950.0  T0QB3YFIHKA3     6
              1541376857   5947951.0  T0QB3YFIHKA3     7
              1541376857   5947952.0  T0QB3YFIHKA3     8
              1541376857   5947953.0  T0QB3YFIHKA3     9
              1541376857         NaN  T0QB3YFIHKA3    10
              1541376865   5947955.0  T0QB3YFIHKA3    11
              1541376865   5947956.0  T0QB3YFIHKA3    12
              1541376865   5947957.0  T0QB3YFIHKA3    13
              1541376865   5947958.0  T0QB3YFIHKA3    14
              1541376865   5947959.0  T0QB3YFIHKA3    15
              1541376865   5947960.0  T0QB3YFIHKA3    16
tpc71ussgcuou 1541523289         NaN  W2EZ7V7KH5QE     1
u5e4la6f115r1 1541529473         NaN  HCN2L5VRPGQX     1
udmhn71cn8500 1541245078         NaN  XDKQOLXCI4OR     1
              1541245242   3867471.0  XDKQOLXCI4OR     2
              1541245242   3867472.0  XDKQOLXCI4OR     3
              1541245242   3867473.0  XDKQOLXCI4OR     4
              1541245252   3867474.0  XDKQOLXCI4OR     5
              1541245252   3867475.0  XDKQOLXCI4OR     6
              1541245252   3867476.0  XDKQOLXCI4OR     7
              1541245252   3867477.0  XDKQOLXCI4OR     8
              1541245252   3867478.0  XDKQOLXCI4OR     9
              1541245252   3867479.0  XDKQOLXCI4OR    10
              1541245315   3867480.0  XDKQOLXCI4OR    11
v9815m0bctrm1 1541387197         NaN  2CMZ2TB27WYG     1
vg1t2qc04afrt 1541171155   6678085.0  ZL7HCKU416T1     1
              1541171165   6678086.0  ZL7HCKU416T1     2
              1541171165   6678087.0  ZL7HCKU416T1     3
              1541171169         NaN  ZL7HCKU416T1     4

                                     action_type  \
session_id    timestamp
00011005327e1 1541539804  interaction item image
              1541539804  interaction item image
              1541539804  interaction item image
              1541539804  interaction item image
              1541539814  interaction item image
              1541539819           clickout item
              1541539943           clickout item
000130c2690b4 1541224805  search for destination
              1541224908           clickout item
000138ab4f789 1541444149          search for poi
              1541444181        filter selection
              1541444181        filter selection
              1541444181        filter selection
              1541444221   interaction item info
              1541444297   interaction item info
              1541444452  interaction item deals
              1541444556    change of sort order
              1541444570    change of sort order
              1541444570        filter selection
              1541444609   interaction item info
              1541444703   interaction item info
              1541444742   interaction item info
              1541446184          search for poi
              1541446208        filter selection
              1541446323   interaction item info
              1541446487           clickout item
              1541446592    change of sort order
              1541446596    change of sort order
              1541446596        filter selection
              1541446690   interaction item info
...                                          ...
s8u671odd7ckk 1541376835  interaction item image
              1541376835  interaction item image
              1541376857  interaction item image
              1541376857  interaction item image
              1541376857  interaction item image
              1541376857           clickout item
              1541376865  interaction item image
              1541376865  interaction item image
              1541376865  interaction item image
              1541376865  interaction item image
              1541376865  interaction item image
              1541376865  interaction item image
tpc71ussgcuou 1541523289           clickout item
u5e4la6f115r1 1541529473           clickout item
udmhn71cn8500 1541245078           clickout item
              1541245242  interaction item image
              1541245242  interaction item image
              1541245242   interaction item info
              1541245252  interaction item image
              1541245252  interaction item image
              1541245252  interaction item image
              1541245252  interaction item image
              1541245252  interaction item image
              1541245252  interaction item image
              1541245315   interaction item info
v9815m0bctrm1 1541387197           clickout item
vg1t2qc04afrt 1541171155    change of sort order
              1541171165    change of sort order
              1541171165        filter selection
              1541171169           clickout item

                                                                  reference  \
session_id    timestamp
00011005327e1 1541539804                                              76571
              1541539804                                              76571
              1541539804                                              76571
              1541539804                                              76571
              1541539814                                              76571
              1541539819                                              76571
              1541539943                                                NaN
000130c2690b4 1541224805                                        Pune, India
              1541224908                                                NaN
000138ab4f789 1541444149  Fort Lauderdale - Hollywood International Airport
              1541444181                                              Hotel
              1541444181                                              Motel
              1541444181                                             Resort
              1541444221                                            1211616
              1541444297                                            1182292
              1541444452                                            2423456
              1541444556                            interaction sort button
              1541444570                           distance and recommended
              1541444570                                  Focus on Distance
              1541444609                                            2423456
              1541444703                                              61216
              1541444742                                              61728
              1541446184                                    Port Everglades
              1541446208                                    Airport Shuttle
              1541446323                                             152444
              1541446487                                            2423456
              1541446592                            interaction sort button
              1541446596                              price and recommended
              1541446596                                         Best Value
              1541446690                                             224686
...                                                                     ...
s8u671odd7ckk 1541376835                                            1236880
              1541376835                                            1236880
              1541376857                                            1236880
              1541376857                                            1236880
              1541376857                                            1236880
              1541376857                                                NaN
              1541376865                                            1236880
              1541376865                                            1236880
              1541376865                                            1236880
              1541376865                                            1236880
              1541376865                                            1236880
              1541376865                                            1236880
tpc71ussgcuou 1541523289                                                NaN
u5e4la6f115r1 1541529473                                                NaN
udmhn71cn8500 1541245078                                                NaN
              1541245242                                            4283966
              1541245242                                            4283966
              1541245242                                            4283966
              1541245252                                            4283966
              1541245252                                            4283966
              1541245252                                            4283966
              1541245252                                            4283966
              1541245252                                            4283966
              1541245252                                            4283966
              1541245315                                            4283966
v9815m0bctrm1 1541387197                                                NaN
vg1t2qc04afrt 1541171155                            interaction sort button
              1541171165                                         price only
              1541171165                                      Sort by Price
              1541171169                                                NaN

                         platform                         city   device  \
session_id    timestamp
00011005327e1 1541539804       US             Port Richey, USA   tablet
              1541539804       US             Port Richey, USA   tablet
              1541539804       US             Port Richey, USA   tablet
              1541539804       US             Port Richey, USA   tablet
              1541539814       US             Port Richey, USA   tablet
              1541539819       US             Port Richey, USA   tablet
              1541539943       US             Port Richey, USA   tablet
000130c2690b4 1541224805       IN                  Pune, India   mobile
              1541224908       IN                  Pune, India   mobile
000138ab4f789 1541444149       US         Fort Lauderdale, USA  desktop
              1541444181       US         Fort Lauderdale, USA  desktop
              1541444181       US         Fort Lauderdale, USA  desktop
              1541444181       US         Fort Lauderdale, USA  desktop
              1541444221       US         Fort Lauderdale, USA  desktop
              1541444297       US         Fort Lauderdale, USA  desktop
              1541444452       US         Fort Lauderdale, USA  desktop
              1541444556       US         Fort Lauderdale, USA  desktop
              1541444570       US         Fort Lauderdale, USA  desktop
              1541444570       US         Fort Lauderdale, USA  desktop
              1541444609       US         Fort Lauderdale, USA  desktop
              1541444703       US         Fort Lauderdale, USA  desktop
              1541444742       US         Fort Lauderdale, USA  desktop
              1541446184       US         Fort Lauderdale, USA  desktop
              1541446208       US         Fort Lauderdale, USA  desktop
              1541446323       US         Fort Lauderdale, USA  desktop
              1541446487       US         Fort Lauderdale, USA  desktop
              1541446592       US         Fort Lauderdale, USA  desktop
              1541446596       US         Fort Lauderdale, USA  desktop
              1541446596       US         Fort Lauderdale, USA  desktop
              1541446690       US         Fort Lauderdale, USA  desktop
...                           ...                          ...      ...
s8u671odd7ckk 1541376835       AU          Mandurah, Australia   mobile
              1541376835       AU          Mandurah, Australia   mobile
              1541376857       AU          Mandurah, Australia   mobile
              1541376857       AU          Mandurah, Australia   mobile
              1541376857       AU          Mandurah, Australia   mobile
              1541376857       AU          Mandurah, Australia   mobile
              1541376865       AU          Mandurah, Australia   mobile
              1541376865       AU          Mandurah, Australia   mobile
              1541376865       AU          Mandurah, Australia   mobile
              1541376865       AU          Mandurah, Australia   mobile
              1541376865       AU          Mandurah, Australia   mobile
              1541376865       AU          Mandurah, Australia   mobile
tpc71ussgcuou 1541523289       IT                Lovere, Italy   mobile
u5e4la6f115r1 1541529473       DE     Bayerisch Gmain, Germany   mobile
udmhn71cn8500 1541245078       MX  Santa Mar√≠a del Oro, Mexico   mobile
              1541245242       MX                Tepic, Mexico   mobile
              1541245242       MX                Tepic, Mexico   mobile
              1541245242       MX                Tepic, Mexico   mobile
              1541245252       MX                Tepic, Mexico   mobile
              1541245252       MX                Tepic, Mexico   mobile
              1541245252       MX                Tepic, Mexico   mobile
              1541245252       MX                Tepic, Mexico   mobile
              1541245252       MX                Tepic, Mexico   mobile
              1541245252       MX                Tepic, Mexico   mobile
              1541245315       MX                Tepic, Mexico   mobile
v9815m0bctrm1 1541387197       BR      Buenos Aires, Argentina   mobile
vg1t2qc04afrt 1541171155       DE            Freiburg, Germany  desktop
              1541171165       DE            Freiburg, Germany  desktop
              1541171165       DE            Freiburg, Germany  desktop
              1541171169       DE            Freiburg, Germany  desktop

                                                            current_filters  \
session_id    timestamp
00011005327e1 1541539804                                                NaN
              1541539804                                                NaN
              1541539804                                                NaN
              1541539804                                                NaN
              1541539814                                                NaN
              1541539819                                                NaN
              1541539943                                                NaN
000130c2690b4 1541224805                                                NaN
              1541224908                                                NaN
000138ab4f789 1541444149                                                NaN
              1541444181                                 Hotel|Motel|Resort
              1541444181                                 Hotel|Motel|Resort
              1541444181                                 Hotel|Motel|Resort
              1541444221                                                NaN
              1541444297                                                NaN
              1541444452                                                NaN
              1541444556                                                NaN
              1541444570                                                NaN
              1541444570               Hotel|Motel|Resort|Focus on Distance
              1541444609                                                NaN
              1541444703                                                NaN
              1541444742                                                NaN
              1541446184               Hotel|Motel|Resort|Focus on Distance
              1541446208  Hotel|Motel|Resort|Focus on Distance|Airport S...
              1541446323                                                NaN
              1541446487  Hotel|Motel|Resort|Focus on Distance|Airport S...
              1541446592                                                NaN
              1541446596                                                NaN
              1541446596      Hotel|Motel|Resort|Airport Shuttle|Best Value
              1541446690                                                NaN
...                                                                     ...
s8u671odd7ckk 1541376835                                                NaN
              1541376835                                                NaN
              1541376857                                                NaN
              1541376857                                                NaN
              1541376857                                                NaN
              1541376857                                                NaN
              1541376865                                                NaN
              1541376865                                                NaN
              1541376865                                                NaN
              1541376865                                                NaN
              1541376865                                                NaN
              1541376865                                                NaN
tpc71ussgcuou 1541523289                                                NaN
u5e4la6f115r1 1541529473                                                NaN
udmhn71cn8500 1541245078                                                NaN
              1541245242                                                NaN
              1541245242                                                NaN
              1541245242                                                NaN
              1541245252                                                NaN
              1541245252                                                NaN
              1541245252                                                NaN
              1541245252                                                NaN

In [19]:
# x[(x['session_id']=='0000be39860d7')]
train_set.loc['0000be39860d7']

,user_id,step,action_type,reference,platform,city,device,current_filters,impressions,prices,counter
timestamp,,,,,,,,,,,
1541104089,X931R6LTG2RE,46,interaction item image,79237,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092373
1541102772,X931R6LTG2RE,9,interaction item image,445081,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092336
1541102772,X931R6LTG2RE,8,interaction item image,445081,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092335
1541102762,X931R6LTG2RE,7,interaction item image,445081,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092334
1541102762,X931R6LTG2RE,6,interaction item image,445081,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092333
1541102772,X931R6LTG2RE,10,interaction item image,445081,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092337
1541102762,X931R6LTG2RE,5,interaction item image,445081,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092332
1541102762,X931R6LTG2RE,4,interaction item image,445081,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092331
1541104089,X931R6LTG2RE,43,interaction item image,79237,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092370
1541102852,X931R6LTG2RE,29,interaction item image,79237,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092356
1541102772,X931R6LTG2RE,15,interaction item image,445081,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092342
1541102782,X931R6LTG2RE,16,interaction item image,445081,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092343
1541102782,X931R6LTG2RE,17,interaction item image,445081,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092344
1541102782,X931R6LTG2RE,18,interaction item image,445081,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092345
1541102782,X931R6LTG2RE,19,interaction item image,445081,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092346
1541102752,X931R6LTG2RE,2,interaction item image,445081,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092329
1541102752,X931R6LTG2RE,1,interaction item image,445081,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092328
1541104090,X931R6LTG2RE,53,clickout item,NaN,US,"Chattanooga, USA",desktop,NaN,1221442|3485396|3396928|2870208|2626700|315318...,171|218|132|209|202|60|123|145|154|174|218|48|...,8092380
1541104089,X931R6LTG2RE,52,interaction item image,79237,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092379
1541104089,X931R6LTG2RE,51,interaction item image,79237,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092378
1541104089,X931R6LTG2RE,50,interaction item image,79237,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092377
1541104089,X931R6LTG2RE,49,interaction item image,79237,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092376
1541102974,X931R6LTG2RE,34,interaction item image,76308,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092361
1541104089,X931R6LTG2RE,48,interaction item image,79237,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092375
1541102762,X931R6LTG2RE,3,interaction item image,445081,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092330
1541102782,X931R6LTG2RE,20,interaction item image,445081,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092347
1541104089,X931R6LTG2RE,47,interaction item image,79237,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092374
1541102772,X931R6LTG2RE,14,interaction item image,445081,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092341
1541102812,X931R6LTG2RE,21,interaction item image,79237,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092348
1541102964,X931R6LTG2RE,30,interaction item image,76308,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092357
1541102841,X931R6LTG2RE,24,interaction item image,79237,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092351
1541102852,X931R6LTG2RE,27,interaction item image,79237,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092354
1541102964,X931R6LTG2RE,31,interaction item image,76308,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092358
1541102772,X931R6LTG2RE,13,interaction item image,445081,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092340
1541102974,X931R6LTG2RE,37,interaction item image,76308,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092364
1541102974,X931R6LTG2RE,36,interaction item image,76308,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092363
1541102974,X931R6LTG2RE,35,interaction item image,76308,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092362
1541102974,X931R6LTG2RE,32,interaction item image,76308,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092359
1541102974,X931R6LTG2RE,33,interaction item image,76308,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092360
1541104089,X931R6LTG2RE,44,interaction item image,79237,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092371
1541104089,X931R6LTG2RE,45,interaction item image,79237,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092372
1541102852,X931R6LTG2RE,28,interaction item image,79237,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092355
1541102841,X931R6LTG2RE,25,interaction item image,79237,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092352
1541102841,X931R6LTG2RE,26,interaction item image,79237,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092353
1541102772,X931R6LTG2RE,11,interaction item image,445081,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092338
1541102772,X931R6LTG2RE,12,interaction item image,445081,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092339
1541104079,X931R6LTG2RE,40,interaction item image,79237,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092367
1541103940,X931R6LTG2RE,39,clickout item,4920008,US,"Chattanooga, USA",desktop,NaN,1221442|3485396|3396928|2870208|2626700|315318...,171|218|132|209|202|60|123|145|154|174|218|48|...,8092366
1541103907,X931R6LTG2RE,38,change of sort order,interaction sort button,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092365
1541104079,X931R6LTG2RE,41,interaction item image,79237,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092368
1541104089,X931R6LTG2RE,42,interaction item image,79237,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092369
1541102812,X931R6LTG2RE,22,interaction item image,79237,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092349
1541102831,X931R6LTG2RE,23,interaction item image,79237,US,"Chattanooga, USA",desktop,NaN,NaN,NaN,8092350

In [ ]:
x.shape

In [ ]:
train_set_org.shape

In [ ]:
result.shape

In [ ]:
train_set = train_set_org[train_set_org['action_type']=='clickout item']
train_set[:5]

In [ ]:
train_set = train_set.sort_values(by=['session_id', 'timestamp'])
train_set[:3]

In [ ]:
# train_set = train_set[train_set['session_id']=='aff3928535f48']
# train_set[:100]

In [ ]:
# ostatnie clickout_item dla ka≈ºdej sesji
train_set = train_set.groupby('session_id').last()
train_set = train_set.reset_index()
train_set = train_set.sort_values(by=['timestamp'])
train_set[:3]

In [ ]:
# train_set.loc['ec139e10b9238']

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test = train_test_split(train_set, test_size=0.2)

In [ ]:
x_train.shape

In [ ]:
temp = False
last_session_id_train_set = x_train.iloc[x_train.shape[0]-1,0]
last_session_id_test_set = x_test.iloc[x_test.shape[0]-1,0]
if last_session_id_test_set.equals(last_session_id_train_set):
    temp = True
    
while temp
    x_train.append(x_test.iloc[x_test.shape[0]-1, :])
    x_test = x_test.iloc[0:x_test.shape[0]-1, :]
    
    last_session_id_train_set = x_train.iloc[x_train.shape[0]-1,0]
    last_session_id_test_set = x_test.iloc[x_test.shape[0]-1,0]
    if last_session_id_test_set.equals(last_session_id_train_set):
        temp = True
    else:
        temp = False

In [ ]:
x_train.iloc[1,0]

In [ ]:
x_train[x_train.shape[0]-10:]

In [ ]:
x_train.iloc[:,5] = np.nan
x_train[:5]